ceph/ceph-build

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

- ceph-ansible is missing a lot of coverage because we don't run all jobs
on every PR.
- add stable-4.0 testing 

ceph-ansible-prs: run all jobs for all PRs

---

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

let's try to use ovh slaves as well, at least for master and stable-4.0
jobs.

ceph-ansible: add more slaves

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

This reverts commit 6072cff00cd0b6951e97dd39fbc3e6a694d7a0e3.
OVH nodes can't access sepia lab, so they can't get the rhel8 image.

Revert "ceph-ansible: add more slaves"

---

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml

- remove bluestore_lvm_osds which is no longer needed in stable-4.0 and
master.
- fix stable-4.0 testing: do not play luminous jobs.
- update some scenarios so they are triggered on stable-4.0

ceph-ansible-pipeline: refact pipeline

---

nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml

Now that nfs-ganesha 2.7.3 is released, we can go back to using the original repo instead of the temporary https://github.com/ceph/nfs-ganesha/tree/V2.7-ceph branch set up by Jeff Layton.

nfs-ganesha-stable: revert back to original repo

---

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml

These conditions were incorrect for stable-4.0
luminous jobs triggered for stable-4.0

ceph-ansible-pipeline: rgw_multisite fixes for stable-4.0

---

ceph-build/build/setup_rpm
ceph-dev-build/build/setup_rpm
ceph-dev-new-build/build/setup_rpm

We should make sure that all the rpm and srpm macros are installed and
at the latest version before installing the build dependencies.
Otherwise, the macros can get updated and we might not get all the
dependencies installed with yum-builddep.

ceph-build: Install latest rpm macros

---

ceph-medic-pull-requests/build/build
ceph-medic-pull-requests/config/definitions/ceph-medic-pull-requests.yml

This allows ceph-medic PRs to pass tests with `tox`. At some point we might want to enable python3.6 everywhere because it is otherwise impossible. The 'python3' label is a bit of a lie right now

ceph-medic-pull-requests python3.6 support

---

scripts/build_utils.sh

in hope to alleviate the ICE issues when building kvstore_tool.cc
see also https://bugzilla.redhat.com/show_bug.cgi?id=1531154

scripts/build_utils.sh: use gcc-8 on bionic

---

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

Testing bluestore is handled in the lvm_osds scenario. We don't need
a dedicated one for that.

ceph-ansible: Remove bluestore_lvm_osds scenario

---

scripts/build_utils.sh

sometimes it can be useful to get the full ceph cluster status
when troubleshooting CI failures.

ceph-ansible: try to get cluster status in teardown

---

ceph-ansible-pr-syntax-check/build/build

CI is failing at the moment because of a pip error:
```
+ /tmp/venv.x2V7jCYRmJ/bin/pip install pip==10.0.0
Traceback (most recent call last):
File "/tmp/venv.x2V7jCYRmJ/bin/pip", line 11, in <module>
load_entry_point('pip==19.1', 'console_scripts', 'pip')()
File "/tmp/venv.x2V7jCYRmJ/lib/python2.7/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/tmp/venv.x2V7jCYRmJ/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
return ep.load()
File "/tmp/venv.x2V7jCYRmJ/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2291, in load
return self.resolve()
File "/tmp/venv.x2V7jCYRmJ/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2297, in resolve
module = …
```

ceph-ansible-syntax: temporary fix CI error

---

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

Add add_rbdmirrors scenario to CI so that it can be tested against master.

ceph-ansible: add add_rbdmirrors scenario to CI

---

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

Add add_mgrs scenario to CI so that it can be tested against master and
nautilus.

ceph-ansible: add add_mgrs scenario to CI

---

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml

When doing condition on branch it's maybe easier to understand the
condition based on the branch name instead of a regex for excluding
all the other branches.

ceph-ansible: use a more meaning syntax on branch

---

ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml

Since all the tests are already run in make check,
there is no reason to run them again in the dashboard.

ceph-dashboard-pull-requests: Disable running tests

---

ceph-volume-pr/build/build

We will now skip any missing interpreters, so we should
run all the tests here always.

ceph-volume-pr: run py36 tox tests

---

ceph-ansible-pr-syntax-check/build/build

let's provide a typical 'all_daemons' inventory host file for the syntax
check process. Otherwise we can get failure because the site.yml file
contains `hosts:` which try to resolve some `{{ groups }}` variables.

ceph-ansible: give a common inventory for syntax-check

---

ceph-ansible-pr-syntax-check/build/build

Because we're now able to execute the infrastructure playbooks from
the main ceph-ansible directory, we don't need to define the ansible
library path (because already define in ansible.cfg).
The roles and group_vars directories are already present in the main
directory so we don't need to copy them anymore.
This commit also exclude both ansible-lint rules: 204 and 205
- [204] Lines should be no longer than 160 chars
- [205] Use ".yml" or ".yaml" playbook extension

ceph-ansible: remove useless command for syntax

---

ceph-container-lint/build/build

Without the selinux flag on the container volume, the container
command will fail:
: openBinaryFile: permission denied (Permission denied)

ceph-container-lint: Add selinux flag to volume

---

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
scripts/build_utils.sh

podman is available on atomic os, from upstream perspective it's better
to test against this image instead a rhel8 which was a beta image outdated.

ceph-ansible: test podman on centos instead rhel

---

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml

The ceph-ansible dashboard job with containerized deployment requires
some changes not merged yet upstream.
This job will be reenable when all the changes are merged.

ceph-ansible: Disable dashboard container job

---

nfs-ganesha/build/build_rpm

The yum repo for google-chrome is not correct -- possibly a bad URL. This is preventing builds; see:
https://jenkins.ceph.com/job/nfs-ganesha/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos7,DIST=centos7,MACHINE_SIZE=huge/41/console
https://jenkins.ceph.com/job/nfs-ganesha/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos7,DIST=centos7,MACHINE_SIZE=huge/42/console
Since we don't need it anyway for nfs-ganesha, just disable it.

nfs-ganesha: disable google-chrome yum repo

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

we stopped to use OVH nodes because of an old ceph-disk race condition.
Since ceph-disk isn't present anymore as of nautilus, let's use ovh
nodes again.

ceph-ansible: use more slave in CI

---

ceph-ansible-scenario/build/build

otherwise it always tries to run scenario using tox.ini only.

ceph-ansible: use start_tox function in ansible-scenario job

---

ceph-ansible-scenario/config/definitions/ceph-ansible-scenario.yml

Since tox.ini file has been split, this is needed to be able to run the
individual scenario testing. Those parameters are used to build the job
name passed to start_tox() function.

ceph-ansible: build job name properly

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

We don't need to run shrink_mds against "oldstable" releases.

ceph-ansible: remove shrink_mds from oldstable

---

scripts/build_utils.sh

using GCC-9 for building mimic and other stable releases has following
consequences:
* it brings runtime dependencies of libstdc++ runtime shipped along with
GCC-9
* GCC-9 is more picky, so some 3rd party libraries fail to build due to
-Werror.
let's continue using GCC-8 on bionic when building non-crimson flavors

scripts/build_utils.sh: only use GCC-9 for building crimson

---

ceph-ansible-nightly/build/build
ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml

When running manually a nightly containerized job against a custom branch of
ceph-ansible, it fails because `CEPH_DOCKER_IMAGE_TAG` is not set.
Typical error:
```
+ case "$CEPH_ANSIBLE_BRANCH" in
+ CEPH_DOCKER_IMAGE_TAG=
+ '[' -n '' ']'
```

ceph-ansible: make it possible to run nighly job on custom branch

---

jenkins-job-builder/build/build

This sets the `-o pipefail` to avoid this situation :
```
++ sort
++ grep -v jenkins-job-builder
++ jq -r '.jobs[].name'
/tmp/jenkins7521600802673204021.sh: line 1043: jq: command not found
++ curl -s https://2.jenkins.ceph.com/api/json
[PostBuildScript] - Executing post build scripts.
[jenkins-job-builder] $ /bin/sh -xe /tmp/jenkins7309655147676749318.sh
+ rm /home/jenkins-build/.jenkins_jobs.2.jenkins.ceph.com.ini
Finished: SUCCESS
```

jjb: install jq package

---

ceph-ansible-nightly/build/build

Set the page size to 100 instead of 10 (default).
Also we should add an extra page when the remainder of the modulo
operation between the tag count and page size isn't zero.

ceph-ansible-nightly: update tags pagination

---

ceph-volume-test/config/definitions/ceph-volume-test.yml

This makes the job skip the simple tests if the condition fails instead
of failing the run.

ceph-volume-test: adds on-evaluation-failure to the simple build step

---

ceph-container-build-push-imgs-devel-nightly/build/build
ceph-container-build-push-imgs-devel-nightly/config/JENKINS_URL
ceph-container-build-push-imgs-devel-nightly/config/definitions/ceph-container-build-push-imgs-devel-nightly.yml

The ceph container images are only built on github event and also based
on stable ceph content.
We can also have nightly builds with ceph developement content from
shaman/chacra.
See https://github.com/ceph/ceph-container/pull/1411

Add ceph container nightly devel build job

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml

Since https://github.com/ceph/ceph/pull/28943 merged, Ceph does not need to have Xenial built for master or Octopus.
This PR should allow building Xenial for older releases. It also tries to document a bit better the mind-melting conditional steps. Hopefully it clarifies what they are trying to accomplish. *Extra caution* when double checking those comments would be great because it is entirely possible that I am not right.

ceph-dev-*: remove xenial for master and octopus

---

ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml

I believe this was causing master to still build Xenial

ceph-dev-trigger: add missing escape for grep on master

---

calamari-clients-setup/config/definitions/calamari-clients-setup.yml
ceph-container-nighlity/config/definitions/ceph-container-nightly.yml
ceph-container-prs/config/definitions/ceph-container-prs.yml
ceph-docs/config/definitions/ceph-docs.yml
ceph-pr-docs/config/definitions/ceph-pr-docs.yml
ceph-pr-render-docs/config/definitions/ceph-pr-render-docs.yml
ceph-setup/config/definitions/ceph-setup.yml
diamond-setup/config/definitions/diamond-setup.yml

s/!include-raw/!include-raw:/
the former is deprecated.

s/!include-raw/!include-raw:/

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

there is no need to put
```
grep -v '\(jewel\|kraken\|luminous\)' | grep '\(mimic\|nautilus\)'
```
as we are not likely to have both "jewel" and "mimic" in a branch name.
this change is a follow-up of the discussion when reviewing #1345

ceph-dev-new-trigger: only use positive match for filter

---

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

since dashboard is enabled by default, we test it in all_daemons
scenario.

ceph-ansible: remove dashboard scenarios

---

nfs-ganesha/build/build_rpm

LizardFS FSAL has been added in [1] and it's enabled by default. This
is currently failing in the CI.
CMake Error at CMakeLists.txt:595 (message):
STRICT_PACKAGE: Cannot find LizardFS client lib.  Disabling lizardfs fsal
This patch configures the USE_FSAL_LIZARDFS option to OFF.
[1] https://github.com/nfs-ganesha/nfs-ganesha/commit/884ec97

nfs-ganesha: Disable LizardFS FSAL

---

ceph-dev-build/build/validate_deb
ceph-dev-build/build/validate_rpm

validate_deb - not redhat does not mean it is deb distro,
there can be other packaging systems
validate_rpm - we do not want to proceed for zypper based,
we only want to proceed for redhat like repo

ceph-dev-build: fix deb and rpm validate

---

nfs-ganesha/config/definitions/nfs-ganesha.yml

Ceph no longer builds its master branch on Xenial. See:
https://github.com/ceph/ceph-build/pull/1345
So we can no longer build the latest nfs-ganesha V2.9-dev on Xenial.

nfs-ganesha: don't build on xenial

---

ansible/slave.yml

On ubuntu, at least, with the addition of the "create a jenkins-build group" task, the creation of the user wasn't adding the user to the group.  I discovered this by seeing a docker command fail after the socket was 'chgrp'ed to jenkins-build
```
+ sudo chgrp jenkins-build /var/run/docker.sock
+ do_clean
+ make clean.all
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock
```
I logged in to the slave and confirmed this was the case.

slave.yml: Add jenkins-build user to jenkins-build group

---

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
ceph-volume-pr/config/definitions/ceph-volume-pr.yml

Before, we stored the GITHUB_TOKEN in Jenkins which was super duper bad, now we only pass it in when we need it, and it remains obscured in logs and parameters. 
This is useful when requesting the tests manually, so Jenkins has a way to set the status without being triggered from Github.

ceph-volume: allow passing GITHUB_TOKEN as a password to manually set github status

---

ceph-build/build/build_deb
ceph-dev-build/build/build_deb
ceph-dev-new-build/build/build_deb

ubuntu names `*dbgsym*` packages .ddeb in hope to put them into a
separated repo. while debian just use the plain .deb extension for them.
so, to include the dbgsym packages created by ubuntu, we need to upload
the .ddeb packages as well.

ceph*build/build/build_deb: upload *.ddeb packages

---

ceph-dashboard-pr-backend/build/build
ceph-dashboard-pr-backend/config/definitions/ceph-dashboard-pr-backend.yml

When we tried adding the "run-backend-api-tests.sh" to the
"ceph dashboard tests" job it would cause all builds to fail
all the time and it would require some more fixes/investigation
in order to fix it. Therefore we would like to use this temporary
Job to avoid breaking the "ceph dashboard tests" for all PRs and
to not interrupt the Job builds.

ceph-dashboard-pr-backend: add job config

---

configshell-fb/build/build_rpm
configshell-fb/build/setup
configshell-fb/config/definitions/configshell-fb.yml

This updated package is required by ceph-iscsi but won't be available
until CentOS 7.7(ish).

configshell-fb: initial builder for python-configshell packages

---

ceph-iscsi-stable/build/build_rpm

The -f `-*` got expanded too many times if there are multiple matches which broke the `if` statement.

ceph-iscsi-stable: Check for specific package files

---

ceph-pr-commits/config/definitions/ceph-pr-commits.yml

When Jenkins fails to clone a repo, signed-off checks will fail. If
all other checks have passed, there's no reason to force a full run of
Jenkins jobs again on that PR. This PR introduces `jenkins test signed`
trigger phrase to allow re-running the pr-commit check.

ceph-pr-commits: add trigger phrase

---

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml

The repos were never getting cleaned up causing `git fetch` to fail. This is already tested and making ceph-volume tests pass again.
/cc @jan--f

ceph-volume: cleanup workspace before running tests

---

ceph-pr-commits/config/definitions/ceph-pr-commits.yml

The repos for ceph-pr-commits job is corrupted and is causing builds to keep failing, this should fix that

ceph-pr-commits: wipe workspace to prevent repo corruption

---

scripts/build_utils.sh

Fixes the problem that causes this:
```
sudo: unable to execute /bin/find: Argument list too long
```
When calling `exec` as before, all the paths found by `find` are done in a single call, since ceph-volume has several dozen jobs, the argument becomes impossible for the system. By using `-delete` we are preventing this from happening.

scripts: use find's -delete option to prevent 'argument too long'

---

scripts/build_utils.sh

Follow up on PR #1383 . We need to remove the path, not specify the directory. We need to remove the directory restriction, otherwise it will only remove directories and we want to remove files as well.

scripts: do not specify directories with find -delete, rm the path

---

scripts/build_utils.sh

Otherwise the command fails to expand

scripts: can't use globbing with quotes

---

ceph-build/build/setup_rpm
ceph-dev-build/build/setup_rpm
ceph-dev-new-build/build/setup_rpm
scripts/build_utils.sh

This reverts commit cf2c26b181a86738e2a8bb17545f45d6aa1c7c45.
since https://bugzilla.redhat.com/show_bug.cgi?id=1726630 has been
fixed. and we have devtoolset-8-gcc-c++-8.3.1-3.1.el7.x86_64.rpm.
no reason to stick to devtoolset-8-gcc-c++-8.2.1-3 anymore.
Fixes: https://tracker.ceph.com/issues/40646

Revert "ceph-*build/build/setup_rpm: downgrade to gcc-c++-8.2.1"

---

scripts/build_utils.sh

My previous attempts where still causing issues when too many directories are matched because they are _still_ processed all at the same time:
```
sudo: unable to execute /bin/find: Argument list too long
```
This is now using a loop

scripts: use a loop instead of globbing directly

---

ceph-build/build/setup_rpm
ceph-dev-build/build/setup_rpm
ceph-dev-new-build/build/setup_rpm

see also 100a0fb5
see also https://github.com/ceph/ceph/pull/30190
Fixes: https://tracker.ceph.com/issues/41603

ceph-*build: install python36-devel for rpm macros

---

ceph-ansible-pr-syntax-check/build/build

This change removes the grep for 'ansible' when isntalling
requirements in ceph-ansible-pr-syntax-check. The grep
cause onlye the ansible requirement to be installed, ignoring
the other packages. This causes an issue in PR[1] which
introduce a filter plugin that depend on the netaddr package.
[1] https://github.com/ceph/ceph-ansible/pull/4339
Closes: #1390
Signed-off-by: Harald Jensås <hjensas@redhat.com>

pr-syntax-check - install all requirements

---

ceph-dev-new-build/build/build_rpm
ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml
ceph-dev-new/config/definitions/ceph-dev-new.yml

This adds a checkout of ceph-container to ceph-dev-new builds and gives the option to build a daemon-base container (for centos7 only) and push it to a configurable (with build variables) container repo.  The idea is to build containers for wip- branches and push them to quay.io to allow testing.
This depends on changes to ceph-container.git in https://github.com/ceph/ceph-container/pull/1457.

Add container builds using ceph-container.git for centos7

---

kernel-trigger/config/definitions/kernel-trigger.yml

We didn't trigger on wip* branches like other ceph projects because
there was a lot of old branches matching that mask in the repository.
Now that they are cleaned up, drop the workarounds (testing*/master*)
and add wip*.

kernel: update the trigger list

---

kernel-trigger/config/definitions/kernel-trigger.yml

I honestly don't know why this works and origin/wip* didn't but here we are.

kernel-trigger: Build any wip branch

---

ceph-build/build/setup_rpm
ceph-dev-build/build/setup_rpm
ceph-dev-new-build/build/setup_rpm

to silence the warning of
Package python36-devel is obsoleted by python3-devel, trying to install
python3-devel-3.6.8-10.el7.x86_64

ceph-*-build: s/python36-devel/python3-devel/

---

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml

This patch is mostly intended to build Seastar without `SEASTAR_DEBUG` flag to avoid impact on performance. There is actually a warnining in `src/core/app-template.cc`:
```cpp
#ifdef SEASTAR_DEBUG
fmt::print("WARNING: debug mode. Not for benchmarking or production\n");
#endif
```
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>

ceph-perf-pull-requests: use Release builds for crimson perf testing.

---

ceph-ansible-prs/build/build
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

This should avoid to display this job on the github status.

ceph-ansible-prs: don't display podman job on github on stable-3.2

---

ceph-ansible-prs/build/build
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

This approach doesn't work as expected, it skips almost all jobs.
Setting back the condition in the build script until we figure out
something better.

ceph-ansible-prs: revert commit 54ed76efcf9

---

ceph-dev-build/build/build_osc
ceph-dev-build/build/setup_osc

This patch addresses the issue when for osc build
it has been reporting always a distro version of
the host system for any branch. However the target
release should be reported to shaman instead.
Signed-off-by: Kyr Shatskyy <kyrylo.shatskyy@gmail.com>

osc: report osc build release correctly

---

ceph-pr-submodules/config/definitions/ceph-pr-commits.yml

we use
```
git diff --submodule=log origin/$ghprbTargetBranch...$ghprbActualCommit
```
for checking the differences between the delta since their common
ancestor, so we have to do a non-shallow clone for accessing the
common ancestor.

ceph-pr-submodules: do not use shallow-clone

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

This commit adds the ooo_collocation that were removed recently.
Related ceph-ansible PR : https://github.com/ceph/ceph-ansible/pull/4401

ceph-ansible-prs: re-add ooo_collocation

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

Add a dedicated project for ooo_collocation since we don't want it to
run in non_container context.

ceph-ansible-prs: run ooo_collocation on container only

---

ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml

Until deps are in epel8 or we figure out an alternative

ceph-pull-requests-arm64: Don't make check on CentOS8 yet

---

ceph-pr-render-docs/build/build

Since these don't get stored on the larger volume attached to docs.ceph.com, they can fill up the root disk without being cleaned up.

ceph-pr-render-docs: Clean up old doc renders

---

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml
ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml
ceph-pull-requests/config/definitions/ceph-pull-requests.yml

* add "ghprbPullId" param, simpler to use than "sha1"
* instead of using "sha1", use "ghprbPullId" to define branches to build,
more consistent this way. as we pull the refs using
`+refs/pull/${ghprbPullId}/*:refs/remotes/origin/pr/${ghprbPullId}/*`
and after the change, the ref to build is specified using
`origin/pr/${ghprbPullId}/merge`. also, by removing "sha1",
we can specify a single parameter when rebuilding/building a branch
on jenkins instead of two parameters.

ceph-*-pull-requests*: use ghprbPullId to define branches

---

ansible/examples/init.yml
ansible/examples/sensu.yml
ansible/examples/slave_static.yml
ansible/roles/grafana/handlers/main.yml
ansible/roles/grafana/tasks/main.yml
ansible/roles/grafana/tasks/nginx.yml
ansible/roles/grafana/tasks/postgresql.yml
ansible/roles/graphite/handlers/main.yml
ansible/roles/graphite/tasks/carbon.yml
ansible/roles/graphite/tasks/main.yml
ansible/roles/graphite/tasks/postgresql.yml
ansible/roles/graphite/tasks/systemd.yml
ansible/roles/kraken/handlers/main.yml
ansible/roles/kraken/tasks/systemd.yml
ansible/roles/nginx/handlers/main.yml
ansible/roles/nginx/tasks/letsencrypt.yml
ansible/roles/nginx/tasks/main.yml
ansible/roles/nginx/tasks/ssl.yml

Since ansible 2.9 sudo statements have been removed and we should use
become instead.
"All previously deprecated sudo/su and module locale global settings have
been removed." [1]
[1] https://github.com/ansible/ansible/blob/stable-2.9/changelogs/CHANGELOG-v2.9.rst

ansible: replace sudo by become

---

scripts/build_utils.sh

This should ensure that gcc 7.4.0 gets picked up, avoiding the problem of using 7.3.0 which is causing segfaults

scripts: add bionic-updates to pbuilderrc for gcc 7.4.0

---

scripts/build_utils.sh

Because otherwise the `$components` var was expanding to:
```bash
components='COMPONENTS="main universe"'
```
I've pushed this change live, no rush on merging/reviewing

scripts: use main and universe directly

---

sepia-fog-images/build/build

30min wasn't enough for jobs to stop scheduling Deploy tasks.

sepia-fog-images: Wait longer for lab to quiet down

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

When a PR can't be merged due to conflicts then we can't check if the
last commit is a merge commit.
Commit message: "Merge xxxx into xxxx"
In this case we only checkout the latest commit in the PR without the
previous one if any.

ceph-ansible-prs: update docs skip condition

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

Add the possibility to trigger `lvm_auto_discovery` job on ceph-ansible PR

ceph-ansible-prs: add lvm_auto_discovery job

---

nfs-ganesha/build/build_deb

LizardFS FSAL has been added in [1] and it's enabled by default. This
is currently failing in the CI for Bionic. 338d18e resolved this for rpm
builds, but not for debs.
CMake Error at CMakeLists.txt:595 (message):
STRICT_PACKAGE: Cannot find LizardFS client lib.  Disabling lizardfs
fsal
This patch configures the USE_FSAL_LIZARDFS option to OFF.
[1] nfs-ganesha/nfs-ganesha@884ec97
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>

nfs-ganesha: Disable LizardFS FSAL for debian

---

ceph-ansible-docs/config/definitions/ceph-ansible-docs.yml

Let's build the upstream documentation for stable-4.0
Closes: https://github.com/ceph/ceph-ansible/issues/4794

ceph-ansible-docs: build doc for stable-4.0

---

ceph-ansible-pr-syntax-check/build/build

Latest ansible-lint release (4.2.0) drops ansible 2.6 support so the
syntax-check job isn't compatible with the ceph-ansible stable-3.2
branch which uses ansible 2.6.

ceph-ansible-pr-syntax-check: pin ansible-lint

---

ceph-ansible-prs/build/build
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
scripts/build_utils.sh

This commit adds a new job for testing the filestore-to-bluestore.yml
playbook.

ceph-ansible-prs: add filestore_to_bluestore job

---

chacra-pull-requests/setup/playbooks/setup.yml
chacra-pull-requests/setup/playbooks/tasks/postgresql.yml

"become" is the correct ansible keyword for priv escalation in newer
versions. So use that.
This will fix at least the ansible-playbook setup.yml call which
previously failed.
Signed-off-by: Thomas Bechtold <tbechtold@suse.com>

chacra-pull-requests: Replace ansible sudo with become

---

ceph-dev-build/build/build_osc

We want to build against openSUSE Leap 15.2 for octopus. So use the
correct repo.
Signed-off-by: Thomas Bechtold <tbechtold@suse.com>

ceph-dev-build: Use correct OBS repo octopus on openSUSE Leap

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

This fixes a problem where CentOS8 was not being built on ceph-ci.git branches.

ceph-dev-new-trigger: build centos8 from ceph-ci

---

ceph-dev-build/build/setup_rpm

Fixes:
```
+ cd dist
+ tar xzf ceph_15.0.0-8623-g8a4458f.orig.tar.gz
+ cd ceph-15.0.0-8623-g8a4458f ceph-15.0.0-8623-g8a4458f.tar.bz2 ceph-15.0.0-8623-g8a4458f.tar.gz
/tmp/jenkins8482303231462049247.sh: line 1064: cd: too many arguments
```

ceph-dev-build: Don't try to cd into tarballs

---

tcmu-runner/build/build_rpm

The el8 mock chroot environment templates now use special include
directives which makes it difficult to inject the shaman repos into
them before initializing the chroot environment. Therefore, just
directly copy the repo file.

tcmu-runner: copy shaman.repo into mock build chroot

---

tcmu-runner/build/build_rpm

It was falling back to the BaseOS repo which includes an older
version of librados/librbd.

tcmu-runner: second attempt at getting mock to use shaman repo

---

ceph-pull-requests/config/definitions/ceph-pull-requests.yml

pbuilder hosts are running Xenial.  We still want to be able to build Bionic packages on Xenial but we do not want make check to run on *all* slaves with the "bionic" label.

ceph-pull-requests: Do NOT run on pbuilder hosts

---

ceph-dev-new-build/build/build_rpm

ceph-dev-new-build: allow containers on centos 7 or 8

---

ceph-dev-build/build/setup_deb
ceph-dev-new-build/build/setup_deb

the uncompressed tarball is not used, moreover, the build fails on
bionic when `dpkg-source -x` the source package. because we've been
relying on a bug on xenial. see
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=826334;msg=31
and on bionic, the bug was fixed. so `dpkg-source -x` started to
fail.

ceph-dev*-build: do not unpack source tar ball

---

ceph-api-nightly/config/definitions/ceph-api-nightly.yml
ceph-dashboard-pr-backend/config/definitions/ceph-dashboard-pr-backend.yml
ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
scripts/dashboard/install-backend-api-test-deps.sh
scripts/dashboard/install-e2e-test-deps.sh

Make use of the script that installs dependencies for backend API
tests as well, therefore rename the script and dir since "e2e" no longer matches here.
Also remove the conditional step to not only execute the script that installs dependencies
for e2e test environments

ceph-dashboard-*,ceph-api-nightly: Remove conditional-step; Replaced dir and script name

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

This commit adds a new 'docker2podman' job for the ceph-ansible CI.

ceph-ansible-prs: add docker2podman scenario

---

scripts/build_utils.sh

This commit makes tox using a dedicated tox ini file for the
docker_to_podman job.

ceph-ansible: use dedicated tox for docker2podman job

---

ceph-build/build/setup_deb
ceph-build/build/setup_rpm

to address following failure
+ cd ceph-14.2.6 ceph-14.2.6.tar.bz2 ceph-14.2.6.tar.gz
/tmp/jenkins10747333749307639424.sh: line 1058: cd: too many arguments

ceph-build: apply 604882e9 to ceph-build

---

ansible/examples/slave.yml
ansible/examples/slave_static.yml

Now that we're using system-provided ansible packages (https://github.com/ceph/mita/pull/135), we're at the mercy of the version provided.
OpenSUSE Leap 15.1 gives us ansible 2.8.1 which has this bug: https://github.com/ansible/ansible/issues/42726

ansible: Set hostname on OpenSUSE

---

ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml

since we've labeled the slaves correctly. and centos8 is able to build
ceph on arm64. the only pending issue is
https://bugzilla.redhat.com/show_bug.cgi?id=1673990 . but we can fix it
manually.

ceph-pull-requests-arm64: only build on centos8 and bionic

---

ceph-build/build/build_deb
ceph-dev-build/build/build_deb
ceph-dev-new-build/build/build_deb
ceph-dev-new-setup/build/build
ceph-dev-setup/build/build
ceph-setup/build/build

we don't build ceph with autotools anymore. we switched to cmake since
luminous. see https://github.com/ceph/ceph/pull/9995.
so there is no need to support autotools anymore. also, this avoids
running install-deps.sh simply for running "make dist". as we use
`make-dist` script after switching over to cmake.

ceph-*: drop autotools support

---

scripts/build_utils.sh

If a job fails and the ceph cluster doesn't respond then the ceph status
task in the collect-logs.yml playbook will wait around 50 mins before
timed out.
```console
"cmd": [
"ceph",
"--cluster",
"ceph",
"-s",
"-f",
"json"
],
"delta": "0:50:00.197544"
"end": "2020-01-16 19:45:06.932819"
"rc": 1,
"start": "2020-01-16 18:55:06.735275"
STDERR: [errno 110] RADOS timed out (error connecting to the cluster)
```
Instead we can use the --connect-timeout paramater to fail after 10s.

collect-logs: set connect timeout value

---

ceph-volume-nightly/build/build

ceph-ansible has dropped centos7 support in master, nautilius however does support it still.
Signed-off-by: Jan Fajerski <jfajerski@suse.com>

use ansible 4.0 for nautlius nightlies

---

ceph-dev-new-setup/build/build
ceph-dev-setup/build/build
ceph-setup/build/build

this is a follow-up change of #1487. since we don't use autotools for
preparing dist tarball, there is no need to run install-deps.sh for
installing the autotools.

ceph-*-setup: do not run install-deps.sh

---

ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml

ktdreyer/ceph-el8 is amd64 only, so to avoid failures like:
```
No matching package to install: 'python3-cherrypy'
No matching package to install: 'python3-pecan'
No matching package to install: 'python3-routes'
```
we need to disable the "make check" test on the combination of
"arm64+centos8" until these packages are packaged for arm64 or
provided by centos8.

ceph-pull-requests-arm64: only build on bionic

---

ceph-pr-docs/config/definitions/ceph-pr-docs.yml

xenial comes with python3.5, and our document is renders with a python3
venv created on the builder, also, the python code is also parsed by
the python3 env, so using python3.5 pratically prevents us from using
python3.6 features.
so we can use python3.6 which is offered by bionic.

ceph-pr-docs: use bionic for building docs

---

ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml

This fixes a quick typo introduced by e70982ce09a712f1182bc66d381de43a9076ec5f

ceph-volume-nightly: fix a typo

---

ceph-dev-build/build/setup_osc

We want to test with the upcoming openSUSE release (15.2) instead of
15.1.
Signed-off-by: Thomas Bechtold <tbechtold@suse.com>

osc: Build octopus on openSUSE Leap 15.2

---

ceph-pull-requests-arm64/build/build
ceph-pull-requests/build/build
ceph-pull-requests/config/definitions/ceph-pull-requests.yml

Debugging unit test failures was difficult on x86 jobs because the slave got rebooted right away.

ceph-pull-requests: Behave like arm64 job

---

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

This commit removes ubuntu testing on ceph-ansible nightlies jobs (stable-4.0)

ceph-ansible: remove ubuntu on nightlies jobs

---

ceph-pull-requests-arm64/build/build
ceph-pull-requests/build/build

the next step is to disable it by default in ceph/ceph, so it's only
compiled and tested when explictly enabled.

ceph-pull-requests*: enable seastar explicitly

---

ceph-api-nightly/config/definitions/ceph-api-nightly.yml
ceph-dashboard-pr-backend/config/definitions/ceph-dashboard-pr-backend.yml
ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
ceph-pull-requests/config/definitions/ceph-pull-requests.yml

We got rid of slave reboots in https://github.com/ceph/ceph-build/pull/1508

ceph-pull-requests: Don't require rebootable label

---

ansible/examples/slave_static.yml

Checkouts of the ceph repo contain directories with symlinks that link
to their parent dirs; this causes the file permissions check to fail.
Avoid following symlinks to work around.

Avoid symlink recursion issue

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
scripts/build_utils.sh

On braggi nodes (CentOS 8) there's no python2 anymore but only python3 so
the virtualenv command will fail.
```console
+ virtualenv -p python2.7 /tmp/venv.iqvT26vCL8
The path python2.7 (from --python=python2.7) does not exist
Build step 'Conditional step (single)' marked build as failure
```
Instead we should try if test if the python2.7 command exist and then try
python3 if this fails.
This commit also removes a duplicate slave_labels declaration in the
ceph-ansible-prs configuration.

build_utils.sh: allow using virtualenv with py3

---

ceph-ansible-prs/build/build
ceph-container-nighlity/build/teardown
ceph-container-prs/build/teardown
ceph-volume-nightly/build/teardown
scripts/build_utils.sh

I was seeing `dirname: missing operand` when there was no output from the `find | grep`
We want the output to just be empty instead of throwing an error

multiple: Use --no-run-if-empty flag with `xargs dirname`

---

ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml

no need to do so at this moment, we just need to build it for wip-*
branches to make sure crimson does not fail to build.

ceph-dev-trigger: do not build crimson flavor on master branch

---

ceph-build/config/definitions/ceph-build.yml
ceph-dev-build/config/definitions/ceph-dev-build.yml
ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml

By requiring 'braggi', none of the ARM64 builds would start.  It wouldn't be appropriate to give the arm64 builders a "braggi" label so I'm creating a new "gigantic" label that can apply to the braggi and arm64 builders.
There are no nodes in mita that have a 'gigantic' label so that guarantees builds won't run on OVH ephemeral nodes.

ceph*build: Use new gigantic label

---

ceph-build/build/setup_deb
ceph-build/config/definitions/ceph-build.yml
scripts/build_utils.sh
scripts/sync-pull

Are there additional changes required in order to bring ceph builds to buster?

Debian buster support for releases

---

scripts/sign-rpms
scripts/sync-pull
scripts/sync-push

Sage requested a new directory structure on download.ceph.com to make posting new versions and potentially pulling releases easier.
Instead of having all packages in a single repo under a `rpm-octopus` directory, `rpm-octopus` on d.c.c will symlink to `rpm-octopus-X.X.X` where X.X.X is the latest release.

scripts: Support new directory structure in signing scripts

---

scripts/sync-push

This allows people to `rsync --copy-links -aiv rsync://download.ceph.com/ceph/{debian,rpm}-octopus .` and have rsync follow the symlink.
The previous way of symlinking did not.

sync-push: Create relative symlinks instead of absolute

---

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml

This adds the ceph-ansible stable-5.0 branch to the nighly jobs which
is used to test the Ceph Octopus release.

ceph-ansible-nightly: add stable-5.0 branch

---

quay-pruner/build/prune-quay.py

Since Ceph Octopus release, the container image are based on CentOS 8
instead of 7 for previous releases.
The current quay pruner script only matches tags for CentOS 7.
This adds the CentOS 8 support.

quay-pruner: add CentOS 8 container support

---

ceph-ansible-nightly/build/build

Since octopus the container image are based on CentOS 8 instead of 7 for
the previous Ceph releases.
The current regex to find the latest stable container image per Ceph
releases is hardcoding 7.

ceph-ansible-nightly: parametrize centos release

---

ceph-ansible-pr-syntax-check/build/build

This commit replaces s/site-docker.yml.sample/site-container.yml.sample
ceph-ansible related PR: ceph/ceph-ansible#5216

ceph-ansible: update syntax check

---

ceph-dev-build/build/build_osc
ceph-dev-build/build/setup_osc
scripts/build_utils.sh

I hope this will fix the FTBFS currently seen in Shaman on openSUSE Leap
15.2 builds of "master" branch:
```
++ case $ver in
++ rel=unknown
++ echo 'ERROR: Unknown release for version '\''16.0.0'\'''
ERROR: Unknown release for version '16.0.0'
++ echo unknown
++ exit 1
+ RELEASE_BRANCH=unknown
```
Signed-off-by: Nathan Cutler <ncutler@suse.com>

build_utils.sh: add pacific

---

ceph-container-nighlity/config/definitions/ceph-container-nightly.yml

The ceph-container tests using ceph-ansible are using:
- ceph_ansible-all_daemons
- ceph_ansible-collocation
- ceph_ansible-lvm_osds

ceph-container-nightly: update job naming

---

ceph-ansible-prs/build/build

We don't need to run an extra podman scenario job on newer branches than
stable-4.0 because we're already using podman by default (CentOS 8) for
all container scenarios.
For older branches we don't support podman.

ceph-ansible-prs: run podman on stable-4.0 only

---

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml

since all "performance" slaves are now el8, we need to update the
dependencies for cbt accordingly

ceph-perf-pull-requests: install cbt dependencies for el8

---

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml

as WITH_SEASTAR is now off by default, we need to enable it for testing
crimson-osd

ceph-perf-pull-requests: enable WITH_SEASTAR

---

ceph-medic-release/config/definitions/ceph-medic-release.yml

This job was writing an incomplete .chacractl config file.

ceph-medic-release: Bind CHACRACTL_KEY credential

---

ceph-dev-build/build/build_rpm
ceph-dev-new-build/build/build_rpm

We need the environment, or else
+ sudo CI_CONTAINER=true SHA1=ca338cb74a4f503555323a668a2ba5b2e1845057 /bin/bash ./contrib/build-push-ceph-container-imgs.sh
+ CI_CONTAINER=true
+ true
+ CEPH_BRANCH=
+ for v in BRANCH SHA1 CONTAINER_REPO_HOSTNAME CONTAINER_REPO_ORGANIZATION CONTAINER_REPO_USERNAME CONTAINER_REPO_PASSWORD
+ require BRANCH
+ [[ -z '' ]]
+ echo 'Required variable BRANCH not set, exiting'
Required variable BRANCH not set, exiting
Signed-off-by: Sage Weil <sage@redhat.com>

ceph-dev-*build: sudo -E for container build

---

ceph-dev-build/build/build_rpm
ceph-dev-new-build/build/build_rpm

because `ceph-container` contains the artifacts created using `root`
user after 6090e4d00c82b8aba1d56ed249f29352e7c308d6, for instance, the
`staging` directory is created by
https://github.com/ceph/ceph-container/blob/2f61465f6a91f15470ff4f87844c5fe9c64b9664/maint-lib/stage.py#L102
so we need to remove `ceph-container` after pushing the created image
using `sudo` as well. otherwise, jenkins is not able to cleanup the
workspace using the "jenkins-build" user.

ceph-dev-*build: remove ceph-container after done with it

---

teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml

Because teuthology has functional and integration tests which
needs a connection to some services running in sepia and
some of the jenkins workers are running far away from the lab,
it takes significantly more time to run tests when using those
nodes. Like 6-7 minutes for running test on nodes in sepia,
and about 55-60 minutes outside.

teuthology: always test pull requests in sepia

---

sepia-fog-images/config/definitions/sepia-fog-images.yml

RHEL/CentOS8 don't support them.

sepia-fog-images: Don't build for mira

---

ceph-dev-new-build/build/build_rpm
ceph-dev-new-setup/build/build
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

supports crimson flavor for centos 8    
add crimson flavor build for octopus and master
See Also: https://github.com/ceph/ceph-build/pull/1334/

support crimson flavor for centos 8

---

ceph-dev-new-setup/config/definitions/ceph-dev-new-setup.yml
ceph-dev-setup/config/definitions/ceph-dev-setup.yml
ceph-setup/config/definitions/ceph-setup.yml

Not sure why this was needed in the first place but not only do we not have any actual 'trusty' slaves anymore but there's nothing in creating a tarball that should require Ubuntu 14.04.

ceph*setup: Unpin to trusty slaves

---

jenkins-job-builder/build/build

I guess jjb needs a newer pip.  This job broke a few weeks ago after https://github.com/ceph/ceph-build/commit/21e7a7b2d3aa4d49b3a38c8eab494adb8f928a4b

jenkins-job-builder: Use latest pip

---

ceph-build/build/setup_rpm
ceph-dev-build/build/setup_rpm
ceph-dev-new-build/build/setup_rpm

if $FLAVOR is crimson, crimson specific build dependencies should be
installed, otherwise we could have following failure when trying to
build crimson flavor of ceph packages:
error: Failed build dependencies:
fmt-devel is needed by ceph-2:16.0.0-1456.g311da94.el8.x86_64

ceph-*-build: enable crimson build dependencies

---

ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml

We need to have access to this key, to be able to record our e2e runs.

ceph-dashboard-pull-requests: Add Cypress key credential

---

kernel/config/definitions/kernel.yml

Commit 458332be6244 ("Add support for Ubuntu Focal Fossa globally")
added support for focal builds but didn't turn them on.

kernel: turn on ubuntu focal builds

---

ansible/examples/slave_static.yml

These variables should be passed on the command line when configuring or reconfiguring a static Jenkins slave.

Support OpenSUSE Leap static slaves too

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

we have now shifted to using centos 8 as base for building crimson
instead of using focal.
Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>

ceph-*-build: remove focal for crimson flavor

---

ceph-deploy-pull-requests/setup/playbooks/tasks/ubuntu.yml

see
https://docs.ansible.com/ansible/latest/modules/apt_module.html#parameters
the desired package state should be "present" instead of "installed".

ceph-deploy-pull-requests: s/installed/present/

---

ceph-website/build/build

The SoftIron folks like to use branch names like 'origin/feature/multingual' so let's support that.

ceph-website: Support GIT_BRANCH with multiple slashes

---

ceph-website/build/build

ceph-website: Fix typo in rsync command

---

nfs-ganesha-stable/build/build_rpm
nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml

We also needed other fixes to the build script to account for both el8/el7 builds, as well as handling for the newer version of "mock" which now uses templates.

nfs-ganesha-stable: Enable CentOS 8 builds of the stable branches of nfs-ganesha

---

nfs-ganesha/build/build_rpm
nfs-ganesha/config/definitions/nfs-ganesha.yml

Enable CentOS 8 builds of the "next" branch of nfs-ganesha.
We also needed other fixes to the build script to account for both el8/el7 builds, as well as handling for the newer version of "mock" which now uses templates.

nfs-ganesha: enable CentOS 8 builds, other fixes

---

ceph-dev-new/config/definitions/ceph-dev-new.yml
ceph-dev/config/definitions/ceph-dev.yml
quay-pruner/build/prune-quay.py
quay-pruner/config/definitions/quay-pruner.yml

This will have to be overridden in ceph.git/qa as well.

ceph-dev*/quay*: Use our own quay.ceph.io registry

---

nfs-ganesha/build/build_rpm

The CentOS 8 PowerTools repo is disabled by default, but we need it for a few *-devel packages.
Also, the sed hack for adding the libacl-devel package is no longer needed. The change was merged upstream:
https://github.com/nfs-ganesha/nfs-ganesha/commit/8f01a5df9dbcdad6c501efb929a711c3ba6a6b4c

nfs-ganesha: enable PowerTools repo for CentOS 8; remove sed hack

---

ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml

as we already have octopus build for el7, which is suffice for preparing
user of older release on el7 to upgrade to octopus, and laster octopus
on el8 or containerized deployment.

ceph-dev-trigger: stop building master on el7

---

ceph-container-build-push-imgs-devel-nightly/build/build

We don't need to build luminous and mimic devel anymore.

container: update devel nightly list

---

ceph-dev-build/build/build_rpm
ceph-dev-new-build/build/build_rpm

This avoids:
* unnecessary breakages in the master branch
* unnecessary pulpito runs due to failing containers
Let's fail early, instead of later in the pulpilto runs.
See
* https://github.com/ceph/ceph/pull/35767
* http://pulpito.ceph.com/swagner-2020-06-25_11:37:21-rados:cephadm-wip-swagner-testing-2020-06-25-1124-distro-basic-smithi/
Signed-off-by: Sebastian Wagner <sebastian.wagner@suse.com>

ceph-dev-new-build: fail, if building containers fail

---

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml

Since "simple" functional tests are meant to test that ceph-volume
successfully takes over ceph-disk deployed OSDs.

ceph-volume: don't run simple func tests against PRs

---

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

To avoid to be rated limited by the docker.io registry when pulling the
ceph container image, we need to use an authenticated user.
https://docs.docker.com/docker-hub/download-rate-limit/

ceph-ansible: add docker hub credentials

---

scripts/build_utils.sh

As a follow up on c9463f5 we also need to declare the dedicated tox
file for the cephadm container scenario.

build_utils.sh: add tox-cephadm.ini file

---

ceph-build/build/setup_rpm
ceph-dev-build/build/setup_rpm
ceph-dev-new-build/build/setup_rpm

I discovered this was missing by reimaging a CentOS7 builder to CentOS8 and it failed the first build it tried to run.
```
+ sudo yum install -y yum-utils
Last metadata expiration check: 0:00:28 ago on Thu Jul 16 21:05:07 2020.
Package yum-utils-4.0.12-3.el8.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
+ get_rpm_dist
+ LSB_RELEASE=/usr/bin/lsb_release
+ '[' '!' -x /usr/bin/lsb_release ']'
++ /usr/bin/lsb_release --short --id
+ ID=CentOS
+ case $ID in
++ /usr/bin/lsb_release --short --release
++ cut -d. -f1
+ RELEASE=8
+ DIST=el8
+ DISTRO=centos
+ echo el8
el8
+ '[' 8 = 7 ']'
+ '[' 8 = 8 ']'
+ sudo dnf config-manager --set-enabled PowerTools
+ sed -e s/@//g
+ '[' default = crimson ']'
+ sudo yum install -y python3-devel
CentOS-8 - PowerTools …
```

ceph*build: Enable lab-extras repo on CentOS8 builders

---

ceph-ansible-scenario/config/definitions/ceph-ansible-scenario.yml

this commit makes this 'individual job scenario testing' using the
`DOCKER_HUB_USERNAME` and `DOCKER_HUB_PASSWORD` environment variable so
the job can run with docker authentication.

ceph-ansible: inject password in scenario job

---

ceph-ansible-prs/build/build

Skip `shrink_osd_legacy` job on all branches but stable-3.2

ceph-ansible: play shrink_osd_legacy on 3.2 only

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
scripts/build_utils.sh

This is for testing in two ways:
1/ shrinking OSDs one by one
2/ shrinking multiple OSDs with a single call of the playbook
Related ceph-ansible PR: ceph/ceph-ansible#5569

ceph-ansible: split shrink_osd scenario

---

ceph-dashboard-pr-backend/build/build

as ceph-pull-requests already covers them.

ceph-dashboard-pr-backend: do not build/run tests for api tests

---

ceph-dev-new-setup/build/build
ceph-dev-setup/build/build

to avoid the issues caused by allocator. we cannot use seastar allocator
in non-seastar thread or threads not managed by ThreadPool.

ceph-*-setup: use libc allocator for crimson flavor

---

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml

This replaces the shrink_osd scenario by shrink_osd_multiple and
shrink_osd_single.

ceph-ansible-nightly: add new shrink_osd scenarios

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

This commit modifies the current project definitions:
1/ it uses the exclude keyword to avoid duplicating project
2/ it declares a new project to only use smithi nodes for 'large'
scenario testing (basically all scenario based on 'all_daemons'
scenario).
3/ exclude 'non_container-cephadm_adopt' for non_containerized deployments

ceph-ansible: refact project definition

---

ceph-dev-new-setup/config/definitions/ceph-dev-new-setup.yml
ceph-dev-setup/config/definitions/ceph-dev-setup.yml
ceph-setup/config/definitions/ceph-setup.yml

This is a new setting in the newest CopyArtifact plugin.
https://stackoverflow.com/a/32084538/6225562

ceph*setup: Give ceph*build jobs permission to copy artifacts

---

ansible/examples/slave.yml

I think these are just leftover mistakes from when I combined all the playbooks.
They were working despite the JNLP/SSH flip-flop because I was only re-adding slaves.  I just tried adding net-new slaves and it tried to register builders in Sepia using SSH which obviously isn't going to work.

Fixes to builder playbook

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

This adds back braggi nodes for all_daemons based scenario.

ceph-ansible: add back braggi node

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

braggi nodes don't have enough resources to support these scenarios.

ceph-ansible: do not play 'all_daemons' scenarios on braggi

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

Using `(smithi || centos7)` allows ovh slave nodes to be used for all
`all_daemons` based scenario which is not what we want since the latest
makes the playbook failing for these scenarios.

ceph-ansible: only use smithi nodes for all_daemons

---

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml

we need clang for detecting build failures with this compiler, and for
performing static analysis.
recently, seastar started to require better C++17 compatible compiler,
and it dropped the support of C++14. so before llvm-toolset-10 is added
to RHEL8/CentOS8, we need to use our own copr repo for clang-10.

ceph-perf-pull-requests: enable llvm-toolset-10 repo for clang-10

---

ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml
ceph-pull-requests/config/definitions/ceph-pull-requests.yml

This should save quite a few resources, as right now if a PR is updated several times in a short lapse of time (typical case when the submitted realizes that they missed some files/changes...), the already started jobs will continue until finishing.

ceph-*pull-requests*: cancel job on PR update

---

scripts/dashboard/install-e2e-test-deps.sh

Cypress is failing due to a missing package.

install-e2e-test-deps.sh: Add libxss1 to debian distros

---

ceph-api-nightly/build/cleanup
ceph-api-nightly/config/definitions/ceph-api-nightly.yml

This job has a bunch of templates.  Each one reaches 30-50GB in size which quickly fills up our builder home dirs.

ceph-api-nightly: Clean up after yourself

---

ceph-ansible-nightly/build/build

In order to avoid the docker.io rate limit.

ceph-ansible-nightly: use quay.ceph.io registry

---

ansible/examples/slave.yml

I accidentally left these out when I combined all the slave playbooks.  It wasn't caught till now because I hadn't actually pulled the latest ceph-build.git on prado

ansible: Start libvirt services on slave spinup

---

ansible/examples/slave.yml
ansible/templates/systemd/jenkins.secret.j2
ansible/templates/systemd/jenkins.service.j2

vstart_runner.py runs 'ps ww' for the jenkins-build user.  This exposes the API key by showing the java.jar process in Jenkins logs.  If we pass the credentials as a file, there's less of a chance of it getting exposed.

ansible: Pass API key to slave.jar as file

---

ansible/examples/slave.yml

Something in ceph.git creates an infinite loop that this task gets stuck on

ansible: Don't follow symlinks

---

ceph-volume-pr/config/definitions/ceph-volume-pr.yml

We are currently running this job on a ubuntu xenial slave which run
python 3.5 where we need python 3.6.
Switching to these centos7 nodes that use python 3.6 should fix this
issue.

ceph-volume-pr: change nodes for tox testing

---

ceph-dev-new-setup/build/build
ceph-dev-setup/build/build
ceph-setup/build/build

I don't know what changed or when but `git describe` started returning a longer string *sometimes*.  Our tooling relies on there only being 8 characters in the last portion of the version so we need to keep naming our packages that way.

ceph*setup: Abbreviate the tag

---

ceph-ansible-nightly/build/build

Currently the curl command is returning all tags matching the ceph
release so the variable contains multiple values.
We only need to have the latest one.

ceph-ansible-nightly: use latest stable tag

---

ceph-dev-new-setup/config/definitions/ceph-dev-new-setup.yml
ceph-dev-new/config/definitions/ceph-dev-new.yml
ceph-dev-setup/config/definitions/ceph-dev-setup.yml
ceph-dev/config/definitions/ceph-dev.yml

The Ceph SHA1 is divined by the -setup job, and not available in the
parent job.  That's easily fixed by the same method it's passed to the
-build job: grab the file artifact and use it to inject SHA1 into the
environment.  This means the parent job can show the SHA1 in its build
label for humans, and can also be searched by Jenkins API calls.

Grab SHA1 into parent job's environment for human or program

---

ceph-dev-new-setup/config/definitions/ceph-dev-new-setup.yml
ceph-dev-setup/config/definitions/ceph-dev-setup.yml

Apparently, sometimes, Jenkins can't find a toplevel job by "name", and
one must specify an "absolute path" to the job by prefixing "/".  This
was causing ceph-dev builds to fail to find ceph-dev-setup, but changing
to /ceph-dev-setup fixed the failure-to-find.  It didn't affect ceph-dev-new.
I've no idea why it affected one and not the other.

Fix intermittent error with last copyartifacts change

---

ceph-dev-new-setup/config/definitions/ceph-dev-new-setup.yml
ceph-dev-setup/config/definitions/ceph-dev-setup.yml

I don't see why from examining the plugin source, but it appears
that if you use both a comma and a space, the second entry will not
be found (as though the space is becoming part of the string for
comparison inside the plugin).  Stopping fighting and just letting it happen.

ceph-dev, ceph-dev-new: copyartifact permission: no spaces

---

ceph-deploy-build/build/build
ceph-deploy-build/build/setup
ceph-deploy-build/config/definitions/ceph-deploy-build.yml
ceph-deploy-tag/config/definitions/ceph-tag.yml
scripts/build_utils.sh

otherwise it fails when trying to use the release.yml playbook:
ERROR! the playbook: release.yml could not be found

ceph-deploy-tag: use ceph-build:origin/master

---

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

This job is not needed anymore, we already have 'collocation' for that.

ceph-ansible: remove ooo_collocation

---

ceph-pr-commits/config/definitions/ceph-pr-commits.yml

report.xml wasn't getting written for docs-only changes because the job `exit 0`s.  The junit plugin was failing the build in those instances but we don't need or want it to.

ceph-pr-commits: Allow empty junit results

---

ceph-pr-api/config/definitions/ceph-pr-api.yml

ceph-pr-api: Clean dpkg db on job abort

---

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml

turns out we have ubuntu test nodes labeled with "performance", and
they use dash for "sh", and jenkins use "sh" for running the embedded
scripts.
let's avoid bashism, and use "." instead.
this change is a follow-up of 4e0a8987c7d19004d33c153b107057f684b547de

ceph-perf-pull-requests: s/source/./

---

ceph-multibranch-pipeline/config/definitions/ceph-multibranch-pipeline.yml

* [Jenkins Job Builder Multibranch Pipeline](https://docs.openstack.org/infra/jenkins-job-builder/project_workflow_multibranch.html)
This change only enables the `Jenkinsfile` detection. For this to work, a `Jenkinsfile` needs to be added to `ceph/ceph`: https://github.com/ceph/ceph/pull/37425
So, it basically means that this change alone doesn't work. `Jenkinsfile` needs to propagate across branches & PRs to start seeing it (basically as soon as it hits a major branch, `master`/`octopus`/etc...).
Unlike regular jobs, Multibranch rather looks like a folder of jobs:

ceph: enable multibranch pipeline

---

jenkins-job-builder/build/build

Pinning it keeps biting us more often than fixing/updating job yamls would.

jjb: Unpin jjb version

---

ceph-pr-commits/build/build

I think GIT_COMMIT is the merge commit.  Everything Kefu and I could find indicated it should be valid to use here but it doesn't work in some instances.
Switching to ${sha1} works though.

ceph-pr-commits: Use sha1 instead of GIT_COMMIT

---

ceph-pr-commits/build/build

instead of using `${sha1}^1...${sha1}^2` use
`origin/master...origin/pr/${ghprbPullId}/head` for getting the range of
commits introduced by a PR. as per `man git-diff`
> "git diff A...B" is equivalent to "git diff $(git-merge-base A B) B".
and `origin/master` and `origin/pr/${ghprbPullId}/head` are fetched by
the Git plugin, so it's safe to use them.

ceph-pr-commits: use origin/master as the base commit

---

ceph-container-lint/build/build

The container lint job, which run shellcheck in a docker container,
doesn't use the --rm docker option so the container aren't removed
after their execution.

ceph-container-lint: use --rm docker option

---

ceph-container-flake8/build/build

Without the selinux flag on the container volume, the flake8 command
fails with:
```console
E902 IOError: [Errno 13] Permission denied: '/envglobals.py'
```

ceph-container-flake8: add selinux flag to volume

---

ceph-dev-new-setup/build/build
ceph-dev-setup/build/build

since we've merged https://github.com/ceph/ceph/pull/37887
This reverts commit 3aa35a92b466212c0c3c715781a8aab8a5e0136c.

ceph-*-setup: use default allocator for crimson flavor

---

ansible/examples/slave.yml
ceph-dev-build/build/build_osc

Previously, packages were being written to `/var/tmp` which does not live on the intended 1TB SSD.

ceph-dev-build: Change build path for Leap builds

---

ansible/examples/slave.yml

This PR fixes unfortunate typo which I missed during review of the #1685

ansible: fix osc build-root typo for opensuse worker

---

ceph-dev-build/build/build_rpm
ceph-dev-new-build/build/build_rpm
scripts/build_utils.sh

because the consumers of ceph container images are referencing the
required images using
"${CONTAINER_REPO_HOSTNAME}/${CONTAINER_REPO_ORGANIZATION}/ceph:${SHA1}".
see ceph-container/contrib/build-push-ceph-container-imgs.sh.
but in a recent change, we push both the images built for el7 and for
el8 with the same tag. and the last one wins. this breaks the tests
which expect the cephadm and other tools included in an image built for
el8. but these tools are not included by el7 because of the missing
dependencies.
so we have at least two options
- stop building octopus+el7 container images
- use a different tag for octopus+el7 to avoid the racing and name collision.
before the 2nd change lands on ceph-container, we should have the 1st
one in ceph-build to unblock the builds of octopus. …

ceph-dev-*-build: reset CI_CONTAINER when building octopus for el7

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml

We do not need for now opensuse-15.1 builds, since
support of it is limited.
The current version of Leap is 15.2 and the 15.1
is going to be EOL, thus we are not going to spend
resources on it.
We can disable it back if required in future.

ceph-dev-new-trigger: disable leap15 for nautilus

---

ceph-container-nighlity/config/definitions/ceph-container-nightly.yml
ceph-container-prs/config/definitions/ceph-container-prs.yml

To avoid docker hub rate limit, we should use the authenticate docker
hub user like we're currently using in the build and publish jobs.
This adds the credentials for both ceph-container-prs and
ceph-container-nightly jobs.

ceph-container: inject registry credentials

---

scripts/build_utils.sh

Fixes a3f26c8ab781a5ffe54aedf45be9e373bede4d6c, which ended up
comparing [[ el7 == centos7 ]].
Follow-on fix for: https://tracker.ceph.com/issues/48162
Signed-off-by: Neha Ojha <nojha@redhat.com>

scripts/build_utils.sh: use correct DIST value for el7

---

ceph-pr-api/config/definitions/ceph-pr-api.yml
ceph-pull-requests/config/definitions/ceph-pull-requests.yml

Skip running make-check and ceph-api tests when the PR only contains
changes in certain dirs (doc/, .github/) or certain extensions (.rst,
.md, .txt). In any case, a Jenkins job can still be manually triggered
(`jenkins test...`).

ceph-pr,api-pr: skip when not needed

---

ceph-volume-ansible-prs/build/build

ceph-volume PRs against nautilus are failing for a while because it
tries to run against centos8 while the tox environment only defines
centos7 environments.
Let's enforce `DISTRO` environment variable when `ghprbTargetBranch` is
`nautilus` so we override the environment variable injected by Jenkins.

ceph-volume: fix nautilus PRs job

---

ceph-volume-ansible-prs/build/build

At the moment it's using ceph-ansible@master to deploy octopus and
nautilus which is wrong.

ceph-volume: set CEPH_ANSIBLE_BRANCH properly

---

scripts/build_utils.sh

I had initially planned on installing the self-signed cert globally but that was not advised.  See https://github.com/ceph/ceph-build/pull/1698#issuecomment-725840305
So we should curl insecurely.

build_utils: curl docker-mirror insecurely

---

ceph-ansible-prs/build/build

`ceph-volume simple scan` in octopus is broken and make the upgrade
testing scenario failing.
Until 15.2.8 is out, which will be the next release including the fix
for this. We can't make this scenario passing the CI.
Let's disable it temporarily.

ceph-ansible: disable update scenario on octopus

---

ceph-ansible-prs/build/build
scripts/build_utils.sh

If this playbook fails for some reason, it interrupts the teardown so
VMs aren't destroyed.

ceph-ansible: fix teardown

---

ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
ceph-pr-api/config/definitions/ceph-pr-api.yml

Applying same change as already applied by
https://github.com/ceph/ceph-build/pull/1426. A divergence has been
observed between `make check` job (ceph-pull-request) and the `make` in
ceph-pr-api job. For the same PR:
* ceph-pull-request `make check` passes
* ceph-pr-api `make` fails
This fix has been suggested by @sebastian-philipp

ceph-{api,dashboard}-pr: fix source branch ref

---

scripts/build_utils.sh

since both CentOS and RHEL now include the updated
gcc-toolset-9-gcc-9.2.1-2.3.el8.
see also https://bugzilla.redhat.com/show_bug.cgi?id=1853900

scripts/build_utils: do not add tchaikov/gcc-toolset-9 copr repo anymore

---

scripts/build_utils.sh

This playbook doesn't work in containerized context.
Importing ceph-defaults and ceph-facts fixes this issue.
This also adds some output that might be helpful.

ceph-ansible: refact write_collect_logs_playbook

---

teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml

Most of Ceph QE is in this group but may not necessarily be in (or need to be in) the 'ceph' group.

teuthology-pull-requests: whitelist red-hat-storage gh group

---

ceph-pull-requests/build/build

to avoid zbd backend bitrot, and for build test it in our "make check"
builds.

ceph-pull-requests: enable WITH_ZBD

---

ceph-dev-build/build/build_osc
ceph-dev-build/build/setup_osc

this change should address the failure like
```
+ RELEASE_BRANCH=quincy
+ case $RELEASE_BRANCH in
+ echo Not supported release '$RELEASE_BRANCH' by openSUSE
Not supported release $RELEASE_BRANCH by openSUSE
+ exit 1
```
see also https://shaman.ceph.com/builds/ceph/wip-yuval-fix-48963/6ae6c340188bb4cda209cbc795db104d877b4516/default/250831/

ceph-dev-build: update {build,setup}_osc for quincy

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml

SUSE is not going to support ceph except of octopus anymore

disable leap15 for master and pacific

---

scripts/build_utils.sh

CentOS 8.3 changed reponames to lowercase.  Try original MixedCase first, and iff that fails, try lowercase.

scripts/build_utils.sh: handle lowercase CentOS dnf repo names

---

tcmu-runner/build/build_rpm
tcmu-runner/config/definitions/tcmu-runner.yml

Add "available arch" arm64, and fix build_rpm script to use aarch64
Also limit aarch64 build to CentOS 8

tcmu-runner: fix for arm64/aarch64

---

ceph-dev-new-setup/build/build
ceph-dev-setup/build/build
ceph-setup/build/build

this flag silences a false-positive from valgrind in boost::context:
```
<error>
<unique>0x0</unique>
<tid>124</tid>
<kind>InvalidRead</kind>
<what>Invalid read of size 8</what>
<stack>
<frame>
<ip>0x52FF7E7</ip>
<obj>/usr/lib64/libradosgw.so.2.0.0</obj>
<fn>spawn::detail::continuation_context::resume()</fn>
</frame>
</stack>
<auxwhat>Address 0x57f65728 is in a rw- anonymous segment</auxwhat>
</error>
```
Fixes: https://tracker.ceph.com/issues/48963

build: notcmalloc builds enable WITH_BOOST_VALGRIND

---

ceph-volume-ansible-prs/build/build

Since, ceph-ansible stable-6.0 has been branched for deploying pacific,
we should use this branch in ceph-volume testing.

ceph-volume-prs: use ceph-ansible@stable-6.0 for pacific

---

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml

The add-osds.yml playbook was dropped as of 5.0

ceph-ansible: remove add_osds jobs

---

ceph-dev-cron/config/definitions/ceph-dev-cron.yml
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

Nobody will use them and crimson is failing anyway

ceph-dev: Disable arm64 notcmalloc and crimson builds

---

ceph-dev-build/build/build_rpm
ceph-dev-cron/config/definitions/ceph-dev-cron.yml
ceph-dev-new-build/build/build_rpm
ceph-dev-new-setup/build/build
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-dev-new/config/definitions/ceph-dev-new.yml
ceph-dev-setup/build/build
ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
ceph-dev/config/definitions/ceph-dev.yml
ceph-setup/build/build

We no longer need notmcalloc packages.  Vagrant works now.

Disable notcmalloc builds!

---

ceph-dev-build/build/validate_deb
ceph-dev-build/build/validate_osc
ceph-dev-build/build/validate_rpm
ceph-dev-new-build/build/build_mingw
ceph-dev-new-build/build/setup_mingw
ceph-dev-new-build/build/validate_mingw
ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml
ceph-dev-new/config/definitions/ceph-dev-new.yml

ceph-dev-new: add Windows build
We're going to do a Windows build using Mingw as part of the
ceph-dev-new job.
"windows" is added as a valid distro. The "validate_mingw" script
will ensure that we're running on top of a Linux distro that the
Windows build script supports (currently just Ubuntu and Suse
distros).

ceph-dev-new: add Windows build

---

ceph-dev-new-build/build/build_mingw

The environment variables should be placed before the command.

ceph-dev-new-build: fixed windows build environment variables

---

ceph-dev-new-build/build/build_mingw
ceph-dev-new-build/build/setup_mingw

Also fixed the chacra endpoints to be consistent between the setup and
build steps.

ceph-dev-new-build: extract artifacts prior to attempting windows build

---

ceph-dev-new-build/build/build_mingw
ceph-dev-new-build/build/setup_mingw
ceph-dev-new-build/build/validate_mingw

The Windows builds that are generated right now are unusable due to
known Mingw runtime bugs.
We need Ubuntu Focal or later, for which reason we're going to use
pbuilder.

ceph-dev-new-build: cross-compile Windows targets using pbuilder

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

ceph-dev-new-trigger: build windows for pacific and master

---

ceph-ansible-nightly/build/build

This adds Pacific release based on CentOS 8 like Octopus.

ceph_ansible_nightly: add pacific centos release

---

ansible/examples/slave.yml

From the man page:
```
-T x, --runtime=x
Execution of tmpreaper will aborted after x seconds; this is to prevent attacks that create many, many files.  By default the timeout is set to 55 seconds.  A value of 0 will disable this feature, which is not advised as this feature prevents possible
race-conditions between different instances of tmpreaper.
```
So tmpreaper wasn't running for the past week since I set this up because there was so much to clean up that it'd time out.  These are Jenkins builders where the primary user already has sudo access so there's no real use to locking down tmpreaper.

ansible: Disable timeout on tmp{watch,reaper}

---

nfs-ganesha/build/build_deb
nfs-ganesha/build/build_rpm

since recent changes in shaman, the query for setting `REPO_URL` must be
updated.
This should fix the builds that are currently broken.

nfs-ganesha: fix devel builds

---

nfs-ganesha/build/build_deb
nfs-ganesha/build/build_rpm

7173ede7ec472b555c137093cb30e272ce1868cd was an attempt to fix the
nfs-ganesha job but it's using the wrong url. This commit fixes it.

nfs-ganesha: fix wrong url for setting REPO_URL

---

scripts/build_utils.sh

This reverts commit 58afbde0aead09adc1f7af06e8491670e1acd614.
See https://github.com/ceph/ceph-build/issues/1770

Revert "build_utils.sh: Prefer python3 instead of python2 for virtual envs

---

scripts/sync-push

Previous directory listing behavior:
```
octopus-15.2.10
octopus-15.2.4
octopus-15.2.5
octopus-15.2.6
octopus-15.2.7
octopus-15.2.8
octopus-15.2.9
```
Desired (and current with this PR) listing behavior:
```
octopus-15.2.4
octopus-15.2.5
octopus-15.2.6
octopus-15.2.7
octopus-15.2.8
octopus-15.2.9
octopus-15.2.10
```
This wasn't discovered until now because the `$newgen` stuff I do in this script only applies to Octopus for now.  Octopus only had single digit minor release versions (15.x.{1..9}) until 15.2.10.  The symlink didn't get updated to download.ceph.com/rpm-octopus still pointed to download.ceph.com/rpm-15.2.9 since it was last in the directory listing.

sync-push: Print releases in order

---

scripts/build_utils.sh

Not sure what happened between 0.229.1 vs 0.230.4 but seems `--use-network no` is now the default.  Discovered on a Focal builder.

build_utils: Use network in pbuilder env

---

ansible/examples/slave.yml

ansible: Install software-properties-common on deb builders

---

ceph-dev-build/config/definitions/ceph-dev-build.yml
ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml
scripts/build_utils.sh

We ran into an issue today where the internal mirror was temporarily unavailable.  The job fell back to docker.io and despite the fact that we're not using it all that much, we still got rate limited.  I suspect other tenants in the Community Cage are still pulling from docker.io anonymously.
This PR will have us login (with a higher rate-limit).

ceph*build: Login to docker.io if needed

---

scripts/build_utils.sh

Let's try this again.  I updated the few Xenial builders we had to Bionic so we should get better results now.  See https://github.com/ceph/ceph-build/issues/1770#issuecomment-801559246

build_utils.sh: Prefer python3 instead of python2 for virtualenvs

---

scripts/build_utils.sh

Started seeing
```
+ /tmp/venv.ivc8u2qcCO/bin/pip install --no-binary=:all: --upgrade --exists-action=i --find-links=file:///home/jenkins-build/.cache/pip --no-index 'jenkins-job-builder>=3.5.0'
Looking in links: file:///home/jenkins-build/.cache/pip
Collecting jenkins-job-builder>=3.5.0
Collecting six>=1.9.0 (from jenkins-job-builder>=3.5.0)
Collecting PyYAML<6,>=3.10.0 (from jenkins-job-builder>=3.5.0)
Could not find a version that satisfies the requirement wheel (from versions: )
No matching distribution found for wheel
```
Even 21.0.1 on Ubuntu 16.04 was failing.  It's just time to pin a newer version.

build_utils: Start using pip 21.0.1 instead of 10.0.0

---

ceph-pr-commits/build/build
ceph-pull-requests/config/definitions/ceph-pull-requests.yml

for better developer experience

ceph-pull-requests: use XUnit for publishing the test result of ctest

---

scripts/dashboard/install-e2e-test-deps.sh

since we've moved to ubuntu focal for running "make check", "ceph-dashboard-pull-requests"
and "ceph-pr-api" tests. and ubuntu focal does not package python2 packages
for python-scipy or python-routes. let's just install the python3
packages.
this change is related to nautilus builds. because nautilus is the last
release which supports python2.

ceph-dashboard-pull-requests: install python3 packages only

---

scripts/build_utils.sh

for using more C++17 compliant compiler

scripts/build_utils.sh: use gcc-9 from ppa on bionic

---

ceph-pull-requests/config/definitions/ceph-pull-requests.yml

otherwise make check, at least, fails

ceph-pull-requests: skip xunit publisher if no test files present

---

ceph-api-nightly/config/definitions/ceph-api-nightly.yml
ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
ceph-pr-api/config/definitions/ceph-pr-api.yml
ceph-pr-docs/config/definitions/ceph-pr-docs.yml
ceph-pull-requests/config/definitions/ceph-pull-requests.yml
teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml

All of Jenkins builders are running Ubuntu Focal.  They all have the bionic label.  They also have the xenial label but that's only because we're still building packages *for* Xenial.  But not *on* Xenial.

multiple PR jobs: Run on any Ubuntu node

---

scripts/build_utils.sh

otherwise the URL is not reachable with quotes in it.

scripts/build_utils.sh: should not quote --mirror option

---

ansible/examples/slave.yml

One of the packages we *do* want to install (software-properties-common maybe) pulls in unattended upgrades.  It's not a strict dependency so we can remove it after package install.  It's the only package that gets removed.

ansible: Remove unattended-upgrades after package install

---

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml

This adds a missing nightly job 'filestore_to_bluestore'

ceph-ansible: add a nightly job

---

ceph-volume-nightly/build/build
ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml

Mimic was already removed and Luminous is EOL so no need to keep jobs
for this release.

ceph-volume-nightly: remove luminous

---

ceph-dev-build/build/build_osc
ceph-dev-build/build/setup_osc

use openSUSE Leap 15.3 repository for pacific and quincy
Fixes: https://tracker.ceph.com/issues/50563
Signed-off-by: Michael Fritch <mfritch@suse.com>

ceph-dev-build: update {build,setup}_osc

---

cephadm-ansible-prs/build/build
cephadm-ansible-prs/build/teardown
cephadm-ansible-prs/config/JENKINS_URL
cephadm-ansible-prs/config/definitions/ceph-ansible-prs.yml

This adds a job definition for cephadm-ansible.
For now it doesn't run anything, it's just adding the definition into
jenkins so we can start setting up the corresponding repository
(cephadm-ansible).

cephadm-ansible: add initial job

---

ceph-dev-new-setup/build/build
ceph-dev-setup/build/build
scripts/build_utils.sh

see also https://tracker.ceph.com/issues/39703, to silence the warning
std::allocator<void> is deprecated in C++17 and will be removed in
C++20, so stop using allocator<void> in quincy and up.
but the libtcmalloc shipped by bionic is still buggy (v2.5), so we should not
build qunincy and up with tcmalloc on this distro.
in this change, we only build with tcmalloc on non-bionic distro.

ceph-dev-*-setup: use libc allocator when building quincy on bionic

---

ceph-dev-new-setup/build/build
ceph-dev-setup/build/build
scripts/build_utils.sh

$DIST env variable is not set by ceph-dev-new-setup, as it prepares
the dist tarball for building on different distros. to build with
tcmalloc if gperftools 2.6.2 is available, we leave it to cmake to
decide the allocator to use. because, if ALLOCATOR is not specified,
cmake first tries to find gperftools, and falls back to JeMalloc, and
the libc allocator. after quincy, the fix for gperftools <2.6.2 is
dropped, and gperftools >= 2.6.2 is required, so it's safe. before
quincy, the fix gperftools <2.6.2 is still included, so it's also safe.

ceph-dev-*-setup: do not specify ALLOCATOR

---

kernel/build/build_deb

Undo the damage caused by linux.git commit 82526ef43399 ("kbuild:
deb-pkg: change the source package name to linux-upstream").
We don't build a source package, but the source package name gets
embedded in the package metadata and ends up affecting the paths in
the repository generated by chacra.

kernel: specify KDEB_SOURCENAME for make bindeb-pkg

---

ceph-ansible-nightly/build/build
ceph-ansible-scenario/build/build

to address the regression introduced by e302eaabb977f3e93b1a7005c879f4b2eba581fc

ceph-ansible*: pass $TEMPVENV to start_tox

---

ceph-ansible-pr-syntax-check/build/build

commit b09f6470745a09ce4fce0265cb7a22a56b049886 supposed to fix
regression introduced by e302eaabb977f3e93b1a7005c879f4b2eba581fc missed
the ceph-ansible-pr-syntax-check job, so the CI is still failing like
following:
```
[ceph-ansible-pr-syntax-check] $ /bin/bash /tmp/jenkins6031146002439656501.sh
+ set -e
+ virtualenv
You must provide a DEST_DIR
Usage: virtualenv [OPTIONS] DEST_DIR
```

ceph-ansible-syntax: fix broken job

---

ceph-ansible-pr-syntax-check/build/build

add back venv creation that has been removed accidentally by
commit 3d832da831f0b938faa6f845617b0257bda184f4

ceph-ansible-syntax: create virtualenv after dir creation

---

teuthology-pull-requests/build/build

it was an oversight in e302eaabb977f3e93b1a7005c879f4b2eba581fc

teuthology-pull-requests: call create_venv_dir()

---

kernel/build/setup

kernel: Export sha1 as an env variable so shaman build URLs work

---

ceph-grafana/build/build
ceph-grafana/config/definitions/ceph-grafana.yml

This job builds a ceph-grafana container for a specific branch of Ceph and a specific architecture.  There are variables in the ceph.git Makefile that it invokes for versions of grafana and other included tools, but those are not currently exposed as parameters in this build job.
This job could be called by a parent job that builds both architectures on demand or via some trigger yet to be discussed.
This job's code depends on changes in https://github.com/ceph/ceph/pull/41559.

Add ceph-grafana job

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
scripts/build_utils.sh

in short, we don't need to test on bionic anymore for couple reasons:
- for accessing newer GCC
- for accessing more packages
see the discussion at
https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/BW5NKQ4KTOPV7OYUBUHVDVCSH72LVIEO/
the only qa suite referencing ubuntu 18.02 is the qa/suites/orch/rook/smoke,
but it deploys ceph using Rook, and the container image of Ceph is
based on CentOS, so stop building on ubuntu/bionic does not
break it, despite the fact that 18.02 is included by
qa/suites/orch/rook/smoke/0-distro.

ceph-dev-*-trigger: stop building master on bionic

---

ceph-pr-api/config/definitions/ceph-pr-api.yml

While other Jenkins jobs don't filter by specific branches, the API
tests do, so we need to support 'feature-*' branch syntax.

pr-api: trigger on feature branches

---

ceph-ansible-nightly/build/build
ceph-ansible-prs/build/build
ceph-ansible-scenario/build/build
ceph-container-nighlity/build/build
ceph-container-prs/build/build
scripts/build_utils.sh

This can't be normal.
```
[jenkins-build@smithi020 ~]$ vagrant global-status
id       name        provider state     directory                                                                                                                                                      
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
531ccc7  osd3        libvirt running   /home/jenkins-build/build/workspace/ceph-ansible-nightly-luminous-centos-container-stable-3.1-purge_filestore/tests/functional/fs-osds/container               
b1fa008  osd5        libvirt running   /home/jenkins-build/build/workspace/ceph-ansible-nightly-luminous-centos-container-st …
```

ceph-{ansible,container}*: Globally destroy all stale VMs

---

scripts/build_utils.sh

Fixes
```
+ sudo virsh undefine container_rgw0_1623696405_fb24199d9194c338f3d6
error: Refusing to undefine while domain managed save image exists
```
and subsequent
```
+ sudo service libvirt-guests restart
Redirecting to /bin/systemctl restart libvirt-guests.service
Job for libvirt-guests.service failed because the control process exited with error code.
See "systemctl status libvirt-guests.service" and "journalctl -xe" for details.
Build step 'Conditional step (single)' marked build as failure
Jun 15 15:40:10 braggi19 libvirt-guests.sh[44513]: Resuming guest container_rgw0_1623696405_fb24199d9194c338f3d6: error: Failed to start domain container_rgw0_1623696405_fb24199d9194c338f3d6
Jun 15 15:40:10 braggi19 libvirt-guests.sh[44513]: error: Network not found: no network with matching name …
```

scripts/build_utils.sh: Remove virsh save images

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

smithi and ovh workers aren't enough powerful, let's use braggi and
adami instead for those jobs.

ceph-ansible-prs: use braggi for biggest jobs

---

ansible/examples/centos8-vagrant.yml

Seeing weird random failures with 2.2.16.

ansible: Pin centos8 vagrant builders to 2.2.10

---

ansible/examples/centos8-vagrant.yml
ansible/examples/slave.yml

The latest version (and possibly older) 0.5.3 is giving us tons of issues.
- VMs hanging on `vagrant up`
- `vagrant ssh-config` failing
Not to mention we have to manually build libssh as well as krb5.
Let's not mess with all that.
With this PR, we also don't /need/ to run centos8-vagrant.yml.  It can be used to RE-install vagrant but the separate playbook is no longer required.

ansible: Pin vagrant-libvirt to 0.3.0

---

ansible/examples/slave.yml

So the vagrant-libvirt project itself admits that it does not support CentOS8.
Jobs /usually/ pass on the smithi builders (CentOS7.9, Vagrant 2.2.3, and vagrant-libvirt 0.3.0) so let's try running that everywhere.

ansible: Pin CentOS7 vagrant-libvirt to 0.3.0

---

scripts/build_utils.sh

curl and sudo are missing.
This reverts commit 92b5739f271a263d58bd7fe6ef8c8000f3cb4204.

Revert "add repo update for arrow installation (ubunto/centos)."

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

smithi nodes aren't enough powerful for that job, let's run it on either
braggi or amadi

ceph-ansible-prs: don't run all_in_one on smithi

---

ceph-ansible-prs/build/teardown

Occasionally having VMs come up but not get an IP.  Or vagrant thinks they got an IP but didn't.  This is impossible to debug after the VMs in the job are torn down so let's spit out some debug info before that.

ceph-ansible-prs: Debug vagrant problems

---

ansible/examples/slave.yml

This is so I can skip it when I'm setting up a new CentOS 8 Vagrant builder.
https://wiki.sepia.ceph.com/doku.php?id=production:jenkins.ceph.com&#setting_up_new_jenkins_builder

ansible: Give registration tasks a tag

---

ceph-volume-test/config/definitions/ceph-volume-test.yml

This is making some tests fail in the CI like following:
```
+ /tmp/venv.LBZdiW0Nx4/bin/tox --workdir=/tmp/tox.pQhNDR2lrs -vre
xenial-bluestore-mixed_type -- --provider=libvirt
using tox.ini:
/home/jenkins-build/build/workspace/ceph-volume-scenario/src/ceph-volume/ceph_volume/tests/functional/lvm/tox.ini
(pid 1864)
ERROR: unknown environment 'xenial-bluestore-mixed_type'
```
it's picking up the wrong tox.ini file because SUBCOMMAND isn't injected
as it should be.

ceph-volume-test: add missing SUBCOMMAND definition

---

ceph-volume-test/config/definitions/ceph-volume-test.yml

SUBCOMMAND is missing for `centos7-bluestore-mixed_type` test.

ceph-volume-test: add missing SUBCOMMAND var

---

ceph-volume-test/config/definitions/ceph-volume-test.yml

Those jobs don't exist anymore in tox.ini of ceph-volume functional
tests. Let's remove them.

ceph-volume-test: cleanup

---

cephadm-ansible-prs/config/definitions/cephadm-ansible-prs.yml

This makes the cephadm-ansible job use the right credential id

cephadm-ansible: use dedicated credential-id

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

smithi nodes aren't enough powerful for that job, let's run it on either
braggi or amadi.

ceph-ansible-prs: don't run cephadm jobs on smithi

---

ceph-website/config/definitions/ceph-website.yml

The previous way this was configured would only build branches from this repo; no forks.  When a PR is submitted from a fork, the job would just build main.  Oops.

ceph-website: Build PR checkouts

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

This adds the purge-dashboards jobs for both container and non container
scenarios.
Those scenarios aren't triggered by default.

ceph-ansible-prs: add purge-dashboard jobs

---

scripts/build_utils.sh

the http://dl.bintray.com/apache/arrow/ mirror returns 403 "Forbidden"
now.

scripts/build_utils: use apache repo hosted by apache.jfrog.io

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-dev-new/config/definitions/ceph-dev-new.yml
ceph-dev-setup/build/build
scripts/build_utils.sh

1. if jaeger in branch name for ceph-ci: this shall only build focal and centos 8
default packages with jaeger on, the FLAVOR=jaeger gets exported to ceph_extra_args_flavor 
Jaeger can be useful when someone wants to do analysis with tracing, most preferably we want to use it on centos 8 and focal, for component of interest, that can be a perf/latency analysis for crimson to debugging operations in client, please use preferred method to produce ceph builds with jaeger as adding jaeger suffix to branch name. 
Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>

build_utils: set extra args for jaeger based on branch name

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

this should address the regression introduced by
99ac2b60d3e9c236802daf752d9924076151bf82

ceph-dev-new-trigger: add escape ) by adding \ before it

---

scripts/build_utils.sh

we don't use nocheck for disabling the "make check" dependencies,
instead, <pkg.ceph.check> is used to enable "make check" dependencies.
so they are not enabled by default.

scripts/build_utils: do not include nocheck in $PROFILES

---

scripts/build_utils.sh

otherwise the following "--use-network" would be taken as a profile,
and "yes" is used as the path to package's dsc file.

scripts/build_utils.sh: quote $PROFILES

---

ansible/examples/slave.yml

ansible: fakeroot-ng doesn't exist anymore

---

ceph-container-build-ceph-base-push-imgs-arm64/config/definitions/ceph-container-build-push-imgs.yml
ceph-container-build-ceph-base-push-imgs/config/definitions/ceph-container-build-push-imgs.yml

We're switching from docker.io registry for the ceph/ceph container images
to quay.io registry.
This requires to have a new credential-id in jenkins and update the
environment variables used by the ceph-container build script.

ceph-container: publish ceph/ceph to quay.io

---

ansible/roles/ceph-release/tasks/main.yml

should be replace the VERSION number in project(...). this is the
authentic place to set version number.

ansible: replace version number in project(..VERSION..)

---

ceph-grafana-trigger/build/build
ceph-grafana-trigger/config/definitions/ceph-grafana-trigger.yml

Build both x86_64 and arm64 containers using ceph-grafana job,
and then pull, create a combined manifest, and push, currently to
both docker.io and quay.io

add ceph-grafana-trigger job

---

ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml

since the dependencies on aarch64 are available now, and the "make
check" passes on this architecture also. let's test the PRs on arm64.
this change reverts 1e0b902baa33b3b972891779d2950e580bb18e63

ceph-pull-requests-arm64: reenable test on arm64

---

ansible/examples/slave.yml

This change will install the copr repo to the test slave nodes so we can install the `python3-asyncssh` dependency for non-containerized tests, needed for ceph/ceph/pull/42051. The copr repo has the `python3-asyncssh` package we need for cephadm.
Fixes: https://tracker.ceph.com/issues/44676
Signed-off-by: Melissa Li <li.melissa.kun@gmail.com>

ansible: install python3-asyncssh copr repo on EL8 for cephadm

---

ansible/examples/slave.yml

This reverts commit 733be223a72951db7e66eac0f28e379d83da54bd.
Discussion at https://github.com/ceph/ceph/pull/42051#issuecomment-888817516: on why it's not needed
Signed-off-by: Melissa Li <li.melissa.kun@gmail.com>

Revert "ansible: install python3-asyncssh copr repo on EL8 for cephadm"

---

ansible/examples/slave.yml

let's add python3-venv.
keep python3-virtualenv around for a while just in case.

ansible/examples/slave.yml: add python3-venv to python3_debs of debian

---

ceph-dashboard-cephadm-e2e/config/definitions/ceph-dashboard-cephadm-e2e.yml
scripts/dashboard/install-cephadm-e2e-deps.sh

To be merged after https://github.com/ceph/ceph/pull/42263
Project: run Dashboard E2E tests with cephadm as orchestrator backend
on dashboard/cephadm PRs.
Fixes: https://tracker.ceph.com/issues/51301

project config: dashboard-cephadm-e2e

---

ceph-container-build-push-imgs-arm64/config/definitions/ceph-container-build-push-imgs-arm64.yml
ceph-container-build-push-imgs-devel-nightly/config/definitions/ceph-container-build-push-imgs-devel-nightly.yml
ceph-container-build-push-imgs/config/definitions/ceph-container-build-push-imgs.yml
ceph-container-nighlity/config/definitions/ceph-container-nightly.yml
ceph-container-prs/config/definitions/ceph-container-prs.yml

We're switching from docker.io registry for the ceph/{daemon,daemon-base}
container images to quay.io registry.
This requires to have a new credential-id in jenkins and update the
environment variables used by the ceph-container build script.
This impacts image tags like:
- latest-xxxxx
- latest-xxxxx-devel
- latest-bis
- vX.Y.Z-stable-X.Y

container: publish daemon,daemon-base to quay.io

---

ceph-container-build-ceph-base-push-imgs-arm64/config/definitions/ceph-container-build-push-imgs.yml
ceph-container-build-ceph-base-push-imgs/config/definitions/ceph-container-build-push-imgs.yml
ceph-container-build-push-imgs-arm64/config/definitions/ceph-container-build-push-imgs-arm64.yml
ceph-container-build-push-imgs-devel-nightly/config/definitions/ceph-container-build-push-imgs-devel-nightly.yml
ceph-container-build-push-imgs/config/definitions/ceph-container-build-push-imgs.yml

Because we don't push to Docker Hub registry anymore, we don't need to have
that in the job display name.

container: update push jobs display name

---

ceph-api-nightly/config/definitions/ceph-api-nightly.yml

It's making dashboard e2e nightly fail: https://jenkins.ceph.com/job/ceph-api-nightly-master-e2e/

dashboard-nightly-e2e: add APPLITOOLS_API_KEY

---

ceph-build/build/setup_deb
ceph-build/build/setup_rpm
ceph-dev-build/build/setup_deb
ceph-dev-build/build/setup_osc
ceph-dev-build/build/setup_rpm
ceph-dev-cron/build/notify
ceph-dev-new-build/build/setup_deb
ceph-dev-new-build/build/setup_mingw
ceph-dev-new-build/build/setup_rpm
ceph-dev-new-trigger/build/notify
ceph-dev-trigger/build/notify
kernel/build/setup
nfs-ganesha-stable/build/build_deb
nfs-ganesha-stable/build/build_rpm
nfs-ganesha/build/build_deb
nfs-ganesha/build/build_rpm
scripts/build_utils.sh

it's identical to update_build_status(), apart from that it is only used
for creating the build status. but from the semantic point of view,
create is also an "update", IMHO. so consolidating them sounds like a
good move.

scripts/build_utils: remove create_build_status()

---

ceph-website-prs/config/definitions/ceph-website-prs.yml
ceph-website/config/definitions/ceph-website.yml

They're very low cost and 1 day's worth of builds is not useful

ceph-website*: Keep 20 builds

---

scripts/build_utils.sh

we started to have following error recently:
```
+ local path=/tmp/venv.0D0Gwn9bMl
+ '[' -d /tmp/venv.0D0Gwn9bMl ']'
+ command -v python3
+ virtualenv -p python3 /tmp/venv.0D0Gwn9bMl
/tmp/jenkins5609477504730019125.sh: line 106: virtualenv: command not found
```
instead of relying on `virtualenv`, let's use the builtin venv
module to create virtualenv.

scripts/build_utils.sh: use "python3 -m venv" to create venv

---

ansible/examples/slave.yml

We don't build for Jessie anymore

ansible: Stop installing Jessie key

---

ceph-build/build/build_rpm
ceph-dev-build/build/build_rpm
ceph-dev-new-build/build/build_rpm
scripts/build_utils.sh

For deb builds, this is all in build_utils.sh; for rpm, it's in
build_rpm for each build

ceph-*-build: add step to extract and store cephadm binary

---

ceph-api-nightly/config/definitions/ceph-api-nightly.yml
ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml

Fixes: https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/8764/consoleFull#-85362248744e9240e-b50a-4693-bac0-8a991bac86ac

dashboard-e2e: fix applitools BATCH_ID error

---

ceph-windows-test/build/run_tests
ceph-windows-test/config/definitions/ceph-windows-test.yml

Add a new freestyle Jenkins job that can be used to test a Ceph
Windows build uploaded to Chacra, on the Jenkins agents labeled with
`amd64`, `focal`, `libvirt`.
The Ceph Windows build is identified in Chacra using the following
Jenkins job parameters:
* `CEPH_WINDOWS_VERSION`
* `CEPH_WINDOWS_SHA1`
As a build step, the new job will execute the `./build/run_tests`
bash script. This script sets up a KVM virtual machine with Windows
Server 2019, that it's used to run the Ceph Windows unit tests from
the Chacra build. On top of that, it takes care of the everything
needed to run the Ceph Windows tests.

Add Ceph Windows testing job

---

ceph-container-lint/build/build

We don't want to run shellcheck on shell script removed by a pull
request.

ceph-container-lint: filter out file removed

---

ceph-container-lint/build/build

The pipe was removed in the previous change but it shouldn't.

ceph-container-lint: add missing pipe

---

ceph-container-flake8/build/build
ceph-container-lint/build/build

Otherwise we will still use an outdated container image.

container-{flake8,lint}: always pull the image

---

scripts/dashboard/install-cephadm-e2e-deps.sh

`ceph/make-dist` file and Angular 12 ([#43404](https://github.com/ceph/ceph/pull/43404)) require nodejs >= 12.

ceph-dashboard-cephadm-e2e job: update nodejs to v12

---

ceph-windows-pull-requests/build/build
ceph-windows-pull-requests/config/definitions/ceph-windows-pull-requests.yml
ceph-windows-test/build/get_chacra_build
ceph-windows-test/config/definitions/ceph-windows-test.yml
scripts/build_utils.sh
scripts/ceph-windows/cleanup_tests
scripts/ceph-windows/run_tests

* Update `ceph-windows-test` job
* Create `scripts/ceph-windows` directory with the common scripts for the Ceph Windows testing.
* Move `run_tests` script to `scripts/ceph-windows`.
* Remove VM image caching from the `run_tests` script.
* Add `cleanup_tests` script to `scripts/ceph-windows`, and call this as a post-build step when the job is aborted.
* Add `get_chacra_build` build script, and refactor away this logic from the `run_tests` script.
* Move cleanup Windows tests function to `scripts/build_utils.sh`.
* Add `ceph-windows-pull-requests` job
* Used to run Windows tests against Ceph pull requests.

Add ceph-windows-pull-requests job & Update ceph-windows-test job

---

ceph-windows-test/build/get_chacra_build
ceph-windows-test/config/definitions/ceph-windows-test.yml

The default value is `master`, since Windows builds for the master
branch were enabled by https://github.com/ceph/ceph-build/pull/1928.
The `get-bin.py` script is updated to support `--branchname` parameter:
https://github.com/ceph/ceph-win32-tests/pull/1

Add branch param to the `ceph-windows-test` job

---

ceph-api-nightly/config/definitions/ceph-api-nightly.yml
ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml

We don't need to build tests for this job and also this change is a workaround for: https://tracker.ceph.com/issues/53582
Also do not build tests for nautilus nightly jobs.

ceph-dashboard-pull-requests (e2e) job: do not build tests, only build ceph

---

ceph-dashboard-cephadm-e2e-nightly/config/definitions/ceph-dashboard-cephadm-e2e-nightly.yml

Project: run the ceph dashboard cephadm e2e tests against master,
pacific and octopus

project config: ceph-dashboard-cephadm-e2e-nightly

---

scripts/build_utils.sh
scripts/ceph-windows/cleanup
scripts/ceph-windows/setup_libvirt_vm
wnbd-build/build/build
wnbd-build/build/failure
wnbd-build/build/setup
wnbd-build/config/definitions/wnbd-build.yml

* Add the Jenkins job used to build the `wnbd` project.
* Add the following utils functions: `ssh_exec`, `scp_upload`, `scp_download`.
* Add `./scripts/ceph-windows/cleanup` script that can be used as a
post-build step to clean up the Windows test / build environment.
* Add `./scripts/ceph-windows/setup_libvirt_vm` script used to spawn a
libvirt VM with the Windows test / build environment.
* Upload the build artifact to chacra.

[wnbd-build] Add new Jenkins job to build the wnbd project

---

ceph-windows-pull-requests/config/definitions/ceph-windows-pull-requests.yml
ceph-windows-test/config/definitions/ceph-windows-test.yml
scripts/build_utils.sh
scripts/ceph-windows/cleanup_tests
scripts/ceph-windows/run_tests

Refactor the Ceph Windows Jenkins jobs (`ceph-windows-test` and `ceph-windows-pull-requests`) with common scripts from `scripts/ceph-windows` and `scripts/build_utils.sh`
The purpose of this change is to eliminate code duplication.

Refactor `ceph-windows-test` and `ceph-windows-pull-requests` jobs

---

ceph-windows-installer-build/build/build
ceph-windows-installer-build/build/failure
ceph-windows-installer-build/build/setup
ceph-windows-installer-build/config/definitions/ceph-windows-installer-build.yml

The `ceph-windows-installer` project creates a Windows MSI installer
that can be used to setup Ceph on Windows.
It bundles the `wnbd` driver, and the `ceph` binaries.
These are downloaded from Chacra prior to building the installer.
Depends on: https://github.com/ceph/ceph-build/pull/1935

[ceph-windows-installer-build] Add Jenkins job to build the ceph-windows-installer project

---

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml

ceph-perf-pull-requests: When enabling llvm-toolset-10 copr repo, dnf
uses the following URL layout:
https://copr.fedorainfracloud.org/coprs/'repository'/repo/'distribution-version'/dnf.repo?arch='architecture'
The current merged command for enabling specifies repo, distribution and architecture
but not version.
This causes an incorrect url to be calculated and returns a 404 error as seen below:
https://copr.fedorainfracloud.org/coprs/tchaikov/llvm-toolset-10/repo/centos-stream/dnf.repo?arch=x86_64
When centos-stream-8 is specified the repo is fetched:
https://copr.fedorainfracloud.org/coprs/tchaikov/llvm-toolset-10/repo/centos-stream-8/dnf.repo?arch=x86_64
Signed-off-by: Christopher Hoffman <choffman@redhat.com>

ceph-perf-pull-requests: enable llvm-toolset-10 repo using distribution-version-architecture format.

---

ceph-dashboard-cephadm-e2e-nightly/config/definitions/ceph-dashboard-cephadm-e2e-nightly.yml

In the nightly runs we saw that the ceph_cluster.yml file which we used
to deploy kcli plans is not up-to-date with the master one. It cause
problems in the nightlies. We've narrowed down the problem is with the basedir
and and also with the path difference in the dependency script and the location of
ceph. So changing the workspace path to workspace/ceph.
Also jenkins adviced against using basedir in the jenkins config

ceph-dashboard-cephadm-e2e-job: update workspace path 

---

cephadm-ansible-prs/config/definitions/cephadm-ansible-prs.yml

This will allow using default images from cephadm instead of
maintaining what needs to be used in the tox.ini file of cephadm-ansible.

cephadm-ansible: add new credentials

---

ceph-windows-image-build/README.md
ceph-windows-image-build/build/autounattend.xml
ceph-windows-image-build/build/build
ceph-windows-image-build/build/cleanup
ceph-windows-image-build/build/install-openssh-server.ps1
ceph-windows-image-build/build/install-virtio-guest-tools.ps1
ceph-windows-image-build/build/install-windows-updates.ps1
ceph-windows-image-build/build/setup.ps1
ceph-windows-image-build/config/definitions/ceph-windows-image-build.yml
scripts/build_utils.sh

Adds a new freestyle Jenkins job that builds, unattended, the
Windows Server 2019 qcow2 image used in the Ceph CI with libvirt.

[ceph-windows-image-build] Add job to build the CI Windows image

---

ceph-windows-installer-build/config/definitions/ceph-windows-installer-build.yml
wnbd-build/config/definitions/wnbd-build.yml

Add daily triggers for `wnbd-build` and `ceph-windows-installer-build`.
The ceph-windows installer trigger time is offset by 1 hour to
allow the `wnbd` build to be uploaded to Chacra.

Add triggers for `wnbd-build` and `ceph-windows-installer-build`

---

ceph-build/build/build_rpm
ceph-dev-build/build/build_rpm
ceph-dev-new-build/build/build_rpm
scripts/build_utils.sh

https://github.com/ceph/ceph-build/pull/1919 added a conditional
test to check for cephadm package existence (so the code to extract
cephadm could work on older builds that did not have a cephadm package).
However, it used bash's [[ operator, and that doesn't expand file globs
in its arguments, so it effectively stopped creating the cephadm
binary altogether.
Switch to [, which doesn't have that problem.

ceph-{,dev,dev-new} build: fix conditional for cephadm package test

---

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml

Ensure version of libarchive is installed due to cmake dependency: https://access.redhat.com/solutions/6068431
Error message encountered:
cmake3: symbol lookup error: cmake3: undefined symbol: archive_write_add_filter_zstd
Related: https://github.com/ceph/ceph/pull/42294
Signed-off-by: Christopher Hoffman <choffman@redhat.com>

ceph-perf-pull-requests: update libarchive

---

scripts/build_utils.sh

arrow is a runtime dependency, so we won't be relying on this apache repo
~~for ubuntu, we'll submodule the arrow library. ubuntu/debian have all of arrow's dependencies~~
~~for centos, we need this 'storage sig' repo for both the arrow library and its missing utf8proc dependency~~
edit: we'll build arrow from submodule until it's available from distros

arrow: remove apache jfrog repositories

---

ceph-dev-build/build/build_rpm
ceph-dev-new-build/build/build_rpm
scripts/build_utils.sh

Non-stream CentOS8 containers no longer work because the BaseOS and AppStream repos moved.  We now use the centos/centos:stream8 container image as our BASEOS_TAG.  Except that container lives on quay.io and not dockerhub.
docker-mirror.front.sepia.ceph.com:5000 can only mirror one registry.  We'll keep it as mirroring dockerhub.

ceph-dev*build: Stop using docker-mirror

---

ceph-pr-render-docs/config/definitions/ceph-pr-render-docs.yml
teuthology-docs/config/definitions/teuthology-docs.yml

We're using RTD now.  The docs Jenkins builder is retired.

{ceph-pr-render,teuthology}-docs: Disable job

---

scripts/dashboard/install-cephadm-e2e-deps.sh

Need to recreate the network to avoid issues like ssh ing into the
environment.
Last runs with this change in the configuration is a success.
Fixes: https://tracker.ceph.com/issues/54131
Signed-off-by: Nizamudeen A <nia@redhat.com

dep: delete the network before creating it again

---

ceph-dev-container-only/build/build_rpm
ceph-dev-container-only/build/failure
ceph-dev-container-only/config/definitions/ceph-dev-container-only.yml

This job will allow users to build a container for https://quay.ceph.io/repository/ceph-ci/ceph?tab=tags given a branch name.  Should work for ceph.git and ceph-ci.git.
This is mostly useful for when packages and a repo successfully get built for a ceph-dev*build job but the container build fails.

ceph-dev-container-only: Create job

---

ceph-windows-installer-build/build/build
ceph-windows-installer-build/build/setup
ceph-windows-installer-build/config/definitions/ceph-windows-installer-build.yml

Remove the `FORCE` parameter from the `ceph-windows-installer-build`
Jenkins job, and use it by default.
This job builds the installer from source code, and it bundles
the Ceph binaries and the WNBD driver.
Therefore, the logic to skip the build if the latest installer commit
didn't change is not useful, because the installer might contain
different Ceph binaries and WNBD driver.

[ceph-windows-installer-build] Remove `FORCE` parameter

---

ceph-grafana-trigger/build/build
ceph-grafana-trigger/config/definitions/ceph-grafana-trigger.yml

update grafana container image version to 8.2.6
Signed-off-by: Aashish Sharma <aasharma@redhat.com>

ceph-grafana-trigger: update grafana container image version to 8.2.6

---

ceph-iscsi-tox/config/definitions/ceph-iscsi-tox.yml

mira042, the only node with python3 label, was retired two months ago.

ceph-iscsi-tox: replace python3 node label constraint

---

ansible/examples/master.yml
ceph-api-nightly/config/definitions/ceph-api-nightly.yml
ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
ceph-pr-api/config/definitions/ceph-pr-api.yml

archive the logs as an artifact in both pr and nightly jobs of
dashboard frontend e2es.

dashboard-e2e-job: get mgr logs as an artifact

---

scripts/build_utils.sh

As we continue to slowly move on from python2, this is a relic that should get future-proofed.

scripts: Use bash instead of python to determine is_not_tar

---

scripts/build_utils.sh

String format appears to be incompatible with the python version being
used and so this is causing more failures than the original.
This reverts commit 4668da7fb015138b626ad21d2519c76a64e390a0.

Revert "scripts: Use python3 to test is_not_tar"

---

ceph-api-nightly/config/definitions/ceph-api-nightly.yml
ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml

E2E nightlies have been failing for a while due to visual regression issues (browser upgrades). However, Applitools doesn't seem to be able to mark those issues as resolved (because they need to be resolved in the baseline branch: `master`, `pacific`, etc, and Applitools doesn't find any branch with that name):
Adds correct Branch to Nightly jobs:
* ~~`$CEPH_LOCAL_BRANCH` instead of `$CEPH_BRANCH`: `master` vs. `origin/master`~~ (it didn't work: it needs a specific option enabled in the git plugin).
* Let's try with shell substring replacement: `${{GIT_BRANCH#*/}}`. Yesss, it now works:
* Renames Batches with a more intuitive naming (`PR-<number>`, `Nightly-<branch>`).
```sh
+ export APPLITOOLS_BATCH_ID=ceph-api-nightly-master-e2e_jenkins-ceph-api-nightly-master-e2e-880
+ export …
```

dashboard/nighlty: fix applitools baseline

---

ceph-pull-requests/build/build

WITH_RBD_RWL variable is added in https://github.com/ceph/ceph/pull/45872.

ceph-pull-requests: enable the RWL mode of RBD persistent cache

---

ceph-ansible-docs-prs/config/definitions/ceph-ansible-docs-prs.yml
ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
ceph-ansible-rpm/config/definitions/ceph-ansible-rpm.yml
ceph-container-flake8/config/definitions/ceph-container-flake8.yml
ceph-container-lint/config/definitions/ceph-container-lint.yml
ceph-container-nighlity/config/definitions/ceph-container-nightly.yml
ceph-container-prs/config/definitions/ceph-container-prs.yml

ceph-{ansible,container}*: Use CentOS8 builders instead of 7

---

ceph-dashboard-cephadm-e2e-nightly/config/definitions/ceph-dashboard-cephadm-e2e-nightly.yml
ceph-dashboard-cephadm-e2e/config/definitions/ceph-dashboard-cephadm-e2e.yml

If the provided pattern for eg: `log/*.log` is not found, archiving takes
way too longer to fail and that increased the job time to 1 hour on our
cephadm dashboard e2e jobs. Instead I added a pattern like `log/**` and
this way it immediately failed when there is no logs. (In cephadm
dashboard e2e, there
won't be any logs if the job is succesfull and the logs are saved only
when the job is failed)
This is yesterday's nightly job which took more than 1hr to complete.
https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e-nightly-master/171/
This job ran with the current changes in PR and it took only 15 mins (usual time for a successful job run)
https://jenkins.ceph.com/job/ceph-dashboard-cephadm-e2e/3342/console

cephadm-dashboard-e2e: archiving takes too long to fail

---

wnbd-build/build/build
wnbd-build/build/setup
wnbd-build/config/definitions/wnbd-build.yml

Remove the `FORCE` parameter from the `wnbd-build` Jenkins job, and
use it by default.
The `wnbd` project is not updated that frequently, so the daily
build trigger mostly skips the Chacra upload. This is a problem
because when old Chacra artifacts are deleted, the `wnbd` build will
not be available in Chacra.
We need `wnbd` to always be available in Chacra, since the
Windows Teuthology tests will try to download it from there.

[wnbd-build] Remove `FORCE` parameter

---

ansible/examples/centos8-vagrant.yml
ansible/examples/slave.yml

The time finally came to update 2.jenkins.ceph.com's builders to CentOS8. Along with that change came the library issues mentioned here: https://github.com/vagrant-libvirt/vagrant-libvirt#additional-notes-for-fedora-and-similar-linux-distributions

ansible: Update playbooks to install newest vagrant&plugin

---

scripts/build_utils.sh

@guits and I think there's either a bug in `alternatives` or we just can't figure out how it's supposed to work.  Even with setting `alternatives --set python3 /usr/bin/python3.9`, python3.6 was still the "best" version according to `alternatives --display`.
So we'll just remove the other version entirely.
```
+ set_centos_python3_version python3.9
++ sudo alternatives --display python3
++ grep -e 'Current.*best.* version is'
++ awk '{ print $5 }'
++ sed 's/\.$//'
+ local CURRENT_PYTHON3_VERSION=/usr/bin/python3.6
+ local EXPECTED_PYTHON3_VERSION=python3.9
+ [[ /usr/bin/python3.6 =~ .*python3\.9 ]]
++ rpm -qf /usr/bin/python3.6
++ cut -d - -f1
+ PYTHON3_TO_REMOVE=python36
+ sudo dnf remove -y 'python36*'
Dependencies resolved.
=============================================================== …
```

build_utils.sh: Remove python3 versions we don't want

---

cephadm-ansible-prs/config/definitions/cephadm-ansible-prs.yml

The tox config in cephadm-ansible has now more than 1 test.
Let's rename from 'deploy_and_purge' to 'tox' so it's more generic

cephadm-ansible-prs: update scenario name

---

cephadm-ansible-prs/config/definitions/cephadm-ansible-prs.yml

el9 RPMs aren't available yet.

cephadm-ansible-prs: disable el9-functional

---

ceph-dev-build/config/definitions/ceph-dev-build.yml
ceph-dev-cron/config/definitions/ceph-dev-cron.yml
ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-dev-new/config/definitions/ceph-dev-new.yml
ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
ceph-dev/config/definitions/ceph-dev.yml
ceph-iscsi-cli-trigger/config/definitions/ceph-iscsi-cli-trigger.yml
ceph-iscsi-config-trigger/config/definitions/ceph-iscsi-config-trigger.yml
ceph-iscsi-tools-trigger/config/definitions/ceph-iscsi-tools-trigger.yml
ceph-iscsi-trigger/config/definitions/ceph-iscsi-trigger.yml
ceph-pr-arm-trigger/config/definitions/ceph-pr-arm-trigger.yml
kernel-trigger/config/definitions/kernel-trigger.yml
mita-deploy/config/definitions/mita-deploy.yml
rtslib-fb-trigger/config/definitions/rtslib-fb-trigger.yml
samba-trigger/config/definitions/samba-trigger.yml
tcmu-runner-trigger/config/definitions/tcmu-runner-trigger.yml

https://www.jenkins.io/changelog-stable/#v2.319.1
I don't know if it's a bug or what but giving the controller a "controller" label and instructing the jobs to run on that label only, they would still get stuck on `(pending—Waiting for next available executor on ‘builtin’)`.

Use Jenkins' 'built-in' magic phrase

---

scripts/build_utils.sh

There is no /etc/mock/epel-8-x86_64.cfg with the deprecation of CentOS 8.
```
[root@braggi07 mock]# ls -l /etc/mock/ | grep epel
-rw-r--r--. 1 root mock  201 Mar  3 07:18 alma+epel-8-aarch64.cfg
-rw-r--r--. 1 root mock  201 Mar  3 07:18 alma+epel-8-ppc64le.cfg
-rw-r--r--. 1 root mock  198 Mar  3 07:18 alma+epel-8-x86_64.cfg
-rw-r--r--. 1 root mock  200 Mar  3 07:18 centos+epel-7-ppc64le.cfg
-rw-r--r--. 1 root mock  197 Mar  3 07:18 centos+epel-7-x86_64.cfg
-rw-r--r--. 1 root mock  256 Mar  3 07:18 centos-stream+epel-8-aarch64.cfg
-rw-r--r--. 1 root mock  256 Mar  3 07:18 centos-stream+epel-8-ppc64le.cfg
-rw-r--r--. 1 root mock  253 Mar  3 07:18 centos-stream+epel-8-x86_64.cfg
-rw-r--r--. 1 root mock  256 Mar  3 07:18 centos-stream+epel-9-aarch64.cfg
-rw-r--r--. 1 root mock  256 Mar  3 …
```

build_utils: Fix get_distro to support CentOS Stream

---

scripts/build_utils.sh

For some reason, python36 is a dependency of python3-virtualenv.  python39 is not.
So removing python36 was removing python3-virtualenv.

build_utils.sh: Do not remove unwanted python3 versions

---

ceph-pull-requests/build/build

WITH_PMEM is added in
https://github.com/ceph/ceph/commit/17d2bc3707bb0078e2fa1b4eef31b39804e45135.
Signed-off-by: Yin Congmin <congmin.yin@intel.com>

ceph-pull-requests/build/build: enable WITH_PMEM

---

ceph-dashboard-cephadm-e2e/config/definitions/ceph-dashboard-cephadm-e2e.yml
ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml

[JUnit Plugin](https://plugins.jenkins.io/junit/)
[JJB Config](https://docs.openstack.org/infra/jenkins-job-builder/publishers.html?highlight=junit#publishers.junit)
TODO:

dashboard-pr: add JUnit tests

---

scripts/build_utils.sh

CEPH_EXTRA_RPMBUILD_ARGS="--with seastar"

build_utils: do not pass -DWITH_SEASTAR=ON for building crimson flavor

---

scripts/build_utils.sh

This makes tox pick the right tox config file when scenario is
'rbdmirror'

build_utils.sh: update start_tox()

---

ceph-dev-build/config/definitions/ceph-dev-build.yml
ceph-dev-setup/config/definitions/ceph-dev-setup.yml
ceph-dev/config/definitions/ceph-dev.yml

multijob projects only keep the lowest number of builds specified in build-discarder config.  So we only had 25 builds.  That only correlates to 3-5 days which isn't log enough to debug failed builds from a week ago, for example.

ceph-dev: Keep 14 days' worth of builds

---

ceph-setup/config/definitions/ceph-setup.yml
ceph/config/definitions/ceph.yml

Despite adding some logic to strip '-release' if it was accidentally entered, the ceph-setup job will build a tarball successfully.  However stripping '-release' doesn't get carried over to the `ceph-build` job so https://github.com/ceph/ceph-build/blob/main/ceph-build/config/definitions/ceph-build.yml#L56-L70 immediately exits 0.

ceph: Clarify branch name to enter

---

scripts/dashboard/install-cephadm-e2e-deps.sh

cephadm dashboard e2e's were throwing this error in some machines (eg: braggi16)
```docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "error adding seccomp filter rule for syscall clone3: requested action matches default action of filter": unknown```
Upon further debugging it was related to the runc version where in the
error prone machines the runc version is 1.01 while as per some recent
threads docker needs runc version of 1.02.
https://github.com/containerd/containerd/issues/6203#issuecomment-1006713706

dashboard-cephadm-e2e: update runc version

---

ceph-ansible-prs/build/build

Corresponding PRs:
- ceph/ceph-ansible/pull/7269 (stable-7.0)
- ceph/ceph-ansible/pull/7268 (stable-6.0)

ceph-ansible-prs: run rbdmirror against stable branches

---

scripts/build_utils.sh

we've used this repo in the past to get access to newer compiler versions. reenable it for ubuntu focal for access to gcc 11
note that these changes don't preserve the original behavior against old distros like trusty/xenial. if there is still interest in building against those releases, i can work through these differences:
trusty: PPA 7 -> 11
xenial: PPA 8 -> 11
bionic: does not use PPA (unchanged)

reenable ubuntu's toolchain ppa for c++20 support

---

ceph-windows-image-build/build/build
scripts/ceph-windows/setup_libvirt_vm

On some of the KVM hosts targeted by the Windows jobs, the main
interface within the VM will have a different NIC name.
Therefore, the command:
```
virsh domifaddr --source agent --interface Ethernet --full $VM_NAME
```
will not return anything, since the NIC name is not guaranteed to
have `Ethernet` name.
These changes improve how the VM IP is detected, by filtering the
guest NICs via MAC address to find the proper NIC. Furthermore, the
VM address belonging to the `default` virsh network is returned.

Improve Windows libvirt VM IP detection

---

scripts/dashboard/install-cephadm-e2e-deps.sh

as node.js 12 is being deprecated. and the oldest node.js which is
packaged by https://github.com/nodesource is node.js 14. see
https://github.com/nodesource/distributions#debinstall

dashboard-cephadm-e2e: bump node version to 14

---

ceph-build-pull-requests/build/build

as urllib3 v1.22 is not compatible with python3.10 which is shipped by
ubuntu jammy. see https://pypi.org/project/urllib3/1.22/
so, to run jjb in a python3.10 venv we should use a newer urllib.

ceph-build-pull-requests: use a newer urllib3 when installing jjb

---

ceph-build-pull-requests/build/build

now that we've bumped up the urllib3's version in
f2f9bec9da002ac07b27c5caf5131aeab196509c. the comment does not
apply anymore.

ceph-build-pull-requests: drop stale comment

---

scripts/ceph-windows/cleanup

Fixes:
```
+ [[ -x /home/jenkins-build/build/workspace/wnbd-build/cephadm ]]
+ sudo /home/jenkins-build/build/workspace/wnbd-build/cephadm rm-repo
[sudo] password for jenkins-build:
sudo: no password was provided
sudo: a password is required
Build step 'Execute scripts' changed build result to FAILURE
Build step 'Execute scripts' marked build as failure
```

windows: Check for cephadm binary before attempting to use it

---

ceph-doc-releases-rtd/config/definitions/ceph-doc-releases-rtd.yml

See https://github.com/ceph/ceph/pull/46917
This Jenkins job will receive webhooks from the github plugin.  It will then check if the main branch is what was updated and if the `doc/releases` dir was updated.
If true, it will trigger a build for each active Ceph release's docs.
https://github.com/ceph/ceph/pull/47442
https://github.com/ceph/ceph/pull/47443
https://github.com/ceph/ceph/pull/47444

ceph-docs-rtd: Create job to keep releases docs up-to-date

---

ceph-dev-build/build/build_rpm
ceph-dev-new-build/build/build_rpm

ceph-container isn't ready yet.  There is work being done in https://github.com/ceph/ceph-container/pull/2038 but our build scripts still need a lot of adjustments.

ceph*build: Do not build containers on CentOS9 for now

---

ceph-dev-cron/config/definitions/ceph-dev-cron.yml

ceph-dev-cron: Build main on centos9 daily

---

scripts/build_utils.sh

Come to find out unless --buildplace is defined, pbuilder builds in /var/cache/pbuilder/build.
The braggi and adami builders have separate faster and larger SSDs mounted at /home/jenkins-build but pbuilder hasn't been using them.

pbuilder: build in $WORKSPACE

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

ceph-dev-new: Build centos9 for main and quincy based ceph-ci branches

---

ansible/files/rpmmacros.j2
ceph-build/build/setup_rpm
ceph-dev-new-build/build/setup_rpm
ceph-iscsi-cli/build/build_rpm
ceph-iscsi-config/build/build_rpm
ceph-iscsi-stable/build/build_rpm
ceph-iscsi-tools/build/build_rpm
ceph-iscsi/build/build_rpm
cephmetrics-release/build/build_rpm
cephmetrics/build/build_rpm
configshell-fb/build/build_rpm
diamond-build/build/build_rpm
kernel/build/setup
nfs-ganesha-stable/build/build_rpm
nfs-ganesha/build/build_rpm
rtslib-fb/build/build_rpm
samba/build/build_rpm
tcmu-runner/build/build_rpm

lsb_release was removed in EL9 and we already have functions to read /etc/os-release and return the values we want.

Stop using lsb for rpm-based distros

---

scripts/build_utils.sh

less "magic numbers" this way.

build_utils/build_debs: use variable when appropriate

---

scripts/build_utils.sh

build boost with valgrind annotations enabled so they run cleanly under valgrind for https://tracker.ceph.com/issues/56500

add WITH_BOOST_VALGRIND to default build flavor

---

ceph-pr-api/build/build

More often than not, docs-only PRs hang during this job for 45-50 minutes then crash like this:
```
+ '[' true = true ']'
+ echo 'Only the doc/ dir changed.  No need to run make check or API tests.'
Only the doc/ dir changed.  No need to run make check or API tests.
+ exit 0
[PostBuildScript] - [INFO] Executing post build scripts.
[PostBuildScript] - [INFO] Build does not have any of the results [ABORTED]. Did not execute build step #0.
Archiving artifacts
java.lang.OutOfMemoryError: Java heap space
at java.base/java.util.Arrays.copyOf(Arrays.java:3689)
at java.base/java.util.Vector.grow(Vector.java:261)
at java.base/java.util.Vector.ensureCapacity(Vector.java:241)
at org.apache.tools.ant.util.VectorSet.doAdd(VectorSet.java:86)
at …
```

ceph-pr-api: Avoid artifact archive plugin hang

---

ceph-dev-cron/config/definitions/ceph-dev-cron.yml

ceph-dev-cron: Build quincy on el9 daily

---

scripts/ceph-windows/cleanup

`ceph-windows/run_tests` installs client side dependencies using
`cephadm install ceph-common`, which leaves us with a bunch ceph
packages after the test finishes. and they inteferes with succeeding
tests which, for instance, try to import python modules from test's
building directory.
but they end up with importing the python modules installed in system.
in this change, the installed package and its ceph dependencies are
removed in the cleanup script. the list of packages is collected by
inspecting `/var/log/dpkg.log` on the system where the test failures
were spotted and `ceph/debian/control` 's "ceph-common" section.

ceph-windows: remove installed packages

---

ceph-api-nightly/config/definitions/ceph-api-nightly.yml
ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
ceph-pr-api/config/definitions/ceph-pr-api.yml

after #46848, the log dir will be changed because the test is going to
use the mstart instead of vstart

dashboard-e2e: change artifact dir to mstart ones

---

nfs-ganesha/build/build_rpm

The previous commit installed the gperftools-devel package and set the cmake ALLOCATION variable to tcmalloc but this isn't used at all during the RPM package build via mock.
We also need those changes in the RPM spec file.
This is a temporary solution until the upstream nfs-ganesha RPM spec file will support such change.

nfs-ganesha/rpm: Fix tcmalloc allocator setup

---

ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml

update ceph-volume nightly jobs.
drop nautilus testing as it's EOL for a while.
drop testing against el7
drop testing against xenial (replace with focal)
test against quincy and pacific

ceph-volume-nightly: cleanup

---

ceph-windows-pull-requests/config/definitions/ceph-windows-pull-requests.yml

Also, set `artifact-days-to-keep` and `artifact-num-to-keep` to make sure we don't clutter the Jenkins server with log files.

ceph-windows-pull-requests: Collect tests logs

---

ceph-volume-ansible-prs/build/teardown
ceph-volume-nightly/build/teardown
ceph-volume-scenario/build/teardown
scripts/build_utils.sh

typical error from ceph-volume tests:
```
ERROR! the playbook: /home/jenkins-build/build/workspace/ceph-volume-prs-lvm-centos8-bluestore-dmcrypt/tests/functional/collect-logs.yml could not be found
```
Since `collect-logs.yml` is maintained in ceph-ansible repository, when `collect_ceph_logs` is called from a job different from ceph-ansible, the path is incorrect.
The idea is to make ceph-volume jobs override this path.

build_utils: fix collect_ceph_logs function

---

ceph-volume-ansible-prs/build/teardown
ceph-volume-nightly/build/teardown
ceph-volume-scenario/build/teardown
scripts/build_utils.sh

this reverts the collect-logs refactor as it doesn't allow to use the collect-logs playbook in different projects.

build_utils: revert collect-logs refactor

---

ceph-volume-nightly/build/build
ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml

ceph-volume nightly jobs are broken for a while because it picks 'main' as ceph-ansible branch for any ceph release being tested.
With this commit, the right ceph-ansible branch will be picked.

ceph-volume-nightly: fix broken tests

---

scripts/ceph-windows/run_tests

We noticed old logs in the Jenkins `ceph-windows-pull-requests` job artifacts. This is very likely due to the fact that there were existing logs from previous runs.
Make sure that there are no leftover logs from previous runs by cleaning up the `$WORKSPACE/logs` dir prior to collecting new logs from the Windows tests machine.

ceph-windows: Cleanup logs dir before collecting new logs

---

nfs-ganesha/build/build_rpm

This reverts commit 953f385e4b410fb7c560b47295ef2fd34e25d44a.
This isn't needed anymore since the changes in nfs-ganesha have been merged [1]
[1] https://github.com/nfs-ganesha/nfs-ganesha/commit/5eada8d

Revert "nfs-ganesha/rpm: Fix tcmalloc allocator setup"

---

kernel-trigger/config/definitions/kernel-trigger.yml

Commit 39e983f0198c ("master-> main") shouldn't have touched kernel-trigger job as ceph-client.git still has the master branch which feeds into linux-next.git.

kernel: re-add master branch to the trigger list

---

ceph-windows-image-build/build/setup.ps1

* Bump Python to `3.11`.
* Add `fio` as part of Windows CI image setup.
* Add `prettytable` pip dependency. We'll use this for the Python `test_rbd_wnbd.py` script.

ceph-windows: Update `ceph-windows-image-build` setup script

---

scripts/ceph-windows/run_tests

Run `test_rbd_wnbd.py` script from the upstream Ceph QA Windows workunit scripts
as part of the `script/ceph-windows/run_tests`.
The new test cases don't take a lot of time to execute (unless something is wrong with Ceph on Windows or Linux).
So, we won't have any noticeable jobs' execute time penalty.
This adds more Windows tests to the Jenkins jobs:
* `ceph-windows-test`
* `ceph-windows-pull-requests`

ceph-windows: Add more Windows testing

---

ceph-dev-new/config/definitions/ceph-dev-new.yml

Temporarily, so we can unblock building on git push.

ceph-dev-new: Default to internal quay instance

---

scripts/ceph-windows/run_tests

One of the rbd-wnbd tests has started failing after the Windows image got updated. The disks now show up as "read-only" by default.
https://pastebin.com/raw/JXmLXFnN
We'll temporarily disable this test to unblock the Windows job while doing further investigation.

temporarily disable windows RbdStampTest test

---

ceph-ansible-nightly/build/build

If the reponse is in an unexpected format (e.g. it's an error response), we were looping infinitely; one job got to over 60k pages!

ceph-ansible-nightly: Don't search tags endlessly

---

scripts/ceph-windows/run_tests

We had to disable one of the rbd-wnbd tests while investigating the reason why disks started coming up as read-only.
This was actually caused by the wnbd bus type, which changed from virtual to SAS. The default Windows policy (offlineShared) doesn't automatically bring online such disks, SAS being considered a shared bus.

ceph-windows: re-enable rbd-wnbd stamp test

---

scripts/ceph-windows/run_tests

Use the locally cloned `test_rbd_wnbd.py` script if `$WORKSPACE/ceph` repository was cloned as part of the Jenkins job.

ceph-windows: Use locally cloned script, if possible

---

scripts/ceph-windows/run_tests

We have a new PowerShell script that runs all the Ceph Windows tests from the main repository.

ceph-windows: Use PowerShell script to run tests

---

scripts/build_utils.sh

In continuation to: https://github.com/ceph/ceph/pull/49678
Jenkins uses `build_utils.sh` (not `install-deps.sh` from ceph/main).
This should affect centos 8 **Crimson** builds only.
Tested by editing `ceph.spec.in` before pushing to Shaman.
Successful test Run: https://shaman.ceph.com/builds/ceph/wip-matanb-c-disable-ceph-fs-java/1c5cdf90ab6fca5c575e0cc90dba1d44802fb08c/crimson/328749/
Signed-off-by: Matan Breizman <mbreizma@redhat.com>

build_utils.sh: Disable cephfs_java with Crimson

---

ceph-ansible-prs/build/build

Due to a regression introduced in tox 4.3.1, multiple environment variable substitution is broken.
```
tox.report.HandledError: replace failed in centos-non_container-update.commands with MatchRecursionError('circular chain between set env DOCKER_HUB_USERNAME, DOCKER_HUB_PASSWORD, INVENTORY')
```
Let's pin to the last tox stable version where it used to work fine (4.2.8).

ceph-ansible-prs: pin tox version

---

ceph-volume-scenario/build/build

Due to a regression introduced in tox 4.3.1, we have to pin the version used in the CI in order to avoid the following error:
```
tox.report.HandledError: replace failed in centos8-filestore-create.commands with MatchRecursionError('circular chain between set env VAGRANT_UP_FLAGS, CEPH_DEV_BRANCH, CEPH_DEV_SHA1')
```

ceph-volume-scenario: pin the tox version

---

ceph-container-prs/config/definitions/ceph-container-prs.yml

ceph-container repo is being reworked.
ceph-ansible is about to drop ceph/daemon entrypoints anyway so theses tests don't make sense anymore.
This disables ceph-ansible tests in the ceph-container CI.
Signed-off-by: Guillaume Abrioux <gabrioux@ibm.com>

ceph-container-prs: disable ceph-ansible tests

---

scripts/ceph-windows/run_tests

The Python rbd-wnbd tests time out on stable branches. The reason is that if the test script is missing, we're fetching it from the main branch and then run the tests individually.
The issue is that while on the main branch the entire suite uses a 30m timeout, on stable branches we're excuting each individual test with a 5m timeout, which isn't enough for some of the tests (e.g. the FIO one).
For this reason, we're going to increase the timeout.
While at it, we're pinning the commit id when fetching the test script on older branches. That will allow us to move it or refactor it.

ceph-windows: update test timeouts

---

ceph-dev-build/build/build_mingw
ceph-dev-build/build/setup_mingw
ceph-dev-new-build/build/build_mingw
ceph-dev-new-build/build/setup_mingw

Ceph now uses c++ 20, thus requiring gcc 10 or later.
We'll need to update Windows jobs that leverage pbuilder to from Ubuntu Focal (20.04) to Ubuntu Jammy (22.04) to get mingw 8.0 and gcc 10.3.0.
Fixes: https://tracker.ceph.com/issues/58562

ceph-dev-*: bump pbuilder dist when targeting Windows

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

For those working on details of a centos9 build, testing should not involve a bunch of other builds. Presenting this as a potential solution.
Signed-off-by: J. Eric Ivancich <ivancich@redhat.com>
**I don't know if this is the best solution to limiting builds. I'm not sure that it scales well. But I thought I'd offer this PR to start a discussion and see what the best approach is.**

ceph-dev: allow for a strictly centos9 build

---

ceph-windows-pull-requests/config/definitions/ceph-windows-pull-requests.yml
ceph-windows-test/config/definitions/ceph-windows-test.yml
scripts/ceph-windows/cleanup_libvirt_ubuntu_vm
scripts/ceph-windows/setup_ceph_vstart
scripts/ceph-windows/win32_build

Make sure that the Ceph on Windows build is done inside an Ubuntu libvirt VM. This ensures that the build is done on a clean environment on each job run.
After the Windows build is done, the Ubuntu VM is rebuilt to ensure that Ceph vstart will have a clean environment as well.

ceph-windows: Build Ceph on Windows inside libvirt VM

---

scripts/ceph-windows/run_tests

One of the Windows scripts tries to do "ceph status" before and after executing the ceph tests.
The issue is that it's using a wrong path. The ceph dir is actually located in the home dir.
We'll update the script accordingly.

windows: fix running "ceph status"

---

scripts/ceph-windows/setup_libvirt_ubuntu_vm

Windows jobs run ceph clusters in Ubuntu VMs. This change ensures that the jq binary used by vstart will be available.

windows: install jq package

---

scripts/ceph-windows/run_tests

In some cases, the OSDs seem to crash while running Windows tests.
In order to be able to investigate the issue, we'll need to collect additional information. This commit fetches the following:
* the entire journal since the last boot
* ceph logs
* available memory at the end of the job

windows: collect additional information

---

scripts/ceph-windows/collect-event-logs.ps1

The event log collection script was throwing an error if no event logs could be found for the filters applied. 
Therefore, the Get-WinEvent call in DumpEventLogTxt has been modified to silently continue if such case arises.

ceph-windows: Fixed txt event log dump

---

scripts/ceph-windows/collect-event-logs.ps1
scripts/ceph-windows/run_tests

The "Get-WinEvent" command used to retrieve Windows event log messages can fail if the specified log has no entries.
We're using the "SilentlyContinue" action to avoid erroring out in such cases.
However, the script still terminates abruptly while collecting logs. For this reason, we'll use the "Ignore" error action instead. We'd rather not have test failures just because we failed to retrieve some Windows event log entries.
Unlike "SilentlyContinue", "Ignore" doesn't populate the global $Error variable, which may be used when running the script remotely.
While at it, we're adding some log messages at the end of the "run_tests" and "collect-event-logs.ps1" scripts.

windows: fix log collection

---

scripts/ceph-windows/run_tests

We're attempting to collect Windows event logs at the end of the job.
The issue is that some logs cannot be collected and the job terminates abruptly despite the error action being set to "ignore".
We'll temporarily skip this step in order to unblock the Windows job.

windows: temporarily disable event log collection

---

ceph-windows-image-build/build/setup.ps1

Dokany is required in order to map cephfs on Windows through ceph-dokan.
For this reason, we're updating the Windows image build script to include Dokany.

windows: install dokany

---

scripts/build_utils.sh
scripts/ceph-windows/collect-event-logs.ps1
scripts/ceph-windows/run_tests

Cleanup `collect-event-logs.ps1` script:
* Rely on the default `$ErrorActionPreference` value (which is `Continue`).
* Add new function `SanitizeName` that it's used to sanitize the name of the log files.
The function code existed before, but it was duplicated in the script.
* General PowerShell code cleanup.
The Windows event log collection was failing due `ssh_exec` abruptly
closing the connection, because the default timeout of `30 secs` was exceeded.
This change re-enables the Windows event log collection by increasing the
SSH timeout to `30 minutes`.
Additionally, the `ssh_exec` function is updated to print an appropriate
error message when SSH timeout is exceeded.

ceph-windows: Re-enable Windows event logs collection

---

scripts/build_utils.sh

We need to use `return` inside the function to properly return the exit code of the function.
Using `exit` will abruptly exit the entire script, which is not what we want.

utils: fix ssh_exec function

---

scripts/ceph-windows/setup_libvirt_ubuntu_vm

The Windows job is failing because of a missing mgr dependency.
We'll update the setup script, ensuring that python3-bcrypt is installed.

windows: install python3-bcrypt dependency

---

ceph-volume-test/config/definitions/ceph-volume-test.yml

filestore support has been dropped as of Reef release. This commits drops ceph-volume filestore testing for reef onward.

ceph-volume: do not test filestore against reef onward

---

scripts/sign-rpms

I couldn't validate repomd.xml.asc against repomd.xml without swapping these stanzas.

Use createrepo_c, and change order of signing operations to avoid invalid repomd.xml sigs

---

ceph-release-rpm/config/definitions/ceph-release-rpm.yml

Builds CentOS 9 build for ceph-release rpm.

ceph-release-rpm: add CentOS 9 build

---

ceph-api-nightly/config/definitions/ceph-api-nightly.yml
ceph-dashboard-cephadm-e2e-nightly/config/definitions/ceph-dashboard-cephadm-e2e-nightly.yml

Remove the email notifications from the configuration.  They're just cluttering the ceph-qa inbox and no one is acting on them.

ceph-api-nightly, ceph-dashboard-cephadm-e2e-nightly: stop emails

---

cephadm-ansible-prs/build/build
cephadm-ansible-prs/config/definitions/cephadm-ansible-prs.yml

el9 RPMs weren't available so `el9` distribution was left commented out so far. Given that we now have el9 packages, let's add el9 testing.

cephadm-ansible: add el9 testing

---

scripts/build_utils.sh

The latest version of chacractl requires requests-toolbelt==0.9.1. This is not compatible with the latest version of urllib3, which dropped support for appengine.
We need to pin urllib3 to an older version that still supports appengine, and requests to an older version that still supports the older urllib3 until charactl allows a higher version of requests-toolbelt.
Fixes: https://tracker.ceph.com/issues/59652
Signed-off-by: Laura Flores <lflores@redhat.com>

scripts/build_utils.sh: pin urllib3 and requests

---

jenkins-job-builder/build/build
scripts/build_utils.sh

I'm unsure if this is exactly the right way to solve the issues I saw, but here's my rationale:
When the jjb job executes, sometimes it picks adami02, whose system python is 3.6; newer jjb versions appear to require `dataclasses`, which was new in 3.7 - a version that itself is EOL.
Other times, braggi02 gets selected. That host has 3.10, but was failing because of a lack of `wheel`.

Fix broken jenkins-job-builder job

---

ceph-dev-setup/config/definitions/ceph-dev-setup.yml

ceph-dev-setup is using 67G out of the 200G on /var/lib/jenkins, far larger than any other job.  There's no reason to save all these jobs.

ceph-dev-setup: save only 25 builds (rather than 2 weeks)

---

scripts/ceph-windows/setup_ceph_vstart

We've been using memstore in order to put as much load as possible on the Windows clients in a relatively short timeframe.
However, we've been hitting memstore segfaults:
https://tracker.ceph.com/issues/61416
For this reason, we'll make the OSD backend configurable, defaulting to bluestore for now.

windows: use bluestore instead of memstore by default

---

ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml

Solution for this in ceph-dev-new-build:
```
[EnvInject] - Inject global passwords.
[EnvInject] - Mask passwords that will be passed as build parameters.
Failed to evaluate name macro:org.jenkinsci.plugins.tokenmacro.MacroEvaluationException: Error processing tokens
[gigantic] $ /bin/sh -xe /tmp/jenkins6948878898411108393.sh
+ echo 'Cleaning up top-level workarea (shared among workspaces)'
Cleaning up top-level workarea (shared among workspaces)
+ sudo rm -rf dist
+ rm -rf venv
+ rm -rf release
rm: cannot remove 'release/18.0.0-4267-g48627125/ceph-18.0.0-4267-g48627125': Permission denied
rm: cannot remove 'release/18.0.0-4267-g48627125/version': Permission denied
rm: cannot remove 'release/18.0.0-4267-g48627125/ceph_18.0.0-4267-g48627125.orig.tar.gz': Permission denied
rm: cannot remove …
```

ceph-dev-new-build/config/definitions: give proper permission to remove a folder

---

ceph-release-rpm/build/build

This causes a syntax error.  Also, the script didn't have -e set, so the error went unnoticed

ceph-release-rpm build script missing space before =

---

ceph-dev-cron/config/definitions/ceph-dev-cron.yml
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

Followup to https://github.com/ceph/ceph-build/pull/2142; removes crimson pacific from additional build jobs.

ceph-dev-cron, ceph-dev-new-trigger: don't build crimson for pacific

---

ceph-dev-new-setup/config/definitions/ceph-dev-new-setup.yml

Might help address failures like
```
fatal: fetch-pack: invalid index-pack output`
```
and
```
error: rev-list died of signal 15
error: github.com:ceph/ceph-ci.git did not send all necessary objects
```

ceph-dev-new-setup/config/definitions: increase timeout for cloning ci repo

---

jenkins-job-builder/build/build

This is to allow job development without losing the jobs and past builds as other ceph-build PRs are pushed.  It's assumed that if you create a job with 'preserve-' in its title that you will clean it up when you're done.

jenkins-job-builder: don't delete jobs named 'preserve-*'

---

kernel/config/definitions/kernel.yml

commit 4b61a221e4e2f53dc7df3137fc34f418c3f3b879 just forgot to enable it after adding centos9.

kernel: enable centos9 build

---

ansible/ansible.cfg

Jenkins also uses ansible for some builds, and this config item breaks the run, because although the ansible secret isn't needed, if you configure it, ansible requires it.  <sigh>

ansible: remove vault_password_file; jenkins-build doesn't have one

---

ansible/examples/builder.yml
ansible/library/jenkins_node

As part of enumerating jenkins node labels in ansible/inventory, the custom ansible module 'jenkins' works better if it can update existing nodes (for example, to change labels).  Add the functionality to update nodes.  (This was a little sticky because the Jenkins API for nodes only uses XML descriptions, so there was data conversion to do, and I decided it would be best to use the xmltodict module, not a part of python but present as an OS package in all the distributions I looked at.)
Another minor enhancement: make failures in the jenkins_node module a little more clear/complete.

ansible: enhance library/jenkins_node to allow node update

---

scripts/ceph-windows/run_tests

Some Windows test jobs have failed after the OSDs ran out of disk space. Those jobs use Linux VMs with 128GBs of storage and run 3 OSDs, each having 15GB.
In order to get a better picture, we'll log the disk space usage, including the vstart directory contents.

windows: log available disk space

---

ceph-container-flake8/build/build

Looks like this job has never worked.
The file should be bind-mounted in /code, not in / There's no need to pass arguments, the entrypoint automatically scan /code and run flake8 against any present files.

ceph-container-flake8: fix test

---

ceph-container-flake8/build/build

the current image is old and uses a flake8 build based on py2.7.
It means we are checking python 3.x code with a python 2.7 version of flake8. That doesn't work very well.

ceph-container-flake8: migrate to alpine/flake8 image

---

ansible/examples/builder.yml
ansible/library/jenkins_node

Several changes bundled together here: smoothing the jenkins_node library module, adding bookworm deb signing keys, changing some conventions in the jenkins-builder inventory entries (see also https://github.com/ceph/ceph-sepia-secrets/pull/836)

Update jenkins-builder support

---

nfs-ganesha/config/definitions/nfs-ganesha.yml

Instead of just building the tip of whatever is in the "next" branch, let's pin the daily nfs-ganesha build to the latest stable tag: V5.5.

nfs-ganesha: pin the daily build to V5.5

---

scripts/ceph-windows/run_tests

The "Start-Serice" command doesn't really say why the service could not be started:
```
Start-Service : Service 'ceph-rbd (ceph-rbd)' cannot be started
due to the following error: Cannot start service
```
We'll use the "net.exe start" command instead, which provides additional information.

windows: use "net.exe start" instead of Start-Service

---

scripts/ceph-windows/run_tests

We're getting occasional false positives from Windows Defender. For this reason, we'll add the Ceph dir to the exclusion list.
```
ERROR - Test exception: [WinError 225] Operation did not complete
successfully because the file contains a virus or potentially unwanted
software. Total exceptions: 22
Windows Defender Antivirus has taken action to protect this machine from
malware or other potentially unwanted software.
For more information please see the following:
https://go.microsoft.com/fwlink/?linkid=37020&name=Trojan:Win32/Bearfoos.A!m
l&threatid=2147731250&enterprise=0
Name: Trojan:Win32/Bearfoos.A!ml
ID: 2147731250
Severity: Severe
Category: Trojan
Path: file:_C:\ceph\rbd-wnbd.exe
Detection Origin: Local machine
Detection Type: Concrete
Detection Source: Real-Time Protection
User: NT …
```

windows: add Ceph dir to Windows Defender exclusion list

---

scripts/dashboard/install-cephadm-e2e-deps.sh

the reasoning for choosing the node 16 is because it supports angular version 12, 13, 14 and 15. We have angular 12 in the pacific

deps: upgrade the node version to 16

---

ceph-dev-new-setup/build/build

Note: it has been this way since at least 35e1a715. It's difficult to tell when
or even if ceph was ever properly built with debugging configurations for QA as
there are corresponding changes in ceph with the switch to cmake which makes
this challenging to evaluate.
It's likely that it was wrongly assumed that cmake would set the build type to
Debug because the ".git" directory would be present. This is not the case
because the "make-dist" script (executed below) creates a git tarball that is
used for the actual untar/build. See also:
https://github.com/ceph/ceph/pull/53800

ceph-dev-new-setup: enable debug options for dev builds

---

ceph-build-pull-requests/build/build

ansible 8.5.0 includes a change to ansible-galaxy that breaks the installation of sensu and rabbitmq:
https://github.com/ansible/ansible/issues/82073
Work around that by pinning ansible to 8.4.0
Fixes: https://tracker.ceph.com/issues/63223

ceph-build-pull-requests/build/build: pin ansible to 8.4.0

---

nfs-ganesha/config/definitions/nfs-ganesha.yml

The latest upstream nfs-ganesha 5 tag was released. Bump from V5.5 to V5.7.

nfs-ganesha: pin the daily build to V5.7

---

ceph-build-pull-requests/build/build

Last change pinned ansible to 8.4.0 to workaround a bug.  The buggy code is actually in ansible-core, so pin that instead. See https://github.com/ceph/ceph-build/pull/2173

ceph-build-pull-requests: rather than ansible, pin ansible-core

---

kernel/build/build_rpm
kernel/build/setup

A bunch of kbuild changes went into 6.6-rc1.  In particular, the location of rpmbuild structure has changed and BuildRequires clauses are now applied universally so we need dwarves to be installed.

kernel: unbreak RPM builds

---

kernel-trigger/config/definitions/kernel-trigger.yml

From time to time Jenkins kills "git index-pack" due to a timeout:
> git fetch --no-tags --progress -- https://github.com/ceph/ceph-client.git +refs/heads/*:refs/remotes/origin/* # timeout=20
ERROR: Timeout after 20 minutes
...
remote: Enumerating objects: 9769655, done.
remote: Counting objects:   0% (1/368573)
...
remote: Counting objects: 100% (368573/368573), done.
remote: Compressing objects:   0% (1/73615)
...
remote: Compressing objects: 100% (73615/73615), done.
Receiving objects:   0% (1/9769655)
...
Receiving objects:  99% (9762992/9769655), 2.61 GiB | 19.22 MiB/s
remote: Total 9769655 (delta 294178), reused 368051 (delta 293885), pack-reused 9401082
Receiving objects: 100% (9769655/9769655), 2.62 GiB | 19.00 MiB/s
Receiving objects: 100% (9769655/9769655), 2.63 GiB | 19.17 …

kernel-trigger: increase clone timeout

---

ceph-dev-build/build/build_osc
ceph-dev-build/build/setup_osc
scripts/build_utils.sh

The counterpart in `ceph/ceph.git` is ~~https://github.com/ceph/ceph/pull/51488~~ https://github.com/ceph/ceph/pull/53191.

kickoff v19 squid

---

ceph-setup/build/create_tag
ceph-tag/build/build

This is a temporary hack until we have time to properly test changing include to include_tasks, required by ansible 9 (include has been deprecated for some time, and now it's officially gone)

ceph-setup, ceph-tag: pin ansible to < 9

---

scripts/sync-push

Avoid the "staging" nomenclature to avoid confusion with the staging operation of ceph-container.  Also, allow specifying, for example, "reef-18.2.1" to only sync that specific release rather than everything named reef (avoids using up lots of extra time and space in the prerelease directory).

sync-push: "staging" -> "prerelease", and allow specifying releasename-version

---

ceph-container-prerelease-build/build/build
ceph-container-prerelease-build/config/JENKINS_URL
ceph-container-prerelease-build/config/definitions/ceph-container-prerelease-build.yml

Based on ceph-container-build-ceph-base-push-imgs, but for building containers for testing before the release is validated and committed.  Differences:
1) pulls packages from download.ceph.com/prerelease 2) does not attempt to build aarch64
3) pushes built container to quay.ceph.io:ceph/prerelease
The prerelease directories are password-protected to avoid any early exposure to in-progress builds.
This requires corresponding changes to ceph-container.git (see https://github.com/ceph/ceph-container/pull/2178)

Add ceph-container-prerelease-build

---

scripts/build_utils.sh

No idea why sometimes the builddep phase fails, and I can't reproduce it on demand; perhaps -v will give a little more of a clue

Add verbosity to yum-builddep to try to get more info about failure

---

ceph-iscsi/config/definitions/ceph-iscsi.yml
tcmu-runner/build/build_rpm
tcmu-runner/config/definitions/tcmu-runner.yml

adds centos9 to AVAILABLE_DIST for these packages
the build script for nfs-ganesha looked like the only one that needed a small change to handle centos9

enable centos9 builds for ceph-iscsi, tcmu-runner

---

scripts/build_utils.sh

It leaves root-owned files around which causes cleanup issues

build_utils.sh: remove --debugsolver

---

ceph-iscsi-stable/build/setup
ceph-iscsi-stable/config/definitions/ceph-iscsi-stable.yml

also remove centos7 builds
setup change was because build_utils.sh had already been updated to solve the mystery of the mock configuration file, but since this had had it hardcoded, we had two places to fix the same thing

ceph-iscsi-stable: make centos9 work

---

ceph-build-pull-requests/build/build
jenkins-job-builder/build/build

Something's happened in the new release of jjb that breaks our yml templates.  There are hints here, perhaps.
https://groups.google.com/g/jenkins-job-builder/c/FQOIorLgi9g
For now, 5.1.0 seems to work.
Also pin it in jenkins-job-builder.

ceph-build-pull-requests: pin jenkins-job-builder to <6.0.0

---

scripts/ceph-windows/setup_libvirt

The Windows jobs use Libvirt VMs to build Ceph and run the tests.
The issue is that we're assuming Libvirt to be preinstalled, which isn't necessarily the case.
This change will explicitly install Libvirt.

windows: install libvirt

---

scripts/ceph-windows/setup_libvirt

Libvirt is still not available after installing the libvirt-daemon-system package.
We'll explicitly enable the libvirtd service and install qemu-kvm.

windows: explicitly enable libvirtd and install qemu-kvm

---

ceph-container-build-ceph-base-push-imgs-arm64/build/build
ceph-container-build-ceph-base-push-imgs/build/build

otherwise, the build-ceph-base.sh script complains because this variable has no default value.

ceph-container: set PRERELEASE env var

---

scripts/ceph-windows/setup_libvirt

The Windows job is failing because of libvirt failures, specifically the libvirt unix socket is missing.
After some trial and error, looks like the libvirtd.socket service needs to be restarted.

windows: restart libvirtd.socket if the socket is missing

---

ceph-dev-cron/config/definitions/ceph-dev-cron.yml
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml

Reverting until the container machinery will support pulling c9 builds.
This reverts commit 1984464b9a80f6857877aac0620737cbc40fd67c.

Revert "ceph-dev*: remove centos8 crimson builds"

---

ceph-pull-requests-arm64/build/build

On arm nodes confusa*, there are enough memory to run `nproc` build jobs, but the test jobs number `$(nproc) / 4` are too small, and make check test run pretty slow.

ceph-pull-requests-arm64: set test jobs number equal to build jobs number

---

sync-images/build/build
sync-images/build/sync.yml
sync-images/config/JENKINS_URL
sync-images/config/definitions/sync-images.yml

This adds a nightly job in order to mirror some container images (grafana image only for now) from docker.io to quay.io

Add sync-images job

---

sync-images/config/definitions/sync-images.yml

according to the documentation [1], my understanding is that `!include-raw` should be used instead of `!include-raw-escape`.
[1] https://jenkins-job-builder.readthedocs.io/en/latest/definition.html#inclusion-tags

sync-images: fix the inclusion section

---

sync-images/build/build

adding `--security-opt label=disable` to workaround the following error:
```
time="2024-02-29T12:04:24Z" level=fatal msg="open /sync.yml: permission denied"
```

sync-images: address permission denied issue

---

scripts/build_utils.sh

centos8: add yum Configs for CentOS Cloud SIG in order to satisfy new build dependency `grpc-devel`
example of the [failing build](https://jenkins.ceph.com/job/ceph-dev-new-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos8,DIST=centos8,MACHINE_SIZE=gigantic/76580//consoleFull).

centos8: add yum Configs for  ceph/grpc copr https://copr.fedorainfracloud.org/coprs/ceph/grpc/

---

scripts/build_utils.sh

The playbook needs to be in the root directory so it can discover the roles

build_utils: move collect lgos playbook into the root dir

---

ceph-pull-requests-arm64/build/build

WITH_RBD_RWL variable is added in https://github.com/ceph/ceph/pull/45872.

ceph-pull-requests-arm64: enable RWL mode on arm64

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

as described in https://lists.ceph.io/hyperkitty/list/dev@ceph.io/thread/ONAWOAE7MPMT7CP6KH7Y4NGWIP5SZ7XR/, lack of jammy packages for quincy is an obstacle to dropping ubuntu focal support on squid

ceph-dev-new-trigger: start building quincy packages on jammy

---

ceph-api-nightly/config/definitions/ceph-api-nightly.yml
ceph-build/config/definitions/ceph-build.yml
ceph-dashboard-cephadm-e2e-nightly/config/definitions/ceph-dashboard-cephadm-e2e-nightly.yml
ceph-dev-cron/config/definitions/ceph-dev-cron.yml
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
ceph-doc-releases-rtd/config/definitions/ceph-doc-releases-rtd.yml
scripts/build_utils.sh
scripts/sign-rpms
scripts/sync-push

Based on @jdurgin's commit from last year for reef.
> and other jobs (except for ceph-volume)
I'm clueless about `CEPH_ANSIBLE_BRANCH` and other version bits there, so I'm leaving ceph-volume jobs to @guits.

Add squid to ceph-dev-cron and other jobs (except for ceph-volume)

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

depends on ~~https://github.com/ceph/ceph/pull/55976~~ (edit: merged) to remove the last dependencies on focal packages for quincy upgrade suites

ceph-dev-new-trigger: stop building focal packages on main

---

ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml

This drops the pacific nightly ceph-volume testing

ceph-volume: drop pacific nightly testing

---

scripts/ceph-windows/setup_libvirt_ubuntu_vm

There have been a lot of Windows job failures lately due to qemu errors caused by insufficient Jenkins slave memory:
```
ERROR    internal error: process exited while connecting to
monitor: 2024-04-21T11:37:28.922183Z qemu-system-x86_64: cannot
set up guest memory 'pc.ram': Cannot allocate memory
```
Each Windows job spins up two virtual machines: a Linux one with 64GB of ram and a Windows VM with 8GB of ram. Since the Windows job no longer uses memstore, we can probably reduce the Linux vm memory to 16GB.

windows: reduce Linux VM memory

---

scripts/ceph-windows/run_tests
scripts/ceph-windows/setup_ceph_vstart

We've decreased the amount of resources allocated to Windows PR test jobs but as a result we're now experiencing timeouts.
We'll double the timeouts used by our test scripts.

windows: increase timeouts

---

ceph-dev-new-build/build/build_rpm

A quick change to add timestamps to the execution logs

ceph-dev-new-build: add timestamps to the build log

---

ceph-windows-installer-build/build/build
scripts/build_utils.sh
scripts/ceph-windows/run_tests

Some failed Windows jobs are missing the build artifacts and it seems like the log collection function times out.
https://jenkins.ceph.com/job/ceph-windows-pull-requests/39380/
We'll increase the timeout from 30s to 10m.

windows: increase log collection timeout

---

scripts/build_utils.sh

The existing mirror is defunct, and hard-stopping bookworm builds. For now, let's just revert to not specifying a mirror (as we have in the past for other repo configurations) and solve any problems that result if they pop up.

build_utils.sh: remove pbuilder's --mirror option for Debian

---

scripts/ceph-windows/setup_ceph_vstart

One "apt-get install" command times out after the default 30 seconds. We'll increase the timeout to 10m.

windows: increase package install timeout

---

ceph-dev-new-setup/config/definitions/ceph-dev-new-setup.yml
ceph-dev-setup/config/definitions/ceph-dev-setup.yml
ceph-setup/config/definitions/ceph-setup.yml

They only do file operations to build a source tarball and debian source package things, so the architecture isn't important.

Allow all the ceph -setup jobs to run on arm64.

---

scripts/build_utils.sh

To pbuild Debian on Ubuntu (as we do), one must specify a mirror that contains the Debian environments.  Use the most-generic one.

build_utils.sh: re: last commit: one must specify a mirror

---

scripts/sign-rpms
scripts/sync-pull
scripts/sync-push

All the tools and paths basically grow a "project" argument to distinguish ceph from ceph-iscsi.
In addition, drop el7, add vim modelines, and other minor cleanup.

Modify scripts/{sync-pull,sign-rpms,sync-push} to handle ceph-iscsi

---

ceph-pull-requests-arm64/build/build

Because performance of omani series machine are not so well which caused make check often failed, especially when cache hit was low, extend timeout to 4h seems reasonable.
Ref build duration: https://jenkins.ceph.com/job/ceph-pull-requests-arm64/buildTimeTrend

ceph-pull-requests-arm64: extend timeout to 4h

---

ceph-container-build-ceph-base-push-imgs-arm64/config/definitions/ceph-container-build-push-imgs.yml
ceph-container-build-ceph-base-push-imgs/config/definitions/ceph-container-build-push-imgs.yml
ceph-container-build-push-imgs-arm64/config/definitions/ceph-container-build-push-imgs-arm64.yml
ceph-container-build-push-imgs-devel-nightly/config/definitions/ceph-container-build-push-imgs-devel-nightly.yml
ceph-container-build-push-imgs/config/definitions/ceph-container-build-push-imgs.yml

Some of these were using the *same display-name for different jobs*. O_o

ceph-container-build-*: make display-name the job name

---

ansible/requirements/sensu-requirements.yml
ceph-build-pull-requests/config/definitions/ceph-build-pull-requests.yml

Clone the upstream ansible task repos "Mayeu/ansible-playbook-rabbitmq" and "andrewschoen/ansible-playbook-sensu" (already a clone of "Mayeu/ansible-playbook-sensu"); add commits to transition from "include:" to "import_tasks:", and use the new clones as the ansible-galaxy dependency in this repo's pull-request tests.
also, add a trigger phrase to rerun the tests.

Replace obsolete "include:' in upstream ansible tasks

---

ceph-container-build-ceph-base-push-imgs-arm64/config/definitions/ceph-container-build-ceph-base-push-imgs-arm64.yml
ceph-container-build-ceph-base-push-imgs/config/definitions/ceph-container-build-ceph-base-push-imgs.yml

Add parameters to set variables that the job scripts will look for to choose which flavors to build.  This will override the defaults in ceph-container.git; the defaults are set to the same as ceph-container.git at this moment, but are probably soon to change to centos,9.

ceph-container-build-ceph-base-push-imgs*: allow specifying FLAVOR

---

ceph-windows-pull-requests/config/definitions/ceph-windows-pull-requests.yml

Currently, the intersection of focal && libvirt labels returns some smithi (nproc == 8) and mira (nproc == 4) nodes, which are inadequate for the two VMs that the Windows job spawns.  It turns we already have a windows label, which, after dropping it from mira015, seems to be on point (i.e. would filter those low CPU nodes out).  Let's use it!

ceph-windows-pull-requests: constrain to windows label

---

ceph-dev-cron/config/definitions/ceph-dev-cron.yml
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml

~~staging as a draft until qa suites stop depending on centos8-based container images~~
centos8 eol is causing all of the builds to fail now, so remove from all current releases

ceph-dev: stop building centos8 packages/container on quincy/reef/squid/main

---

cephadm-ansible-prs/config/definitions/cephadm-ansible-prs.yml

Due to CentOS 8 eol on May 31, 2024*, cephadm-ansible testing against CentOS 8 is removed
*https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

cephadm-ansible: remove el8 test scenario

---

sync-images/build/build

This commit makes the job sync nginx images from docker.io to quay.io
Also, this makes sure the latest stable image of skopeo is pulled from quay.io

sync-images: sync nginx images

---

ceph-volume-scenario/config/definitions/ceph-volume-scenario.yml

due to recent EOL of CentOS Stream 8, the workers were migrated to CentOS Stream 9.
This commit reflect that change to the ceph-volume-scenario job.

ceph-volume: use centos9 worker

---

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
ceph-volume-pr/config/definitions/ceph-volume-pr.yml

These labels must be updated to make ceph-volume jobs use `centos9` workers.

ceph-volume: update labels

---

sync-images/config/definitions/sync-images.yml

This updates the labels for the `sync-images` job. (c8->c9)

sync-images: update worker labels

---

quay-pruner/build/prune-quay.py

A number of issues and performance enhancements.  Primarily it was not finding recent images at all because we'd switched to 'stream8' rather than '8', and so it was not searching for the right tags.  There were almost 20000 saved images.  That's back down to about 450.  Also, there's no 'image_id' attribute for images anymore, so we must use the sha1 digest to identify same images/different tags.
Also added some performance enhancements; removed an inner loop-inside-loop for every image by building a digest-to-image map, snarfing up all the shaman results in one request so that we can do all the comparisons in local memory, and a few more progress messages.

Fix up quay-pruner

---

ceph-dev-cron/config/definitions/ceph-dev-cron.yml

followup to https://github.com/ceph/ceph-build/pull/2220 which only covered ceph-dev-new-trigger

ceph-dev-cron: stop building focal packages on squid/main

---

ceph-container-flake8/config/definitions/ceph-container-flake8.yml
ceph-container-lint/config/definitions/ceph-container-lint.yml

Due the the EOL of CentOS Stream 8, all the Jenkins workers were migrated to CentOS Stream 9. Therefore, we need to make these jobs pick these workers.

ceph-container: migrate to c9 jenkins workers

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

Due to CentOS 8 eol on May 31, 2024*, cephadm-ansible testing against CentOS 8 is removed
*https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

ceph-ansible: remove el8 test scenario

---

sepia-fog-images/build/failure

Tested here: https://jenkins.ceph.com/job/sepia-fog-images/816/console
The tracebacks are ugly but aren't causing problems; their root cause is that the job expects teuthology to _not_ have any fog configuration present.

sepia-fog-images: Unlock on failure

---

sepia-fog-images/build/build

The mount module is now ansible.posix.mount, and ansible-playbook can't seem to find it when executed from the parent directory. Set ANSIBLE_CONFIG, which sets the collection search path.

sepia-fog-images: allow ansible to find collections

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

This makes the CI not trigger the jobs when "draft" label is set on PRs.

ceph-ansible-prs: set black-list-labels

---

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml

As per [1] `test-black-list-labels` expects a list.
[1] https://jenkins-job-builder.readthedocs.io/en/latest/triggers.html

ceph-ansible-prs: follow up on edf5311

---

ceph-windows-image-build/build/build
ceph-windows-installer-build/build/setup
scripts/ceph-windows/setup_libvirt
scripts/ceph-windows/win32_build
wnbd-build/build/build

... as they are ignored in scripts/build_utils.sh since commit 3517941ef2aa ("script/build_utils.sh: don't fail if any mirror is not accessible").  This is prompted by an issue with libboost repo, which started returning 403 Forbidden errors.
While at it, skip fetching language and translation packs.

windows: ignore "apt-get update" errors

---

ceph-dev-new-build/build/build_rpm
ceph-dev-new-build/build/failure
ceph-dev-new-build/build/setup_rpm
ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml
ceph-dev-new/config/definitions/ceph-dev-new.yml

- invoke ${SRC}/container/build.sh to build the container
- do not check out ceph-container.git
- add test to loop for "is repo ready" to test for the jenkins job url ${BUILD_URL} as well as ready, so that we're not racing against preexisting repos for this branch/os/flavor
This depends on https://github.com/ceph/ceph/pull/59868

ceph-dev-new-*: change for in-tree container builds

---

sync-images/build/build

The sync is not syncing the different architectures supported by the images atleast for grafana. And hence only the amd64 gets mirrored to the quay repo and causes issues to arm64 builds. I saw that skopeo supports an `--all` opton that copies images of every aarch.
Refer: https://github.com/containers/skopeo/blob/main/docs/skopeo-sync.1.md#options
Fixes: https://tracker.ceph.com/issues/68627

sync-images: sync all images including their different aarch

---

scripts/get-tarballs.sh

This is used by sync-pull to fetch the tarballs when constructing a release, but needs modification for the prerelease/ directory structure.  It's invoked by ssh to download.ceph.com to run from /home/signer/bin, because it needs to copy large files from chacra to download.ceph.com and doing that on download.ceph.com is much more efficient.

Keep track of extra script get-tarballs.sh

---

ceph-pr-api/build/build
ceph-pull-requests-arm64/build/build
ceph-pull-requests/build/build
ceph-windows-pull-requests/build/check_docs_pr_only
scripts/build_utils.sh

Parallel to the docs-only test, skip PR checks (api, make check, etc.) if the only changes are to the container/ subdirectory

build_utils.sh, various PR build scripts: skip if container/

---

ceph-dev-build/build/build_rpm
ceph-dev-build/build/failure
ceph-dev-build/build/setup_rpm
ceph-dev-build/config/definitions/ceph-dev-build.yml
ceph-dev/config/definitions/ceph-dev.yml

This is the same change as done by 6361c5c4bac7467893b1f629090712c8c0d736a8 and 435515fe481bd1752b630d23986249e90c0fa4f8 in ceph-dev-new-build, but for ceph-dev-build.  ceph-container is no longer used.
Also remove CONTAINER_BRANCH parameter from ceph-dev.

ceph-dev-build: change to use container/Containerfile

---

ceph-dev-build/build/setup_rpm

Reversed the =~ operator when porting change from ceph-dev-new-build

ceph-dev-build/build/setup_rpm: fix syntax error

---

ceph-build/build/build_rpm
ceph-build/build/setup_rpm
ceph-build/config/definitions/ceph-build.yml
ceph/config/definitions/ceph.yml

The final change to use container/build.sh rather than ceph-container: the release-build jobs "ceph/ceph-setup/ceph-build".  These changes cause builds to also build a container (they had not done so before) and push the images to quay.ceph.io/ceph/prerelease* for validation before promotion.  See container/make-manifest-list.py for the final container-release steps: building the 'fat' manifest-list image and promoting allt three images to quay.io/ceph/ceph.

ceph,ceph-build: build prerelease containers (using container/)

---

ceph-website-prs/config/definitions/ceph-website-prs.yml

These filters block anyone outside the ceph org from having the site compile check run on their PRs. We do want people from outside the org to be able to raise PRs, so removing these filters will allow that check to run.

ceph-website-prs/config/definitions: remove org filter for site compile check

---

ceph-website-prs/config/definitions/ceph-website-prs.yml

This reverts commit a227cbd01c628e9d98cf5cb3d96f0a299c4d12c3. We decided that this is too much of a security risk and are looking into better options.

Revert "ceph-website-prs/config/definitions: remove org filter for site compile check

---

ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml
ceph-dev-new-setup/config/definitions/ceph-dev-new-setup.yml
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

See individual commit messages for the rationale between each job's change.

Keep more builds and artifacts for ceph-dev-new builds

---

ansible/examples/builder.yml

it always should have been, but this syntax is now an error.  Make it a nested dict.

ansible/examples/builder.yml: "vars" should be a list, not a dict

---

ceph-pr-api/config/definitions/ceph-pr-api.yml
ceph-pull-requests/config/definitions/ceph-pull-requests.yml

Saw many jobs fail on smithi004.  dmesg shows lots of OOM kills.

Do not run make check or API tests on smithi due to OOM

---

ceph-build/config/definitions/ceph-build.yml

ceph-build job needs to push to quay.ceph.io/ceph/prerelease, and the credentials for that are quay-ceph-io-ceph-prerelease

ceph-build: use correct quay.ceph.io credentials

---

ceph-build/config/definitions/ceph-build.yml

(this is why it's a bad idea to switch between . and _)

ceph-build.yml: fix the name of the Jenkins cred

---

ceph-api-nightly/config/definitions/ceph-api-nightly.yml
ceph-build/config/definitions/ceph-build.yml
ceph-dashboard-cephadm-e2e-nightly/config/definitions/ceph-dashboard-cephadm-e2e-nightly.yml
ceph-dev-build/build/build_osc
ceph-dev-build/build/setup_osc
ceph-dev-cron/config/definitions/ceph-dev-cron.yml
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-pr-api/config/definitions/ceph-pr-api.yml
ceph-volume-nightly/build/build
ceph-windows-pull-requests/config/definitions/ceph-windows-pull-requests.yml
scripts/sign-rpms
scripts/sync-push

Intentionally leaving the map from number to name in build_utils.sh for historical purposes.
I need folks to carefully review this, as I've not only removed quincy from some places, but also older releases (this should help clean up the build matrix displays in Jenkins for clarity as well).   Please suggest/add other reviewers for areas of expertise.

Remove quincy builds/mentions from most builds/build configs.

---

ceph-build/build/build_rpm
ceph-build/config/definitions/ceph-build.yml
ceph-dev-build/build/build_mingw
ceph-dev-build/build/build_osc
ceph-dev-build/build/build_rpm
ceph-dev-build/config/definitions/ceph-dev-build.yml
ceph-dev-new-build/build/build_mingw
ceph-dev-new-build/build/build_rpm
ceph-dev-new-build/build/setup_pbuilder
ceph-dev-new-build/build/setup_rpm
ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml
ceph-dev-new-setup/config/definitions/ceph-dev-new-setup.yml
ceph-dev-pipeline-trigger/build/Jenkinsfile
ceph-dev-pipeline-trigger/config/definitions/ceph-dev-pipeline-trigger.yml
ceph-dev-pipeline/build/Jenkinsfile
ceph-dev-pipeline/config/definitions/ceph-dev-pipeline.yml
scripts/build_container
scripts/build_utils.sh
scripts/setup_sccache.sh
scripts/status_completed

This may ultimately replace the existing ceph-*build jobs; for now, it is a
work in-progress.

Add ceph-dev-pipeline

---

ceph-dev-setup/build/build
ceph-setup/build/build

After f381e3f05fcb08a7b1a3a1aa8f86e066bd4718ba, which is quite the win for ceph-dev-new-setup, credit to zack@redhat.com

ceph-{dev-,}setup: Make git submodule operations much quieter.

---

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

Actually modify the trigger job to use choosing-strategy: ancestry and
maximum-age: 7, so that only branches newer than 7 days old get built.
Also set build-name to the branch being triggered, for clarity.

ceph-dev-new-trigger: use new feature, 7-day-old or newer branches

---

ansible/examples/builder.yml

I'm working on a combination of terraform and ansible to quickly spin up instances in IBM Cloud so they can join Jenkins as builders.
Part of this process involves creating a virtualenv and running ansible from it.  python-jenkins needs to be installed in the virtualenv and setting the python interpreters inside the playbook breaks that.
This PR will let me `--skip-tags interpreter`

ansible: Add tag to python interpreter var setting tasks

---

scripts/build_utils.sh

Add the build-with-container.py script and the helper shell script and Dockerfile that support the builder image to the container_only_pr patterns in build_utils.sh.  This should save time and resources when contributing patches to only these files in the ceph/ceph repo.

scripts: add build-with-container.py and friends to container_only_pr

---

ansible/examples/builder.yml

I think this was working during my testing because sub{u,g}id_check.rc /wasn't/ 0.  I had manually modified the system so it wasn't in the same state as a fresh cloud instance.
I manually ran this playbook on an instance and confirmed it gets past the podman setup now.

ansible: Fixes to podman subuid/subgid checks

---

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml
ceph-pull-requests-arm64/build/build
ceph-pull-requests/build/build
scripts/build_utils.sh

See: https://github.com/ceph/ceph/pull/61672
This PR changes any WITH_SEASTAR / --with-seastar to WITH_CRIMSON / --with crimson respectively. We should let our builders add the new flags and once the PR is merged we could clean up the unused WITH_SEASTAR.

ceph-dev*: intermediate transition to WITH_CRIMSON

---

ceph-dev-new-setup/config/definitions/ceph-dev-new-setup.yml
ceph-dev-setup/config/definitions/ceph-dev-setup.yml
ceph-setup/config/definitions/ceph-setup.yml

We're already low on ARM builders.  This is a waste of resources.

ceph*setup: Do not run on arm64 builders

---

ceph-build/build/build_rpm

The container must be built from signed packages, and signing is not part of the Jenkins build.  So we'll create two new jobs to build the prerelease containers (so that builders don't have to have access to both amd64 and arm64 build hosts).

ceph-build: remove container build

---

attic/ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
ceph-api-nightly/config/definitions/ceph-api-nightly.yml
ceph-build/config/definitions/ceph-build.yml
ceph-dashboard-cephadm-e2e-nightly/config/definitions/ceph-dashboard-cephadm-e2e-nightly.yml
ceph-dev-build/build/build_osc
ceph-dev-build/build/setup_osc
ceph-dev-cron/config/definitions/ceph-dev-cron.yml
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-pr-api/config/definitions/ceph-pr-api.yml
ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
ceph-windows-pull-requests/config/definitions/ceph-windows-pull-requests.yml
scripts/build_utils.sh
scripts/sign-rpms
scripts/sync-push

See: https://github.com/ceph/ceph/pull/61321

Tentacle kickoff!

---

ceph-release-containers/build/Jenkinsfile
ceph-release-containers/config/definitions/ceph-release-containers.yml

Builds prerelease versions of ceph container images: two arch-specific images and one 'manifest-list' image.  Pushed all to quay.ceph.io/ceph, in a private set of repos (prerelease-amd64, prerelease-arm64, and prerelease) for testing and signoff.  Once moved, the script container/make-manifest-list.py can be used with the --promote flag to promote them from quay.ceph.io to quay.io for public release.

Add ceph-release-containers job

---

attic/ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
ceph-dev-cron/config/definitions/ceph-dev-cron.yml
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml

Crimson should be built only for main and T.
Remove R and S builds.

ceph-dev*: Remove Crimson unsupported builds

---

scripts/build_utils.sh

distutils is removed from python 3.12 so pip 20.3.4 is incompatible with systems running python3.12.
Ubuntu Noble is our new target Jenkins builder OS so let's bump to 24.0 (the latest as of this PR)
https://stackoverflow.com/questions/69919970/no-module-named-distutils-util-but-distutils-is-installed

build_utils: Use pip 24.0 by default

---

scripts/build_utils.sh

avoid building from source and running the various 'make check's when the pr only touches PendingReleaseNotes

scripts: docs_pr_only() considers PendingReleaseNotes

---

ceph-source-dist/build/Jenkinsfile
scripts/build_utils.sh

See: https://github.com/ceph/ceph-build/pull/2167/files Builds should be set to Debug only when ending in "-debug".
https://github.com/ceph/ceph-build/pull/1805 set Crimson to always use Debug. That made sense in earlier development phases.
However, today we should align with Classical builds and use Debug only when needed.

scripts/build_utils: remove Debug build from Crimson

---

ceph-build/config/definitions/ceph-build.yml

This was removed from build_rpm, but then when a reorg happened to separate the function into a separate script, the fact that ceph-build doesn't do container builds anymore was missed.
Release container builds now happen after the manual signing step using job ceph-release-containers

ceph-build: remove container build step

---

ceph-dev-cron/config/definitions/ceph-dev-cron.yml
ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
ceph-dev-new/config/definitions/ceph-dev-new.yml
ceph-dev-pipeline/config/definitions/ceph-dev-pipeline.yml
ceph-dev/config/definitions/ceph-dev.yml
ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml
ceph-source-dist/build/Jenkinsfile
ceph-source-dist/config/definitions/ceph-source-dist.yml
quay-pruner/build/prune-quay.py
scripts/build_utils.sh

The following change would allow us to:
* Keep testing "Debug" builds (crimson-debug) by default.
* When crimson-only is used, crimson-release would also be built.
* `crimson-release` builds would be used in the weekly nightlies and on
selected PR gatings (when crimson-debug is not enough).
Note: Once crimson-release is stable enough we could switch crimson-debug
to actaully be of: "RelWithDebInfo + !NDEBUG + asserts" instead of "Debug".
For now, let's keep it as Debug since we know it's stable.
See: https://github.com/ceph/ceph/pull/63557

Seperate Crimson flavors to crimson-debug/release

---

kernel/config/definitions/kernel.yml

These are too old and kernel packages are no longer needed.

kernel: stop building for trusty, xenial and bionic

---

sepia-fog-images/build/build

When checking for scheduled deploy tasks, check not only for existing deploy tasks but for deploy tasks *for the image we're proposing to capture*.  There are often deploy tasks on a busy fog server, but we only need to avoid affecting tasks for the image we're updating

sepia-fog-images: add image test to 'poll for deploy' loop

---

ceph-trigger-build/README.md

Underscores aren't valid; we missed this in review

ceph-trigger-build: correct git trailer examples

---

scripts/setup_container_runtime.sh

This fixes errors like:
RunRoot is pointing to a path (/run/user/$ID/containers) which is not writable. Most likely podman will fail. Error: creating events dirs: mkdir /run/user/$ID: permission denied

Enable linger for the Jenkins user

---

ceph-dev-pipeline/build/Jenkinsfile

[The build I tested with](https://jenkins.ceph.com/job/ceph-dev-pipeline/392/pipeline-overview/?selected-node=296) this failed, which was helpful in that I was able to manually verify `jenkins-build` was able to `rm -rf` the workspace without using `sudo`

ceph-dev-pipeline: Clean up workspace in post

---

scripts/build_utils.sh

noble provides both gcc-13 and 14, but its gcc 13.2.0 suffers from an LTO bug that causes ceph daemons to crash horribly (tracked in https://tracker.ceph.com/issues/63867)

scripts/build_utils: default to gcc-14 for ubuntu noble

---

ceph-release-containers/build/Jenkinsfile

A ceph-release-container run suffered from
error running container: from /usr/bin/crun creating container for [<sh command>]: sd-bus call: Interactive authentication required.: Permission denied
That is thought to be because of the lack of 'linger' on the jenkins-build user, such that the /run/user directory didn't persist.  The exact mechanism of failure isn't fully understood, but this script has fixed similar issues for ceph-dev-pipeline.
Also, add an echo of the node for convenience.

ceph-release-container: add setup_container_runtime.sh

---

scripts/sync-pull

This heuristic remains questionable, but continue it on by allowing some named distro/version repos to not exist without stopping sync-pull from working

sync-pull: in the 'ugly loop', skip nonexistent repos

---

ansible/examples/builder.yml

- Installing java-21 insted of java-17(EOL)
- Stoping unattended-upgrades to avoid conflicts
- Refreshes the apt package cache to ensure the system has the latest package metadata before performing upgrades
- Upgrades all installed packages to their latest versions on debian based systems and cleans up unused dependencies and cached files
- Updates the package cache and upgrades all packages to their latest versions on redhat based systems
- Updates the package cache and upgrades all packages on suse based systems
- Fixing the task - "get github host key from github if necessary" that checks github_host_key == "" but since github_host_key is undefined, ansible throws an error
- Fixing the taks - "Install the systemd unit files for jenkins" by using playbook_dir for explicit path …

builder.yml: Add tasks to update builder

---

kernel/build/build_deb
kernel/build/setup

bc has been required for building the Linux kernel for a long time. It was installed explicitly (albeit from the wrong script) in the deb case, but not installed in the rpm case:
error: Failed build dependencies:
bc is needed by kernel-6.17.0_rc1_g0dccf5229fc7-1.x86_64
make[2]: *** [scripts/Makefile.package:75: binrpm-pkg] Error 11

kernel: install bc

---

ceph-trigger-build/config/definitions/ceph-trigger-build.yml

This pipeline doesn't support tags, and it doesn't seem like shaman does either.

ceph-trigger-build: Do not trigger on tag pushes

---

scripts/dashboard/install-cephadm-e2e-deps.sh

Change directory before trying to open files from it.  
Fixes one Jenkins Indication.
Don't try to do docker logs unless docker had something running.  
Removes some error lines in Jenkins console log which are seen on some failed jobs.

dashboard-cephadm-e2e: fix and silence a few errors

---

ceph-dashboard-cephadm-e2e/config/definitions/ceph-dashboard-cephadm-e2e.yml

cephadm-dashboard-e2e: use node version from dashboard/frontend

---

ceph-source-dist/build/Jenkinsfile

They are very slow when running this job.

ceph-source-dist: Avoid arm64 machines

---

ansible/roles/ceph-release/tasks/create.yml
ansible/roles/ceph-release/tasks/main.yml
ansible/roles/ceph-release/tasks/push.yml
ansible/roles/ceph-release/tasks/write_sha1_file.yml
ceph-dev-pipeline/build/Jenkinsfile
ceph-release-pipeline/build/Jenkinsfile
ceph-release-pipeline/config/definitions/ceph-release-pipeline.yml
ceph-source-dist/build/Jenkinsfile
ceph-tag/build/build
ceph-tag/config/definitions/ceph-tag.yml
scripts/setup_chacractl.sh

- Uses new ceph-source-dist job for creation of tarball inside container
- Uses new ceph-dev-pipeline pipeline to build in containers
Example here: https://2.jenkins.ceph.com/job/ceph-release-pipeline/17/pipeline-overview/
It failed during the automated version commit PR creation.  Unrelated to this PR.

Create ceph-release-pipeline for upstream release builds

---

ceph-dev-pipeline/build/Jenkinsfile

If sccache is supposed to be enabled, but isn't - for example due to the feature not being backported - we were still attempting to archive, and hanging. Check for the existence of the file directly.

ceph-dev-pipeline: Fix archive-skipping

---

ceph-build-pull-requests/build/build
jenkins-job-builder/build/build

jenkins-job-builder finally released 6.4.3, which includes https://review.opendev.org/c/jjb/jenkins-job-builder/+/941310, so we can stop using the git url

Update jenkins-job-builder spec to released version

---

ceph-pull-requests-arm64/build/build
ceph-pull-requests/build/build

Convert the arm64 and standard (amd64) CI jobs to execute make check in containers. This allows us to separate the build and test environment from the underlying CI node OS.

Run make check in containers

---

ceph-dev-pipeline/build/Jenkinsfile

when setting DEB_BUILD_PROFILES, a '=' was missing, so the env file didn't contain an actual setting of the value.

ceph-dev-pipeline/build/Jenkinsfile: add missing '=' to env setting

---

ceph-build-pull-requests/build/build

It probably shouldn't have been pinned to a specific version anyway, but because it had custom import code, it broke with the Python in noble (3.13 I think).  Removing the pin gets a version without the problem (I think the custom import code went away altogether).

ceph-build-pull-requsts: unpin urllib3

---

ceph-trigger-build/build/Jenkinsfile

Since nothing normally uses the arm64 packages, only build for main and release branches.

ceph-trigger-build: Build less arm64 by default
