radosgw-agent/build/build, radosgw-agent/config/definitions/radosgw-agent.yml
This will need some iteration over (commented out lines courtesy of Jenkins copy/pasted shell forms)
Once this hits master it will not overwrite the current radosgw-agent job (this uses a different name). Only when this is finally fully functional we can get it do be the defacto one.
=> initial take on radosgw-agent task

ceph-build/build/build1, ceph-build/build/build2, ceph-build/config/definitions/ceph-build.yml, ceph-package/build/build, ceph-package/config/definitions/ceph-package.yml, ceph-setup/build/build, ceph-setup/config/definitions/ceph-setup.yml, ceph/config/definitions/ceph.yml
This imports the current settings for "ceph" as YAML.
This is an import of the job previously defined in Jenkins' own data store (ie `/home2/jenkins/jobs/ceph/config.xml`)
=> import ceph task

ceph-release-rpm/build/build, ceph-release-rpm/config/definitions/ceph-release-rpm.yml
This imports the current settings for "ceph-release-rpm" as YAML.
This is an import of the job previously defined in Jenkins' own data store (ie `/home2/jenkins/jobs/ceph-release-rpm/config.xml`)
=> import ceph-release-rpm jjb task

ceph-build/config/definitions/ceph-build.yml
We no longer are supporting this for Ceph
=> remove squeeze from matrix

ceph-deploy-docs/config/definitions/ceph-deploy-docs.yml, ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml, ceph-deploy/config/definitions/ceph-deploy.yml, ceph-qa-suite-pull-requests/config/definitions/ceph-qa-suite-pull-requests.yml, jjb/config/definitions/jjb.yml, teuthology-docs/config/definitions/teuthology-docs.yml
These are now mapped to a mira host.
=> Nix dcompute

ceph-deploy/build/build, ceph-deploy/config/definitions/ceph-deploy.yml
Had to concatenate the three scripts together because I am not sure we can do an 'if/else' depending on rpm/deb to execute them, as it was the case before.
From here we can just tinker to get it right. This as it is should still not work with the new hosts added.
=> port ceph-deploy scripts to jjb build script

ceph-deploy/build/build
=> add trusty to list of deb distros

ceph-build/build/build_deb, ceph-build/build/setup_pbuilder
We aren't even building for it and the mirror doesn't have anything to support it either:
W: Failed to fetch http://us.archive.ubuntu.com/ubuntu/dists/raring/main/binary-amd64/Packages  404  Not Found [IP: 91.189.91.13 80]
=> remove raring from pbuilder setup

ceph-build/build/build_deb
This fixes a few issues:
* a variable that was not set properly because of backticks
* use of $DIST, replacing the hard-coded `$dists`
* removes hardcoded DEBEMAIL
=> use $DIST properly

ceph-build/build/build_rpm
=> rpm script runs only in rpm systems

ceph-build/build/build_rpm
=> use -eq to really tell if this is suse

ceph-setup/build/build
=> port release_tarballs.sh to ceph-setup/build/build

ceph-build/build/build_rpm
Otherwise we will fail to be in the right directory to copy the
artifacts
=> cd to $WORKSPACE

ceph-build/config/definitions/ceph-build.yml
=> remove wheezy i386 builds

ceph-deploy/build/setup, ceph-deploy/config/definitions/ceph-deploy.yml
I apparently forgot to submit this PR that would've fixed the problems found in the ceph-deploy build today.
I apologize.
=> Install ceph-deploy dependencies.

teuthology-pull-requests/build/build, teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
Let me know if we're missing anybody in the white-list or admin-list.  I'm also unsure what the process is to deploy this after merge, so I'll need some guidance there.
=> Ports the teuthology-pull-requests job to JJB

ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml
A first initial pass to tackle this one, if all goes well we can make this a common throughout so we can call playbooks and other bits and pieces we might need from ceph-build on certain jobs.
=> try to get multiple repos for ceph-deploy-pull-requests

ceph-deploy-pull-requests/build/setup, ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml
This PR uses `basedir` to allow cloning to a sub-directory relative to `$WORKSPACE`
=> fix some issues with `$WORKSPACE` being overwritten

ceph-deploy/build/setup
=> fix lack of SUDO in ceph-deploy setup script

ceph-deploy/build/setup
=> remove quotes on yum install

ceph-build/build/setup_pbuilder
=> check if we have valid tars for pbuilder

ceph-deploy/config/definitions/ceph-deploy.yml
=> remove sles and suse from the builders list

ice-setup/build/build, ice-setup/config/definitions/ice-setup.yml
Migrate the ice-setup job from our internal jenkins-calamari server to jenkins.ceph.com.
=> import ice-setup

takora/build/build, takora/config/definitions/takora.yml
Start building upstream packages for https://github.com/ceph/takora
=> import takora

takora-pull-requests/config/definitions/takora-pull-requests.yml
test PRs for https://github.com/ceph/takora
=> import takora-pull-requests job

ceph-build/build/build_deb
=> infer the BPTAG from the value of DIST

mariner-installer-pull-requests/config/definitions/mariner-installer-pull-requests.yml
Test PRs for https://github.com/ceph/mariner-installer
For merge **after** #117 
=> Add mariner-installer-pull-requests job

rhcs-installer/build/rename-rhcs-installer
Rename filenames and content in appropriate files in bin/ and
config/ as well.
=> Rename scripts and config files

ceph-build/build/build_deb, ceph-build/build/build_rpm, ceph-deploy/build/build, ceph-release-rpm/build/build, ceph-setup/build/build, ceph/config/definitions/ceph.yml, do_release.sh, kmod/sign-and-sync-from-jenkins, push_to_rpm_repo.sh, radosgw-agent/build/build, sign_and_index_rpm_repo.sh, tag_release.sh
=> use the new key for signing

ceph-release-rpm/build/build
=> update ceph.com urls for ceph-release

merfi-pull-requests/build/build, merfi-pull-requests/config/definitions/merfi-pull-requests.yml
=> implement a job to check for merfi PRs

ansible/library/jenkins-node, ansible/slave.yml.j2
And adds the jenkins-node library requirement. Ken will not like this one bit. We can fix/improve by requiring it properly later.
=> No disk format for ovh

ceph-build-next/build/setup
This uses variables created by the masks-passwords jenkins plugin.
=> programatically make the .chacractl file

ceph-build-next/config/definitions/ceph-build-next.yml, ceph-next/config/definitions/ceph-next.yml, ceph-setup-next/config/definitions/ceph-setup-next.yml, jenkins-job-builder/config/definitions/jjb.yml
Thes variables are defined on the jenkins master using the web UI.
http://jenkins.ceph.com/configure
=> allow some jobs to use globally configured variables

ceph-build-next/build/build_deb, ceph-build-next/build/build_rpm, ceph-next/config/definitions/ceph-next.yml
If FORCE is checked then binaries will be built and pushed to chacra even if they already exist in chacra.
=> check the exit status on the chacractl exists command; add a FORCE flag to ceph-next

ceph-mirror/config/definitions/ceph-mirror.yml
=> fix remotes definition for ceph-mirror

ansible/roles/ceph-release/handlers/main.yml, ansible/roles/ceph-release/tasks/main.yml, ansible/roles/ceph-release/tasks/release/candidate.yml, ansible/roles/ceph-release/tasks/release/development.yml, ansible/roles/ceph-release/tasks/release/stable.yml
An initial take on what it would entail to craft a release with ansible.
This work is based on github.com/alfredodeza/ceph-jenkins-build
=> Ansible release

ceph-tag/build/build, ceph-tag/config/definitions/ceph-tag.yml
This adds the configuration and build scripts needed for a first pass at tagging ceph with ansible
=> Ceph tag with ansible

ansible/roles/ceph-release/tasks/main.yml
=> force push to ceph-releases

ceph-tag/config/definitions/ceph-tag.yml
=> use the jenkins-build ssh key so we can push to ceph-releases.git

ceph-setup-next/config/definitions/ceph-setup-next.yml
=> add jenkins-build user ssh credentials to ceph-setup-next

jenkins-job-builder/config/definitions/jjb.yml, teuthology-docs/config/definitions/teuthology-docs.yml
use the github trigger only instead of polling
=> GitHub trigger

ceph-setup-next/config/definitions/ceph-setup-next.yml
=> ceph-setup-next: add comment explaining credential-id

ceph-build-next/build/build_deb, ceph-build-next/build/build_rpm
A bunch of random things related to fixing failed builds.
=> various updates to ceph-build-next

ceph-build-next/build/build_deb, ceph-build-next/build/build_rpm
=> ceph-build-next: source the venv in build_deb and build_rpm

ceph-docs/config/definitions/ceph-docs.yml
polling is slow, webhooks are better
=> ceph-docs: switch to github webhooks

README.rst
=> remove old docs that relied on a convention that is not enforced

ceph-build-next/build/build_deb
=> fix a typo when constructing the chacra endpoint

ceph-next/config/definitions/ceph-next.yml, ceph-tag/build/build
avoid re-tagging if we have already created one and we are re-building
=> Ceph retag

ceph-release-rpm/build/build
=> fix links to post to ceph-release, not ceph urls

ceph-release-rpm/build/build, ceph-release-rpm/config/definitions/ceph-release-rpm.yml
=> inject passwords

ceph-build-next/build/build_deb, ceph-build-next/build/build_rpm
=> ceph-build-next: use --force with chacractl when FORCE is checked

ansible/files/rpmmacros.j2, ansible/slave.yml, ansible/slave.yml.j2
So that we don't end up with RPM binaries that have 'centos' in there
=> Create `rpmmacros` file

ceph-build-next/build/build_deb, ceph-build-next/build/build_rpm, ceph-deploy/build/build
=> fix the chacractl exists call in ceph-build-next and ceph-deploy

ansible/roles/ceph-release/tasks/release/candidate.yml, ansible/roles/ceph-release/tasks/release/development.yml, ansible/roles/ceph-release/tasks/release/stable.yml
=> set the environment vars for dch to use authors

ceph-build/config/definitions/ceph-build.yml
=> add the 'huge' label to ensure competent machines are used for building

ceph-build/build/build_deb, ceph-build/build/build_rpm, ceph/config/definitions/ceph.yml
So that we don't mix non rc with rc binaries
=> Allow to push binaries to `$BRANCH-rc` refs

ansible/master.yml
=> install the multiple scm plugin

ansible/slave.yml
=> correct the location to the hostkeys

ansible/slave.yml
=> do not use backrefs for changing sudoers

ceph-build/config/definitions/ceph-build.yml
=> build arm64 on trusty

ceph-build/build/setup_pbuilder, ceph-build/config/definitions/ceph-build.yml
=> use ports mirror for arm packages in pbuilder

ceph-deploy/config/definitions/ceph-deploy.yml
=> remove the need for scm and axes on the parent ceph-deploy job

ceph-deploy-pull-requests/build/setup
=> use the full path to the ansible-playbook executable

ceph-deploy-build/build/build
=> define universal and all/noarch for ceph-deploy binaries

ceph-deploy-tag/build/build
=> use the full path for ansible-playbook executable

ceph-deploy-tag/config/definitions/ceph-tag.yml, ceph-tag/config/definitions/ceph-tag.yml
It was preventing ssh-agent-credentials from working
=> dedupe wrapper configuration

ceph-build/config/definitions/ceph-build.yml
=> also remove venv that is left behind

ceph-pull-requests/config/definitions/ceph-pull-requests.yml
This would replace the make-check-bot. 
=> create a ceph-pull-requests job

ceph-pull-requests/config/definitions/ceph-pull-requests.yml
=> make-check for ceph should be concurrent

ceph-pull-requests/config/definitions/ceph-pull-requests.yml
=> use the 'huge' slaves that have more ram

ceph-pr-commits/build/build, ceph-pr-commits/config/definitions/ceph-pr-commits.yml
=> create a new ceph-pr commit check

ceph-pr-commits/config/definitions/ceph-pr-commits.yml
=> enable distinct notifications for signed-off-by job

ceph-pr-commits/config/definitions/ceph-pr-commits.yml
=> remove whitespace in ceph-pr-commits config

ceph-pr-commits/build/build
=> do not start with a newline when creating the xml

scripts/sign-rpms, scripts/sync-pull, scripts/sync-push
These scripts are only useful for the signer box.
=> add the signer scripts

ceph-pr-commits/build/test_commits.py
=> default to origin/master, not master

ceph-pull-requests/config/definitions/ceph-pull-requests.yml
Fixes: http://tracker.ceph.com/issues/14172
=> ceph-pull-requests: require a centos7 node and reboots after make check

ceph-pr-commits/build/test_commits.py
I've failed completely at this. Hopefully this will not eat up what is going on
=> do not parametrize for now because we need to find out why this is not working

ceph-pull-requests/config/definitions/ceph-pull-requests.yml
Signed-off-by: Loic Dachary <loic@dachary.org>
=> ceph-pull-requests: keep 300 logs and run on trusty

ceph-build/build/setup_pbuilder
=> fixing pbuilder so it looks in universe as well

ceph-build/config/definitions/ceph-build.yml
=> remove arm for now

ceph-pr-commits/build/test_commits.py
=> use HEAD for comparing commits

ansible/slave.yml.j2
=> do not use files as prado does not support them yet

ceph-pr-commits/build/test_commits.py
=> fetch origin master before doing a comparison

ansible/slave.yml.j2
=> do not use lsb

ceph-pr-commits/build/test_commits.py
=> fix unbound local errors

ceph-pull-requests/config/definitions/ceph-pull-requests.yml
=> make this thing timeout because it can hang for sure

ceph-ansible-pull-requests/build/build, ceph-ansible-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
=> initial take on ceph-ansible pull requests

ceph-ansible-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
=> do not build anything that isn't unique, right?

ceph-pr-commits/config/definitions/ceph-pr-commits.yml
=> use a label so mita can create nodes if needed

ceph-pr-commits/config/definitions/ceph-pr-commits.yml
=> pr checks should be concurrent

ceph-ansible-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
This will require some mita configuration to understand what a "unique" machine means.
=> when the build is done, tell mita to destroy the node to ensure it gets a new one

ceph-ansible-pull-requests/build/build
=> use the new single-machine inventory

ceph-ansible-pull-requests/build/build
=> pass the needed extra vars

ceph-ansible-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
=> mita is only providing unique nodes for now, not ceph-ansible-unique

ceph-ansible-pull-requests/build/build
=> specify journal collocation

ceph-ansible-pull-requests/build/teardown
=> pass an option to delay the deletion of the node

ceph-pr-commits/build/build
=> testing pull request commits should never take more than 10 minutes

README.rst
=> mention the timeout on scripts

ceph-installer-docs-pull-requests/build/build, ceph-installer-docs-pull-requests/config/definitions/ceph-installer-docs-pull-requests.yml, ceph-installer-docs/build/build, ceph-installer-docs/config/definitions/ceph-installer-docs.yml
Creates two jobs, one for building docs for pull requests and the other one for publishing them when master gets changed.
=> Installer docs

ceph-installer-docs-pull-requests/build/build, ceph-installer-docs/build/build
=> use VENV to reference installed utils

ceph-installer-docs-pull-requests/config/definitions/ceph-installer-docs-pull-requests.yml
=> had the same name in two jobs

ceph-installer-coverage/build/build
It needed some minor adjustments.
=> fix ceph-installer coverage call

ansible/slave.yml
This sets the correct java version on ubuntu precise. 
Signed-off-by: Martin Palma <martin@palma.bz>
=> Set the correct java version on ubuntu precise.

ansible/slave.yml.j2
=> port the java jdk fix to the slave template as well

ceph-deploy-pull-requests/setup/playbooks/tasks/ubuntu.yml
=> install python2.6-dev as well for python2.6 support

ceph-build-arm64/build/build_deb, ceph-build-arm64/build/build_rpm, ceph-build-arm64/build/setup, ceph-build-arm64/build/setup_pbuilder, ceph-build-arm64/config/definitions/ceph-build.yml
Some things want to be different in this build; let's keep them
away from the main ceph build until we're sure they can coexist
peacefully.
=> ceph-build-arm64: Test for arm64 build, separate from ceph-build

ansible/roles/ceph-release/tasks/main.yml, ceph-tag/config/definitions/ceph-tag.yml
=> remove duplicate command directive

ceph-build-arm64/build/build_deb
=> ceph-build-arm64: tweaks for avoiding more chacra, correct dist

ceph/config/definitions/ceph.yml
=> default to using a trailing slash now

ansible/slave.yml, ansible/slave.yml.j2
=> set java conf for wheezy too

jenkins-job-builder/build/build
=> jenkins-job-builder: sigh, log_level, not log-level

ceph-build/config/definitions/ceph-build.yml
=> ceph-build: don't try x86_64/xenial builds (yet)

ansible/master.yml, ceph-build/config/definitions/ceph-build.yml, ceph/config/definitions/ceph.yml
This will allow to modify the DIST variable dynamically so that different distro versions can be used.
https://wiki.jenkins-ci.org/display/JENKINS/DynamicAxis+Plugin
=> Dynamic axis for Ceph builds

ceph-build/config/definitions/ceph-build.yml
=> allow xenial builds for amd64 with the combination filter

calamari-server-trusty/config/definitions/calamari-server-trusty.yml
=> vagrant not required to build

calamari-server-trusty/config/definitions/calamari-server-trusty.yml
=> I need to clone I want to build, surprise

ceph-build/config/definitions/ceph-build.yml
=> Allow ceph-build to run on arm64/centos7 as well

ceph-build/config/definitions/ceph-build.yml
This didn't worked out :( 
It will need https://github.com/ceph/mita/pull/59
=> Revert combination filter

calamari-server-trusty/build/build
=> need to checkout calamari source

ansible/slave.yml
=> use the correct ID for the Jessie key

ceph-build-pull-requests/build/build
=> upgrade setuptools for ceph-build-pull-requests

ansible/slave.yml
=> slave.yml: remove openjdk7 from default install list

ceph-setup/config/definitions/ceph-setup.yml
=> ceph-setup: build from tag, not from branch

ceph-build/build/setup_pbuilder
=> add debootstrapopts for Debian to point to the correct keyring location

mita-deploy/build/build, mita-deploy/config/definitions/mita-deploy.yml
Requires manual addition of `JENKINS_PRADO` and `JENKINS_PRADO_TOKEN` on the Jenkins UI
=> create a job to deploy mita

mita-deploy/config/definitions/mita-deploy.yml
=> mita-deploy: change the job name to mita-deploy

mita-deploy/build/build, mita-deploy/config/definitions/mita-deploy.yml
Since mita runs on Jenkins master, restrict it to run on local only, and use the new local_deploy.yml file in mita
=> local deploys for mita

README.rst
=> fix the example in the README on how to test and update jobs

build_snapshot_native.sh
Signed-off-by: Sage Weil <sage@redhat.com>
=> build_snapshot_native.sh: use make-dist

ansible/deploy_grafana.yml, ansible/roles/grafana/defaults/main.yml, ansible/roles/grafana/handlers/main.yml, ansible/roles/grafana/tasks/main.yml, ansible/roles/grafana/tasks/nginx.yml, ansible/roles/grafana/tasks/postgresql.yml, ansible/roles/grafana/templates/grafana.ini.j2, ansible/roles/grafana/templates/nginx_site.conf, ansible/roles/grafana/vars/main.yml, ansible/roles/nginx/handlers/main.yml, ansible/roles/nginx/tasks/main.yml, ansible/roles/nginx/templates/nginx.conf, ansible/roles/nginx/templates/nginx_site.conf
Has Github Auth disabled for now (it requires an actual public address for callbacks).
=> Grafana (and Nginx) Role

shaman-pull-requests/build/build, shaman-pull-requests/config/definitions/shaman-pull-requests.yml, shaman-pull-requests/setup/playbooks/ansible.cfg, shaman-pull-requests/setup/playbooks/setup.yml, shaman-pull-requests/setup/playbooks/tasks/postgresql.yml
Will run tox tests for each PR
=> adds a shaman-pull-requests job

ansible/roles/ceph-release/tasks/main.yml
=> replace version number in CMakeLists.txt if it exists

ansible/roles/nginx/tasks/main.yml, ceph-build-pull-requests/build/build
=> ceph-build-pull-requests: yaml files moved; update location

scripts/build_utils.sh
=> scripts: disable chacractl ssl verification temporarily

ceph-dev-build/config/definitions/ceph-dev-build.yml, ceph-dev/config/definitions/ceph-dev.yml
=> ceph-dev: gives the ability to select with architectures to build for

ceph-dev-build/build/build_rpm
This will need some functional testing to fix inconsistencies.
Not sure if the paths/urls are 100% correct.
=> ceph-dev-build: create ceph-release configuration and build steps

ceph-dev-build/build/build_deb, ceph-dev-build/build/build_rpm, ceph-dev-setup/build/build, ceph-dev/config/definitions/ceph-dev.yml
Does not include cmake work (yet) but leaves the cmake flags commented out to pave the way for changes later
=> flavor support for ceph-dev builds

calamari-server-trusty/build/build, calamari-server-trusty/config/definitions/calamari-server-trusty.yml
=> calamari-server-trusty: Upload the packages to chacra

ceph-dev-build/build/build_deb, ceph-dev-build/build/build_rpm
=> ceph-dev-build: print the shaman url for the repo on success

calamari-server-trusty/config/definitions/calamari-server-trusty.yml
=> calamari-server-trusty: pass the passwords for chacra upload

ansible/examples/slave.yml
=> ansible: if 127.0.1.1 add it and map it to ansible_hostname

ceph-dev-build/build/build_deb, ceph-dev-build/build/build_rpm
=> ceph-dev-build: post repo build info to chacra

ceph-dev-build/build/build_deb, ceph-dev-build/build/build_rpm
=> ceph-dev-build: remove trailing comma from repo extra json

ceph-dev-build/build/build_deb, ceph-dev-build/build/build_rpm
=> ceph-dev-build: fix the chacra url when posting repo-extra.json

ceph-dev-build/build/build_deb
=> ceph-dev-build: fix the value for package_manager_version for DEB

ceph-dev-build/config/definitions/ceph-dev-build.yml, ceph-dev-setup/build/build, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml, ceph-dev/config/definitions/ceph-dev.yml
This new job will respond to pushes to the ceph repo and trigger the ceph-dev job.
=> adds a ceph-dev-trigger job

diamond-build/build/build_rpm, diamond-build/build/setup, diamond-build/build/validate_rpm, diamond-build/config/definitions/diamond-build.yml, diamond-setup/build/build, diamond-setup/config/definitions/diamond-setup.yml, diamond/config/definitions/diamond.yml
=> Add initial diamond jenkins job

diamond-build/build/build_rpm, diamond-build/build/setup, diamond-build/config/definitions/diamond-build.yml, diamond-setup/build/build
=> diamond: Redesign + fixes

diamond-setup/build/build
=> diamond-setup: Handle VERSION properly

calamari-build/build/build_rpm, calamari-build/build/setup, calamari-build/build/validate_rpm, calamari-build/config/definitions/calamari-build.yml, calamari-setup/build/build, calamari-setup/config/definitions/calamari-setup.yml, calamari/config/definitions/calamari.yml
=> calamari: Add initial files for jenkins build

ceph-dev-build/build/build_deb, ceph-dev-build/build/build_rpm, ceph-dev-setup/build/build, scripts/build_utils.sh
This was already done in the setup job, but the variable doesn't percolate when modified it seems, so we need to do this filtering everywhere
=> Filter slashes out of branches

ceph-dev-setup/build/build
=> ceph-dev-setup: call autogen only when not using cmake

ceph-dev-setup/config/definitions/ceph-dev-setup.yml
=> ceph-dev-setup: include the build utils when building

ansible/examples/slave.yml
=> ansible: set utf-8 locale for the build user

ceph-dev-build/build/build_deb, ceph-dev-build/build/build_rpm, ceph-dev-build/build/failure, ceph-dev-build/config/definitions/ceph-dev-build.yml, ceph-dev-setup/build/build, ceph-dev-setup/build/failure, ceph-dev-setup/config/definitions/ceph-dev-setup.yml, scripts/build_utils.sh
Includes a  couple of helper scripts to avoid repetitive shell-to-json-and-back
=> update shaman on build status

ansible/examples/slave.yml, ansible/examples/slave_static.yml, ansible/library/jenkins_node
=> Rename jenkins-node module for ansible v2 compatibility

ceph-setup/build/build
=> ceph-setup: when in cmake use different flags for compression

ceph-docker-pull-requests/build/build, ceph-docker-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
and require the actual (better) host for this thing to build
=> install correct deps

ceph-docker-pull-requests/build/build, ceph-docker-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
A few fixes related to the actual location of the scripts for ceph-docker
=> Docker workspace

ceph-docker-pull-requests/build/build
=> ceph-docker-pull-requests: use sudo to remove deamon base and demo

ceph-setup/build/build
=> ceph-setup: mkdir and then copy recursively vs. using mv

ceph-docker-pull-requests/build/build
=> ceph-docker-pull-requests: really try to remove containers

ceph-docker-pull-requests/build/teardown
=> docker-pull-requests: use the correct path for teardown

ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph-dev-trigger: use a list, not a continuated string

ansible/roles/ceph-release/tasks/main.yml, ceph-tag/build/build, scripts/build_utils.sh
And a minor fix for the new kraken release of Ceph.
=> no binary installs for pip

ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph-dev-trigger: granularly define the branches to build for testing

ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph-dev-trigger: enable notcmalloc flavor

ceph-ansible-pr-syntax-check/build/build, ceph-ansible-pr-syntax-check/config/definitions/ceph-ansible-pr-syntax-check.yml
=> adds a new job to do syntax checks on ceph-ansible pull requests

ceph-ansible-pr-syntax-check/build/build, ceph-ansible-pr-syntax-check/config/definitions/ceph-ansible-pr-syntax-check.yml
Fixes found while testing with: https://github.com/ceph/ceph-ansible/pull/1051
=> ceph-ansible-pr-syntax-check: various fixes

ceph-build/build/build_rpm, ceph-build/build/setup_deb, ceph-build/build/setup_rpm, ceph-build/config/definitions/ceph-build.yml, ceph-setup/config/definitions/ceph-setup.yml, ceph/config/definitions/ceph.yml
Various fixes for things I found while rebuilding older versions of ceph.
=> fixes to allow for chacra.ceph.com repos to register with shaman

calamari/build/build_deb, calamari/build/build_rpm, calamari/config/definitions/calamari.yml
=> calamari: Fix-up deb and rpm builds

ceph-docker-pull-requests/build/failure
Signed-off-by: Ivan Font <ifont@redhat.com>
=> Do not exit immediately in failure script

samba/build/build_deb, samba/build/build_rpm, samba/build/setup, samba/config/definitions/samba.yml
This is just the result of the template script for samba/samba input. I want to get this in so that Ira could start testing his changes to this soon (he is not very thrilled with committing untested PRs so I'm doing it for him).
=> samba: Initial commit

kernel/build/build_deb, kernel/build/build_rpm, kernel/build/prepare_config
=> kernel: repo-extra json with kernelrelease

kernel/build/build_deb, kernel/build/build_rpm
=> kernel: Send package_manager_version information

ceph-dev-setup/config/definitions/ceph-dev-setup.yml, ceph-setup/config/definitions/ceph-setup.yml
define the arch so it doesn't pick up arm64 nodes
=> Ceph setup arch

ceph-pr-submodules/build/build, ceph-pr-submodules/config/definitions/ceph-pr-commits.yml
If the pull request has modified submodules, then fail the build
=> Ceph PRs submodules check

ansible/examples/slave_libvirt.yml
=> ansible: create a libvirt slave playbook

ceph-ansible-prs-centos7-cluster/build/build, ceph-ansible-prs-centos7-cluster/build/teardown, ceph-ansible-prs-centos7-cluster/config/definitions/ceph-ansible-prs-centos7-cluster.yml, ceph-ansible-prs-xenial-cluster/build/build
This job tests the centos7-cluster functional testing scenario in ceph-ansible.
Also, fixes the environment name for ceph-ansible-prs-xenial-cluster.
=> Adds the ceph-ansible-prs-centos7-cluster job

ceph-ansible-prs/build/build, ceph-ansible-prs/build/teardown, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: create a template for all jobs

ceph-ansible-pr-syntax-check/build/build
We now use yaml files so we need to change the mv accordingly.
=> ceph-ansible-pr-syntax-check: use yml file

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
For dmcrypt and collocated journals
=> enable other ceph-ansible scenarios

ceph-dev-new/config/definitions/ceph-dev.yml
=> ceph-dev-new: create a sister job for ceph-dev to build from ceph-ci

ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph-dev-trigger: trigger ceph-dev-new

ceph-dev-new/config/definitions/ceph-dev.yml
=> ceph-dev-new: fix the collision on the job name

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: adds the docker_cluster scenario

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> Revert "ceph-ansible-prs: add 2 scenarios"

ceph-docker-nightly/build/build, ceph-docker-nightly/config/definitions/ceph-docker-nightly.yml
=> ceph-docker-nightly: initial pass on a nightly test run for ceph-docker

samba/build/build_deb, samba/build/build_rpm
=> samba: send extra information

ansible/release.yml
=> ansible: use the ceph-release-team for the debian changelog

ceph-setup/build/build
=> ceph-setup: move the git diff check before calling autogen.sh

ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph-dev-trigger: remove the trigger for wip- branches for ceph.git

nfs-ganesha/build/build_deb, nfs-ganesha/build/build_rpm, nfs-ganesha/build/setup, nfs-ganesha/config/definitions/nfs-ganesha.yml
Need to quickly address issues marked "ALI TO DO" before able to merge.
=> nfs-ganesha: first run at a build script for rpms and debs

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: adds the purge_cluster_collocated scenario

nfs-ganesha/build/build_deb, nfs-ganesha/build/build_rpm, nfs-ganesha/config/definitions/nfs-ganesha.yml
=> nfs-ganesha: ceph fsals ON, change git repo url

nfs-ganesha/build/build_deb, nfs-ganesha/build/build_rpm, nfs-ganesha/build/setup, nfs-ganesha/config/definitions/nfs-ganesha.yml
Made changes to scm section to configure both git
repos.
Made all references to "dist" dir absolute paths
Made sure directories being git cleaned are
actual git repos
=> nfs-ganesha: fix scm section, add absolute paths

nfs-ganesha/build/build_deb, nfs-ganesha/build/build_rpm
=> nfs-ganesha: edit cmake command

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
So that we can notify shaman of queued builds.
We are currently getting 401's from shaman
=> Inject password triggers 

ceph-dev-build/build/setup_rpm, ceph-dev-new-build/build/setup_rpm
=> Revert "Send status to shaman earlier when building ceph rpm binaries"

calamari/build/build_rpm
=> print out build log if mock fails

calamari/config/definitions/calamari.yml
=> need sudo to clean dist on centos

nfs-ganesha/build/build_deb, nfs-ganesha/build/build_rpm, nfs-ganesha/config/definitions/nfs-ganesha.yml
nfs-ganesha/build/build_deb is still a WIP and the changes just mirror the changes made in build_rpm. Further changes to build_deb will be made in a separate PR soon.
=> nfs-ganesha: add "Build" section, 'Extras', other fixes

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This is deployed now and testing this ceph-ansible PR https://github.com/ceph/ceph-ansible/pull/1250
=> ceph-ansible-prs: adds purge cluster scenarios

ceph-docker-prs/config/definitions/ceph-docker-prs.yml
This is already enabled and testing https://github.com/ceph/ceph-docker/pull/470
=> ceph-docker-prs: enable PR testing for kraken images

nfs-ganesha/build/build_deb, nfs-ganesha/build/build_rpm, nfs-ganesha/build/failure, nfs-ganesha/build/setup, nfs-ganesha/config/definitions/nfs-ganesha.yml
=> nfs-ganesha: fixes to enable "Builds" section in shaman

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: adds the ansible2.2-docker_dedicated_journal test

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: adds ansible2.2-docker_dmcrypt_journal_collocation

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: adds the ansible2.2-update_dmcrypt scenario

nfs-ganesha/build/build_deb, nfs-ganesha/build/build_rpm, nfs-ganesha/build/setup_deb, nfs-ganesha/build/setup_rpm, nfs-ganesha/config/definitions/nfs-ganesha.yml
.debs building with pbuilder
remove $BRANCH variable
exit 0's are now exit 1
various minor fixes
=> nfs-ganesha: Debian builds working various fixes

nfs-ganesha/build/build_deb
=> nfs-ganesha: fix shaman url check for build_deb

ceph-dev/config/definitions/ceph-dev.yml, nfs-ganesha-trigger/build/notify, nfs-ganesha-trigger/config/definitions/nfs-ganesha-trigger.yml
=> nfs-ganesha: job that triggers builds of nfs-ganesha

chacra-pull-requests/setup/playbooks/tasks/postgresql.yml
=> chacra-pull-requests: fix postgresql installs for trusty and xenial

nfs-ganesha/build/build_deb
=> nfs-ganesha: add '-d' flag back to dpkg-buildpackage

nfs-ganesha/config/definitions/nfs-ganesha.yml
=> nfs-ganesha: fix broken shaman link for ubuntu builds

rtslib-fb-trigger/config/definitions/rtslib-fb-trigger.yml, rtslib-fb/build/build_rpm, rtslib-fb/build/setup, rtslib-fb/config/definitions/rtslib-fb.yml
=> rtslib-fb: initial builder definition

rtslib-fb/build/build_rpm
=> rtslib-fb: ensure rubygems package is installed

rtslib-fb/build/build_rpm
=> rtslib-fb: include rpm iteration based on git hash

tcmu-runner-trigger/config/definitions/tcmu-runner-trigger.yml, tcmu-runner/build/build_rpm, tcmu-runner/build/setup, tcmu-runner/config/definitions/tcmu-runner.yml
=> tcmu-runner: initial builder definition

tcmu-runner/build/build_rpm
=> tcmu-runner: install librbd1-devel and correct typo

tcmu-runner/build/build_rpm
=> tcmu-runner: include missing kernel header

nfs-ganesha/config/definitions/nfs-ganesha.yml
=> nfs-ganesha: add cron option to pollurl

rtslib-fb/build/build_rpm, tcmu-runner/build/build_rpm
=> tcmu-runner / rtslib-fb: sanitize branch name

rtslib-fb/build/build_rpm
=> rtslib-fb: corrected arch to 'noarch'

nfs-ganesha/config/definitions/nfs-ganesha.yml
=> nfs-ganesha: add default to

ceph-dev-build/config/definitions/ceph-dev-build.yml, nfs-ganesha/build/build_deb, nfs-ganesha/build/build_rpm, nfs-ganesha/config/definitions/nfs-ganesha.yml
=> nfs-ganesha: trigger builds from ceph-dev-build

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: adds the ansible2.2-update_cluster scenario

ceph-dev-build/config/definitions/ceph-dev-build.yml
=> nfs-ganesha: $CEPH_SHA1 now takes $SHA1 from ceph-dev-build job

ceph-dev-build/config/definitions/ceph-dev-build.yml
=> nfs-ganesha: add property files from ceph-dev-build to nfs-ganesha job

ceph-build/build/setup_pbuilder, ceph-dev-build/build/setup_pbuilder, ceph-dev-new-build/build/setup_pbuilder
=> setup_pbuilder: fix boolean test

nfs-ganesha/build/build_deb, nfs-ganesha/build/build_rpm, nfs-ganesha/build/setup
=> nfs-ganesha: add flavors and assing BRANCH to NFS_GANESHA_BRANCH

nfs-ganesha/build/build_deb, nfs-ganesha/build/build_rpm
=> nfs-ganesha: put flavor after chacra_endpoint

nfs-ganesha/build/build_rpm
=> nfs-ganesha: add missing quotation mark

ceph-ansible-prs/build/build, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: run tests for jewel and kraken

ceph-ansible-docs/build/build, ceph-ansible-docs/config/definitions/ceph-ansible-docs.yml
=> ceph-ansible-docs: initial take on automatic docs for ceph-ansible

ceph-ansible-docs-prs/build/build, ceph-ansible-docs-prs/config/definitions/ceph-ansible-docs-prs.yml
=> ceph-ansible-docs-prs: create a job for building docs on prs

bz-mill/config/definitions/bz-mill.yml
=> adds a job definition

bz-mill/config/definitions/bz-mill.yml
=> adds a builder def.

ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph-dev-trigger: also build luminous

bz-mill/config/definitions/bz-mill.yml
=> del the project -- don't need it

bz-mill/build/build, bz-mill/build/generate_map_namespace_to_query.sh
=> see what is in the enviroment

bz-mill/config/definitions/bz-mill.yml
=> add config to run the template generator

bz-mill/build/build, bz-mill/build/head, bz-mill/build/map_namespace_to_query, bz-mill/config/definitions/bz-mill.yml
=> re-organize the script

ceph-pr-arm-trigger/config/definitions/ceph-pr-arm-trigger.yml
=> ceph-prs-arm: create a job to build arm on PRs

ceph-pr-arm-trigger/config/definitions/ceph-pr-arm-trigger.yml
=> ceph-prs-arm: disable for now, needs to get worked on

ceph-ansible-scenario/build/build, ceph-ansible-scenario/build/teardown, ceph-ansible-scenario/config/definitions/ceph-ansible-scenario.yml
=> ceph-ansible-scenario: create an individual scenario job

ceph-ansible-scenario/config/definitions/ceph-ansible-scenario.yml
=> ceph-ansible-scenario: enable concurrent builds

ceph-docker-lint/build/build, ceph-docker-lint/config/definitions/ceph-docker-lint.yml
=> adds a linting of all shell files the project

ceph-docker-lint/build/build
=> install EPEL and correct package name

ceph-docker-lint/build/build
also add some provisions for running locally
=> limit shellcheck to files changed by the PR

ceph-docker-lint/build/build
=> fix exit of build script

ceph-docker-lint/config/definitions/ceph-docker-lint.yml
=> remove trigger whitelist

ceph-docker-lint/config/definitions/ceph-docker-lint.yml
=> check lint on all PRs automatically

ceph-docker-lint/build/build
=> filter files in PR to be only files ending in .sh$

ceph-docker-lint/build/build
and exit when deps aren't installed when running locally
=> fix the expected value of HUDSON_URL

ceph-docker-nightly/config/definitions/ceph-docker-nightly.yml, ceph-docker-prs/config/definitions/ceph-docker-prs.yml
=> ceph-docker: update scenario names

ceph-docker-lint/build/build
=> really fix the expected url to be canonicalized

ceph-dev-build/config/definitions/ceph-dev-build.yml, samba-trigger/config/definitions/samba-trigger.yml, samba/build/build_deb, samba/build/build_rpm, samba/config/definitions/samba.yml
This will trigger a samba build on push to any of master* ceph* or wip-*
branches.
=> samba-trigger: Trigger build on commits

ceph-docker-prs/config/definitions/ceph-docker-prs.yml
=> ceph-docker-prs: add more tests for osd scenarios and luminous

ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml
=> ceph-deploy-pull-requests: use python3 nodes

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: adds the ansible2.2-purge_docker_cluster scenario

ceph-dev-build/config/definitions/ceph-dev-build.yml
=> ceph-dev-build: disable nfs-ganesha and samba builds for now

ceph-dev-build/config/definitions/ceph-dev-build.yml
=> nfs-ganesha: re-enable triggered builds

ceph-docker-flake8/build/build, ceph-docker-flake8/config/definitions/ceph-docker-flake8.yml
This is a blatant ripoff of ceph-docker-lint, only for Python files.
=> Add ceph-docker-flake8

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: adds the *-update_docker_cluster scenario

ceph-volume-docs/build/build, ceph-volume-docs/config/definitions/ceph-lvm-docs.yml
=> ceph-volume-docs: renamed from ceph-lvm-docs

ceph-medic-pull-requests/build/build, ceph-medic-pull-requests/config/definitions/ceph-medic-pull-requests.yml
=> ceph-medic-pull-requests: adds a job to test ceph-medic PRs

nfs-ganesha/build/build_deb, nfs-ganesha/build/build_rpm
=> nfs-ganesha: fix version to match PACKAGE_MANAGER_VERSION

ceph-medic-rpm/build/build, ceph-medic-rpm/config/definitions/ceph-medic-rpm.yml
This models the same build process we do for ceph-ansible.
Has been tested and generated this repo: https://shaman.ceph.com/repos/ceph-medic/rpm-build/912c8154e3cc732355e494af60b999094be1e710/default/34894/
=> ceph-medic-rpm: a job to build rpms for every branch of ceph-medic

cephmetrics/build/build_rpm, cephmetrics/build/setup, cephmetrics/config/definitions/cephmetrics.yml
=> cephmetrics: Add new build job

cephmetrics/build/build_rpm
I missed this bit when doing the original PR :-/
=> cephmetrics: Use sudo for yum

nfs-ganesha-stable/build/build_deb, nfs-ganesha-stable/build/build_rpm, nfs-ganesha-stable/build/failure, nfs-ganesha-stable/build/setup, nfs-ganesha-stable/build/validate_deb, nfs-ganesha-stable/build/validate_rpm, nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml
=> nfs-ganesha: nfs-ganesha for download.ceph.com

samba/config/definitions/samba.yml
=> samba: Cleanup added yum/apt repos

samba/config/definitions/samba.yml
=> samba: fix path to shaman.list when tearing down

nfs-ganesha-stable/build/build_deb, nfs-ganesha-stable/build/build_rpm, nfs-ganesha-stable/build/failure, nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml
=> nfs-ganesha-stable: correct job name and display name

cephmetrics/build/setup, cephmetrics/config/definitions/cephmetrics.yml
=> cephmetrics: Clean with sudo

cephmetrics-pull-requests/build/build, cephmetrics-pull-requests/config/definitions/cephmetrics-pull-requests.yml
=> Add cephmetrics-pull-requests

cephmetrics-pull-requests/build/build, cephmetrics-pull-requests/config/definitions/cephmetrics-pull-requests.yml, cephmetrics-pull-requests/setup/setup
=> cephmetrics-pull-requests: Install package deps

cephmetrics/build/build_rpm
=> download the source for the pie-chart panel

cephmetrics/build/build_rpm
=> fix destination path for pichart plugin

cephmetrics/config/definitions/cephmetrics.yml
=> cephmetrics: build on pushes for now

ceph-medic-docs/build/build, ceph-medic-docs/config/definitions/ceph-medic-docs.yml
=> ceph-medic-docs: create a docs job

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Add luminous release to CI tests.
=> ceph-ansible-prs: Add luminous release

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: add bluestore dmcrypt scenario

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This is a bit hacky but I don't any other ways to achieve that.
=> ceph-ansible-prs: do not run bluestore on luminous

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
We decided to only test LTS releases.
=> ceph-ansible-prs: remove testing on Kraken

ceph-medic-release/build/build_rpm, ceph-medic-release/config/definitions/ceph-medic-release.yml
This job will be used to make repos we can host on
download.ceph.com
=> adds new ceph-medic-release job

ceph-medic-release/config/definitions/ceph-medic-release.yml
This looks like a bad copy & paste from elsewhere.
=> ceph-medic-release: rm SSH key comment

ceph-medic-tests/build/build, ceph-medic-tests/config/definitions/ceph-medic-tests.yml
This uses a job-template so as we build more testings scenarios
they can be added here easily.
=> ceph-medic-tests: a job to run nightly tests for ceph-medic

ceph-iscsi-config-trigger/config/definitions/ceph-iscsi-config-trigger.yml, ceph-iscsi-config/build/build_deb, ceph-iscsi-config/build/build_rpm, ceph-iscsi-config/build/setup, ceph-iscsi-config/build/validate_deb, ceph-iscsi-config/build/validate_rpm, ceph-iscsi-config/config/definitions/ceph-iscsi-config.yml
=> ceph-iscsi-config: initial rpm package testing

ceph-iscsi-config/build/build_rpm
=> ceph-iscsi-config: corrected sed replacements

ceph-iscsi-config/build/build_rpm, ceph-iscsi-config/config/definitions/ceph-iscsi-config.yml
=> ceph-iscsi-config: additional RPM build fixes

ceph-iscsi-config/build/build_rpm
=> ceph-iscsi-ansible: fix mock chroot name

ceph-iscsi-cli/build/build_rpm, ceph-iscsi-config/build/build_rpm
=> ceph-iscsi-config: alternate attempt to build source tarball

ceph-iscsi-cli/build/build_rpm, ceph-iscsi-config/build/build_rpm
=> ceph-iscsi: fixed chacra rpm path

ceph-iscsi-tools/build/build_deb, ceph-iscsi-tools/build/build_rpm, ceph-iscsi-tools/build/setup, ceph-iscsi-tools/build/validate_deb, ceph-iscsi-tools/build/validate_rpm, ceph-iscsi-tools/config/definitions/ceph-iscsi-tools.yml
=> ceph-iscsi: added builder for ceph-iscsi-tools

ceph-volume-pr/config/definitions/ceph-volume-pr.yml
Without this change, it manage to get triggered on every ceph PR
=> ceph-volume-pr: only get triggered on phrases

ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml, ceph-pull-requests/config/definitions/ceph-pull-requests.yml
pattern to skip : qa tests .* skip build
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>
=> Add option to skip build for qa scripts/yaml changes

ceph-dev-build/config/definitions/ceph-dev-build.yml, nfs-ganesha/config/definitions/nfs-ganesha.yml
=> nfs-ganesha: build only twice a day, change nfs-ganesha-debian branch

chacra-pull-requests/build/build
=> chcacra-pull-requests: cleanup repos before ansible runs

ceph-pr-docs/config/definitions/ceph-pr-docs.yml
=> ceph-pr-docs: only get triggered on prs

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml, ceph-docker-prs/config/definitions/ceph-docker-prs.yml
=> Revert "ceph-ansible-prs: add naginator configuration"

scripts/sync-push
=> scripts: Don't sync any lockfiles leftover by reprepro

ceph-volume-ansible-prs/build/build, ceph-volume-ansible-prs/build/teardown, ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
=> ceph-volume-ansible-prs: create job template(s)

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
=> ceph-volume-ansible-prs: do not use raw xml, use the jjb option for ghprb

ceph-volume-ansible-prs/build/build
=> ceph-volume-ansible-prs: fallback on sha1 to get remote branch

lab-cop/build/build, lab-cop/config/definitions/lab-cop.yml
=> adds a tool to check node usage in the labs

nfs-ganesha/config/definitions/nfs-ganesha.yml
=> nfs-ganesha: fix timer

ceph-pr-docs/config/definitions/ceph-pr-docs.yml
=> ceph-pr-docs: make build concurrent

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: adds the lvm_osds and purge_lvm_osds scenarios

README.rst
Give developers a hint about what to look for in the output of "jenkins-jobs test".
=> README: more context for what "jenkins-jobs test" does

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Seconds https://github.com/ceph/ceph-ansible/pull/1803
=> ceph-ansible-prs: add disk autodiscovery scenario

tcmu-runner/build/build_rpm, tcmu-runner/config/definitions/tcmu-runner.yml
=> tcmu-runner: remove UAPI patch and add Ceph repo for build

tcmu-runner/config/definitions/tcmu-runner.yml
=> tcmu-runner: remove shaman repo file after build

tcmu-runner/build/build_rpm
=> tcmu-runner: added missing distro release

tcmu-runner/build/build_rpm
=> tcmu-runner: updated libtcmu package contents

tcmu-runner/build/build_rpm, tcmu-runner/config/definitions/tcmu-runner.yml
=> tcmu-runner: removed duplicate DIST axis

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml, ceph-docker-nightly/config/definitions/ceph-docker-nightly.yml, ceph-medic-tests/config/definitions/ceph-medic-tests.yml
=> Only test using ansible 2.3

tcmu-runner/build/build_rpm
=> tcmu-runner: adjust build flags to match brew environment

tcmu-runner/build/build_rpm
=> tcmu-runner: handle vX.Y.Z-rcX git tag formats

tcmu-runner/build/build_rpm
=> tcmu-runner: convert all dashes to period in revision

lab-cop/config/definitions/lab-cop.yml
=> change this job to be manually triggered

lab-cop/build/build
=> checkout teuthology

lab-cop/build/build
=> fix syntax error

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: add shrink mon/osd for container

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Add collocation scenario for containers.
=> ceph-ansible-prs: add collocation scenario

scripts/build_utils.sh
=> scripts: Fix typo

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
=> ceph-ansible-nightly: test all luminous scenarios

ceph-docker-nightly/build/build, ceph-docker-nightly/config/definitions/ceph-docker-nightly.yml
=> ceph-docker-nightly: Update definition to match PR scenarios

ansible/examples/slave_libvirt_static.yml
=> ansible: Set jenkins_group on Zesty and later

scripts/build_utils.sh
Fixes bug in https://github.com/ceph/ceph-build/pull/884
=> scripts: Fix libvirt cleanup script from previous PR

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml, ceph-docker-nightly/config/definitions/ceph-docker-nightly.yml
For ceph-ansible and ceph-docker.
=> ceph-ansible-nightly: add new scenarios to nightly

nfs-ganesha/build/build_rpm
=> nfs-ganesha: update cmake options for rpms

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml, ceph-docker-nightly/config/definitions/ceph-docker-nightly.yml, ceph-docker-prs/config/definitions/ceph-docker-prs.yml
Relies on https://github.com/ceph/mita/pull/116
=> ceph-{ansible,docker}: Run jobs on centos7 slaves

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
we need to test purge_cluster for filestore and for bluestore.
=> ceph-ansible-prs: split purge_cluster test

ansible/examples/slave_libvirt.yml, ansible/slave_libvirt.yml
Required by https://github.com/ceph/ceph-docker/blob/master/tests/tox.sh#L77
=> ansible: add iproute to centos libvirt slave deps

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: test against ansible2.4 on pull requests

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
test nightlies against ansible2.2 and 2.4 for ceph-ansible
=> ceph-ansible-nightly: test against ansible2.2/2.4

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
=> ceph-ansible-nightly: add more nightly tests

jenkins-job-builder/build/build
=> jenkins-job-builder: Delete stale jobs

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
We don't test master with ansible2.2
=> ceph-ansible-nightlies: followup on 3adf56e

ceph-volume-ansible-prs/build/build, ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
=> ceph-volume-ansible-prs: adds the bluestore testing scenario

ceph-ansible-nightly/build/build, ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml, ceph-ansible-prs/build/build, scripts/build_utils.sh
update ceph-ansible-nightlies according to new needs for downstream product
=> ceph-ansible-nightlies: update nightlies test to fit new needs

ceph-container-nighlity/config/definitions/ceph-container-nightly.yml, ceph-container-prs/config/definitions/ceph-container-prs.yml
=> ceph-container: Get rid of jewel bluestore tests

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
=> ceph-ansible: restore stable-2.2 scenarios for ceph-ansible

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
=> ceph-ansible-nightly: update project name

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
=> ceph-ansible-nightly: add project for jewel/stable3.0

ceph-volume-ansible-prs/build/build, ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
=> ceph-volume: adds pr tests for the simple subcommand

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: enable github-hooks for oldstable-trigger

ceph-build/build/setup_pbuilder, ceph-dev-build/build/setup_pbuilder, ceph-dev-new-build/build/setup_pbuilder
=> setup_pbuilder: point gcc to gcc-7 on trusty

sepia-fog-images/README.rst, sepia-fog-images/build/build, sepia-fog-images/build/failure, sepia-fog-images/config/definitions/sepia-fog-images.yml
=> sepia-fog-images: Job creation

kernel-trigger/config/definitions/kernel-trigger.yml
=> kernel: added 'ceph-iscsi*' branches to trigger list

ceph-build/config/definitions/ceph-build.yml, ceph-dev-build/config/definitions/ceph-dev-build.yml, ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml, ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
by "new branches", i mean any branche whose name is not started with
"jewel" or "luminous".
see http://groovy-lang.org/operators.html, and
https://issues.jenkins-ci.org/browse/JENKINS-25465
=> ceph-*-build: do not build new branches on trusty

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml, ceph-pr-arm-trigger/config/definitions/ceph-pr-arm-trigger.yml
=> ceph-dev{,-new}-trigger: pass DISTROS using a list

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
it's a regression introduced by 3a0b799b
=> ceph-dev-{,new-}trigger: add FLAVOR=notcmalloc back
