- ceph-build-pull-requests/config/definitions/ceph-build-pull-requests.yml
- ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml
Looks like these jobs should now not poll GH for changes. The only trigger should be the pull request
> remove poll scm option for pull request jobs

- ceph-setup/build/build
Remove `do_autogen.sh` from the ceph-setup task. Run `./autogen.sh` and `./configure` instead.
I've copied this long `./configure` argument list from a prior run of `./do_autogen.sh` so that we're using the same arguments. We can adjust it as needed.
One of the reasons for making this change is that `./do_autogen.sh` takes an argument ("`-L`") depending on whether we're building a Hammer or Firefly release. The goal of this change is to use a more stable interface for doing the builds.
As background, from Sage on IRC yesterday:
```
sage: i'm surprised jenkins is using do_autogen.sh at all actually?
ktdreyer: what should it use?
sage: ./autogen.sh and then pass the args explicitly to ./configure
that it wants?
sage: it doesn't really matter i guess, but do_autogen.sh piles a
bunch of …
```
> ceph-setup: remove do_autogen.sh

- build_rpms.sh
As Ceph changes and new files get installed by default, we need to ensure that the commits which create these files also update the packaging files lists as well.
One way to do this is to tell Gitbuilder to stop skipping unpackaged files in the RPMs. This will cause Gitbuilder builds to indicate a failure when new files get added without packaging updates.
> build_rpms.sh: terminate on unpackaged files

- ceph-package/config/definitions/ceph-package.yml
When I imported the ceph-package job, I made a bad copy & paste in the name - it was erroneously named "ceph-build".
This PR updates the job's name to the correct value.
> ceph-package: fix job name

- ceph-package/config/definitions/ceph-package.yml
Commit f8d03a28c00e8ad6b2c496e069de6492791496ba fixed the internal Jenkins job name, this fixes the display name as well.
> ceph-package: fix display name

- ceph-build-pull-requests/build/build
Running the pull requests script with `-x` is very noisy. The script already prints a lot of information with "echo", so just silence the debugging outupt.
> ceph-build-pull-requests: quiet output

- ceph-setup/config/definitions/ceph-setup.yml
Jenkins (un)helpfully tags each build. Don't do this in the ceph-setup task.
See https://bugzilla.redhat.com/show_bug.cgi?id=1214907
> ceph-setup: skip tagging each build

- radosgw-agent/config/definitions/radosgw-agent.yml
It doesn't make sense to name this job "wip", since we're using it to build releases.
> radosgw-agent: remove wip display name

- ceph-deploy/config/definitions/ceph-deploy.yml
- radosgw-agent/config/definitions/radosgw-agent.yml
Prior to this commit the archive settings were quoted `'false'` or `'true'` instead of simply the boolean types that YAML expects.
jenkins-jobs interpreted these strings to be "true", so we ended up with the following XML:
```
<latestOnly>true</latestOnly>
```
This meant that Jenkins deleted all the older archived ceph-deploy packages each time a new version was built.  When 1.5.22.1 was built, the "older" 1.5.23 package was deleted.
Unquote the boolean values so JJB will properly interpret them.
Thanks @dmick for pointing me in the right direction here.
> unquote archive settings

- ceph-build/config/definitions/ceph-build.yml
- ceph-deploy/config/definitions/ceph-deploy.yml
- ceph-package/config/definitions/ceph-package.yml
- ceph-release-rpm/build/build
- ceph-release-rpm/config/definitions/ceph-release-rpm.yml
- radosgw-agent/config/definitions/radosgw-agent.yml
Remove the Fedora 20 build slave from the job configs.
We're having trouble resurrecting gitbuilder-cdep-rpm-cloud-fedora20-amd64-basic.cloud.sepia.ceph.com in DreamCompute, and Fedora 20 itself is going EOL in a month or so.
This is the only Fedora builder we have, and this VM does build packages for http://ceph.com/rpm-hammer/fc20/, so it would be nice to get fresh Fedora build slaves set up eventually. But in the meantime, since this one is giving us trouble, just remove it.
> remove fedora20 Jenkins slave

- ceph-deploy/build/build
It will now use `$DIST` although in a not very flexible way. 
It fixes a EOF error as well and removes some hard coded variables.
> fix/improve ceph-deploy build script

- ceph-deploy/build/build
/bin/sh is dash on Ubuntu/Debian. Switch to bash for uniformity with RPM systems.
> ceph-deploy: build with bash, not /bin/sh

- ceph-build-pull-requests/config/definitions/ceph-build-pull-requests.yml
- ceph-deploy-docs/config/definitions/ceph-deploy-docs.yml
- ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml
- ceph-deploy/config/definitions/ceph-deploy.yml
- ceph-qa-suite-pull-requests/config/definitions/ceph-qa-suite-pull-requests.yml
- ceph-setup/config/definitions/ceph-setup.yml
- jjb/config/definitions/jjb.yml
- teuthology-docs/config/definitions/teuthology-docs.yml
Fixes the problem with all the other jobs that used a rather hardcoded name.
Using 'trusty' is more flexible because we can have more 'trusty' nodes around
> use the 'trusty' label

- ceph-build/build/setup_pbuilder
So that it avoids building every distro on every server on
every build
> make setup_pbuilder use DIST

- ceph-build/build/build_rpm
- ceph-build/config/definitions/ceph-build.yml
This completes the porting of scripts needed to build Ceph and finally removes all the `$bindir` requirements.
> port the build_rpm scripts

- ceph-setup/build/build
1) invoke sh with -ex for verbosity and exit-on-error
2) fix syntax error with [] (missing space before ])
3) restore commented-out mv before dpkg-source -b.
I'm not sure why the copy copies to release/$vers and then
later moves to ceph-$vers, but something has to put it in
ceph-$vers.
> Three fixes to ceph-setup/build/build:

- ceph-setup/build/build
`/bin/sh` is dash on Ubuntu/Debian. Switch to bash for uniformity with RPM systems.
> ceph-setup: use bash, not sh

- ceph-setup/build/build
Now that we "`set -e`" in ceph-setup (#74), we can drop the bits that check exit codes "$?" throughout the ceph-setup task.
> ceph-setup: rm exit code checking

- jenkins-slave-chef-pull-requests/config/definitions/jenkins-slave-chef-pull-requests.yml
- radosgw-agent-pull-requests/config/definitions/radosgw-agent-pull-requests.yml
- radosgw-agent/config/definitions/radosgw-agent.yml
The DreamCompute builders (including the Precise builder) are no longer available to us.
Switch the jobs that used the DreamCompute Precise builder to use the trusty label instead.
> switch "precise" jobs to build on trusty

- ceph-build/build/build_rpm
As was done in 18890d5a0351ffe4fc495e0d47e3a86e0a9cb7ad for radosgw-agent, update ceph-build's SUSE detection so we check for the "zypper" file directly on-disk.
> ceph-build: better SUSE detection

- teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
This should be defaulted by the plugin and is unneeded here.
> teuthology-pull-requests: remove empty trigger-phrase

- ceph-build-pull-requests/config/definitions/ceph-build-pull-requests.yml
- ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml
- ceph-qa-suite-pull-requests/config/definitions/ceph-qa-suite-pull-requests.yml
- jenkins-slave-chef-pull-requests/config/definitions/jenkins-slave-chef-pull-requests.yml
- radosgw-agent-pull-requests/config/definitions/radosgw-agent-pull-requests.yml
- teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
From the Jenkins GitHub Pull Requests plugin docs on "useGitHubHooks":
Checking this option will disable regular polling (cron) for changes
in GitHub and will try to create a GitHub hook. Creating a GitHub hook
requires that the user which is specified in the GitHub Pull Request
Builder configuration has admin rights to the specified repository.
Based on the documentation above, since our PR jobs have "`github-hooks: true`", the "`cron`" values have no effect and can be removed.
> pull requests: rm "cron" settings

- ceph-setup/config/definitions/ceph-setup.yml
The ceph-setup task occasionally gets weird errors that can only be fixed by wiping the workspace.
The latest example:
tardir=ceph-0.94.1.3 && ${TAR-tar} chof - "$tardir" | GZIP=--best gzip -c >ceph-0.94.1.3.tar.gz
tar: ceph-0.94.1.3/src/gmock/gtest/xcode/Samples/FrameworkSample/WidgetFramework.xcodeproj/project.pbxproj: file name is too long (max 99); not dumped
tar: ceph-0.94.1.3/src/test/ubuntu-12.04/debian: File removed before we read it
tar: ceph-0.94.1.3/src/test/ubuntu-14.04/debian: File removed before we read it
tar: ceph-0.94.1.3/src/test/debian-jessie/debian: File removed before we read it
tar: Exiting with failure status due to previous errors
... btw, :heart: the comment in this job's description, "The clear workspace before checkout box for the git plugin is used."
> ceph-setup: wipe workspace

- teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
- teuthology-pull-requests/setup/setup
This will setup the jenkins slaves properly to successfully run the tox
tests on pull requests.
> teuthology-pull-requests: run the teuthology bootstrap on setup

- teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
If we don't do this pip breaks. See:
http://jenkins.ceph.com/job/teuthology-pull-requests/1560/console
> teuthology-pull-requests: wipe workspace on each run

- teuthology-pull-requests/setup/setup
This is a flag used to tell the bootstrap script to install any missing
packages it finds needed for the bootstrap process.
> teuthology-pull-requests: pass the 'install' command to ./bootstrap

- teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
Ivo Jimenez (@ivotron) is a Red Hat intern working on teuthology. Whitelist his account so we don't have to manually approve testing his PRs.
cc @andrewschoen , @zmc
> whitelist Ivo for teuthology PRs

- ansible/master/master.yml
This plugin is not color-blind friendly. It is possible to turn it off on a per-user setting, but that requires logging into Jenkins. Let's just turn it off entirely so we're fully accessible for people who
aren't logged in.
> ansible: rm green balls plugin

- ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml
These users have contributed patches to ceph-deploy. Whitelist their PRs going forward so we don't have to manually approve testing each one.
Milan Broz (@mbroz)
David Disseldorp (@ddiss)
Owen Synge (@osynge)
cc'ing @trhoden & @alfredodeza
> update user whitelist for ceph-deploy PRs

- deb_dists
to fix the error on gitbuilder of "gitbuilder-ceph-deb-jessie-amd64-basic":
```
+ /srv/ceph-build/gen_reprepro_conf.sh ../out/output/sha1/6ffb1c4ae43bcde9f5fde40dd97959399135ed86.tmp 03C3951A
dists sid
wheezy
squeeze
raring
quantal
precise
saucy
trusty
components main
done
+ GNUPGHOME=/srv/gnupg reprepro --ask-passphrase -b ../out/output/sha1/6ffb1c4ae43bcde9f5fde40dd97959399135ed86.tmp -C main --ignore=undefinedtarget --ignore=wrongdistribution include jessie out~/ceph_0.94.2-50-g6ffb1c4-1jessie_amd64.changes
Cannot find definition of distribution 'jessie'!
There have been errors!
```
see http://gitbuilder.sepia.ceph.com/gitbuilder-ceph-deb-jessie-amd64-basic/log.cgi?log=6ffb1c4ae43bcde9f5fde40dd97959399135ed86
> add jessie to deb_dists

- ceph-setup/build/build
We are no longer using this method of dealing with script dependency.
> remove references/tests for bindir

- ceph-setup/build/build
- ceph-setup/config/definitions/ceph-setup.yml
always call `./install-deps.sh` so that deps are ensured because `configure` checks for them and comment about pinning on trusty which is no longer needed in the new environment
> Ceph setup unpin

- jjb/config/definitions/jjb.yml
In commit fac5ec4127ac1178b40ce0bd8bd176af355aadce I slowed down the Git SCM polling for the JJB management job, with the reasoning that the GitHub webhook would be a more responsive and efficient method of triggering builds.
However, this was not entirely sufficient because the JJB job itself must also be explicitly configured to accept the GitHub webhook notifications.
Add "github" to the list of triggers for the JJB job. (This setting corresponds to the "Build when a change is pushed to GitHub" checkbox in Jenkins web UI.)
> jjb: accept change notifications from GitHub

- ceph-build/config/definitions/ceph-build.yml
Not sure if we need a combination filter anymore :/
> remove i386 from ceph-build

- ceph-puppet-modules/build/rename-ceph-puppet-modules
- ceph-puppet-modules/config/definitions/ceph-puppet-modules.yml
The downstream takora package in RHCS is named "ceph-puppet-modules". Define a job that creates debian packages with that name.
> import "ceph-puppet-modules" job

- mariner-installer/build/build
- mariner-installer/config/definitions/mariner-installer.yml
Start building upstream packages for
https://github.com/ceph/mariner-installer
> Add mariner-installer job

- ceph-build/build/build_deb
- ceph-build/build/setup_pbuilder
- ceph-build/config/definitions/ceph-build.yml
- ceph-deploy/build/build
- ceph-deploy/config/definitions/ceph-deploy.yml
- ceph-package/config/definitions/ceph-package.yml
- radosgw-agent/build/build
- radosgw-agent/config/definitions/radosgw-agent.yml
Adds Jessie support on the build scripts for Ceph, radosgw-agent, and ceph-deploy
Removes older distros that we do not build for anymore
> Jessie support

- ceph-build/build/build_deb
- ceph-build/build/setup_pbuilder
- ceph-deploy/build/build
- ceph-deploy/config/definitions/ceph-deploy.yml
- deb_dists
- gen_debian_version.sh
- update_pbuilder.sh
Ubuntu 12.10 (Quantal Quetzal) reached EOL May 16 2014. Remove support from the tree.
https://lists.ubuntu.com/archives/ubuntu-announce/2014-April/000183.html
This also removes the execution strategy filter, since it was only for quantal/arm, similar to what was done in bd3113c09370dad9eb08d5536e19ab3e94b141b9.
> rm references to "quantal"

- takora/build/build
Makes takora job similar to ceph-deploy and mariner-installer
> Use $DIST for determining distro

- rhcs-installer/build/rename-rhcs-installer
- rhcs-installer/config/definitions/rhcs-installer.yml
Job to build rhcs-installer package from upstream mariner-installer
source/job.
At first I didn't think this would do everything we needed, but when going through it I think it might get it all.  Only way to find out I think is to build it and see what happens.
FWIW, I think in the `debian/control` file that the `Source:` line may not need to changed.  It is possible in debian packaging to handle renaming an upstream project with a different package name, but I don't know much about it.  Let's start here. :)
> Add rhcs-installer job

- ceph-build/config/definitions/ceph-build.yml
- ceph-deploy/config/definitions/ceph-deploy.yml
- ceph-package/config/definitions/ceph-package.yml
- ceph-puppet-modules/config/definitions/ceph-puppet-modules.yml
- ceph-release-rpm/config/definitions/ceph-release-rpm.yml
- ice-setup/build/build
- ice-setup/config/definitions/ice-setup.yml
- mariner-installer-pull-requests/config/definitions/mariner-installer-pull-requests.yml
- mariner-installer/config/definitions/mariner-installer.yml
- radosgw-agent/config/definitions/radosgw-agent.yml
- rhcs-installer/config/definitions/rhcs-installer.yml
- takora-pull-requests/config/definitions/takora-pull-requests.yml
- takora/config/definitions/takora.yml
This allows us to finally get rid of the dependency of setting `DIST` and `BPTAG` on actual slaves, giving us flexibility to just consume whatever is set by Jenkins.
Since the configuration matrix will use `DIST` and not `Dist` it means that it will be available as an environment variable throughout.
It does some other minor cleanups as well.
> normalizing to `DIST`

- rhcs-installer/build/rename-rhcs-installer
> rhcs-installer needs ceph-puppet-modules

- ceph-build/build/setup_pbuilder
Fixes invalid use of paths for removing tgz files.
Corrects the call to Python to verify a file is a valid tgz file. Adds `sudo` to the `rm` call (it totally didn't work before) and uses the GTECH Debian mirror because the internal mirror doesn't know about Jessie and we should not wait for a full sync of the Jessie repo to run this build.
The changes are currently in place and building http://jenkins.ceph.com/job/ceph-build/ARCH=x86_64,DIST=jessie/410/console
> Jessie mirror

- ceph-build/config/definitions/ceph-build.yml
The Jessie builder is offline at the moment. Don't hold up all the builds because of this.
(this reverts commit ddb77546e58501edbf01a20c4971445a46ae2351)
> ceph-build: remove jessie

- teuthology-docs/build/build
Manually changed this in Jenkins and the job was a success.
http://jenkins.ceph.com/job/teuthology-docs/608/
> remove -e flag because that 'execs' an ssh command and there is none

- ansible/slave.yml
- ceph-build-next/build/build_deb
- ceph-build-next/build/build_rpm
- ceph-build-next/config/definitions/ceph-build-next.yml
After deb and rpm binaries are built, push them to chacra.
Also includes ansible to upload the .chacractl file to the jenkins slaves. Because of the api credentials that actual file is not committed here.
> ceph-build-next: push binaries to chacra

- ansible/roles/ansible-jenkins/tasks/config.yml
- ansible/roles/ansible-jenkins/tasks/dependencies.yml
- ansible/roles/ansible-jenkins/tasks/dependencies_yum.yml
- ansible/roles/ansible-jenkins/tasks/jenkins.yml
- ansible/roles/ansible-jenkins/tasks/repo.yml
- ansible/roles/ansible-jenkins/vars/main.yml
We originally copied this role from https://github.com/ICTO/ansible-jenkins, and then modified it to support CentOS.
As it turns out, our master runs on Ubuntu (Trusty), so we still need the Ubuntu bits. Add them back in here.
> ansible: merge back in Ubuntu support

- ansible/roles/ansible-jenkins/templates/nginx.conf
On CentOS, the nginx package from EPEL defaults to using the "nginx" UID.
On Ubuntu, the nginx package defaults to using the "www-data" UID.
Ideally we'd conditionalize this with Ansible variables, but I'll just hack it in for now.
> ansible: use Ubuntu UID for nginx.conf

- ansible/roles/ansible-jenkins/templates/jenkins.conf
Add HTTPS to the jenkins web server to protect authentication.
The key and certificate files are managed outside of Ansible.
> ansible: nginx configs for HTTPS

- ansible/master.yml
not needed on jenkins.ceph.com
> ansible: don't enable ldap plugin

- ansible/master.yml
https://wiki.jenkins-ci.org/display/JENKINS/Mask+Passwords+Plugin
Currently the jenkins-job-builder job relies on a static /etc/jenkins_jobs.ini config file that we put into place on a slave by hand. We do that to avoid exposing the account password that JJB uses.
The mask-passwords Jenkins plugin will allow us to dynamically write passwords in to files on the fly. This means that we can construct JJB's config file on the fly, or chacractl's config file, etc. It allows us to avoid storing cryptographic secrets (passwords) on the slaves, since the secret material will only be stored on the master.
> ansible: add mask-passwords plugin

- ansible/slave.yml
- ansible/slave.yml.j2
We're not going to worry about the private keys anymore and the
jenkins_job.ini and .chacractl files are going to be created using the
mask-passwords plugin for jenkins.
> remove unneeded tasks from slave.yml and slave.yml.j2

- ansible/slave.yml
- ansible/slave.yml.j2
Update the URL for our new production Jenkins instance
Use the dedicated "prado" UID to join the systems to Jenkins
Use the new SSH key credentialId for our new production Jenkins instance
> ansible: slave config updates

- ansible/slave.yml.j2
These packages were failing to install on CentOS 7, we do not think they
are needed anyway.
> do not install dpkg and dpkg-dev on yum based jenkins slaves

- ansible/master.yml
Some jobs use this plugin. Add it to our master's Ansible configuration.
> ansible: add description-setter plugin

- ceph-build-next/build/build_deb
- ceph-build-next/build/build_rpm
- ceph-next/config/definitions/ceph-next.yml
If TEST_BUILD is checked, it'll push binaries to chacra.ceph.com under the ``test`` ref. This way we can make sure to separate testing binaries from release ones.
> add the ability to do ceph test builds

- ceph-mirror/build/build
- ceph-mirror/config/definitions/ceph-mirror.yml
Initially it will just list the remotes because reading the docs I couldn't see how to 'name' a remote. This doesn't do anything just yet.
> mirror the ceph repo

- ceph-setup-next/config/definitions/ceph-setup-next.yml
We've updated our tagging scheme, so now this job should request a slave
that's tagged with both 'huge' and 'trusty'.
> ceph-setup-next should request a huge trusty node

- ceph-setup-next/config/definitions/ceph-setup-next.yml
> use the right credentials id user for git ceph-releases

- jenkins-job-builder/config/definitions/jjb.yml
GitHub's webhooks to https://jenkins.ceph.com/git/notifyCommit are not triggering rebuilds of this job.
Tweak the URLs to see if this makes a difference.
> jenkins-job-builder: update URLs

- ceph-deploy-docs/config/definitions/ceph-deploy-docs.yml
* normalize the GitHub URLs
* switch to GitHub webhooks (instead of polling)
* only keep the logs for the last 10 jobs
> ceph-deploy-docs: misc changes

- ceph-build-next/build/build_deb
> ceph-build-next: fix the grep that finds the binaries to push to chacra

- calamari-clients-precise-vagrant/config/definitions/calamari-clients-precise-vagrant.yml
- calamari-clients-precise/config/definitions/calamari-clients-precise.yml
- calamari-clients-rhel/config/definitions/calamari-clients-rhel.yml
- calamari-clients-rhel7/config/definitions/calamari-clients-rhel7.yml
- calamari-clients-trusty/config/definitions/calamari-clients-trusty.yml
- calamari-clients-vagrant/config/definitions/calamari-clients-vagrant.yml
- calamari-clients-wheezy/config/definitions/calamari-clients-wheezy.yml
- calamari-server-centos/config/definitions/calamari-server-centos.yml
- calamari-server-precise/config/definitions/calamari-server-precise.yml
- calamari-server-rhel/config/definitions/calamari-server-rhel.yml
- calamari-server-rhel7/config/definitions/calamari-server-rhel7.yml
- calamari-server-trusty/config/definitions/calamari-server-trusty.yml
- calamari-server-vagrant/config/definitions/calamari-server-vagrant.yml
- calamari-server-wheezy/config/definitions/calamari-server-wheezy.yml
- calamari-server/config/definitions/calamari-server.yml
A bug in jenkins-job-wrecker screwed up the "branches" settings when we
imported these jobs from the internal Calamari jenkins server. Fix this.
> fix calamari jobs' "branches" definition

- ansible/roles/ansible-jenkins/templates/jenkins.conf
This will cause a browser to automatically load the "https://" URL when the user enters "jenkins.ceph.com" into the browser.
We are using HTTP redirects from HTTP -> HTTPS already on jenkins.ceph.com, but this change should make it a bit more secure.
See https://www.owasp.org/index.php/HTTP_Strict_Transport_Security for more information
> ansible: set HSTS header in nginx

- ceph-release-rpm/build/build
This should be more reliable than the Gitweb interface, and matches what we've done in ceph's docs, ceph-deploy, etc.
> ceph-release-rpm: use download.ceph.com GPG key URL

- ceph-build-next/build/build_deb
- ceph-build-next/build/build_rpm
This was edited in-place for the Infernalis build and is now working. Before it would just error out regardless of the `|| true`
> prevent an early exit from a non-zero exit status

- ansible/master.yml
- jenkins-job-builder/config/definitions/jjb.yml
Clean up this file after each run, to make it less likely other jobs will have access to it.
> jenkins-job-builder: rm jenkins_jobs.ini after build

- ansible/slave.yml.j2
Jenkins authorizes this user account to add or remove slaves. In order to have permission to add or remove slaves, we have to give this account administrator rights to Jenkins.
Prior to this change, we had a system user "prado" in Jenkins with administrator rights.
Since we do not control this user account on GitHub.com, it is better to use a GitHub.com user account that we control.
> ansible: use "ceph-jenkins" as API user

- ansible/slave.yml
- ansible/slave.yml.j2
The jenkins-job-builder module on PyPI requires this package.
> ansible: install libyaml-dev on the slaves

- jenkins-job-builder/config/definitions/jjb.yml
Prior to this commit, the JJB YAML syntax was just broken, and
jenkins-job-builder would not parse this file.
Fix the YAML syntax, make the script run properly as a "shell" step,
make it execute regardless of the build status (with the
"script-only-if-*" settings).
> jenkins-job-builder: postbuildscript publisher fixes

- ceph-deploy-docs/build/build
- ceph-deploy-docs/config/definitions/ceph-deploy-docs.yml
- ceph-docs/build/build
- ceph-docs/config/definitions/ceph-docs.yml
- teuthology-docs/build/build
- teuthology-docs/config/definitions/teuthology-docs.yml
Now that we're running a dedicated Jenkins slave for the docs jobs, there are some cleanups we can do.
No need to rsync over SSH, or even use ssh-agent with the jenkins-publish credentials. We can just rsync the job's output directly into the proper location in /var.
Update the "node" setting to make the job run on the node labeled "docs".
> use docs.ceph.com slave for docs jobs

- ansible/slave.yml
- ansible/slave.yml.j2
The new docs VM is moving behind a firewall / reverse-proxy, so it will
not be directly accessible from the internet. We will to run the
documentation jobs directly on the docs VM as a Jenkins slave, and we
will stop using rsync over SSH for publishing the docs.
Since there's no direct SSH access to the docs VM any more, remove the
SSH host key from the slaves.
(My Ansible syntax in slave.yml.j2 was broken anyway.)
> ansible: do not pre-populate an SSH key for docs.ceph.com

- ceph-build-pull-requests/config/definitions/ceph-build-pull-requests.yml
- ceph-deploy-docs/config/definitions/ceph-deploy-docs.yml
- ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml
- ceph-deploy/config/definitions/ceph-deploy.yml
- ceph-qa-suite-pull-requests/config/definitions/ceph-qa-suite-pull-requests.yml
- ceph-tag/config/definitions/ceph-tag.yml
- jenkins-job-builder/config/definitions/jjb.yml
- mariner-installer-pull-requests/config/definitions/mariner-installer-pull-requests.yml
- merfi-pull-requests/config/definitions/merfi-pull-requests.yml
- radosgw-agent-pull-requests/config/definitions/radosgw-agent-pull-requests.yml
- radosgw-agent/config/definitions/radosgw-agent.yml
- takora-pull-requests/config/definitions/takora-pull-requests.yml
- teuthology-docs/config/definitions/teuthology-docs.yml
- teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
Many jobs specified the githubweb browser and defined a specific URL to find the commits.
Reduce the duplication and rely on the Jenkins Git plugin's ability to automatically construct the URLs to the SCM commits.
> use auto browser for Git SCMs

- calamari-clients-centos/config/definitions/calamari-clients-centos.yml
- calamari-clients-precise-vagrant/config/definitions/calamari-clients-precise-vagrant.yml
- calamari-clients-precise/config/definitions/calamari-clients-precise.yml
- calamari-clients-rhel/config/definitions/calamari-clients-rhel.yml
- calamari-clients-rhel7/config/definitions/calamari-clients-rhel7.yml
- calamari-clients-trusty/config/definitions/calamari-clients-trusty.yml
- calamari-clients-vagrant/config/definitions/calamari-clients-vagrant.yml
- calamari-clients-wheezy/config/definitions/calamari-clients-wheezy.yml
- calamari-clients/config/definitions/calamari-clients.yml
Use the publicly-accessible, non-SSH URLs for Git and GitHub.
> standardize calamari URLs

- ceph-build-next/build/build_deb
- ceph-build-next/build/build_rpm
- ceph-build-next/build/setup
So that we avoid these things:
$ rpm -qpR ceph-9.2.0-0.el7.x86_64.rpm
/bin/bash
/bin/sh
/bin/sh
/bin/sh
/bin/sh
/bin/sh
/home/jenkins-build/build/workspace/ceph-build-next/ARCH/x86_64/DIST/centos7/venv/bin/python
/usr/bin/env
...
> do not activate virtualenv when building

- ceph-deploy/build/build
- ceph-release-rpm/build/build
When we source the virtualenv the virtualenv path is linked within the
binaries.
> do not source the venv in ceph-deploy and ceph-release-rpm jobs

- ceph-build-next/build/setup
- ceph-deploy/build/setup
- ceph-release-rpm/build/build
This fixes a bug where we don't get newer versions of chacractl
installed when we want it because of the use of the pip cache.
> explicitly sepcify a chacractl version to install

- ceph-build-next/build/setup
- ceph-deploy/build/setup
- ceph-release-rpm/build/build
This will allow us to not have to change the CHACRACTL_VERSION variable
each time we release a new version of chacractl.
> use --upgrade when installing chacractl

- ceph-build-next/build/setup
- ceph-deploy/build/setup
- ceph-release-rpm/build/build
We do this to get around a bug in the previous code that would never go
out to look for new packages if something in the cache satisfied the
requirements. Specifically, we wanted chacractl==0.0.5 installed, but
because 0.0.4 exists in the cache and satisified the requirement of
>=0.0.4 the cache was never updated to include 0.0.5.
> always update the pip cache before installing packages

- ceph-next/config/definitions/ceph-next.yml
Update ceph-next's "TAG" parameter description to clarify what happens when the box is checked or unchecked.
> ceph-next: clarify "TAG" parameter description

- ceph-setup-next/build/build
$Branch is undefined. Use $BRANCH.
arior to this change, Jenkins would not print the branch name to the
console log during the "ceph-setup-next" job.
> ceph-setup-next: correct $BRANCH variable in output

- ceph-build/build/setup
- ceph-build/config/definitions/ceph-build.yml
- ceph-deploy/build/setup
- ceph-deploy/config/definitions/ceph-deploy.yml
- ceph-release-rpm/build/build
- ceph-release-rpm/config/definitions/ceph-release-rpm.yml
- scripts/build_utils.sh
This way we can have a single bit of code that installs python packages and configures chacractl as these are very common steps in our build jobs.
This also ports ceph-build, ceph-deploy and ceph-release-rpm to use these utils.
> creates a utility to install python packages and configure chacractl

- ceph-build-pull-requests/build/build
With this change, the ceph-build-pull-requests job will run `ansible-playbook` with the `--syntax-check` flag on every playbook in the top-level of `./ansible/`. This will help us avoid simple Ansible syntax errors.
> ceph-build-pull-requests: check ansible syntax

- ansible/slave.yml
- ansible/slave.yml.j2
- radosgw-agent/build/build
- radosgw-agent/config/definitions/radosgw-agent.yml
- scripts/build_utils.sh
This also moves a few more things into build_utils.sh. I'll make another PR to use those methods in the other jobs that need them.
This branch was tested here: https://jenkins.ceph.com/job/radosgw-agent/8/
> Make the radosgw-agent job push to chacra.ceph.com

- jenkins-job-builder/build/build
- jenkins-job-builder/config/definitions/jjb.yml
This will wipe out JJB's cache if set. It is useful for wiping out changes that may have occurred outside of GitHub's master branch.
For example, if I make a change to a job on a local branch, and I apply my JJB changes locally, I want to force this jenkins-job-builder job to wipe out my changes later.
> jenkins-job-builder: add FORCE parameter

- ceph-build/config/definitions/ceph-build.yml
We need these specific scripts grouped into their own shell directives
so that if setup_deb exits on a centos node then setup_rpm will still be
ran against that same node.
> ceph-build: separate deb build scripts from rpm build scripts

- ceph-deploy/build/build
- ceph-deploy/config/definitions/ceph-deploy.yml
This branch tested out fine here: https://jenkins.ceph.com/job/ceph-deploy/22/
> ceph-deploy: use methods from build_utils.sh

- ansible/master.yml
https://wiki.jenkins-ci.org/display/JENKINS/JobConfigHistory+Plugin
This plugin tracks changes in each job. Among other features, the Build History widget will show an icon of a wrench with the tooltip "Config changed since last build", indicating that the config has changed from one build to the next.
> ansible: add jobConfigHistory plugin

- ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml
Because the GitHub Pull Request Builder plugin handles updating the status
See https://github.com/jenkinsci/ghprb-plugin/issues/104
> remove github notifier

- ceph-deploy-pull-requests/build/setup
- ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml
It fixes the issues we've had when the "jenkins" script was not found in ceph-deploy.
> port ceph-deploy-pull-requests to use new utitlies

- ceph-build/build/setup_pbuilder
The pbuilder steps in the ceph-build job relied on apt-mirror.sepia.ceph.com. Remove this dependency, and point at the main alias for the US-based Ubuntu mirrors instead.
> ceph-build: do not rely on apt-mirror.sepia.ceph.com

- ceph-build/build/build_deb
- ceph-build/build/build_rpm
- ceph-build/build/setup
- ceph-release-rpm/build/build
Prior to this commit, some of the build scripts would print the time and date to the console log.
As far as I can tell this is a hold-over from the original Gitbuilder scripts. Jenkins already logs the start and end times for us so there's no need to clutter the build scripts with this.
Remove the code that prints `date`.
> rm date/time tracking

- jenkins-job-builder/config/definitions/jjb.yml
It's not totally clear from the JJB documentation whether we need this or not, but I'm seeing an issue with our helga-jenkins plugin when we leave this parameter out of the "!ci build jenkins-job-builder" invocation.  Explicitly set a default, just to see if this makes a difference.
> jenkins-job-builder: set default value for FORCE param

- jenkins-job-builder/config/definitions/jjb.yml
To avoid running on huge / arm nodes.
> jenkins-job-builder: run on "small" nodes

- jenkins-job-builder/build/build
Default to the encrypted HTTPS url (not HTTP)
> jenkins-job-builder: use HTTPS url for jenkins.ceph.com

- ansible/slave.yml.j2
Fixes the path to the github.com.pub file and makes a fix for ansible-playbook==1.9.1 version compatibility.
> prado playbook updates

- teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
This fixes a bug where the job incorrectly picks an arm64 node, which
does not compile gevent correctly causing the job to fail.
> teuthology-pull-requests: change node to trusty&&amd64&&small

- ceph-deploy-tag/build/build
- ceph-deploy-tag/config/definitions/ceph-tag.yml
- ceph-deploy/config/definitions/ceph-deploy.yml
So that it runs before the actual ceph-deploy release job, using the new ansible playbooks and allowing us to basically release with a single, push-button action.
> implement a ceph-deploy-tag job

- ceph-deploy/config/definitions/ceph-deploy.yml
because ceph-deploy is no longer a matrix job, but rather, a multijob. This should now really fix how ceph-deploy looks in jenkins
> fix project type to multijob

- ceph-deploy-build/config/definitions/ceph-deploy-build.yml
since we are building 'generic' ceph-deploy, we really need 1 for ubuntu and 1 for debian. We could do 1 for both but it might be odd to push them just for debian and not ubuntu and vice versa 
For now we push to both. This doesn't affect the repo building because it will just skip it if it already exists
> remove redundant slaves from matrix

- ceph-deploy-tag/config/definitions/ceph-tag.yml
- ceph-tag/config/definitions/ceph-tag.yml
According to docs we were using an old style of configuring the ssh-credentials plugin:
The users with one value in list equals to the user. In this case old style XML will be generated. Use this format if you use SSH-Agent plugin < 1.5.
https://jenkins-job-builder.readthedocs.org/en/latest/wrappers.html#wrappers.ssh-agent-credentials
For some reason this meant that the credentials was not being used making tagging/cloning fail
> Ssh user fix

- scripts/build_utils.sh
Hopefully getting rid of:
ImportError: No module named setuptools
According to: https://pip-cn.readthedocs.org/en/latest/distribute_setuptools.html#solution
> ensure latest pip is installed, preventing odl, distro-based pip being used

- ansible/release.yml
- ansible/roles/ceph-deploy-release/tasks/clear_version.yml
- ansible/roles/ceph-deploy-release/tasks/main.yml
otherwise we are going to be doing a reset to revert back to the previous commit for no reason if the version appears in the commit message (the case before this PR)
> safer check for previously tagged 

- scripts/build_utils.sh
Because otherwise it causes issues when re-using it (jenkins doesn't wipe this out).
There is a plugin that wipes out top-level $WORKSPACE but that would also mean going through each project that uses the build script (vs. just fixing it there)
> make sure that venv is always removed prior to creating it

- ceph-pr-commits/build/build
- ceph-pr-commits/build/test_commits.py
- ceph-pr-commits/config/definitions/ceph-pr-commits.yml
So that they can just use py.test and spit out the report.xml file
> reconfigure ceph-pr-commits 

- ceph-pr-commits/build/build
- ceph-pr-commits/build/test_commits.py
- ceph-pr-commits/config/definitions/ceph-pr-commits.yml
So that we use the master branch in ceph-build (it was defaulting to something else, because it was not specified).
It fixes the junit flag used in py.test and fixes the correct parametrize invocation.
> ceph pr fixes

- ceph-pr-commits/build/build
- ceph-pr-commits/build/test_commits.py
For ceph-pr-commits. We were getting a bunch of "skipped" tests because we were looking in the wrong path for commits
> Path fixes

- ceph-pull-requests/config/definitions/ceph-pull-requests.yml
This way we can report the correct status to github and still reboot the node on failure.  Before this change the node would never reboot if the make check failed.
> ceph-pull-requests: use a postbuildscript to only reboot on failure

- ansible/slave.yml
- ansible/slave.yml.j2
So that mita can find these nodes because it depends on the naming.
> Fix node naming

- ceph-pr-commits/build/build
- ceph-pr-commits/build/test_commits.py
So that we can also track when something goes wrong. Right now it is very difficult to tell what commands are being run so that we can debug this.
> Verbose commit check

- ansible/slave.yml
- ansible/slave.yml.j2
So that we don't get nodes rebooted by script like make-check.sh while we are doing a release.
This is why rebooting a node because a test requires it is not just a matter of slapping "sudo reboot" on a script.
This option should at some point be made optional so that mita can toggle it with `huge` nodes only.
> default to number of executors to just 1

- ansible/slave.yml.j2
Otherwise the playbook will fail since lsb_release might not be there and ansible needs it to write the rpmmacros file.
> set the macros after installing dependencies

- ceph-build-pull-requests/config/definitions/ceph-build-pull-requests.yml
- ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml
- ceph-qa-suite-pull-requests/config/definitions/ceph-qa-suite-pull-requests.yml
- teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
Most pull request jobs need to be concurrent. This is because projects that have lots of pull requests will otherwise pile up waiting for the previous check to be finished.
The low-traffic PR jobs like the radosgw-agent have not been updated.
> pull requests that need to be concurrent

- ceph-ansible-pull-requests/build/build
If we don't activate our virtualenv ceph-ansible can not find ansible to
perform its version check and fails.
> ceph-ansible-pull-requests: activate the venv for the version check

- ceph-ansible-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
Setting both script-only-if-succeeded and script-only-if-failed to True
makes is so that this postbuildscript is never ran.
> always destroy the slave after a ceph-ansible-pull-requests job

- ceph-ansible-pull-requests/build/build
This allows us to pass a list of devices to --extra-vars. The key=value
method of using --extra-vars doesn't allow for complex data types like a
list or a hash.
This also sets monitor_interface to eth1
> ceph-ansible-pull-requests: use json for --extra-vars

- ceph-ansible-pull-requests/build/build
Set these to the same values used for vagrant testing
> ceph-ansible-pull-requests: add os_tuning_params to --extra-vars

- ceph-ansible-pull-requests/build/build
The trusty and centos nodes we're using in OVH both use eth0. This also
fixes a typo when setting monitor_interface in the json file used by
extra-vars.
> ceph-ansible-pull-requests: set monitor_interface correctly

- ceph-ansible-galaxy/build/build
- ceph-ansible-galaxy/config/definitions/ceph-ansible-galaxy.yml
When new code is merged to master of ceph-ansible a command is run to
update the individual role repos with the changes for Ansible Galaxy.
See the first request of https://github.com/ceph/ceph-ansible/issues/507
> Adds a new job to update the ceph-ansible galaxy repos on merge

- ceph-ansible-pull-requests/build/build
The value in os_tuning_params that set vm.min_free_kybtes used to lock
up our testing slaves so we removed it from this job. However,
ceph-ansible is now attempting to auto calculate this.
> ceph-ansible-pull-requests: remove os_tuning_params from extra-vars

- ceph-installer-pull-requests/config/definitions/ceph-installer-pull-requests.yml
So that it doesn't break like:
[ceph-installer-pull-requests] $ /bin/bash /tmp/hudson6743631504151945894.sh
/tmp/hudson6743631504151945894.sh: line 5: install_python_packages: command not found
/tmp/hudson6743631504151945894.sh: line 7: /tox: No such file or directory
> include the build utils for ceph-installer prs

- ceph-installer-coverage/build/build
- ceph-installer-coverage/config/definitions/ceph-installer-coverage.yml
- ceph-installer-coverage/config/definitions/ceph-installer-merged.yml
It will create two reports: junit report from py.test and coverage report from pytest-coverage
Should run only on merges to master (similar to when we build docs)
> ceph-installer coverage

- ceph/config/definitions/ceph.yml
Will be consumed by this change: https://github.com/ceph/ceph/pull/8250
For older builds it doesn't cause issues, it is just an environment variable
> set the CEPH_BUILD_VIRTUALENV environment variable for ceph jobs

- ceph-build-arm64/config/definitions/ceph-build-arm64.yml
- ceph-setup-arm64/build/build
- ceph-setup-arm64/config/definitions/ceph-setup.yml
Make ceph-build-arm64 take from its own private setup build phase,
and add a BRANCH parameter to try to make it grab the requested
branch rather than 'latest'
> Test: add ceph-setup-arm64; use it from ceph-build-arm64

- ceph-setup-arm64/build/build
- ceph-setup-arm64/config/definitions/ceph-setup.yml
- pull from ceph.git, not ceph-releases
- always rebuild tarball
- name all source tars by $vers (x.y.z), not $cephvers (x.y.z-N-gSHA1)
> ceph-setup-arm64: tweaks for building unreleased branches

- ceph-ansible-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
These tests will now run against both trusty and centos7 nodes.
> ceph-ansible-pull-requests: support for trusty and centos7

- jenkins-job-builder/build/build
- jenkins-job-builder/config/definitions/jjb.yml
Adding --log-level DEBUG to hope to point out problems, and allow
job to run on master so it runs without mita provisioning (it's small
and should be fast)
> jenkins-job-builder: diagnostics and allow to run on master

- ceph-build/build/build_deb
> ceph-build/build/build_deb: restore mistakenly dropped changes for arm64

- ceph-build/build/build_deb
- ceph-build/build/build_rpm
define a `check_url` and an `endpoint` one for chacra interactions
This fixes the issue where the same url would be used to check DEB (or RPM) binary existence
and to POST new binaries causing this:
POST /binaries/ceph/jewel/ubuntu/trusty/x86_64/librados2_10.2.0-10.2.0-1trusty_x86_64.deb/ HTTP/1.1" 400
Which is the wrong URL for DEB binaries. Similar problem was for RPMs
> Base url fix

- ceph-build/config/definitions/ceph-build.yml
- ceph/config/definitions/ceph.yml
It messed up the builds picking Centos7 instead of say, Jessie.
See: https://jenkins.ceph.com/job/ceph-build/90/ARCH=x86_64,DIST=jessie,MACHINE_SIZE=huge/console
> Revert dynamic axis

- ceph-build/build/build_deb
This corrects the name of librados2 so that we can do a proper check
against chacra before reuploading a binary.
> ceph-build: fix the chacra_check_url for debian builds

- ceph-build/build/setup_pbuilder
Without this change xenial builds were using the debian mirror.
> ceph-build: fix mirror url for xenial

- ansible/slave.yml
- ansible/slave.yml.j2
In Jenkins lingo: "exclusive" means that it will only be used on jobs with
label restrictions matching the node (vs. the normal which is 'use this node as
much as possible')
> allow nodes to be configured as 'exclusive'

- ansible/slave.yml
- ansible/slave.yml.j2
This is the behavior we want by default always. We don't want jobs to just use whatever machine.
> default to being exclusive, always

- ceph-ansible-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
When the labels were more generic other jobs would pick them up and run
the risk of being destroyed by the ceph-ansible-pull-requests job after
a run. There was also an issue were jobs that didn't need a node with an
extra device would provision one of the 'unique' nodes because the
labels also included 'small' and 'trusty'. Making the labels this
specific ensures that only this job will use those node types.
> make ceph-ansible-pull-requests request nodes specific to the job

- ceph-pull-requests/config/definitions/ceph-pull-requests.yml
This is to signal node selection that the job will reboot the node
after it finishes.  Without an explicit label on the node and a request
for it, any 'trusty' node would satisfy, and be rebooted; this is
a problem for nodes that 'dial in' to the Jenkins master (such as
physical slaves on the sepia network).
This corresponds with the addition of 'rebootable' tags to mita's
configuration, so that mita nodes continue to suffice for this job.
> Add 'rebootable' label to ceph-pull-requests

- ceph-build/config/definitions/ceph-build.yml
Creates an axis for pbuilder so that all DEB distros will have it.
Updates the combination filter to exclude CentOS.
> Pbuilder support

- ansible/slave.yml
To avoid the error: 
E: Release signed by unknown key (key id 8B48AD6246925553)
> install the debian keys so pbuilder will work with newer distros

- ansible/slave.yml
Regardless of the machine, since we are usually building on Trusty, this will
allow that type of server to build and avoid the "Release signed by unknown
key" issue.
> Add Debian Jessie GPG Key

- ansible/slave.yml
This will prevent errors from builders with improper hostnames:
sudo: unable to resolve host vm
> ensure the current hostname is defined in /etc/hosts

- ansible/slave.yml
It was getting a 404 before this :(
> typo fix on debian gpg key for jessie

- ansible/slave.yml
These are needed to pip install ansible.
> install dev packges for libssl and libffi on rpm and deb sytems

- ceph-build-pull-requests/build/build
- ceph-build-pull-requests/config/definitions/ceph-build-pull-requests.yml
- ceph-deploy-docs/build/build
- ceph-deploy-docs/config/definitions/ceph-deploy-docs.yml
- ceph-qa-suite-pull-requests/build/build
- ceph-qa-suite-pull-requests/config/definitions/ceph-qa-suite-pull-requests.yml
- ceph-tag/build/build
- ceph-tag/config/definitions/ceph-tag.yml
- jenkins-job-builder/build/build
- jenkins-job-builder/config/definitions/jjb.yml
- merfi-pull-requests/build/build
- merfi-pull-requests/config/definitions/merfi-pull-requests.yml
- scripts/build_utils.sh
- teuthology-docs/build/build
- teuthology-docs/config/definitions/teuthology-docs.yml
- teuthology-pull-requests/build/build
- teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
This sets the upgrade to setuptools in just one place: `build_utils.sh` and makes all jobs use that utility (before this only a few used the util).
It drastically reduces the code copy/pasta by reusing the utility script.
> Newer setuptools across all python-using jobs

- ceph-ansible-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
Requires https://github.com/ceph/mita/pull/62 to be merged+deployed before this.
This would take care of https://github.com/ceph/ceph-ansible/issues/507
> ceph-ansible-pull-requests: add a xenial instance when testing

- ansible/slave.yml
Because this thing is no longer the same name in Xenial
> slave.yml: condition opnjdk installs for xenial

- ceph-ansible-pull-requests/build/build
> ceph-ansible-pull-requests: use the ens3 monitor interface with xenial

- ceph-pull-requests/config/definitions/ceph-pull-requests.yml
By default, run-make-check divide by 2 the number of processors to be used
during the make process.
When building a PR on our build farm, we need to use the full potential of the
build hosts.
By overriding NPROC with the actual number of processors, we speedup the build
process and use in a more efficient way the build hosts.
> ceph-pull-requests: Override processor numbers

- ceph-build/build/build_deb
> ceph-build: map the DIST to distro to properly detect ubuntu vs debian

- ceph-setup/config/definitions/ceph-setup.yml
- ceph-tag/config/definitions/ceph-tag.yml
To avoid conflicts in Jenkins for these jobs. After removing them manually both ceph-tag and ceph-setup were able to complete.
java.lang.ClassCastException: org.acegisecurity.providers.UsernamePasswordAuthenticationToken cannot be cast to org.jenkinsci.plugins.GithubAuthenticationToken
> Remove ssh-agent credentials

- ansible/slave.yml
On a fresh new image, the /home/jenkins-build relies to root.root making ccache
failing at creating a file here.
That means that anything trying to write a file in the home dir will fail.
This patch simply enfore the user/group of the home dir
> ansible: Enforce rights on /home/jenkins-build

- ceph-pull-requests/config/definitions/ceph-pull-requests.yml
By default, ccache is now configured and uses only 1G of space.
While monitoring the build it appears that if we would have a larger cache, more
hits could be done making a faster build process.
This patch simply makes the ccache bigger up to 5G which is fine regarding the
openstack flavor we have.
> ceph-pull-request: Increasing ccache size

- radosgw-agent-pull-requests/config/definitions/radosgw-agent-pull-requests.yml
Because it causes issues when notifying github when more than one SCM is used:
Setting commit status on GitHub for https://github.com/ceph/radosgw-agent/commit/70c05dab3a2087580dcbec5e50541a0df1a51587
ERROR: Build step failed with exception
org.jenkinsci.plugins.github.common.CombineErrorHandler$ErrorHandlingException: java.io.FileNotFoundException: {"message":"No commit found for SHA: 70c05dab3a2087580dcbec5e50541a0df1a51587"
> radosgw-agent-pull-requests: remove github-notifier

- ceph-ansible-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
- ceph-build-pull-requests/config/definitions/ceph-build-pull-requests.yml
- ceph-installer-pull-requests/config/definitions/ceph-installer-pull-requests.yml
- ceph-pull-requests/config/definitions/ceph-pull-requests.yml
- ceph-qa-suite-pull-requests/config/definitions/ceph-qa-suite-pull-requests.yml
- merfi-pull-requests/config/definitions/merfi-pull-requests.yml
- takora-pull-requests/config/definitions/takora-pull-requests.yml
- teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
This publisher is not needed as the github-pull-requests trigger takes care of
updating the status on the pull request.
> removes the deprecated github-notifier publisher from all jobs

- ceph-tag/config/definitions/ceph-tag.yml
This reverts commit f4398ab8df10e6fef419e742afc9547634c1c214.
Currently failing with:
"stderr": "Warning: Permanently added the RSA host key for IP address '192.30.252.123' to the list of known hosts.\r\nPermission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists."
> add ssh creds back to be able to push tags 

- ansible/slave.yml
- teuthology-docs/config/definitions/teuthology-docs.yml
- teuthology-docs/setup/setup
Even though we can't actually *install* them, since we don't have tty-less sudo on ``docs.dhc``, it's useful to put jobs' dependencies in the job definition.
> teuthology-docs: Move package dependencies into the job definition

- deb_dists
- gen_debian_version.sh
- update_pbuilder.sh
Gitbuilder builds on Xenial are failing due to
+ GNUPGHOME=/srv/gnupg reprepro --ask-passphrase -b ../out/output/sha1/35ecf84c44dc9cd23331d8244927923034d661e2.tmp -C main --ignore=undefinedtarget --ignore=wrongdistribution include xenial out~/ceph_10.2.0-2147-g35ecf84-1xenial_amd64.changes
Cannot find definition of distribution 'xenial'!
There have been errors!
Adding 'xenial' in the proper places using https://github.com/ceph/ceph-build/pull/102 as reference.
> Add xenial

- radosgw-agent/config/definitions/radosgw-agent.yml
> radosgw-agent: have some defaults to prevent null var references

- ceph-tag/config/definitions/ceph-tag.yml
> ceph-tag: always use the master branch of ceph-build

- ceph-build/config/definitions/ceph-build.yml
- ceph-setup/build/build
The ceph-setup job is the only one with the access to the current sha1 being built because it performs the clone of ceph. We need to write that value to a properties file that is archived and then injected into the ceph-build job.
> Make the sha1 from the current build available in the build scripts

- ceph-build/build/build_deb
- ceph-build/build/build_rpm
- ceph-deploy-build/build/build
- ceph-release-rpm/build/build
- radosgw-agent/build/build
This can't be merged until https://github.com/ceph/chacra/pull/129 is merged and deployed.
The SHA1 variable comes from the ceph-setup job. See: https://github.com/ceph/ceph-build/pull/409
> include the sha1 when uploading binaries to chacra

- ceph-dev-build/build/build_deb
- ceph-dev-build/build/build_rpm
- ceph-dev-build/build/setup
- ceph-dev-build/build/setup_pbuilder
- ceph-dev-build/config/definitions/ceph-dev-build.yml
- ceph-dev-setup/build/build
- ceph-dev-setup/config/definitions/ceph-dev-setup.yml
- ceph-dev/config/definitions/ceph-dev.yml
- scripts/build_utils.sh
A first pass as creating the job that will build ceph for testing purposes. This most likely will need polishing before it works correctly.
A few things:
1) SHAMAN_API_KEY and SHAMAN_API_USER need created in the Jenkins UI
2) shaman.ceph.com will need chacra nodes registered with it before it can give out chacra nodes at /api/nodes/next/
3) currently builds on a static list of distros, eventually we'll want that to dynamic and user driven
4) This currently only builds a branch, I'm unsure if passing a sha1 for that config option will work. I know a tag will.
> creates a ceph-dev job for testing builds

- ceph-dev-build/build/setup
- ceph-dev-build/config/definitions/ceph-dev-build.yml
- ceph-dev-setup/build/build
- ceph-dev/config/definitions/ceph-dev.yml
- scripts/build_utils.sh
This PR allows for the user to select which distros ceph will be built for. It also fixes a few things that were found while testing.
> ceph-dev: provide the ability to choose which distros are used

- ceph-build/build/build_deb
- ceph-build/build/build_rpm
- ceph-deploy-build/build/build
- ceph-deploy-pull-requests/build/build
- ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml
- ceph-dev-build/build/build_deb
- ceph-dev-build/build/build_rpm
We need to do this now as the virtualenv is being created in a temp directory and not a standard path.
> use the value of VENV from build_utils.sh everywhere

- ansible/roles/nginx/tasks/letsencrypt.yml
> ansible: use letsencrypt renew vs. asking for a new cert every 12 hours

- ceph-dev-build/build/build_deb
- ceph-dev-build/build/validate_deb
- ceph-dev-build/build/validate_rpm
- ceph-dev-build/config/definitions/ceph-dev-build.yml
This will make sure a build script fails early if it will not work on
the distro being built for. Doing this early avoids duplicate calls to
the build_utils and setup scripts.
> ceph-dev-build: add scripts to validate distro type

- ceph-dev-build/build/build_rpm
- ceph-dev/config/definitions/ceph-dev.yml
Adds support for defining `$FLAVOR`, although just being used for ceph-release for now.
> ceph-release url fixes (for ceph-dev)

- calamari-server-trusty/build/build
The calamari-server-trusty build fails because there is no multitee available. Fix this by installing it before running the multitee'd salt command.
> calamari-server-trusty: Install multitee before we use it

- calamari-server-trusty/build/build
The sudo command resets the enviroment by default so we never passed the
WORKSPACE variable to salt. This made salt default to HOME instead.
Also, we store the packages in pkgs/ subdir of WORKSPACE dir, fixing
that as well.
> calamari-server-trusty: fix environmental issues

- ceph-dev-setup/build/build
Just working for the tarball (ceph-dev-setup) process. The actual binary builds still need work.
> ceph-dev-setup: produce the tarball with cmake if make-dist exists

- ceph-dev-setup/build/build
Prevents this from failing:
cp: target ‘ceph-10.2.2-427-g089bb43/debian/’ is not a directory
> ceph-dev-setup: ensure that the debian dir exists before copying

- ceph-build/config/definitions/ceph-build.yml
If we do setup in it's own -shell then the virtualenv created there will
not be used in the other two -shell sections. This is because we
switched from using a standard venv to using one created in a temp
directory.
> ceph-build: setup must be performed for both deb and rpm

- ceph-build/build/build_deb
- ceph-build/build/build_rpm
To avoid:
++ cat ./dist/version
cat: ./dist/version: No such file or directory
> cd to $WORKSPACE before building

- ceph-build/build/validate_deb
- ceph-build/build/validate_rpm
- ceph-build/config/definitions/ceph-build.yml
- ceph/config/definitions/ceph.yml
This gets ceph-build caught up with the features we added to ceph-dev-build.
You can now pick with distros and archs you wish to build for. This also adds validation scripts that will very early avoid build scripts that do not pertain to the distro being built for by the current job.
> Ceph build updates

- ceph-dev-build/config/definitions/ceph-dev-build.yml
- ceph-dev/config/definitions/ceph-dev.yml
> ceph-dev-build: add centos6, precise, and wheezy to available distros

- ceph-dev-build/config/definitions/ceph-dev-build.yml
- ceph-dev/config/definitions/ceph-dev.yml
> ceph-dev: specify a laxed pinning for nodes

- ceph-dev-build/build/build_deb
- ceph-dev-build/build/build_rpm
For DEB repos there is a different version that apt uses, this
allows the API to provide that information as well as the project
version.
> ceph-dev-build: adds a new package_manager_version field to repo extra

- ceph-dev-setup/build/build
And prevent them from building if the actual branch name contains a slash.
E.g. This would not build:
origin/historic/async_mds
> further fixing for spliting branches on forward slashes

- ceph-dev-build/build/build_rpm
Should fix https://github.com/ceph/shaman/issues/57
> parse and set a correct representation of 'version' for RPMs using the spec file

- ansible/examples/slave.yml
This will create a global .gitconfig (we relied on horrible hostnames before) so that we can get nice commits whenever the CI system is pushing changes
> define a .gitconfig for slaves

- ceph-dev-build/build/build_rpm
Newer Ceph uses autosetup, not setup.
> ceph-dev-build: modify autosetup when setup is not defined in spec file

- ansible/examples/slave.yml
> ansible: allow for setting the number of executors on a slave

- ceph-dev-build/config/definitions/ceph-dev-build.yml
- ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
- ceph-dev/config/definitions/ceph-dev.yml
We want these jobs to use master until we can enable mita to spin up nodes with many executors for these types of "coordinating" jobs.
> pin jobs to master that used to use huge_xenial_builder`

- ansible/examples/slave.yml
This adds a use_jnlp flag to slave.yml which provides support to
register the slave with jnlp instead of ssh if use_jnlp: true
> ansible: support registering slaves with jnlp

- jenkins-job-builder/config/definitions/jjb.yml
master is not setup for building anything and does not have virtualenv
installed which this job needs. In general, we don't want jobs that do
any "building' to use master.
> jenkins-job-builder: should not use the master node

- ceph-dev-build/build/build_deb
- ceph-dev-setup/build/build
Before this the binaries produced did not include the distro codename in the filename.
This fixes the issues described here: https://github.com/ceph/shaman/issues/57#issuecomment-246037415
> ceph-dev: fix debian binary names

- ceph-dev-setup/build/build
Without this command the dsc artifacts are not created correctly and
ceph-dev-build fails to find them, resulting in errors like:
"dpkg-source: error: cannot read ceph_10.2.2-508-g9bfc0cf-1.dsc: No such
file or directory"
From:
https://jenkins.ceph.com/job/ceph-dev-build/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=xenial,DIST=xenial,MACHINE_SIZE=huge/492/console
> ceph-dev-setup: add back the dch -v command

- ceph-build/build/setup_pbuilder
- ceph-dev-build/build/setup_pbuilder
Newer versions of pbuilder maps `$HOME` to `/nonexistent`. This breaks everything that relies on writing files to `$HOME`. This PR reverts this back to what it was before `0.220`
From the changelog entry:
* configuration:
+ new config: BUILD_HOME: set the value of HOME while building.
Default it to /nonexistent to prevent builds from writing to /home.
This reverts what was done for #170762.  Closes: #441052
The actual failure in a Jenkins node (xenial) failed like:
Complete output from command /tmp/ceph-disk-virtualenv/bin/python2.7 - setuptools pkg_resources pip wheel:
The directory '/nonexistent/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, …
> set BUILD_HOME in pbuilderrc

- ansible/examples/hosts-static
- ansible/examples/slave_static.yml
- ansible/templates/systemd/jenkins.service.j2
- ansible/templates/yum-repos/epel.repo
- ceph-build-pull-requests/build/build
I used this playbook to add smithi118 - smith128 (except smithi126) to jenkins. 
I decided to go with a different playbook than slave.yml because I wasn't going to use this with prado and some of the paths to templates and files were different when running this outside of prado.
> A playbook to configure static jenkins slaves

- ansible/examples/init.yml
We use this playbook on new chacra nodes to set the SSH port to 2222. All new chacra nodes are xenial, so we'll also need to install python2.7 on these nodes before ansible modules will work.
> ansible: install python2.7 on xenial nodes

- ceph-dev/config/definitions/ceph-dev.yml
The sepia lab is mostly testing on trusty, so we want to build trusty by
default as well.
> ceph-dev: also build trusty by default

- ceph-build/build/setup_pbuilder
- ceph-dev-build/build/setup_pbuilder
It was making `.pbuilderrc` (the configuration **file**) a directory. This makes it right
> set BUILD_HOME to the right path

- ceph-build/build/setup_pbuilder
- ceph-dev-build/build/setup_pbuilder
Because ceph components may want to install things that are cached and buggy in certain environments. Hi Xenial. Hello there pip 8.1.1. How are you urllib3
> allow network access in pbuilder builds

- ansible/examples/slave.yml
- ansible/examples/slave_static.yml
We are seeing OVH slaves fail builds because they can not use sudo. When inspecting the nodes we see the hostname is set to ``(none)``. This should fix that.
> ansible: set hostname on slaves

- ansible/examples/slave.yml
- ansible/examples/slave_static.yml
- ceph-dev-setup/build/build
- ceph-dev/config/definitions/ceph-dev.yml
- ceph-setup/build/build
This is a first crack at release builds supporting cmake and autotools.
To Do: modify ceph/ceph.spec.in to support CEPH_EXTRA_CMAKE_ARGS
> cmake: modified several scripts for cmake support

- ceph-dev-setup/build/build
- ceph-setup/build/build
Because it looks like it was missing a `; then`
> Unexpected fi token

- ansible/examples/slave.yml
The nodes we spin up in OVH are using an image that sets the hostname
to 'ceph-builders'. Also, the hostname we give it is too long to use and
ansible silenty fails to set it.
This change ensures that nodes can use sudo correctly and avoids errors
like: 'sudo: unable to resolve host ceph-builders'.
> ansible: always add 'ceph-builders' to /etc/hosts

- diamond-build/build/build_deb
- diamond-build/build/build_rpm
- diamond-build/build/setup_pbuilder
- diamond-build/build/validate_deb
- diamond-build/config/definitions/diamond-build.yml
- diamond-setup/build/build
- diamond/config/definitions/diamond.yml
The patch adds debian support for diamond jobs and also adds few minor updates/sync-ups for rpm part of the build.
> diamond: Add debian support

- ansible/examples/slave.yml
We will never use prado to setup slaves using jnlp and
the way this was before was causing a recursion error when
ansible was trying to render the playbook.
> ansible: set use_jnlp: false in slave.yml

- diamond-setup/build/build
There is one more fix that needs to be applied, the old path was an artefact from one of my online jenkins attempts.
> diamand: Fix dir name mismatch

- ceph-dev-build/config/definitions/ceph-dev-build.yml
- ceph-dev-setup/config/definitions/ceph-dev-setup.yml
You have to explicitly set ``script-only-if-succeeded`` to ``False`` because the default is ``True`` and even if you set ``script-only-if-failed`` to ``True`` jenkins checks the other value first and fails the build without running the postbuildscript.
> post build info status to shaman on failure

- ceph-dev-build/build/failure
- ceph-dev-setup/build/failure
The failure scripts are not run in the same context as the build scripts, so they do not get the modified versions for ``BRANCH`` or ``SHA1``. They will get the fresh versions from ``ceph-ev``  which causes trouble in shaman when a branch looks like ``origin/*``.
> we need to set variables when reporting build failures

- ceph-dev-build/build/setup_rpm
I was using the incorrect values for the NORMAL_* values in setup_rpm
which was posting incorrect information to shaman.
> ceph-dev-build: write the correct vars to build_info in setup_rpm

- ceph-dev-build/build/setup_deb
- ceph-dev-build/build/setup_rpm
- scripts/build_utils.sh
Centralizes the creation of the build_info properties file in build_utils.sh so that other jobs don't need to create it.
> scripts: create the build_info properties file when updating shaman

- ceph-docker-pull-requests/build/build
- ceph-docker-pull-requests/build/failure
Remove the ceph-mon call since it isn't really available and add a header before `on failure` scripts are called because they tend to be super verbose, making it hard to tell where the actual failure ocurred
> Docker fixes

- ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
dev builds should not really hit this, but as we start getting into dev workflow we see that it is entirely possible to get in a situation where the binary existed, and the whole build will fail because the binary was there.
This check was useful mostly for releases, for dev workflows it should just accept a forceful update
> ceph-dev-trigger: force push even when remote package exists

- ansible/examples/slave.yml
If a node is rebooted the /etc/hosts file is rewritten with these
template files because ``manage_etc_hosts`` is set to ``true``. This
causes jobs to fail because the hostname is no longer resolveable after
reboot.
> ansible: update the cloud-init templates for /etc/hosts

- ansible/examples/slave.yml
This would fix having to host this key in download.ceph.com
> ansible: use pgp.mit.edu to fetch the jessie release key

- release_tarball.sh
this enables us to prepare release tarball for versions without
autotools support, where we use make-dist to create the release tarball
instead.
> release_tarball: use make-dist if available

- scripts/build_utils.sh
The first commit adds a simple function that transforms DIST variable into DISTRO variable while setting MOCK_TARGET on rpm systems.
The second commits adds the setup_pbuilder file as a function so that it could be shared amongst the build jobs.
> Add 2 new helper functions

- ceph-ansible-pull-requests/build/build
Ansible 2.2 seems to be breaking things, let's stick with 2.1 for now.
> ceph-ansible-pull-requests: force ansible version

- ceph-docker-pull-requests/build/build
The docker ps command was returning no containers that caused the docker
rm command to fail. That, combined with the set -e flag was causing the
build script to exit prematurely.
Signed-off-by: Ivan Font <ifont@redhat.com>
> Fix CI errors caused by container status commands

- samba/build/build_rpm
fixes failure https://jenkins.ceph.com/job/samba/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos7,DIST=centos7,MACHINE_SIZE=huge/2/console
> needs sudo to install deps

- ansible/examples/slave.yml
- ceph-pull-requests/config/definitions/ceph-pull-requests.yml
We aren't installing the dependency in the new tenant and these machines are
short lived anyway.
> ceph-pull-requests: remove ccache

- kernel/build/build_deb
- kernel/build/setup
- kernel/config/definitions/kernel.yml
Includes:
- posting deb binaries to chacra as x86_64 instead of amd64
- building for trusty instead of precise by default
- uploading to chacra.ceph.com instead of a test chacra instance so binaries persist past 2 weeks
> updates to the kernel build job

- ceph-build/config/definitions/ceph-build.yml
- ceph-dev-build/config/definitions/ceph-dev-build.yml
- ceph-dev-setup/build/build
- ceph-setup/build/build
Inject another file, this one a 'catchall' of other environment variables
that -setup may need to pass to -build.  At the moment, that contains
CEPH_EXTRA_CMAKE_ARGS, but there doesn't seem to be much point in creating
one file per variable.
> ceph{-dev}-{setup,build}: pass CMAKE_EXTRA_CONFIG_ARGS

- ansible/examples/slave.yml
- ansible/examples/slave_static.yml
Also, install curl on all slaves
> ansible: add missing ssl deps to static deb builders

- ceph-ansible-pull-requests/build/build
- ceph-ansible-pull-requests/build/teardown
- ceph-ansible-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
Enables the new tox-based testing for ceph-ansible pull requests.
This will require some extra work on the node assign to it to ensure that it runs properly.
> Ceph ansible tox

- ceph-ansible-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
If the tests succeed tox will clean up everything for us so
we only need to run this on failure.
> ceph-ansible-pull-requests: only run teardown on failure

- ceph-installer-rpm/build/build
- ceph-installer-rpm/config/ceph-installer-rpm.yml
This job builds RPMs for each ceph-installer GitHub branch.
NOTE: the current build script does not yet upload the builds to chacra. How should I implement that?
> add ceph-installer-rpm job

- kernel/build/build_deb
- kernel/build/build_rpm
- kernel/build/setup
The chacra instances are now configured to always keep
a build for the 'testing' ref, so it should be safe
to store these in the dev chacra instances now.
> kernel: upload binaries to a dev chacra instance

- ceph-ansible-pull-requests/config/definitions/ceph-ansible-pull-requests.yml
The idea is to have more slaves and not make every build request wait in line
> ceph-ansible-pull-requests: make the job concurrent so other slaves can do work too

- ceph-ansible-pr-syntax-check/config/definitions/ceph-ansible-pr-syntax-check.yml
Adds the trigger phrase 'jenkins test playbook syntax' to start a build
of this job.
> ceph-ansible-pr-syntax-check: add a trigger phrase

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Using a '-' breaks the service that creates machines based on labels
since it evaluates it as Python and '-' is seen as an operator
> ceph-ansible-prs: update labels required

- ceph-ansible-galaxy/build/build
We now use the latest version of the splitup.sh script that now pushes
branches and tags from ceph-ansible to ansible-ceph-* repositories.
> ceph-ansible-galaxy: update the splitup script

- ceph-ansible-pr-syntax-check/build/build
We now use group_vars/alll.yml files. So only yaml files, this
ceph-ansible PR introduced that:
https://github.com/ceph/ceph-ansible/pull/1113
So we apply the change here as well.
> ceph-ansible-syntax: update syntax check

- ceph-ansible-galaxy/build/build
The current path to execute the script is wrong, see:
bash:
/home/jenkins-build/build/workspace/ceph-ansible-galaxy/contrib/push-roles-to-ansible-galaxy.sh:
No such file or directory
It tries to execute
ceph-ansible-galaxy/contrib/push-roles-to-ansible-galaxy.sh where the
actual script is in
ceph-ansible-galaxy/ceph-ansible/contrib/push-roles-to-ansible-galaxy.sh
This commit fixes this.
> ceph-ansible-galaxy: fix workspace path

- ceph-ansible-prs/build/build
We need to set a working directory for tox because the default for some
scenarios are too long and the job fails to call pip because it exceeds
the char limit.
> ceph-ansible-prs: set a working directory for tox

- ceph-ansible-pr-syntax-check/config/definitions/ceph-ansible-pr-syntax-check.yml
We don't want this job picking up our arm64 slaves.
> ceph-ansible-pr-syntax-check: adds a x86_64 label

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This avoids an issue in tox where it splits on dashes and picks an
incorrect scenario because we had dashes in our environment names.
> ceph-ansible-prs: use underscores instead of dashes for scenarios

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Both:
* xenial_mon_osd: tests a 1 mon 1 osd xenial cluster using
raw_multi_journal OSD scenario
* xenial_conf_tests: test a 3 mon cluster and ensures
ceph.conf is rendered correctly
were missing, so adding them to the CI.
> ceph-ansible-prs: add 2 scenarios

- ceph-build/build/build_deb
- ceph-dev-build/build/build_deb
- ceph-dev-new-build/build/build_deb
This should finally allow notcmalloc builds on debian.
Setting the variable on the sudo command line does affect the
resulting pbuilder debian/rules execution (tested with a dummy
debian package)
> Pass CEPH_EXTRA_CMAKE_ARGS through sudo to pbuilder build

- ceph-installer-rpm/build/build
Don't hardcode the `ceph-installer` package name in the ceph-installer-rpm build script. Determine the package name from the Jenkins job name instead.
The purpose of this change is to make the build script more re-usable between different packages. (Eventually we could use JJB templates to construct multiple jobs using these same build steps.)
> ceph-installer-rpm: abstract build script

- samba/build/build_deb
- samba/build/build_rpm
I was able to perform a centos7 build with these changes. The ubuntu
builds fail because the libgnutls-dev version is too knew [1] -- this should
be fixable in samba sources.
[1] I hit the same issue as https://lists.samba.org/archive/samba/2015-April/191253.html but the workaround did not work for me as the libgnutls28-dev was in the failing 3.4 version as well :-/
> samba: Fix-up the build

- samba/build/build_deb
- samba/build/build_rpm
- samba/config/definitions/samba.yml
- scripts/build_utils.sh
This also fixes the get_distro_and_target function to get the proper
DIST and DISTRO for the new trusty-pbuilder-like tags.
> samba: Minor fix-ups

- ceph-ansible-rpm/build/build
- ceph-ansible-rpm/config/ceph-ansible-rpm.yml
This job builds RPMs for each ceph-ansible GitHub branch.
(This is a 99% copy and paste from ceph-installer-rpm, so we probably need to come up with a centralized area for these types of jobs and use JJB templates. I can't come up with a good directory name at the moment, though.)
> add ceph-ansible-rpm job

- ceph-ansible-rpm/config/definitions/ceph-ansible-rpm.yml
- ceph-installer-rpm/config/definitions/ceph-installer-rpm.yml
Our jenkins-job-builder job expects the JJB YAML to be located in a `config/definitions` directory. Add the child "definitions" directory here.
> ceph-{ansible,installer}-rpm: fix config location

- ceph-dev-new-setup/build/build
- ceph-dev-setup/build/build
Forgot to move these (for reference see PR #596 )
> move git diff checks on dev builds

- ceph-ansible-rpm/build/build
- ceph-installer-rpm/build/build
When an ephemeral slave is first created, we have to add the jenkins-build UID to the `mock` group so that it can run mock.
The problem is that `usermod -a -G ...` will not affect the current login shell. When the ceph-*-rpm jobs run `usermod` for the first time, the jenkins-build UID obtains those group rights for any future jobs, but not the current job.
The result is that every time an ephemeral slave boots, it will fail its first ceph-*-rpm build job (and future ones succeed).
Call `newgrp` to refresh the mock group for this login shell, so that all mock operations succeed, including the first one on each slave.
> ceph-{ansible,installer}-rpm: fix mock group addition

- ceph-ansible-rpm/build/build
- ceph-installer-rpm/build/build
The previous commit (0d90b3c5fec43fe66fc1e9c3856519f91e4454cf) attempted to use newgrp to refresh groups, but I did not realize that this just spawns a new shell (at least in my experiments in a bash interactive shell), and it is ineffective on our JNLP slaves.
Use the approach we implemented for Docker (in f9cc49aec026c2ae17b1db2603d262f5cb1c8a00), and run mock through `sg` to
set the group.
> ceph-{ansible,installer}-rpm: use "sg" for mock group

- ceph-pr-submodules/build/build
The check is returning false positives and it is hard to tell why without these -ex flags
> ceph-pr-submodules: increase verbosity to try and get values out of vars

- ceph-ansible-rpm/build/build
- ceph-ansible-rpm/config/definitions/ceph-ansible-rpm.yml
- ceph-installer-rpm/build/build
- ceph-installer-rpm/config/definitions/ceph-installer-rpm.yml
Our slaves in sepia, which use JNLP, are having troubles building these repos. The first issue we found was that the ``jenkins-build`` user was not added to the ``mock`` group properly on these sepia slaves. The attempted solution to that was proposed in: https://github.com/ceph/ceph-build/pull/600
The solution from https://github.com/ceph/ceph-build/pull/600 worked in that the mock command was able to execute without permissions errors but the builds were failing to build the 'noarch' rpm.  Here's an example of one of those repos: https://1.chacra.ceph.com/r/ceph-installer/master/1cd19fb1217c4f1b2083d85f3d148375e4106eb6/centos/7/flavors/default/noarch/
Let's just use the OVH slaves which we know can build these rpms until we have some automated tests in place, then we can use those tests …
> ceph-{ansible,installer}-rpms: do not use sepia slaves or sg

- ceph-installer-nightly/build/build
- ceph-installer-nightly/config/definitions/ceph-installer-nightly.yml
This job is parametrized so that we can also run it manually or
trigger it easily from other jobs.
> Adds a nightly job that tests ceph-installer

- ceph-deploy-build/build/build
We're using pbuilder in many build jobs now so we can't depend on the
host to be the actual distro version that the binaries are being built
for. This uses the value from the JJB matrix to determine what distro
value to use when posting to chacra.
> ceph-deploy-build: do not use python to detect the distro

- ceph-dev-trigger/build/notify
- ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
This will (unfortunately) need to also be ported to `ceph-dev-new-trigger` once it is up and running. It is safer to just use it on ceph-dev-trigger for now
> report when a build is triggered

- ceph-dev-new-trigger/build/notify
- ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
We already have this for ceph-dev, this would make it for ceph-dev-new (that builds ceph-ci PRs)
> notify of queued builds from trigger job

- ceph-installer-tests/build/build
- ceph-installer-tests/config/definitions/ceph-installer-tests.yml
This will create a new jenkins job for each testing scenario defined in
the config file. These jobs will run daily and can be trigger manually,
optionally providing which branches of ceph-installer and ceph-ansible
to test with.
> ceph-installer-tests: a project to run ceph-installer functional tests

- ceph-dev-build/build/setup_rpm
- ceph-dev-new-build/build/setup_rpm
This resolves an issue where the ``$SUDO yum-builddep -y $DIR/ceph.spec`` fails to fetch packages from epel and the build script fails before letting shaman know it ever started.
> Send status to shaman earlier when building ceph rpm binaries

- scripts/build_utils.sh
Hopefully the original order of pip vs. setuptools
in this script was not important, because apparently
we now need latest pip in order to install setuptools.
Fixes: http://tracker.ceph.com/issues/18645
Signed-off-by: John Spray <john.spray@redhat.com>
> build_utils: fix setuptools installation

- ceph-build/build/build_deb
- ceph-build/build/build_rpm
- ceph-dev-build/build/build_deb
- ceph-dev-build/build/build_rpm
- ceph-dev-new-build/build/build_deb
- ceph-dev-new-build/build/build_rpm
- ceph-dev-new-setup/build/build
- ceph-dev-setup/build/build
- ceph-setup/build/build
Prior to cmake, --with(out)-tcmalloc must be passed to the
configure done during the actual build.  For rpm, that means an
extra arg to the invocation of rpmbuild in build_rpm; for deb,
debian/rules invokes configure.  Also, no reason to export
the shell variables; they're used locally and passed as
property files between Jenkins jobs.
Fixes: http://tracker.ceph.com/issues/18744
> ceph-dev-*: fix tcmalloc args for pre-cmake builds

- ceph-docker-nightly/build/build
- ceph-docker-nightly/build/teardown
- ceph-docker-nightly/config/definitions/ceph-docker-nightly.yml
Creates a set of jobs that test building and deploying jewel and kraken
containers with the master branch of ceph-ansible. It also includes a
test for building and deploying a jewel container with the stable-2.1
branch of ceph-ansible.
> ceph-docker-nightly: scheduled tests for ceph-docker

- scripts/sync-push
~/repos was a symlink and an unnecessary extra step.  If the true path
were to change, either this file or the symlink would need to change
anyway.
The 'signer' user does not have sudo access.  'dhc-user' was the legacy
user from when download.ceph.com was hosted in DreamCompute.
> Change user and path for pushing upstream releases

- calamari/build/build_deb
- samba/build/build_deb
- samba/config/definitions/samba.yml
We used DEB_ARCH instead of ARCH when pushing to chacra in
samba/calamari. This meant that we pushed to amd64 instead of x86_64.
> Samba+calamari: minor fixes

- ansible/roles/ansible-jenkins/templates/jenkins.conf
Specifically introducing this change because JJB was hitting gateway timeouts since the POST requests are large enough that it was taking longer than the 90 seconds allowed.
> ansible: double the time for nginx-to-jenkins for timeouts

- nfs-ganesha/config/definitions/nfs-ganesha.yml
This job doesn't use SSH, so there's no need to make this credential available to the job.
> nfs-ganesha: rm SSH credential

- scripts/build_utils.sh
All our chacra endpoints (https://*.chacra.ceph.com) use HTTPS certs
signed by LetsEncrypt now. There's no need to disable SSL verification
here any more.
This reverts f5e28bdeb675f6e245c26ae7d0e7f662ac1ed0f1.
Signed-off-by: Ken Dreyer <kdreyer@redhat.com>
> build_utils: enable SSL verification

- ceph-docs/build/build
> ceph-docs: Verify push contains docs files; don't build if not

- ceph-pr-submodules/build/build
Prior code never generated any output at all.
Fixes: http://tracker.ceph.com/issues/19244
> ceph-pr-submodules: fix submodule check.

- ceph-build/build/setup_pbuilder
- ceph-dev-build/build/setup_pbuilder
- ceph-dev-new-build/build/setup_pbuilder
- diamond-build/build/setup_pbuilder
- scripts/build_utils.sh
The nfs-ganesha pbuilder setup code configures the pbuilder caches to
point at repos from shaman. Since all Jenkins jobs uses the same
pbuilder cache tarballs, this means that these shaman repositories will
still be enabled in the next jobs that run on a slave.
1) nfs-ganesha job runs on a slave
2) nfs-ganesha job configures pbuilder cache to use shaman repo
3) nfs-ganesha job finishes
4) ceph-build job runs on same slave slave
5) ceph-build job uses same pbuilder cache with shaman repo configured
In addition to polluting the pbuilder environment, this can also lead to
pbuilder failures when shaman/chacra garbage-collects old repositories,
because Apt wants to download repo metadata from old ceph repos that
are no longer available.
Force every job that runs "pbuilder update" to also run …
> reconfigure apt during every "pbuilder update"

- nfs-ganesha/build/build_deb
The curl command sometimes returns 504, since the repository isn't ready yet. That exist status stops the rest of the script from running instead of running through the loop for $TIME_LIMIT and rerunning curl every $INTERVAL. This fix ensures the exit status is always true.
This was inspired by failures such as this: https://jenkins.ceph.com/job/nfs-ganesha/1164/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=trusty,DIST=trusty,MACHINE_SIZE=huge/console repeatedly occurring.
> nfs-ganesha: fix build_deb shaman polling loop

- nfs-ganesha/build/build_deb
- nfs-ganesha/build/build_rpm
Certain Trusty builds were failing because the
repos weren't available until 11-15 mins after
the job was run
> nfs-ganesha: change shaman polling time to 20 mins

- nfs-ganesha/config/definitions/nfs-ganesha.yml
Trusty builds aren't necessary and I don't want any resources unnecessarily going to them.
> nfs-ganesha: remove trusty from axis

- ceph-pr-submodules/build/build
This ceph-pr-submodules job is still giving us false positives in some cases.
We were comparing against a target branch (for example "origin/jewel"), but we could not see the *exact* sha1 that Jenkins thought was "origin/jewel". Sometimes this job would fail, and the failure hinted that Jenkins might be comparing an older target branch.
Explicitly fetch the target branch immediately before doing the "git log" operation, and print the target branch's sha1 ref to stdout in case we need further debugging.
> ceph-pr-submodules: explicitly fetch the target branch

- ceph-ansible-docs/build/build
> ceph-ansible-docs: fix a typo on mkdir

- ceph-ansible-prs/build/teardown
> ceph-ansible-prs: destroy and undefine libvirt networks on teardown

- ceph-ansible-prs/build/build
Occasionally we deal with libvirt network issues on jenkins slaves that
have been used for a couple test runs, this attempts to avoid those.
> ceph-ansible-prs: remove old libvirt networks before running tests

- nfs-ganesha/build/build_deb
The missing comma breaks this job when it attempts to POST to chacra nodes
> nfs-ganesha: add missing comma in JSON blob

- ansible/examples/slave_static.yml
- ansible/slave.yml
After the latest jenkins upgrade to 2.57 our centos slaves failed to
connect to jenkins, upgrading to a 1.8.0 version of java fixed the
issue.
> ansible: we now need java-1.8.0-openjdk on rpm nodes

- ceph-ansible-rpm/build/build
- ceph-installer-rpm/build/build
It appears that Yum is not installing "mock" when installing fedpkg
(with fedpkg-1.28-1.el7). Explicitly install it in our build steps.
> ceph-ansible/-installer: explicitly install mock

- ansible/examples/slave.yml
- ansible/examples/slave_libvirt.yml
- ansible/examples/slave_static.yml
- ansible/slave.yml
- ansible/slave_libvirt.yml
This is already live in prado.ceph.com for slave.yml
> ansible: using forked version of python-jenkins until we can fix upstream

- ceph-ansible-scenario/config/definitions/ceph-ansible-scenario.yml
This job is not using a job-template and fails with the following error
when using include-raw-escape:
syntax error near unexpected token `{{'
> ceph-ansible-scenario: use include-raw instead of include-raw-escape

- ceph-ansible-prs/build/build
- ceph-ansible-scenario/build/build
- ceph-docker-nightly/build/build
- ceph-docker-prs/build/build
- ceph-installer-tests/build/build
- scripts/build_utils.sh
We continue to have issues with ceph-ansible/docker/installer tests failing because of libvirt networking issues. This is an attempt to get libvirt back into a good state by delete old networks and restarting services before we run tests.
Here is an example of the error we see often: https://jenkins.ceph.com/view/ceph-installer/job/ceph-installer-tests-ansible2.2-nightly_xenial/124/console
> attempt to make libvirt slaves more stable

- ceph-docker-nightly/config/definitions/ceph-docker-nightly.yml
We don't need to test on stable-2.1 of ceph-ansible anymore
> ceph-docker-nightly: test on stable-2.2 of ceph-ansible

- ceph-docker-lint/build/build
Excluding the following code:
* SC1091: since our entrypoint copies files in / during this shellcheck
the files can not be found. Basically we source ./file but presently the
file is under osd_directory/file so can not be found.
* SC2015: because we use 'set -e' we don't have other choice to use '||
true' here.
* SC2009: pgrep returns processes ID where we are looking for a specific
string in the process line.
* SC2001: our sed expressions are too complex we can not substitute them
with bash ${variable//search/replace}.
> ceph-docker-lint: exclude codes

- ceph-docker-lint/build/build
selinux is disabled so this command is useless.
> ceph-docker-lint: remove chcon command

- ceph-docker-lint/build/build
yum does not start services after installation, so starting it and using
sudo to call docker command.
> ceph-docker-lint: start docker and use sudo

- ceph-docker-nightly/build/teardown
- ceph-docker-prs/build/teardown
- scripts/build_utils.sh
Some of the network errors thrown by libvirt when running
Docker builds were because the slave had leftover Vagrant VMs that didn't
get destroyed.
This PR ensures all slaves being used for Docker tests will have VMs and disk images cleaned up if the build fails.
> scripts: Add function to delete leftover vagrant VMs

- ceph-ansible-prs/build/build
- ceph-ansible-scenario/build/build
- ceph-docker-nightly/build/build
- ceph-docker-nightly/build/teardown
- ceph-docker-prs/build/build
- ceph-docker-prs/build/teardown
- ceph-installer-tests/build/build
- scripts/build_utils.sh
This PR ensures all slaves that use tox & Vagrant don't have any running libvirt VMs that could cause IP collisions
Builds on https://github.com/ceph/ceph-build/pull/720
> scripts: Be more aggressive with deleting libvirt VMs

- scripts/build_utils.sh
c7edf24 introduced a new behavior regarding teardown.
`virsh pool-refresh default` might fail if the pool doesn't exist yet.
> scripts: fix virsh pool-refresh issue

- samba/build/build_deb
Debian/Ubuntu does not tie the package versions the same way the rpm
packagin does so upgrading a single package won't remove any old
packages. Remove the old bits before installing any new.
This should fix a build failure on xenial where there were two libcephfs
libraries present on the system at the time of build which broke the
build.
> samba: Clean old ceph bits before getting new

- samba/build/build_deb
- samba/build/build_rpm
- samba/config/definitions/samba.yml
We had random build failures on missing pam library, the xargs command did not work the way I expected it to and we no longer need to build for trusty by default, especially now since we have the builds being triggered automatically.
> A couple more samba fixes

- samba/build/setup
- samba/config/definitions/samba.yml
When we pass the CEPH_BRANCH from ceph-dev-build, it contains
origin/<branch>, we need to strip out the remote from the CEPH_BRANCH
before we can use it.
> samba: Strip out origin/ for CEPH_BRANCH

- scripts/build_utils.sh
See https://github.com/vagrant-libvirt/vagrant-libvirt/issues/670#issuecomment-261964248
Can confirm that deleting the default network still allows vagrant-libvirt to run fine on Ubuntu 16.04.
> scripts: Be more aggressive with libvirt network destruction

- ceph-lvm-docs/build/build
This was causing the build to just sync to the root directory which we don't want, we really want to be able to have the same behavior as ceph-ansible and ceph docs
> ceph-lvm-docs: define BRANCH to sync it to the right dir

- ceph-docs/build/build
This touches on http://tracker.ceph.com/issues/19976, but doesn't
fix it; it just defaults to "build it if it's not a merge commit".
I'm still not sure the ideas in the bug are workable.  So this
mitigates the issue.
> ceph-docs/build/build: don't try to skip if not a merge commit

- cephmetrics/build/build_rpm
The build uses wget to get the vonage-status-panel but wget might not
always be available on the system.
> cephmetrics: Install wget

- ceph-ansible-prs/build/build
Add a timeout (5h) since sometimes some job can get stuck in the CI for
a very long time.
> ceph-ansible-prs: add a timeout

- cephmetrics/config/definitions/cephmetrics.yml
The build job does not work well with empty branch, we should provide a
default master branch to fix it.
It looks like it is not enough to remove the wipe-workspace line, it was
on even without that line. Adding wipe-workspace: false to hopefully fix
it.
> cephmetrics: Add default branch, forbid wipe

- ceph-pull-requests-arm64/build/build
- ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml
This has several XML sections; removing the two smaller ones seems safe,
but I'm concerned about the last one (the GitSCM clone behavior).  It
doesn't currently look like either jjb or jjw handle that option section
correctly, so I'm leaving the XML for now.
> Add ceph-pull-requests-arm64

- cephmetrics/build/build_rpm
- cephmetrics/config/definitions/cephmetrics.yml
This kicked off a build, but it failed because `BRANCH` was unset :-/
https://jenkins.ceph.com/job/cephmetrics/ARCH=x86_64,AVAILABLE_ARCH=x86_64,AVAILABLE_DIST=centos7,DIST=centos7,MACHINE_SIZE=small/42/console
> DNM: cephmetrics: Build for all branches

- ceph-ansible-pr-syntax-check/build/build
Explicitly set the LIBRARY path to avoid the following Ansible error:
ERROR! no action detected in task. This often indicates a misspelled
module name, or incorrect module path.
We need this change because roles path changed from ceph-ansible/ to
ceph-ansible/infrastructure-playbooks so now when we are running the
syntax check it looks in ceph-ansible/infrastructure-playbooks/library
instead of ceph-ansible/library.
> ceph-ansible-pr-syntax-check: add library path

- cephmetrics-release/build/build_rpm
- cephmetrics-release/build/setup
- cephmetrics-release/config/definitions/cephmetrics-release.yml
The purpose of this job is to allow for manual
builds of cephmetrics that will be stored on chacra.ceph.com
where the repo can be combined with cephmetrics-debs.
> adds the cephmetrics-release job

- cephmetrics-release/config/definitions/cephmetrics-release.yml
wipe_workspace does not use sudo which causes some of our builds to fail
> cephmetrics-release: sets wipe_workspace to false

- scripts/sync-pull
You can now specify which project you'd like to pull from chacra. This
also removes el6 as we don't build for that anymore.
> scripts: sync-pull now supports multiple projects

- ansible/examples/slave_libvirt_static.yml
Used successfully on smithi118 and smithi119 which are passing ceph-docker jobs.  (Ignore the jobs that failed with `ERROR: unknown environment`.  That was as dumb mistake on my part.)
> ansible: Add playbook for libvirt/vagrant static slaves

- ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml
Specifically reinstate the 'status-context/*-status' fields, but also
regularize like ceph-pull-requests job.  (This one originally came from
jjw and probably lost the fields/gained a lot of defaults in the
process)
> ceph-pull-requests-arm64: make ghprb config like amd64 version

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
ceph-ansible-prs: adds the ansible2.2-cluster_bluestore and
ansible2.2-journal_collocation_bluestore scenarios.
> ceph-ansible-prs: add bluestore scenarios

- ceph-ansible-prs/build/build
it will always return 0 even if tox return an error.
We must check wether the expression is not true instead.
> ceph-ansible-prs: fix bug with timeout

- ceph-medic-release/build/build_rpm
There is no need to try and infer the project name, just upload directly
to chacra as ceph-medic.
> ceph-medic-release: upload directly to the ceph-medic project

- ceph-docker-prs/config/definitions/ceph-docker-prs.yml
As it has been decided to stop testing against kraken, this commit
remove all tests for kraken.
> ceph-docker-prs: remove kraken tests

- kernel/config/definitions/kernel.yml
Started seeing failures like:
Resolving deltas:  60% (2773158/4615018)
Resolving deltas:  60% (2775140/4615018)
Resolving deltas:  60% (2776500/4615018)
error: fetch-pack died of signal 15
kernel-trigger and a lot of other jobs use 20.
> kernel: set git clone/fetch timeout to 20 minutes

- ceph-ansible-prs/build/build
- ceph-docker-prs/build/build
- Add the same timeout than for ceph-ansible PRs in ceph-docker PRs.
- Change logged error message
> Add timeout for ceph-docker

- kernel/config/definitions/kernel.yml
Setting the timeout to 20 minutes helped some, but I'm still seeing
failures during the CPU-intensive "Resolving deltas" stage.  Use git
clone --depth 1 for kernel to avoid stressing slaves.
> kernel: use shallow clones

- ceph-pr-docs/build/build
- ceph-pr-docs/config/definitions/ceph-pr-docs.yml
It might need the HTML publisher plugin in Jenkins. This is so that we can render html right from Jenkins for pull requests
> ceph-pr-docs: create a trigger-only job for testing docs

- ceph-pr-docs/build/build
- ceph-pr-docs/config/definitions/ceph-pr-docs.yml
* I suspect the order of `publishers` is making the job not configure it (build was last item in yaml before)
* use ubuntu only because the deps (mainly ditaa) are not available in CentOS7
* remove frigging lingering shaman.list files that can mess up builds (temporary only)
> Ceph pr docs fixes

- ansible/examples/slave.yml
- ansible/examples/slave_libvirt.yml
- ansible/examples/slave_static.yml
- ansible/slave.yml
- ansible/slave_libvirt.yml
This PR reverts https://github.com/ceph/ceph-build/pull/693 and bumps our pinned version to 0.4.15. This upstream version has support for creating nodes with "+" in the names.
I don't feel great about continuing to pin to an exact version, but let's take the short-term defensive route for now.
> ansible: use python-jenkins 0.4.15

- shaman-pull-requests/setup/playbooks/tasks/postgresql.yml
the real "apt fix" was to remove all the garbage left behind in a server in /etc/apt/sources.list.d/ which included a shaman.list
$ ls /etc/apt/sources.list.d
ppa_fkrull_deadsnakes_xenial.list  ppa_fkrull_deadsnakes_xenial.list.save  saltstack-ubuntu-salt-xenial.list shaman.list
The rest is just to overcome 9.5 in xenial. This still fails horribly on the shaman side with unittests
> Shaman apt fix

- ceph-ansible-scenario/config/definitions/ceph-ansible-scenario.yml
With these parameters, if you are using a dev-* testing scenario, you can
control which ceph branch and sha1 is deployed and tested.
> ceph-ansible-scenario: adds the CEPH_DEV_BRANCH and CEPH_DEV_SHA1 params

- ansible/examples/slave_libvirt_static.yml
- ansible/slave_libvirt.yml
Required to switch to Ubuntu 16.10.
The group `libvirtd` have been renamed to `libvirt`.
> ceph-ansible-prs: Change group for jenkins_user

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
- ceph-docker-prs/config/definitions/ceph-docker-prs.yml
When a PR is updated, jobs that were launched by the previous PR are not
aborted. It can even happen that you update a PR several times in a
short time. So it's n*x jenkins slave locked until they end.
Adding `cancel-builds-on-update` to the jobs templates force the job to be
aborted to free a jenkins slave quicker.
> Abort builds on update

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
- ceph-docker-prs/config/definitions/ceph-docker-prs.yml
Auto-restart failed builds 3 times with 60 seconds interval.
> ceph-ansible-prs: add naginator configuration

- ceph-ansible-scenario/config/definitions/ceph-ansible-scenario.yml
In testing I noticed that without this set sometimes the latest sha1 from the
ceph-ansible branch wasn't fetched if the jenkins slave had already been
used for this job.
> ceph-ansible-scenario: wipe the workspace before each job

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
- ceph-docker-prs/config/definitions/ceph-docker-prs.yml
Add CancelOnUpdate option in raw/xml format
The option `cancel-builds-on-update` doesn't work in job template
because we are not using a recent version of JJB, therefore we had to
revert the previous commit.
This commit adds the cancel-builds-on-update option but in raw/xml
format instead.
Fixes: #817
> Abort on updated pr

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
- ceph-docker-prs/config/definitions/ceph-docker-prs.yml
- jenkins-job-builder/build/build
Basically just puts https://github.com/ceph/ceph-build/commit/18a1bbc24552ca0466500b6121818292e645f41b back into place.  JJB>=2.0.0 is needed as well for this to work.
> Abort build on updated PR

- ceph-volume-ansible-prs/build/build
- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
* uses ceph.git instead of the wrong ceph-ansible.git (bad copy pasta)
* fixes the script to use a shorter tmp path for tox
* adds parsing for finding the remote branch of the github pull request
> Ceph volume pr fixes

- ceph-ansible-prs/build/build
- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This drops support for testing jewel on PRs and changes the ansible
version to 2.3. If we want to continue testing against jewel we can
schedule nightly tests that run against master. With this approach we
can still get the same coverage and reduce a lot of demand on the CI
caused by PR testing.
> ceph-ansible-prs: test against ansible2.3 and luminous only

- ceph-ansible-nightly/build/build
- ceph-ansible-nightly/build/teardown
- ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
These tests are scheduled to be run automatically by jenkins daily. They can
also be triggered manually and given a branch of ceph-ansible to test
against.
> ceph-ansible-nightly: run tests against jewel and ansible2.2 and 2.3

- ceph-volume-ansible-prs/build/build
- ceph-volume-pr/build/build
- ceph-volume-pr/config/definitions/ceph-volume-pr.yml
It now requires a python3 node to be able to run py35 tests. Had to omit Python 3.6 tests for now as that is not available in build nodes (yet).
Fixes the `scm` section to correctly narrow down the scope to the PR only (before it would just build any PR or any merge even)
> Ceph volume fixes for PRs

- ceph-pr-docs/build/build
- ceph-pr-docs/config/definitions/ceph-pr-docs.yml
This will build on docs.ceph.com, and publish to `ceph-pr/$PR-ID`
> Ceph docs for prs on docs.ceph.com

- ceph-pr-docs/config/definitions/ceph-pr-docs.yml
This is so that it is easier for everyone to refer to the actual URL used for the PR docs build. Otherwise it would be tricky to find out (or remember!) where the build is to look at it
> ceph-pr-docs: include the pull request ID for the url as a comment

- cephmetrics/build/build_rpm
This will try to use git describe to get the current version and release
and fall back to the old method if HEAD is not part of any tag.
> cephmetrics: Add support for versioning with git tags

- ceph-pr-docs/build/build
- ceph-pr-docs/config/definitions/ceph-pr-docs.yml
- ceph-pr-render-docs/build/build
- ceph-pr-render-docs/config/definitions/ceph-pr-render-docs.yml
This PR creates 2 jobs (adapting the previous doc check for Ceph). The *previous* one will now be called "render" so that a reviewer (or proponent of a PR) can trigger on demand and get a representation of the rst->html online
The new one will just build (on Ubuntu nodes) and will not publish anything. This is done this way because not every pull request needs HTML rendered (that uses the docs.ceph.com server) and sometimes is sufficient to know that docs are broken by looking at the build.
Now that Ceph docs builds will refuse to publish because the `-W` (treat warnings as errors) this is going to be useful to know what PR broke docs
> Enforce ceph doc checks on all Ceph prs

- ceph-ansible-docs-prs/config/JENKINS_URL
- ceph-ansible-docs/config/JENKINS_URL
- ceph-ansible-galaxy/config/JENKINS_URL
- ceph-ansible-nightly/config/JENKINS_URL
- ceph-ansible-pr-syntax-check/config/JENKINS_URL
- ceph-ansible-prs/config/JENKINS_URL
- ceph-ansible-rpm/config/JENKINS_URL
- ceph-ansible-scenario/config/JENKINS_URL
- ceph-docker-flake8/config/JENKINS_URL
- ceph-docker-lint/config/JENKINS_URL
- ceph-docker-nightly/config/JENKINS_URL
- ceph-docker-prs/config/JENKINS_URL
- jenkins-job-builder/build/build
- jenkins-job-builder/config/definitions/jjb.yml
Once this is merged and JJB gets run, 2.jenkins.ceph.com will then be the source of truth for ceph-ansible and ceph-docker builds.
> Move ceph-ansible and ceph-docker builds to 2.jenkins.ceph.com

- nfs-ganesha-stable/build/build_deb
- nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml
- nfs-ganesha/config/definitions/nfs-ganesha.yml
These changes allow for libntirpc and nfs-ganesha debs to be built on the same VMs
for download.ceph.com.The libntirpc binaries will go in the same repo as the nfs-ganesha ones
> nfs-ganesha-stable: add seperate libntirpc packages

- ceph-pr-docs/build/build
cython is needed for generating docs from pyx docstrings and
python-sphinx is not needed because it is installed in a virtualenv by
the admin/build-doc script
> ceph-pr-docs: install cython, remove python-sphinx

- kernel-trigger/config/definitions/kernel-trigger.yml
- kernel/config/definitions/kernel.yml
After a recent jenkins/plugins update, jenkins started listing tags and
attempting git rev-parse ^{commit} on them:
Seen branch in repository origin/wip-tighter-types
Seen 39 remote branches
> git tag -l # timeout=10
> git rev-parse refs/tags/v4.7-rc7^{commit} # timeout=10
> git rev-parse refs/tags/v2.6.30-rc7^{commit} # timeout=10
On the Linux kernel repo, this eventually fails with:
> git rev-parse refs/tags/v2.6.11^{commit} # timeout=10
FATAL: Command "git rev-parse refs/tags/v2.6.11^{commit}" returned status code 128:
stdout: refs/tags/v2.6.11^{commit}
stderr: error: refs/tags/v2.6.11^{commit}: expected commit type, but
the object dereferences to tree type
Only "trigger" jobs seem to be affected, but we don't really need tags,
so don't fetch them for both kernel-trigger and kernel. …
> kernel: do not fetch git tags

- ceph-ansible-docs/config/JENKINS_URL
Because docs.ceph.com is a slave of jenkins.ceph.com
> Build ceph-ansible docs on jenkins.ceph.com

- nfs-ganesha-stable/build/build_deb
- nfs-ganesha-stable/build/setup
- nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml
-ntirpc scm wasn't applying properly
-clean up ntirpc directory
-various pbuilder related fixes
-directory ownership fix for creating local ntirpc repo
> nfs-ganesha-stable: fixes to get build scripts working

- ceph-docker-flake8/build/build
- ceph-docker-lint/build/build
> ceph-docker: run flake8 and lint jobs on 2.jenkins

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
The CI will now test migration from non-containerized to containerized
scenario.
Linked to https://github.com/ceph/ceph-ansible/pull/1812
> ceph-ansible-prs: add switch_to_containers scenario

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This test will install the latest master version of ceph from shaman.ceph.com
to verify that dev installs still work.
> ceph-ansible-prs: adds the dev-ansible2.3-centos7_cluster scenario

- kernel-trigger/config/definitions/kernel-trigger.yml
- kernel/config/definitions/kernel.yml
kernel-trigger job needs to specify do-not-fetch-tags, otherwise
cloning fails, "No changes" is reported and nothing gets triggered (see
commit b34f8fa ("kernel: do not fetch git tags") for more details).
do-not-fetch-tags was added to jenkins-job-builder in commit
badab0264717 ("Add do-not-fetch-tags to CloneOption for Git"), which
isn't in any tag.  The version we get from pypi, 2.0.0.0b2, simply
ignores it, leaving us with no kernel builds.
Use raw xml generated with jenkins-job-builder's master to get
<noTags>true</noTags> up there after all.
> kernel: use raw xml for configuring scm module

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
We don't need to bootstrap a full cluster to bootstrap bluestore. We
have individual scenarios for that.
> ceph-ansible-prs: remove bluestore_docker_cluster

- ceph-ansible-prs/build/teardown
Delete with force any `fetch/` directories that could have been left after a
build.
> ceph-ansible-prs: improve teardown

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
These lvm_osd tests won't pass until 12.2.1 is released, but if we have
them use ceph@master then they should pass. After 12.2.1 is out we can
move these back to be a 'luminous' test.
> ceph-ansible-prs: only run lvm_osd tests on ceph@master

- ceph-docker-nightly/config/definitions/ceph-docker-nightly.yml
There is no ceph_ansible2.3 factor, we shouldn't need to test kraken
anymore and luminous needed to be added.
> ceph-docker-nightly: update scenarios

- ceph-ansible-docs/config/definitions/ceph-ansible-docs.yml
The stable-3.0 branch has not been created yet, but putting this in
place now will ensure we get docs built when it is.
> ceph-ansible-docs: adds the stable-2.2 and stable-3.0 branches

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Adding the string 'no-tests' to either the PR title
or description will keep CI jobs from triggering on PR updates or
creation.
> ceph-ansible-prs: adds skip-build-phrase

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
> ceph-ansible-prs: skip-build-phrase must be a regex

- ceph-ansible-pr-syntax-check/build/build
Enhance the ceph-ansible-pr-syntax-check job by running ansible-lint as
well.
> ceph-ansible-pr-syntax-check: use ansible-lint

- ceph-ansible-prs/build/build
- ceph-ansible-prs/build/teardown
sometimes, it happens that the Jenkins Slave processes crashes before
teardown is executed (ie. `java.io.EOFException`), it means we keep leftofver from previous build.
This commit ensures before the test is launched that no fetch directory
from previous build is present.
> ceph-ansible-prs: fix leftover

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This creates two different projects, one which lists scenarios that will
auto start on every PR and another which lists scenarios that will only
start if a comment is made on the PR with its trigger phrase.
> ceph-ansible-prs: allow for tests to be auto started or only triggered

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
I tried setting the value of only-trigger-phrase as a variable on the
project so we didn't have to duplicate the job template but that didn't
seem to work. Duplicating the job template does allow us to create jobs
that do not auto start when PRs are created.
> ceph-ansible-prs: setting only-trigger-phrase with a var did not work

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Adding update_cluster and docker_cluster to test by default on each new
PR.
> ceph-ansible-prs: add two default scenarios

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Scenarios requested by leseb to run only on smithi:
* luminous-ansible2.3-xenial_cluster
* luminous-ansible2.3-centos7_cluster
* luminous-ansible2.3-docker_cluster
* luminous-ansible2.3-purge_cluster
* luminous-ansible2.3-update_cluster
* luminous-ansible2.3-update_docker_cluster
* luminous-ansible2.3-switch_to_containers
* luminous-ansible2.3-purge_docker_cluster
Building/testing old yaml
```
dgalloway@w541 ceph-build (wip-limit-smithi)$ jenkins-jobs --conf ~/.jenkins_jobs.2.jenkins.ceph.com.ini test ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml.old -o /tmp/output-old
INFO:jenkins_jobs.cli.subcommand.update:Updating jobs in ['ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml.old'] ([])
INFO:jenkins_jobs.local_yaml:Including file '../../../scripts/build_utils.sh' from …
```
> ceph-ansible-prs: limit certain scenarios to smithi nodes

- ceph-ansible-pr-syntax-check/build/build
We better to stabilize existing jobs before adding new like this one.
> syntax-check: temporary disable ansible-lint

- ansible/examples/slave_libvirt_static.yml
- scripts/build_utils.sh
Playbook tested on Zesty and CentOS slave.
Only thing untested is the change to build_utils.sh but looks pretty standard.
> Support CentOS static libvirt slaves & update playbook

- ceph-docker-prs/build/build
since a recent change on hypervisors, we need to make this script
runnable on centos.
> ceph-docker-prs: make build script compatible with centos

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
- ceph-docker-prs/config/definitions/ceph-docker-prs.yml
* introduces new osd scenarios to reduce amount of osds
* do not run update jobs by default
> DNM: ceph-ansible-prs: simply osd scenarios

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This must be a dev scenario for now as the functionality for ceph-volume
to create bluestore osds is not in a luminous release yet.
> ceph-ansible-prs: adds the dev-ansible2.3-bluestore_lvm_osds

- ansible/examples/slave_libvirt_static.yml
- ansible/examples/slave_static.yml
Makes sure latest version of JNLP is being used.  Primarily useful when
re-running the playbook against a static slave.
> ansible: always update slave.jar

- ceph-docker-nightly/build/build
Related: https://github.com/ceph/ceph-build/pull/886
> ceph-docker-nightly: nightlies run on centos now

- ceph-build/build/setup_rpm
- ceph-dev-build/build/setup_rpm
- ceph-dev-new-build/build/setup_rpm
enable/install centos-release-scl on rhel7/centos7, so we can use
newer gcc/toolchain offered by Software Collections (scl)'s devtoolset
see https://www.softwarecollections.org/en/scls/rhscl/devtoolset-7/
> ceph{-,dev-,dev-new-}build: install centos-release-scl repo

- ceph-volume-ansible-prs/build/build
- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
I'm not exactly sure of the reason but ``TEST_PATH`` was being rendered by jjb as a list. However, we can easily build the testing path by using the ``subcommand`` factor that we already have.
> ceph-volume-ansible-prs: use subcommand to build the testing path

- ceph-ansible-nightly/build/build
- scripts/build_utils.sh
according to ceph/ceph-ansible#2165 we need to set `CEPH_STABLE_RELEASE`
in ceph/ceph-build.
> ceph-ansible: set CEPH_STABLE_RELEASE in start_tox()

- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
These vars are injected by the ghprb plugin when the job is triggered by a new PR or by a comment in a PR. The idea here is to see if by passing them manually, one can trigger a job without having to be commenting on a PR.
This addition should be neutral and not affect the job itself.
> ceph-colume-ansible-prs: add injected ghprb vars to help manual triggering

- ceph-ansible-nightly/build/build
- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
- Remove a useless test in nightlies jobs.
- Add testing for backport to stable-2.2 PRs
> ceph-ansible-nightly: couple of fixes

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
fix ceph-ansible-2.2-prs template because it triggers jobs that
shouldn't for backport to stable-2.2 PRs.
> ceph-ansible-prs: change trigger-phrase

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
`stable-2.2` is not a correct syntax because it is interpreted as a regexp.
> ceph-ansible-prs: fix wrong syntax in trigger-phrase

- kernel/build/setup
ORC unwinder (default on x86 since 4.15) requires it.
> kernel: install libelf

- ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
This is already working, this should persist the config.
> ceph-dev-trigger support mimic* branches, to include mimic-dev

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
ceph-volume can now be used in luminous, so we should be able to
test PRs for ceph-volume against luminous.
> ceph-ansible-prs: adds lvm tests for the luminous release

- ceph-build/build/setup_pbuilder
- ceph-dev-build/build/setup_pbuilder
- ceph-dev-new-build/build/setup_pbuilder
- scripts/build_utils.sh
* only use GCC-7 offered by ppa repo on mimic and newer release.
we are dropping the support of trusty in mimic and newer releases,
but we still need to use the old toolchain shipped with trusty to
build jewel and luminous. so, only use GCC-7 on trusty for building
mimic and up. as it should be safe to use the new GCC ABI on the
supported distros, like xenial.
* extract the ppa setup related code into build_utils.sh, so the
setup_pbuilder scripts can reuse it.
> setup_pbuilder: only use ppa on newer releases

- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
This will allow you to comment 'jenkins test ceph-volume all' and
all jobs will trigger.
> ceph-volume-ansible-prs: add a trigger phrase to start all jobs

- ceph-volume-ansible-prs/build/build
- ceph-volume-ansible-prs/build/teardown
- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
Will allow for manual notification, that in turn can be used to trigger any of these jobs via alternate methods to Github and still receive notifications
> ceph-volume-ansible-prs: Manual GitHub notification

- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
This removes the ``prepare_activate`` scenario has it has not been implemented yet, so no need to create a job for it.
Also, you can now trigger all tests by their subcommand by commenting ``jenkins test ceph-volume lvm all`` or ``jenkins test ceph-volume simple all``.
> ceph-volume-ansible-prs: remove prepare_activate and add subcommand trigger

- ceph-volume-ansible-prs/build/build
- ceph-volume-ansible-prs/build/teardown
Because otherwise the cached, previous (and buggy) version will be used
> ceph-volume-ansible-prs make sure a newer version of github-status is used

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
We need to get a better coverage for PRs testing.
Adding these 2 purge scenarios will cover osds scenarios testing which
is not the case at the moment.
> ceph-ansible-prs: Add more scenarios in 'auto'

- scripts/build_utils.sh
get CEPH_STABLE_RELEASE back to tox.ini so we do not have to set
explicitely CEPH_STABLE_RELEASE when running test locally.
> ceph-ansible: get CEPH_STABLE_RELEASE back to tox

- ceph-build/build/setup_rpm
- ceph-dev-build/build/setup_rpm
- ceph-dev-new-build/build/setup_rpm
the devtoolset-7 for aarch64 is not offered by centos-release-scl, but
at least centos-release-scl-rh has devtoolset-6.
see https://github.com/sclorg/centos-release-scl
see https://buildlogs.centos.org/centos/7/sclo/aarch64/rh/
Fixes: http://tracker.ceph.com/issues/22301
> ceph{-,dev-,dev-new-}build: install centos-release-scl-rh repo for arm64

- scripts/build_utils.sh
to be immune from the MITM attack
> script/build_utils.sh: import ppa key into apt's keyring

- ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
- scripts/build_utils.sh
This will tell tox which ceph version to install and test. Without this
some of the nightlies advertised that they were testing jewel
but were actually testing luminous.
> build_utils: set CEPH_STABLE_RELEASE in start_tox

- ceph-volume-ansible-prs/build/build
- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
This is problematic when dealing with branches that aren't in ceph.git and PRs need to be tested.
> ceph-volume-ansible-prs: allow to specify branches not in ceph.git

- ceph-ansible-nightly/build/build
- ceph-ansible-prs/build/build
- scripts/build_utils.sh
Setting this variable was originally for nightlies test need.
We should keep `CEPH_DOCKER_IMAGE_TAG` set in tox for PRs.
> ceph-ansible: PRs should keep CEPH_DOCKER_IMAGE_TAG set in tox

- ceph-volume-ansible-prs/build/build
- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
This adds some util functions that libvirt/vagrant jobs typically run that clean up stale libvirt networks and upgrades the vagrant box.
This also adds the ``dmcrypt`` factor to enable the new testing scenarios in https://github.com/ceph/ceph/pull/20054
> ceph-volume-ansible-prs: libvirt cleanup and dmcrypt testing scenarios

- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
So we can start all 'create' tests like 'jenkins test ceph-volume lvm
create'
> ceph-volume-ansible-prs: add trigger phrase per scenario

- nfs-ganesha-stable/build/build_rpm
- nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml
added a $CEPH_VERSION var to specify rpm installations
changed rpm build type to Release
> nfs-ganesha-stable: various rpm build updates

- ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
The jobs will now clone the correct branch of ceph.
> ceph-volume-nightly: fix usage of ceph_branch

- ceph-volume-scenario/build/build
- ceph-volume-scenario/build/teardown
- ceph-volume-scenario/config/definitions/ceph-volume-scenario.yml
This job can be started manually and allows for ceph branch, ceph sha1,
ceph-volume testing scenario and ceph-ansible branch to be entered
as parameters.
> ceph-volume-scenario: a new job to run ceph-volume testing scenarios

- ceph-deploy-pull-requests/setup/playbooks/tasks/ubuntu.yml
Removes the 'dead snakes' PPA, and just ensures that python 2.7 and 3.5 are available. Which is not a problem in Xenial
> ceph-deploy-pull-requests: project does not need 2.6 anymore

- bz-mill/config/definitions/bz-mill.yml
- ceph-dev-build/config/definitions/ceph-dev-build.yml
- ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml
- nfs-ganesha/config/definitions/nfs-ganesha.yml
Enables discarding builds after 90 days for a few projects that were just keeping them for ever. 
Once these are in control, we can try and see what others can this be applied. I picked only the top 4 which were beyond 4,000 jobs
> Discard builds for jobs

- kernel/build/setup
Kconfig lexer and parser are built from real .l and .y since 4.16.
> kernel: install flex and bison

- ceph-volume-test/config/definitions/ceph-volume-test.yml
This job will allow a user to input ceph branch, ceph sha1 and
ceph-ansible branch and from that will start all ceph-volume tests using
those values.
> ceph-volume-test: a job that starts all ceph-volume functional tests

- ceph-container-build-push-imgs/build/build
- ceph-container-build-push-imgs/config/JENKINS_URL
- ceph-container-build-push-imgs/config/definitions/ceph-container-build-push-imgs.yml
After a PR is merged we trigger a build and a push the newly built
images to the Docker Hub.
> ceph-container: add job to build and push images

- ceph-container-build-push-imgs/build/build
Let's execute a script in the ceph-container project instead of writting
the script here.
ceph-build does the CI so let's keep it that way.
> ceph-container-build-push-imgs: use a script from ceph-container

- shaman-pull-requests/setup/playbooks/tasks/postgresql.yml
Fixes:
>       conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
E       OperationalError: (psycopg2.OperationalError) fe_sendauth: no password supplied
> shaman-pull-requests allow users to connect locally over ipv6 sans password

- ceph-volume-ansible-prs/build/build
- ceph-volume-pr/build/build
- ceph-volume-pr/build/teardown
- ceph-volume-pr/config/definitions/ceph-volume-pr.yml
- scripts/build_utils.sh
This allows the ceph-volume tox tests to be run manually but still report back to an open PR with the results of the test.
> ceph-volume-pr: trigger tox tests manually

- ceph-ansible-nightly/build/teardown
- ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
- ceph-ansible-prs/build/teardown
- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
- ceph-ansible-scenario/build/teardown
- ceph-ansible-scenario/config/definitions/ceph-ansible-scenario.yml
- ceph-volume-ansible-prs/build/teardown
- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
- ceph-volume-nightly/build/teardown
- ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
- ceph-volume-scenario/build/teardown
- ceph-volume-scenario/config/definitions/ceph-volume-scenario.yml
- scripts/build_utils.sh
The following jobs will now collect ceph logs from all testing vms and archives them in jenkins when testing fails:
- ceph-volume-scenario
- ceph-volume-ansible-prs
- ceph-volume-nightly
- ceph-ansible-prs
- ceph-ansible-scenario
- ceph-ansible-nightly
You can access these logs in the Jenkins UI. Logs will be found under the 'build artifacts' section, you can see them on this job as an example: https://jenkins.ceph.com/job/ceph-volume-scenario/116/
> Archive ceph logs when CI tests fail

- ceph-container-build-push-imgs/config/definitions/ceph-container-build-push-imgs.yml
We want to parallelise the build image process. Currently it takes 40min
to build 8 images, we hope to reduce this by 8 with this new flavor.
> ceph-container-build-push-imgs: use a bigger machine to build images

- ceph-ansible-nightly/build/build
Instead of sending a commit each time we build a new release, we
discover it through the script.
> ceph-ansible-nightly: auto discover latest stable tag

- ceph-ansible-nightly/build/build
Docker Hub API when queried only returns the 10 first tags. This is
annoying but we have to:
* count the number of pages
* query all the tag from each page
* build a variable with all the tags
* transform this variable in an array
* sort the array
* pick the last element of the array which corresponds to the latest
stable tag
I could have done that with a loop (for luminous and jewel) but assigned
variable in array's name is a nigthmare in bash so I ended up doing
twice the same thing...
This is not elegant but it works.
> ceph-ansible-nightly: fix find for latest stable tag

- jenkins-job-builder/build/build
It was pinned to a beta release in https://github.com/ceph/ceph-build/commit/4f10012571b120e01854fae49be4d43f382787f1 so we could take advantage of an option that wasn't available in the stable version.
It's now in the stable version so we can pin to latest stable.
> jenkins-job-builder: Unpin JJB version

- sepia-fog-images/README.rst
- sepia-fog-images/build/build
I've observed deployment failures while teuthology jobs are running if
the OS image is replaced/removed while it's in use.  Pausing the queue
will allow Deploy tasks to finish so we can capture a new OS image
without interrupting running jobs.
> sepia-fog-images: Add retry function and pause the queue

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
- ceph-container-prs/config/definitions/ceph-container-prs.yml
I think JJB was previously not sending 'jenkins do not test' as the skip
build phrase so the plugin default 'skip ci' was being used and
working.  Since we recently updated JJB, I'm guessing 'jenkins do not
test' *is* being configured so 'skip ci' is no longer working.  This
commit should allow either phrase to be used.
> ceph-{ansible,container}-prs: Fix skip-build-phrase

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
- ceph-container-prs/config/definitions/ceph-container-prs.yml
JJB converts the string to lowercase so the \W was getting converted to
\w so the actual phrase wasn't being detected.  We can just use a space
instead of trying to match any character.
https://git.openstack.org/cgit/openstack-infra/jenkins-job-builder/tree/jenkins_jobs/modules/triggers.py#n1027
> ceph-{ansible,container}-prs: Fix skip-build-phrase regex

- ceph-volume-nightly/build/teardown
Otherwise it was looking at Vagrantfile which exists at the root, but it is not a valid vagrant dir with boxes running
> ceph-volume-nightly: look for the ssh config file to avoid using the root dir

- ceph-container-flake8/build/build
When running the flake8, it's really important to reuse project's
tox.ini to insure the CI is testing the code with the same configuration
unless that brings to a situation where a local flake pass and the CI
fails.
> ceph-container-flake8: Using project's tox.ini

- ceph-container-flake8/build/build
tox.ini is located at the root of the project, so in $workspace/ceph-container
> ceph-container-flake8: Fixing tox.ini path

- ceph-container-build-push-imgs/config/definitions/ceph-container-build-push-imgs.yml
docker-hub-leseb is defined as a credential on 2.jenkins.ceph.com
> container: add docker hub credential binding

- ceph-container-build-push-imgs-arm64/build/build
- ceph-container-build-push-imgs-arm64/config/JENKINS_URL
- ceph-container-build-push-imgs-arm64/config/definitions/ceph-container-build-push-imgs-arm64.yml
We need to build container images on arm64.
> add ceph-container-build-push-imgs-arm64

- ceph-volume-scenario/config/definitions/ceph-volume-scenario.yml
So that we can alternatively use ceph-ci.git
> ceph-volume-scenario: configurable ceph repo url

- scripts/build_utils.sh
Fixes this problem:
Traceback (most recent call last):
File "/tmp/venv.PiUT4JO97l/bin/pip", line 9, in <module>
load_entry_point('pip==1.4.1', 'console_scripts', 'pip')()
File "/tmp/venv.PiUT4JO97l/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/tmp/venv.PiUT4JO97l/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
return ep.load()
File "/tmp/venv.PiUT4JO97l/lib/python2.7/site-packages/pkg_resources.py", line 2265, in load
raise ImportError("%r has no %r attribute" % (entry,attr))
ImportError: <module 'pip' from '/tmp/venv.PiUT4JO97l/lib/python2.7/site-packages/pip/__init__.pyc'> has no 'main' attribute
> scripts: upgrade pip with easy_install before actual pinning

- ceph-container-build-push-imgs-arm64/config/definitions/ceph-container-build-push-imgs-arm64.yml
The arm64 nodes have a 'arm64 xenial' label.
> ceph-container-build-push-imgs-arm64: update node label

- ceph-container-build-push-imgs-arm64/build/build
As ceph-container needs a particular build script for arm64, let's fix
the script name.
> ceph-container-build-push-imgs-arm64: Fixing scripts

- ceph-ansible-nightly/build/build
The job was still configured to test on Ubuntu and we want CentOS.
> ceph-ansible-nightly: always test on centos

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This scenario is failing for every PRs because of a race condition.
A PR has been opened https://github.com/ceph/ceph/pull/21415 but until
it doesn't get merged we better to disable this scenario.
> ceph-ansible-prs: disable purge_bluestore_osds_container

- ceph-build/config/definitions/ceph-build.yml
mimic and nautilus require C++17 to build, but following distro do
not ship new enough GCC compiler:
- ubuntu trusty
- debian jessie
- debian stretch
so we won't build mimic or newer ceph on these distros.
> ceph-build: do not build mimic on old distros

- ceph-build/config/definitions/ceph-build.yml
`GIT_BRANCH` didn't exist, so it wouldn't match and the build would be skipped for everything/anything.
> ceph-build: use BRANCH instead of non-existing GIT_BRANCH

- ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
ceph-volume doesn't have a 'bionic' factor in tox, so there aren't any
functional scenarios to support this. At the moment, there aren't any
ceph packages to test against either. Disabling this for now.
> ceph-volume-nightly: remove bionic

- ceph-pr-commits/build/test_commits.py
Fixes:
```
E               Following commit is not signed, please make sure all commits 
E               are signed following the 'Submitting Patches' guide: 
E               https://github.com/ceph/ceph/blob/master/SubmittingPatches#L61 
```
Signed-off-by: Jos Collin <jcollin@redhat.com>
> ceph-pr-commits/build: Fix Sign your work url

- scripts/build_utils.sh
The wheel's not present in cache so the upgrade fails
> build_utils.sh: Don't update pip after installing it

- scripts/build_utils.sh
At the moment, the teardown isn't fully executed because of `collect-logs.yml`
playbook.
it is expected the following task can fail according to the context of the main failure:
```
TASK [find ceph logs] **********************************************************
task path: /home/jenkins-build/build/workspace/ceph-ansible-scenario/collect-logs.yml:4
fatal: [ceph-nfs0]: FAILED! => {
"changed": true,
"cmd": [
"find",
"/var/log/ceph",
"-name",
"test*.log"
],
"delta": "0:00:00.003363",
"end": "2018-05-23 16:45:22.845782",
"rc": 1,
"start": "2018-05-23 16:45:22.842419"
}
STDERR:
find: ‘/var/log/ceph’: No such file or directory
MSG:
non-zero return code
```
therefore, `teardown_vagrant_tests()` doesn't return `0` and causes the
teardown to stop because of `set -e`
```
PLAY RECAP …
```
> ceph-ansible: fix teardown issue

- scripts/build_utils.sh
as it offers updated binutils which does not exist in the default repo.
and the updated binutils is depended by gcc-7. this change address
following failure like:
The following packages have unmet dependencies:
gcc-7 : Depends: binutils (>= 2.26.1) but 2.26-8ubuntu2 is to be
installed
when installing g++-7.
> build_utils.sh: add ubuntu-ports repo for arm64 build

- scripts/build_utils.sh
related to ceph/ceph-ansible/pull/2665 and ceph/ceph-ansible/pull/2652
We are seeing too many failures related to yum.
These additional tasks will help us to have more information when a yum
failure occurs.
> ceph-ansible: add some tasks for debugging purpose

- scripts/build_utils.sh
these tasks are producing some useless output showing error on debian
based distribution. Let's add a condition to avoid this.
> ceph-ansible: followup on #1036

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This will allow us to test dev installs with a large cluster and many
node types.
> ceph-ansible-prs: adds the dev-ansible2.4-centos7_cluster scenario

- ceph-build-pull-requests/build/build
- scripts/build_utils.sh
When running dev-* tests for ceph-ansible PRs we were setting
CEPH_STABLE_RELEASE to 'dev' which is not an actual release and our
functional tests break because of that.
> build_utils: when running dev-* scenarios set release to nautilus

- scripts/build_utils.sh
it's distracting to read the red alert in jenkins' log like
du: cannot access '/srv/debian-base/xenial.tgz': No such file or
directory
> build_utils.sh: do not try to check non-existent file's size

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This is slowing down CI testing because we can't run more than 1 or 2
PRs at a time. Since I'm not sure if it's still worth to limit these
scenarios to be run only on smithi node, let's try to temporary remove
this limitation.
> ceph-ansible-prs: run 'auto' scenarios on smithi or ovh

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
we are seeing this scenario failing because of the race condition,
moving it to a project which requires smithi nodes should help.
> ceph-ansible: move bluestore_osds_container in ceph-ansible-prs-auto

- ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
- remove testing of stable-2.2 against ceph jewel
- add testing of stable-3.1 against luminous
- update testing of stable-3.0 against luminous:
- remove lvm scenarios
> ceph-ansible: update nightlies definition

- ceph-ansible-pr-syntax-check/build/build
This commit does 2 things:
* split the structure of the script to use functions
* add a function to test if group_vars weren't generated
> ceph-ansible-pr-syntax-check: add group_vars check

- ceph-ansible-pr-syntax-check/build/build
If grep fails the script exits because of the set -e so let's use ||
true to workaround that issue.
> ceph-ansible-pr-syntax-check: fix grep error

- ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml
Not sure why `!!python/unicode` was there originally but the current
version of JJB doesn't like it.
> ceph-pull-requests-arm64: Normalize name to appease JJB

- ceph-pull-requests/config/definitions/ceph-pull-requests.yml
Enable plugin 'Cobertura' to generate code coverage report, for every PR for ceph-dashboard frontend unit test. Cobertura jenkins plugin: https://wiki.jenkins.io/display/JENKINS/Cobertura+Plugin
Fixes: http://tracker.ceph.com/issues/24377
Signed-off-by: Kanika Murarka <kmurarka@redhat.com>
> mgr/dashboard: Adds unit test coverage report

- ceph-pull-requests/config/definitions/ceph-pull-requests.yml
As of today, ccache is installed by run-make-check but the statistics
reports almost no cache it (<1%) and even worse, this is slowing down
the whole process. The needed time to setup the cache isn't compensated
by the reuse of the cache as every build is rebuilding the cache. This
is leading to a 10% loss of the compilation time.
So the question, is why does two consecutives builds doesn't reuse the
cache. Its usually a matter of variables introduces on each builds like
a sha1 or a __DATE__ or __TIME__ in a header.
As per
https://wiki.debian.org/ReproducibleBuilds/TimestampsProposal, several
tools from the tool chain (like compilers or make tools) are able to use
theses variables to enforce a particular timestamp at build time.
This commit also add a "-D ENABLE_GIT_VERSION=OFF" to avoid …
> ceph-pull-requests: Improving ccache efficiency

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
Got my double negatives mixed up.
This job was merging into stable-3.0: https://2.jenkins.ceph.com/job/ceph-ansible-pipeline/304/
This job was merging into master: https://2.jenkins.ceph.com/job/ceph-ansible-pipeline/305/
> ceph-ansible-pipeline: Fix stable-3.0 phase conditional steps

- ceph-pull-requests/config/definitions/ceph-pull-requests.yml
Set `health-auto-update` and `stability-auto-update` to false, as the build failed.
Signed-off-by: Jos Collin <jcollin@redhat.com>
> ceph-build/cobertura: set *auto-update to false

- ceph-ansible-pr-syntax-check/build/build
We now fail if the commits don't contain a Signed-off-by certificate.
> ceph-ansible-pr-syntax-check: add sign-off check

- ceph-pull-requests/config/definitions/ceph-pull-requests.yml
Just tested and clicking 'Rebuild' does carry over the `sha1` variable.
> ceph-pull-requests: Automatically rebuild w/o asking params

- scripts/build_utils.sh
On the jobs that use ceph-ansible to test ceph logs are collected from
the vms on failure. However, if the cluster name was not ceph the find
command would fail to collect any ceph-volume logs.
> scripts: collect all logs in /var/log/ceph on ansible failures

- ceph-ansible-pr-syntax-check/build/build
origin/HEAD does not exist so let's use origin/master instead. This
prevents the following error:
bad revision 'origin/HEAD'
> ceph-ansible-pr-syntax-check: use master instead of HEAD

- ceph-ansible-pr-syntax-check/build/build
When counting the number of commit you must remove the merge commit so
we get the right number of commits.
> ceph-ansible-pr-syntax-check: remove merge commit from count

- ceph-ansible-pr-syntax-check/build/build
This was a leftover from an initial attempt with if combinaison. We now
return 1 only if the test line fails.
> ceph-ansible-pr-syntax-check: return 1 only on failure

- ceph-ansible-pr-syntax-check/build/build
If the test succeeds we return 0.
> ceph-ansible-pr-syntax-check: force return 0

- ceph-pull-requests/config/definitions/ceph-pull-requests.yml
Once https://github.com/ceph/ceph/pull/22847 will be merged, this commit
will remove all the custom hacks from this script as they moved directly
in ./run-make-check.sh
> ceph-pull-requests: Simplifying run-make-check call

- scripts/build_utils.sh
we are running into following error recently
gpg: requesting key BA9EF27F from hkp server keyserver.ubuntu.com
gpgkeys: key 1E9377A2BA9EF27F can't be retrieved
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver helper general error
gpg: keyserver communications error: unknown pubkey algorithm
gpg: keyserver receive failed: unknown pubkey algorithm
so use the local copy of the pubkey instead
> build_utils: import ubuntu-toolchain-r's key without keyserver

- scripts/build_utils.sh
> build_utils: should not use "sudo" in pbuilder hook script

- sepia-fog-images/build/failure
We don't need to mark the systems down.  If there's something wrong with
them, we'll find it during teuthology tests.
I also forgot to unpause the queue in the event of a job failure so I've
added that too.
> sepia-fog-images: Unpause queue and leave systems up

- ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
- scripts/build_utils.sh
We'll set the ansible version in each ceph-ansible branch's respective
requirements.txt.
For example, master will use ansible2.5 and stable-3.{1,2} will use ansible2.4.
The only reason the ansible version was in each scenario name was so it
could get passed to tox.
> ceph-ansible: Stop hardcoding ansible version in scenarios

- ceph-ansible-prs/build/build
`$scenario` gets set by the last iteration in the loop above.
The actual value we want is `$SCENARIO`.
> ceph-ansible-prs: fix a typo

- ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
stable-3.0 => jewel,luminous
stable-3.1 => jewel,luminous,mimic
master     => dev (last sha1 on master)
This also removes `xenial_cluster` scenario on PRs and leave it played in nightly.
> ceph-ansible: update the testing matrix

- ceph-ansible-pr-syntax-check/build/build
One of our convention in ceph-ansible is to not use capital letters in
task's name. So let's hardcode it in the initial phase of the pipeline.
ALso, this will let user discover what's wrong without us doing the
review and finding the problem.
> ceph-ansible-pr-syntax-check: add cbheck for coding convention

- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
This was causing issues in tox, where '-' is used as a delimiter, and it is now being updated on the PR that introduces batch tests ( https://github.com/ceph/ceph/pull/23532 )
> ceph-volume-ansible-prs: use underscores for scenarios

- ceph-ansible-pr-syntax-check/build/build
The git show was returning - and + lines, we only want to check for
lines that were added not removed.
> ceph-ansible-pr-syntax-check: do not check for removed lines

- ceph-ansible-pr-syntax-check/build/build
There is no reason to pin to an old ansible version. Since this is doing
syntax checking we should have the latest Ansible version to compare
against our latest ceph-ansible code.
> ceph-ansible-pr-syntax-check: use latest ansible version

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
We now play the OSD scenarios only when
roles/ceph-defaults/tasks/facts.yml|roles/ceph-osd|ceph-validate are
touched.
> ceph-ansible-pipeline: reduce pipeline workload

- ceph-volume-ansible-prs/build/build
- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
In https://github.com/ceph/ceph/pull/23697 we've made a change so that we can rsync the ceph-volume code to the testing vms instead of waiting for a repo to be built. The ceph-volume tests rarely need a build, so this allows us to test faster and avoid waiting for a repo to be built for each change we make to a ceph-volume PR.
This also disables the centos7 tests because we're having infrastructure issues. When those have been resolved we'll enable them again.
> ceph-volume: deploy the target branch, not the source branch

- ceph-build/build/build_deb
- ceph-dev-build/build/build_deb
- ceph-dev-new-build/build/build_deb
- ceph-pull-requests-arm64/build/build
- ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml
- scripts/build_utils.sh
guess we are using more compile-time optimizations now, to compile
ceph source requires more memory. sometimes, a single cc1plus takes
more than 3GB memeory. that's why we are seeing more and more OOM
in our arm64 builders. following is a sample from omani09 -- a
arm64 builder compiling a ceph/ceph PR targeting master:
```
30474 jenkins+  20   0 2573092 2.388g  16220 R 100.0  3.8   9:11.04 cc1plus
34339 jenkins+  20   0 3279768 3.005g  16296 R 100.0  4.8   5:07.63 cc1plus
36382 jenkins+  20   0  322276 278932  12740 R 100.0  0.4   0:09.78 cc1plus
...
```
also, the performance of over-all compiling is also impacted by the I/O
subsystem. so lower the number of job could actually reduce the time
of the compiling processes to completing for the I/O queue of local
device. so we can use an …
> ceph-pull-requests-arm64: set jobs number according to free memory

- ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
Running the tests on Centos 7.4 hosts allows the vagrant vms
to boot properly.
See:
https://github.com/ceph/mita/pull/126/commits/35d53b13e177831306b0b401b0b5d0fafecf4b78
> ceph-volume-ansible-prs: enable tests on centos 7

- ceph-ansible-pr-syntax-check/build/build
The directory we are looking for is called group_vars not group_var
> ceph-ansible-pr-syntax-check: fix typo

- ceph-ansible-pr-syntax-check/build/build
When defaults/main.yml is touched we will generate 2 group_vars files,
one for all.yml.sample and one for rhcs.yml.sample, this is making the
conditional never pass since there is one more value in the count.
Basically if defaults/main.yml and osd/defaults/main.yml are touched
this will result in 3 group_vars file but the count for
defaults/main.yml is 2.
In the end we want to fail if the number of defaults/main.yml is
greather than the number of group_vars files.
> ceph-ansible-pr-syntax-check: group_vars operator

- ansible/examples/slave.yml
- ansible/slave.yml
I'm not sure why we're just now seeing this.  Perhaps it was manually
fixed on prado.ceph.com and a redeploy overwrote it?  Regardless
non-libvirt slaves are failing to join Jenkins currently.
> ansible: Install python-pip from epel on centos slaves

- scripts/build_utils.sh
there is chance that the system is under extremely high load when `vmstat`
is called. so the "free memory" can not reflect the available memroy
when building Ceph. so use "total memory" instead.
> ceph-*-build: evaluate num jobs using total mem not free mem

- ceph-medic-tests/config/definitions/ceph-medic-tests.yml
There is currently no active development on the project and the nightly tests are thoroughly broken from changes in ceph-ansible.
> ceph-medic-tests: disable nightly tests

- ceph-pr-arm-trigger/config/definitions/ceph-pr-arm-trigger.yml
- ceph-pr-commits/config/definitions/ceph-pr-commits.yml
- ceph-pr-submodules/config/definitions/ceph-pr-commits.yml
- ceph-volume-scenario/config/definitions/ceph-volume-scenario.yml
- ceph-volume-test/config/definitions/ceph-volume-test.yml
So that it isn't limited by the number, it is limited by days only. This
will allow builds to avoid 404'ing when the limit is reached, which is
unexpected if there are too many builds and not long enough time between
them (like 100 builds in one day, but limit is 20 before discarding)
> Change build discard options for ceph and ceph-volume jobs

- ceph-container-nighlity/config/definitions/ceph-container-nightly.yml
- ceph-container-prs/config/definitions/ceph-container-prs.yml
No longer tested on Ubuntu: https://github.com/ceph/ceph-container/pull/1167
> ceph-container: Don't test Ubuntu

- ceph-volume-pr/config/definitions/ceph-volume-pr.yml
So that tox tests can be triggered manually (or via de CLI). Already working nicely for ceph-volume PRs
> ceph-volume-pr: add the TargetBranch param for manually triggering it

- ceph-pr-commits/build/test_commits.py
Relevant changes:
- All non-compliant commits are reported (previously, only the first
wrong one was reported, stopping further processing).
- Signed-off-by regex put in place to check for
<something@somewhere.tld> (including lt and gt symbols). This rule
could be relaxed, as some commits in the past were sent without
the enclosing <...>
Fixes: http://tracker.ceph.com/issues/36082
> ceph-pr-commits: Fix check with many-commit PRs

- ceph-pr-commits/build/test_commits.py
Reverts ceph/ceph-build#1125
Just deployed... and failed! I'll revert this while I look for the failure reason.
```
>           raise CalledProcessError(retcode, cmd, output=output)
E           CalledProcessError: Command '['git', 'log', '-E', '--invert-grep', '--grep=Signed-off-by: \\S.* <[^@]+@[^@]+\\.[^@]+>', '--no-merges', 'origin/luminous..HEAD']' returned non-zero exit status 128
```
> Revert "ceph-pr-commits: Fix check with many-commit PRs"

- ceph-pr-commits/build/test_commits.py
Reverts ceph/ceph-build#1128
This time is because git version running in Jenkins does not recognize `--invert-grep` (https://jenkins.ceph.com/job/ceph-pr-commits/50235/console):
> fatal: unrecognized argument: --invert-grep
> Revert "ceph-pr-commits: Fix check with many-commit PRs (2nd try)"

- ceph-pr-commits/build/test_commits.py
Relevant changes:
- All non-compliant commits are reported (previously, only the first
wrong one was reported, stopping further processing).
- Signed-off-by regex put in place to check for
<something@somewhere.tld> (including lt and gt symbols). This rule
could be relaxed, as some commits in the past were sent without
the enclosing <...>
- `extract_sha` function has been removed
Tested with:
- **NOW!!**: Tested in CentOS 7 (hopefully Xenial versions for python/git won't be so different).
- PR: https://github.com/ceph/ceph/pull/24026
- `CWD=/tmp`
- `WORKSPACE=$HOME/git`
- `ghprbTargetBranch=luminous` (passes, as expected)
- `ghprbTargetBranch=master` (fails, as expected, due to release commits '12.2.x' by Jenkins, which are unsigned)
Fixes: http://tracker.ceph.com/issues/36082
Fixes: …
> ceph-pr-commits: Fix check with many-commit PRs (3rd try)

- scripts/build_utils.sh
it's observed that on our arm64 build host, using the existing
$total_mem/1600, n_build_jobs=37 . but we still have following error
when compiling Ceph:
virtual memory exhausted: Cannot allocate memory
make[3]: *** [src/mds/CMakeFiles/mds.dir/SnapClient.cc.o] Error 1
so increase the denominator to 2200 .
> scripts/build_utils.sh: increase mem per job to 2.2GB

- ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
- ceph-dashboard-pull-requests/setup/setup
This Jenkins job should be triggered for pull-requests labeled with "dashboard" and should execute the frontend (e2e) tests.
To be able to execute the tests it's required to have a browser installed (in this case Google Chrome).
The "[ceph-dashboard-pull-requests.yml](https://github.com/ceph/ceph-build/blob/master/ceph-pull-requests/config/definitions/ceph-pull-requests.yml)" is based on the ceph-pull-requests.yml file with some modifications.
``Signed-off-by: Laura Paduano lpaduano@suse.com``
> ceph-dashboard-pull-requests: Jenkins job for ceph dashboard frontend (e2e) tests

- ceph-dashboard-pull-requests/setup/setup
Tested the new ceph dashboard PR Jenkins job but it failed due to ``/tmp/jenkins8880402979419294012.sh: line 5: /etc/apt/sources.list.d/google-chrome.list: Permission denied``
see: https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/1/console
Also added missing ``sudo`` in some other lines since it would probably fail with the same error.
> ceph-dashboard-pull-requests: fix permission denied error

- ceph-dashboard-pull-requests/setup/setup
Jenkins job failure:
``+ apt-key add linux_signing_key.pub
ERROR: This command can only be used by root.``
see: https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/2/console
> ceph-dashboard-pull-requests: fix another permission denied issue

- ceph-dashboard-pull-requests/setup/setup
Note: this needs to be tested by triggering the Jenkins job (seems to work for the deb repository though), if it does not work I have to revert this change.
> ceph-dashboard-pull-requests: switch to https for Chrome URLs

- scripts/build_utils.sh
some mirrors do not contains the package description translations. when
apt tries to download the packages descriptions, it fails like:
E: Failed to fetch
http://mirror.yandex.ru/mirrors/launchpad/ubuntu-toolchain-r/dists/xenial/main/i18n/Translation-en
404  Not Found [IP: 213.180.204.183 80]
E: Some index files failed to download. They have been ignored, or old
ones used instead.
for more info, see sources.list(5) and apt.conf(5). the default value
of "lang" is set by Acquire::Languages, which is in turn "en" and
"environment" by default. we need to override them with "none".
Fixes #1136
> scripts/build_utils.sh: add lang=none option to sources.list

- ceph-container-build-ceph-base-push-imgs/build/build
- ceph-container-build-ceph-base-push-imgs/config/JENKINS_URL
- ceph-container-build-ceph-base-push-imgs/config/definitions/ceph-container-build-push-imgs.yml
This job runs on a daily basis and is responsible for building ceph/base
versionned images.
> add new ceph-container-build-ceph-base-push-imgs job

- ceph-container-build-ceph-base-push-imgs/build/build
We need to pass the ARCH so the build can successfully run.
> ceph-container-build-ceph-base-push-imgs: build with arg

- sepia-fog-images/build/build
- sepia-fog-images/config/definitions/sepia-fog-images.yml
This change ensures I don't have to add or remove if statements in
funSetProfiles function any time there's a new distro version released.
> sepia-fog-images: Don't hardcode distros

- scripts/build_utils.sh
Let's try to get ceph configuration file on failure, it can be useful at
some point.
> ceph-ansible: fetch ceph config file on failure

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
The code is not ideal and might be hard to read but the rationales are
the following:
* master ceph-ansible has fully adopted ceph-volume and we are about to
remove ceph-disk too
* this means we can not and should not run ceph-disk tests on master BUT
only on stable 3.0 and 3.1 branches.
Only lvm scenarios should play on ceph-ansible master.
> ceph-ansible pipeline branch improvement

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
The job name is ceph-ansible-prs-luminous-lvm_osds_container
> ceph-ansible fix job typo in pipeline

- ceph-ansible-pr-syntax-check/build/build
install the ansible version corresponding to its respective ceph-ansible
ansible.
> ceph-ansible: install expected ansible version

- scripts/build_utils.sh
`ceph_conf_key_directory` doesn't exist in this playbook.
All our testing is done with '/etc/ceph', let's hardcode it here.
> ceph-ansible: fix collect ceph config task

- ceph-container-build-ceph-base-push-imgs-arm64/build/build
- ceph-container-build-ceph-base-push-imgs-arm64/config/JENKINS_URL
- ceph-container-build-ceph-base-push-imgs-arm64/config/definitions/ceph-container-build-push-imgs.yml
Same as ceph-container-build-ceph-base-push-imgs but to build arm64
images.
> add ceph-container-build-ceph-base-push-imgs-arm64

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
Do not play twice osds if they have been ack by the first task of the
pipeline.
> ceph-ansible-ci: do not run osd twice

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
if grep report 0 ceph-osd was modified thus we exit
> ceph-ansible-pipeline: fix wrong condition

- ceph-dashboard-pull-requests/setup/setup
Testing a fix which worked for my local environment when running vstart (was able to reproduce the same error which is currently occurring in the Jenkins job, see e.g. https://jenkins.ceph.com/job/ceph-dashboard-pull-requests/21/consoleFull, tested different PRs and it always failed with the same error):
``/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/build/bin/ceph-mgr -i y -c /home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/build/ceph.conf 
/home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/build/bin/ceph -c /home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/build/ceph.conf -k /home/jenkins-build/build/workspace/ceph-dashboard-pull-requests/build/keyring tell mgr dashboard ac-user-create admin admin administrator``
``no …
> ceph-dashboard-pull-requests: install python3 packages

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
adding `add_osds` and `add_osds_container` to the ceph-ansible pipeline
> ceph-ansible: add "add_osds" scenarios to pipeline

- ceph-volume-scenario/config/definitions/ceph-volume-scenario.yml
We are currently having troubles running test on our OVH nodes. This
locks these tests to smithi nodes for now so we can do some testing for
12.2.9.
> ceph-volume-scenario: lock tests to smithi nodes

- ceph-container-build-ceph-base-push-imgs-arm64/build/build
Run manifest script after the arm64 build is complete.
> ceph-container-build-ceph-base-push-imgs-arm64: run manifest script

- ceph-container-build-ceph-base-push-imgs-arm64/build/build
- ceph-container-build-ceph-base-push-imgs/build/build
> ceph-container-build-ceph-base-push-imgs: install jq

- ceph-ansible-pr-syntax-check/build/build
it can be useful to see which files have matched in `group_vars_check()`
function.
I'm currently facing an issue where the CI complains on that check while
it doesn't on an other environment when trying to reproduce the issue.
on the CI:
```
+ group_vars_check
++ match_file /defaults/main.yml
++ git_diff_to_head
++ wc -l
++ git diff origin/master..HEAD -- . ':(exclude)roles/*/meta/*'
++ sed -n 's|^+++.*\(/defaults/main.yml.*\)|\1|p'
+ nb=1
+ [[ 1 -eq 0 ]]
++ match_file group_vars/
++ wc -l
++ git_diff_to_head
++ git diff origin/master..HEAD -- . ':(exclude)roles/*/meta/*'
++ sed -n 's|^+++.*\(group_vars/.*\)|\1|p'
+ nb_group_vars=0
+ [[ 1 -gt 0 ]]
+ echo 'One or more files containing default variables has/have been modified.'
One or more files containing default variables has/have been …
```
> ceph-ansible-syntax: display matched files in group_vars_check

- ceph-ansible-pr-syntax-check/build/build
when running this code locally for debugging purposes, the sed in
`match_file()` won't match the pattern because of the ANSI codes inserted by
the git diff (colored) output.
> ceph-ansible-syntax: disable syntax coloration in `git_diff_to_head()`

- ceph-medic-tests/config/definitions/ceph-medic-tests.yml
I guess these needed to be disabled as well. ceph-medic is not under development anymore
> ceph-medic-tests: disable all child jobs from template

- ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
since recent updates and 3.2 is out, we should update the matrix of
testing for nightlies jobs.
> ceph-ansible: update nightlies job

- ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
and changed 'only-trigger-phrase' to be able to automatically
start this Job for all dashboard PRs
https://docs.openstack.org/infra/jenkins-job-builder/triggers.html#triggers.github-pull-request
> ceph-dashboard-pull-requests: added 'white-list-labels'

- ceph-volume-ansible-prs/build/build
- ceph-volume-nightly/build/build
- ceph-volume-scenario/build/build
This should allow ceph-volume tests to work. PR https://github.com/ceph/ceph-ansible/pull/3199 made it so that any/all tests should have `python-netaddr` installed
> ceph-volume ansible jobs need python-netaddr installed in the controlling node

- ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
Currently the manual trigger "jenkins test dashboard" does not trigger a new job anymore.
Not sure if this is related to removing the ``only-trigger-phrase`` line or if it's related to the ``white-list-label`` line I've recently added. This PR is just a test to see if it makes a difference when the ``only-trigger-phrase`` line is still present.
> ceph-dashboard-pull-requests: re-add 'only-trigger-phrase'

- ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
This might be just a temporary change - if this change does not fix anything I'll revert it again.
Currently the Job does not work anymore (manual/automated trigger).
Updated based on: https://docs.openstack.org/infra/jenkins-job-builder/triggers.html#triggers.github-pull-request
> Changed config of 'white-list-label'

- ceph-dashboard-pull-requests/setup/setup
Since the JWT PR [#22833](https://github.com/ceph/ceph/pull/22833) has been merged  a new dependency has been introduced which is now missing for the dashboard Jenkins job.
This PR adds the python-jwt dependency.
> ceph-dashboard-pull-requests: add new python-jwt dependency

- ceph-ansible-pr-syntax-check/build/build
Only check for Modified and Changed content, anything else is irrelevant
especially remove, rename and will make the check fail.
> ceph-ansible syntax check

- ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
Since there are currently issues with the dashboard job and its dependencies (python-jwt)
when the test node is based on trusty (and Nautilus has dropped the support for trusty)
it makes sense to switch to a more recent Ubuntu version
> ceph-dashboard-pull-requests: switch node type from trusty to xenial

- nfs-ganesha-stable/build/build_deb
- nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml
- nfs-ganesha/build/build_deb
various fixes to nfs-ganesha-stable deb building
update stable config defaults
add removal of old ceph packages from pbuilder
to normal nfs-ganesha debian job
> nfs-ganesha: fix debian stable build

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
We must test corresponding ceph release for each stable branch of
ceph-ansible.
> ceph-ansible-pipeline: update pipeline matrix

- ceph-ansible-pr-syntax-check/build/build
We need to fetch origin to always ensure we have the right version.
> ceph-ansible-pr-syntax-check: always fetch origin

- ceph-volume-ansible-prs/build/build
- ceph-volume-nightly/build/build
PR https://github.com/ceph/ceph-ansible/pull/3312 caused backwards incompatible changes when using ceph-ansible master branch. It is now required to use stable-3.2 when luminous and mimic ceph branches are targeted.
> ceph-volume: pick stable-3.2 ceph-ansible branches 

- ceph-volume-nightly/build/build
It is causing the following which is wrong (defaulting to master):
+ [[ '' == \m\i\m\i\c ]]
+ [[ '' == \l\u\m\i\n\o\u\s ]]
+ CEPH_ANSIBLE_BRANCH=master
+ VAGRANT_RELOAD_FLAGS='--debug --no-provision'
+ CEPH_ANSIBLE_BRANCH=master
+ CEPH_DEV_BRANCH=mimic
> ceph-volume-nightly check against CEPH_BRANCH, not CEPH_DEV_BRANCH

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
add-osds and add-osds-containers scenarios were not working as expected
in the CI regarding the destination branch.
This commits fixes the scenarios that should be run accoding to the
destination branch.
> ceph-ansible: fix pipeline on add-osds/rgw-multisite scenarios

- ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
In order to be able to get to the step where the dashboard end-to-end tests
are being executed (which seem to pass on centos) the proposal is to temporary remove
the Ubuntu nodes.
When the current issues with Ubuntu have been fixed the plan is to
re-add Ubuntu (xenial) again to the configuration of this Jenkins job.
Since the job is being triggered automatically it would also prevent failing
jobs (which currently happens all the time and is eating up resources).
@tchaikov pointed me to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84428 wrt to the current failures of the job.
For example, see: https://jenkins.ceph.com/view/all/job/ceph-dashboard-pull-requests/94/console
> ceph-dashboard-pull-requests: Temporary remove Ubuntu node(s)

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
filestore|bluestore old osds scenarios shouldn't be run when branch is
stable-3.2
> ceph-ansible-pipeline: remove old scenario from stable-3.2 tests

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
container_podman must run on every PR as it's the same scenario as
docker but using podman.
> ceph-ansible: add container_podman to the pipeline

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
Add scenario purge_lvm_osds_container for master branch.
Only run scenario for corresponding purge playbook (container vs. non
container).
Corresponding ceph-ansible PR: ceph/ceph-ansible#3395
> ceph-ansible-pipeline: add purge_lvm_osds_container scenario

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Add purge_lvm_osds_container definition to the existing list of PRs that
are automatically triggered in the pipeline.
> ceph-ansible: add purge_lvm_osds_container to PRs

- teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
Not sure if there was a default that used to work in the past but this
field was blank in the Jenkins web UI and I had to set it before commenting
'jenkins test' triggered a build.
> teuthology-PRs: Add trigger phrase

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
Reintroduce the purge_cluster_non_container and purge_cluster_container
scenario for stable-3.2 and master (somehow they got removed...)
Don't play dev-purge_lvm_osds on stable-3.2
> ceph-ansible-pipeline: update pipeline

- ceph-ansible-docs/config/definitions/ceph-ansible-docs.yml
Let's build the upstream documentation for stable-3.1 and stable-3.2
Closes: ceph/ceph-ansible#3224
> ceph-ansible-docs: build doc for stable-3.1 and stable-3.2

- ceph-volume-ansible-prs/build/build
- ceph-volume-nightly/build/build
- ceph-volume-scenario/build/build
This was wrongly assumed, netaddr required to be installed in the
virtualenv, and that is the case now. This is no longer necessary, so
removing
> ceph-volume jobs: remove installation of python-netaddr

- ceph-build/build/setup_rpm
- ceph-dev-build/build/setup_rpm
- ceph-dev-new-build/build/setup_rpm
as centos-sclo-rh-source leads us to 404 at this moment. and we are not
using the source repo for building ceph. so we can just skip any
unavailable repo.
Fixes: http://tracker.ceph.com/issues/37707
> ceph-*-build: skip unavailable repo when yum-builddep

- ceph-tag/build/build
There was an issue with pynacl (I think) not having a wheel for the latest version.  Despite manually downloading the required (newer) version in a separate pip transaction, pip would still download the old version and try to use it when installing ansible which broke the build.
> ceph-tag: Use binaries

- nfs-ganesha/build/build_deb
There are occasional problems with failures in "apt-get update" because of the yandex.ru mirror. This just tweaks the command so we don't fail when the mirror is not available.
Similar to: https://github.com/ceph/ceph-build/pull/940/files
Signed-off-by: Thomas Serlin <tserlin@redhat.com>
> nfs-ganesha: minor apt-get update tweak for build_deb

- nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml
Allow building for Ubuntu 18.04 in jenkins.ceph.com.
Up till now, we've only done Xenial builds for nfs-ganesha-stable. Here's an example of a successful build:
https://jenkins.ceph.com/job/nfs-ganesha-stable/213/
Signed-off-by: Thomas Serlin <tserlin@redhat.com>
> nfs-ganesha-stable: enable Ubuntu Bionic builds

- ceph-ansible-prs/build/build
- scripts/build_utils.sh
This is a wrapper to be able to run scripts with tox that contain
shebang with more than 127 char.
> build_utils: add a wrapper for tox in ceph-ansible

- scripts/build_utils.sh
variable are interpreted which is not what we want.
> do not interpret variables in write_exec_cmd_script()

- ceph-ansible-prs/build/build
- scripts/build_utils.sh
revert previous approach and simply use tox with `--workdir`
> build_utils: revert previous approach to get around shebang limitation

- ceph-ansible-docs-prs/config/definitions/ceph-ansible-docs-prs.yml
- ceph-ansible-pr-syntax-check/config/definitions/ceph-ansible-pr-syntax-check.yml
Sometimes, a ceph-ansible PRs are stuck because no OVH nodes are available
while a lot of smithi node aren't busy at all. It's not worth it to block a PR
just because of jobs which take usually less than 2min to be done.
> ceph-ansible: allow doc and syntax job to be run on smithi node

- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
let's make this scenario based as a 'non_container' one so tox.ini will
set right values for`CEPH_ANSIBLE_VAGRANT_BOX` and `PLAYBOOK`.
> ceph-ansible: isolate switch_to_container scenario

- ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
Added "black-list-target-branches" to triggers to avoid an automated
run of the job on PRs targeting luminous.
Note: For some reason the job currently gets randomly triggered on luminous PRs which do not even have the "dashboard" label assigned.
> ceph-dashboard-pull-requests: added blacklist for luminous branch

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
due to recent changes, the scenarios have to be renamed accordingly.
> ceph-ansible: rename basic scenario for stable-3.2

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This commit does the following:
- add an upstream test against rhel8/podman to catch earlier potential
failures.
- refact a bit the pipeline (since there's a check if the scenario
actually exist in build_utils.sh we can define a global matrix).
> ceph-ansible: add rhel8/podman scenario

- ceph-ansible-prs/build/build
- ceph-ansible-prs/build/teardown
This commit clean the fact cache after a run.
Sometimes it might cause issue because ansible thinks the cache is valid
in some cases making some tasks failing.
> ceph-ansible-prs: clean fact cache in teardown

- ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
those jobs aren't available/tested in stable-3.2
> ceph-ansible: remove stable-3.2 nightly jobs

- ceph-ansible-pr-syntax-check/build/build
- scripts/build_utils.sh
ensure the latest version of pip is installed for this job to avoid the
following error:
```
ValueError: ('Expected version spec in', 'ansible~=2.7,<2.8', 'at', '~=2.7,<2.8')
```
> ceph-ansible-pr-syntax-check: get latest version of pip

- ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
This has not been backported into stable-3.2
> ceph-ansible: remove lvm_auto_discovery from stable-3.2

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
add back ubuntu testing on ceph-ansible PRs.
Closes: ceph/ceph-ansible#3590
> ceph-ansible: reintroduce ubuntu testing

- nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml
Update build defaults for the first release of Nautilus (14.1.0).
Also update ntirpc default to 1.7.2.
Signed-off-by: Thomas Serlin <tserlin@redhat.com>
> nfs-ganesha-stable: update defaults for nautilus

- ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
this scenario doesn't exist in stable-3.2
> ceph-ansible: remove add_mons scenario for stable-3.2

- scripts/build_utils.sh
the tox.ini file in ceph-ansible became too big, this commit is a first
step to split this file.
> ceph-ansible: split tox ini file

- ansible/roles/remoto-release/tasks/release.yml
No need for spec file changes for now, since it is being taken care in Fedora. Leaving it commented out because we might want it since EPEL has really old versions for CentOS7
> ansible: remove spec file changes for remoto

- nfs-ganesha/build/build_rpm
We occasionally see "HTTP Error 404 - Not Found" when the jenkins slave tries to contact the EPEL mirrors. Clean up the entire /var/cache/yum/ directory and see if that helps.
Reference: https://wiki.centos.org/yum-errors
> nfs-ganesha: clean out yum cache before build

- ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
- ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Add add_mdss scenario to CI so that it can be tested against master.
Related to [`add-mds.yml` PR](https://github.com/ceph/ceph-ansible/pull/3599).
> add add_mdss scenario to CI

- scripts/build_utils.sh
since a split of the tox ini file has been introduced in ceph-ansible,
we must compare the scenario by listing them in the right tox ini file
according to the scenario being run.
> start_tox: list scenario in the corresponding tox ini file

- nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml
We are currently building a version of nfs-ganesha for nautilus that
lacks many needed patches. Some of those aren't suitable for inclusion
into V2.7-stable, but are already merged for V2.8 (which isn't released
yet).
Switch (at least for now) to building from a custom branch in the
ceph/nfs-ganesha fork.
Signed-off-by: Jeff Layton <jlayton@redhat.com>
> nfs-ganesha: switch to using our own fork for now

- nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml
Now that the first official release of Nautilus is out, set the defaults to 14.2.0.
> nfs-ganesha-stable: update ceph defaults to 14.2.0
