ceph/ceph-build

scripts/build_utils.sh
=> script/build_utils.sh: don't fail if any mirror is not accessible

nfs-ganesha-stable/build/build_rpm, nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml
- set RADOS_URL cmake options ON in rpm build script
- update various config parameters
- ensure removal of any old leftover ceph rpm packages
=> nfs-ganesha-stable: various updates

ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml, ceph-pull-requests/config/definitions/ceph-pull-requests.yml
=> ceph-pull-requests: adds a trigger phrase for make check

ceph-iscsi-cli/build/build_rpm, ceph-iscsi-config/build/build_rpm, ceph-iscsi-tools/build/build_rpm, rtslib-fb/build/build_rpm, tcmu-runner/build/build_rpm
=> iscsi: ensure initial stable release receives proper RPM revision

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
=> ceph-volume-ansible-prs: adds simple dmcrypt_plain and dmcrypt_luks

ceph-volume-nightly/build/build, ceph-volume-nightly/build/teardown, ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
This will run all our PR tests against the luminous and
master branch of ceph nightly.
=> adds nightly functional testing for ceph-volume

tcmu-runner/build/build_rpm
=> tcmu-runner: drop libtcmu-devel RPM

nfs-ganesha-stable/build/build_rpm, nfs-ganesha/build/build_rpm
=> nfs-ganesha: change CMAKE_BUILD_TYPE to Maintainer

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Increase the amount of days to keep for ceph-ansible prs and nightly jobs
Fixes http://tracker.ceph.com/issues/23056
=> ceph-ansible jobs increase daystoKeep for logs to 90

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This commit enable a new 'tripleo deployment' scenario.
ceph-ansible related PR: https://github.com/ceph/ceph-ansible/pull/2407/files
=> ceph-ansible: add tripleo oriented scenario

sepia-fog-images/build/build, sepia-fog-images/build/failure
=> sepia-fog-images: Don't wait for machines to reboot after capture

bz-mill/config/definitions/bz-mill.yml
Because for 90 days it has about 2,300 jobs
=> bz-mill keep just 15 days around of logs

ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
=> ceph-volume-nightly add email notifications

sepia-fog-images/build/build, sepia-fog-images/config/definitions/sepia-fog-images.yml
=> sepia-fog-images: Add support for RHEL

sepia-fog-images/build/build
=> sepia-fog-images: count words in $remaininghosts

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml, scripts/build_utils.sh
=> ceph-dev{,-new}-trigger: do build kraken w/o ppa and on trusty

ceph-volume-nightly/build/build
=> ceph-volume-nightly: add debug flags for vagrant

nfs-ganesha-stable/build/build_rpm, nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml, nfs-ganesha/build/build_rpm
- change CMAKE_BUILD_TYPE to RelWithDebInfo
- include checks to make sure packages are installed
on the machines and necessary FSAL packages are built
- update $CEPH_VERSION to latest luminous
=> nfs-ganesha: change CMAKE_BUILD_TYPE, add checks

sepia-fog-images/README.rst
=> sepia-fog-images: Update setup doc

tcmu-runner/build/build_rpm
=> tcmu-runner: build using in-tree spec file under mock

tcmu-runner/build/build_rpm
=> tcmu-runner: added missing PROJECT environment variable

scripts/build_utils.sh
"pip install --download" was deprecated since v8.0.0, and was replaced
with "pip download". pip v10.0.0 removed support the "--download"
option. so we need to replace "install --dowload" with "download".
=> scripts/build_utils.sh: use "download" instead of "--download"

sepia-fog-images/build/build, sepia-fog-images/config/definitions/sepia-fog-images.yml
=> sepia-fog-images: Add CentOS/RHEL 7.5 support

scripts/build_utils.sh
=> scripts: pin pip to 10.0.0 on missing BASH func

ceph-container-build-push-imgs-arm64/config/definitions/ceph-container-build-push-imgs-arm64.yml
=> ceph-container-build-push-imgs-arm64: fix node label

scripts/build_utils.sh
=> build_utils.sh: Add Bionic

ceph-build/build/setup_deb
=> setup_deb: Forgot bionic

scripts/build_utils.sh
=> build_utils.sh: help bionic to point its gcc back to 7.3

scripts/build_utils.sh
=> build_utils.sh: help bionic to point its gcc back to 7

rtslib-fb/build/build_rpm
=> rtslib-fb: reduce pyudev version requirements

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
this is causing all prs to fail for ceph-volume :(
Should fix the failures for ceph-volume PRs like in https://github.com/ceph/ceph/pull/22116
=> ceph-volume-ansible-prs: remove bionic

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: Don't run auto job if only docs were modified

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
1) Docs and yaml linter (always)
2) Check each infrastructure playbook and run if modified
3) centos7 and docker clusters
4) All other scenarios if basic cluster tests pass
Phases 3 and 4 will NOT be run if infrastructure-playbooks were
modified.
=> ceph-ansible-pipeline: Implement additional phases

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This reverts commit 80f02250028ce5daae6eed3717787732d06302d1.
=> Revert "ceph-ansible-prs: run 'auto' scenarios on smithi or ovh"

ceph-ansible-docs-prs/config/definitions/ceph-ansible-docs-prs.yml, ceph-ansible-pr-syntax-check/config/definitions/ceph-ansible-pr-syntax-check.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
See https://github.com/jenkinsci/ghprb-plugin/issues/608
=> ceph-ansible-*: permit-all to prevent github comment flood

ceph-deploy-build/config/definitions/ceph-deploy-build.yml
=> ceph-deploy-build: remove centos6

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
I think I misunderstood the jjb syntax before.
=> ceph-ansible-pipeline: Only run next phase on SUCCESS

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
=> ceph-ansible-pipeline: Skip *lvm* scenarios if merging into stable-3.0

ceph-iscsi-config-flake8/build/build, ceph-iscsi-config-flake8/config/JENKINS_URL, ceph-iscsi-config-flake8/config/definitions/ceph-iscsi-config-flake8.yml
=> ceph-iscsi-config-flake8: initial version

ceph-iscsi-config-flake8/build/build, ceph-iscsi-config-flake8/config/definitions/ceph-iscsi-config-flake8.yml
=> ceph-iscsi-config-flake8: removed use of docker

ceph-iscsi-config-flake8/config/definitions/ceph-iscsi-config-flake8.yml
=> ceph-iscsi-config-flake8: added context to GitHub PR status

ceph-iscsi-cli-flake8/build/build, ceph-iscsi-cli-flake8/config/definitions/ceph-iscsi-config-flake8.yml
=> ceph-iscsi-cli-flake8: initial version

ceph-ansible-scenario/config/definitions/ceph-ansible-scenario.yml
So we can test a specific docker image.
=> ceph-ansible: add docker params for individual scenario testing

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
=> ceph-volume-ansible-prs: support batch scenarios

ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
=> ceph-volume-nightly add batch tests for master

nfs-ganesha/build/build_rpm
... and install required LTTNG libraries
Signed-off-by: Ramana Raja <rraja@redhat.com>
=> nfs-ganesha: build with LTTNG

ceph-iscsi-stable/README.rst, ceph-iscsi-stable/build/build_rpm, ceph-iscsi-stable/build/failure, ceph-iscsi-stable/build/setup, ceph-iscsi-stable/build/validate_rpm, ceph-iscsi-stable/config/definitions/ceph-iscsi-stable.yml
=> Add job for ceph-iscsi-* stable releases

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
We need this to enable tests for https://github.com/ceph/ceph/pull/23963
=> ceph-volume-ansible-pr: include the batch mixed type tests

ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
=> ceph-volume-nightly: add tests for batch with mixed device types

ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
=> ceph-volume-nightly: add more branches to batch tests

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Add more scenarios for ceph-volume in container
=> ceph-ansible: add more scenarios

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> cpeh-ansible-prs: add lvm_batch scenario

ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph-dev-trigger: include nautilus branch

ceph-ansible-pr-syntax-check/build/build
=> ceph-ansible-pr: fix workspace in syntax check

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
Not sure what's going on, this is mostly a commit to debug
=> ceph-ansible-pipeline osd followup

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Adding new scenarios for "day 2 operation" playbook
=> ceph-ansible: add new scenario 'add_osds'

ceph-volume-scenario/config/definitions/ceph-volume-scenario.yml
I added a few miras as static libvirt slaves.  This builds on https://github.com/ceph/ceph-build/pull/1166
=> ceph-volume-scenario: Also allow building on mira

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml, ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
=> ceph-volume: run all tests on smithi or mira nodes

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
ceph-ansible corresponding PR:
ceph/ceph-ansible#1944
=> ceph-ansible: add rgw_multisite scenario

ceph-iscsi/build/build_rpm, ceph-iscsi/build/setup, ceph-iscsi/build/validate_rpm, ceph-iscsi/config/definitions/ceph-iscsi.yml
=> ceph-iscsi: initial version of combined iSCSI tools repo

ceph-iscsi-tox/build/build, ceph-iscsi-tox/config/definitions/ceph-iscsi-tox.yml, ceph-iscsi-trigger/config/definitions/ceph-iscsi-trigger.yml
=> ceph-iscsi: new PR tox and branch trigger builders

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ceph-ansible-prs: adds the lvm_auto_discovery testing scenario

sepia-fog-images/build/build, sepia-fog-images/build/failure, sepia-fog-images/config/definitions/sepia-fog-images.yml
=> sepia-fog-images: Optionally pause the sepia queue

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml, ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml, ceph-volume-scenario/config/definitions/ceph-volume-scenario.yml
=> ceph-volume: Use DreamCompute instances as slaves

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
this scenario is constantly failing, let's remove it temporarily
=> ceph-ansible-pipeline: remove container_podman temporarily

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml, scripts/build_utils.sh
corresponding ceph-ansible pull-request: ceph/ceph-ansible#3364
- reintroduce ubuntu testing
- rename all scenario
=> ceph-ansible-pipeline: refact ceph-ansible pipeline

scripts/build_utils.sh
=> build_utils: follow up on e5fb7805

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
introduce the same refact in stable-3.2 than the one introduced in
master
=> ceph-ansible: update pipeline for stable-3.2

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
ceph-ansible related PR: https://github.com/ceph/ceph-ansible/pull/3546
=> ceph-ansible: update pipeline for 'containers scenarios only'

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
needed for https://github.com/ceph/ceph-ansible/pull/3492
=> ceph-ansible: adds back lvm_auto_discovery tests to pipeline and prs

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml, ceph-ansible-scenario/build/build, ceph-ansible-scenario/build/teardown
fix all nightly jobs since recent refact in ceph-ansible testing
=> ceph-ansible-nightly: fix nightly jobs (stable-3.2)

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml
=> ceph-ansible: update display name for nightly jobs

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
Update the name for switch_to_containers job for stable-3.2
=> ceph-ansible: update pipeline

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
For ceph-ansible [PR #3547](https://github.com/ceph/ceph-ansible/pull/3547).
=> add add_mons scenario to CI

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
Should be merged once https://github.com/ceph/ceph/pull/26336 goes through (including backports)
=> build tcmalloc flavors only for CentOS7

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
Add testing against ubuntu for purge scenarios
=> ceph-ansible-pipeline: add ubuntu purge testing for PRs on master

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
due to recent changes in ceph-ansible, let's refact all nightly jobs
accordingly in order to fix jobs in jenkins.
=> ceph-ansible: refact nightly jobs

ansible/release.yml, ansible/roles/remoto-release/tasks/clear_version.yml, ansible/roles/remoto-release/tasks/main.yml, ansible/roles/remoto-release/tasks/release.yml
These will end up helping out getting remoto Debian packages. Might want to generalize this at some point, super redundant at the moment.
=> ansible: support remoto packaging for Debian

nfs-ganesha-stable/config/definitions/nfs-ganesha-stable.yml
Signed-off-by: Jeff Layton <jlayton@redhat.com>
=> nfs-ganesha-stable: fix URL in job section of config

ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Retry jobs when we hit an unrelated CI failure.
=> ceph-ansible-prs: retry on CI errors

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml
=> ceph-ansible-pipeline: fix nautilus jobs

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Add add_rgws scenario to CI so that it can be tested against master.
Signed-off-by: Rishabh Dave <ridave@redhat.com>
=> ceph-ansible: add add_rgws scenario to CI

ceph-qa-suite-pull-requests/config/definitions/ceph-qa-suite-pull-requests.yml, teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
Travis has not worked directly on Ceph for a few years.
=> rm trhoden from admin list

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
So the job can update build statuses
=> ceph-dev-new-trigger: Supply SHAMAN_API_KEY

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml, scripts/build_utils.sh
This commit adds a new scenario to test the dashboard deployment.
=> ceph-ansible: add new scenario 'dashboard'

ceph-dashboard-pull-requests/setup/setup
=> ceph-dashboard-pull-requests: Fix repo path

sepia-fog-images/config/definitions/sepia-fog-images.yml
=> sepia-fog-images: Inject IPMI and FOG credentials

ceph-pr-submodules/config/definitions/ceph-pr-commits.yml
Thanks to @tchaikov for pointing me in the right direction
=> ceph-pr-submodules: add trigger phrase

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This commit adds the dashboard scenario to nautilus deployment.
=> ceph-ansible: add dashboard scenario to stable-4.0

scripts/build_utils.sh
let's collect these files in one task instead of two tasks.
By the way, it will avoid undesired failures regarding ceph config files
which don't exist (it first tried ceph.conf > test.conf >
mycluster.conf)
=> ceph-ansible: improve collect ceph config file and logs

ceph-dev-new-setup/build/build, scripts/build_utils.sh
these commits were dropped by accident while doing rebase
=>  ceph-dev-new-setup: missing pieces in PR#1315

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Add shrink_mds scenario to CI so that it can be tested against master.
=> add shrink_mds scenario to CI

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Add shrink_mgr scenario to CI so that it can be tested against master
and nautilus.
=> ceph-ansible: add shrink_mgr scenario to CI

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Add shrink_rbdmirror scenario to CI so that it can be tested against
master and nautilus.
=> ceph-ansible: add shrink_rbdmirror to CI

ceph-ansible-pipeline/config/definitions/ceph-ansible-pipeline.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Add shrink_rgw scenario to CI so that it can be tested against master
and nautilus.
=> ceph-ansible: add shrink_rgw scenario test to CI

ceph-build/build/setup_rpm, ceph-dev-build/build/setup_rpm, ceph-dev-new-build/build/setup_rpm, scripts/build_utils.sh
Fixes: http://tracker.ceph.com/issues/40646
=> ceph-*build/build/setup_rpm: downgrade to gcc-c++-8.2.1

ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
=> ceph-volume: add nautilus to nightly testing

ceph-volume-test/config/definitions/ceph-volume-test.yml
=> ceph-volume: only test simple on mimic and luminous branches

ceph-dev-new/config/definitions/ceph-dev-new.yml, ceph-dev/config/definitions/ceph-dev.yml
=> ceph-dev-*: Clarify job descriptions

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This commit removes some ubuntu job definition which are unused.
=> ceph-ansible: remove unused ubuntu jobs

ceph-volume-test/config/definitions/ceph-volume-test.yml
=> ceph-volume: fix logic when deciding to run simple tests

ceph-volume-test/config/definitions/ceph-volume-test.yml
Hopefully this will be the last tweak here.
=> ceph-volume-test: only run simple tests for luminous and mimic

ceph-build-pull-requests/build/build
=> ceph-build-pull-requests: ping jjb to 2.10.1

ceph-pr-docs/build/build
see also https://github.com/ceph/ceph/pull/29528
=> ceph-pr-docs: install python3 packages

ansible/slave.yml
=> ansible/slave: add opensuse leap15 osc support

ceph-dev-build/config/definitions/ceph-dev-build.yml, ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml
=> leap15: add leap15 to available dist

ceph-iscsi-stable/build/build_rpm, ceph-iscsi-stable/config/definitions/ceph-iscsi-stable.yml
ceph-iscsi-config and ceph-iscsi-cli are now merged into
the ceph-iscsi repo.
=> ceph-iscsi-stable: incorporate consolidated repo changes

ceph-iscsi-stable/build/build_rpm, ceph-iscsi-stable/build/setup
=> ceph-iscsi-stable: query correct chacra host for uploads

ceph-iscsi-stable/config/definitions/ceph-iscsi-stable.yml
=> ceph-iscsi-stable: inject missing credentials

ceph-iscsi-stable/build/build_rpm
=> ceph-iscsi-stable: fix revision to '-1' if building at tag

nfs-ganesha-stable/build/build_deb, nfs-ganesha-stable/build/failure, tcmu-runner/config/definitions/tcmu-runner.yml
Fixes: https://tracker.ceph.com/issues/41877
=> clean up shaman repos left behind after a build

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
remove non breaking space introduced by 54ed76efcf9b956079daf22669dbfc14b6114224
=> ceph-ansible-prs: remove non breaking space

ceph-ansible-pr-syntax-check/config/definitions/ceph-ansible-pr-syntax-check.yml
Automatically run this job on PRs.
=> ceph-ansible-syntax: enable automatic run on PRs

teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
Since only one of the admins responds (gregsfortytwo) and
other do not react to new PRs at all, could please add
me (kshtsk) and Nathan (smithfarm) to admin list so we
can aprove pull requests testing for teuthology.
=> teuthology: add more admins to allow testing pr

ansible/examples/slave.yml, ansible/examples/slave_libvirt.yml, ansible/examples/slave_libvirt_static.yml, ansible/examples/slave_static.yml
=> ansible: Update playbooks for CentOS8 compatibility

ansible/examples/slave.yml, ansible/examples/slave_libvirt.yml, ansible/examples/slave_libvirt_static.yml, ansible/examples/slave_static.yml, ceph-ansible-rpm/build/build, ceph-medic-release/build/build_rpm, ceph-medic-rpm/build/build
Instead of during each individual job
=> Add jenkins-build user to mock group during slave setup

ansible/examples/slave.yml
=> ansible/examples/slave: add leap15

ceph-iscsi-stable/build/setup
=> ceph-iscsi-stable: revert to production chacra instance

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
=> ceph-volume-ansible-prs: remove xenial from PR testing

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This includes:
- add_mdss
- add_mgrs
- add_mons
- add_osds
- add_rbdmirrors
- add_rgws
=> ceph-ansible-prs: re-add add_xxx jobs

quay-pruner/build/build, quay-pruner/build/prune-quay.py, quay-pruner/config/definitions/quay-pruner.yml
=> Add "quay-pruner" to prune stale quay.io container images

ceph-dev-new/config/definitions/ceph-dev-new.yml, quay-pruner/build/prune-quay.py
name change requested by @liewegas
=> ceph-dev-new, quay-pruner: cephci/daemon-base -> ceph-ci/ceph

quay-pruner/build/prune-quay.py
There are two new tags proposed for each image: "branchname" and "full
sha1".  Branchname is currently being created.  When pruning image tags,
we need to prune the associated short tags as well.
This also fixes a current bug where, because branchname tags are being
created, the current unaware prune script deletes them because it
treats "can't parse tagname" as equivalent to "can't find in shaman".
=> quay-pruner/build/prune-quay.py: handle new "short tags"

nfs-ganesha/build/build_deb
This is a follow-up to 888793c4 to 'commit' the patch.
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>
=> nfs-ganesha: dpkg commit source after lizardFSAL patch

nfs-ganesha/build/build_deb
=> Revert "nfs-ganesha: dpkg commit source after lizardFSAL patch"

nfs-ganesha/build/build_deb
This is a follow-up to 888793c4 to 'commit' the patch.
Signed-off-by: Brad Hubbard <bhubbard@redhat.com>
=> nfs-ganesha: Remove lizardFSAL patch

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
Related ceph-ansible PR: ceph/ceph-ansible#4824
=> ceph-ansible-prs: introduce back ceph-disk testing (3.2 only)

scripts/e2e/install-e2e-tests-deps.sh
- https://github.com/ceph/ceph/pull/32151
- https://tracker.ceph.com/issues/43230#note-3
=> ceph-dashboard-pull-requests: Update dependencies

scripts/sign-rpms
=> scripts: use --no-database flag for createrepo

ansible/examples/slave.yml, ansible/examples/slave_static.yml
=> ansible: Install lab-extras and copr repos on EL8

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph-dev{-new}: Build notcmalloc dev packages for centos8

ansible/examples/slave.yml, ansible/examples/slave_static.yml
=> ansible: Adjust `when` statements to put EL8 repos on EL8 only

ceph-iscsi/build/build_rpm, ceph-iscsi/config/definitions/ceph-iscsi.yml
=> ceph-iscsi: add centos8 distro for dev builds

ceph-iscsi/config/definitions/ceph-iscsi.yml
=> ceph-iscsi: switch to huge centos builders

ceph-dev-build/config/definitions/ceph-dev-build.yml
=> ceph-dev-build: Build master on centos8

tcmu-runner/build/build_rpm, tcmu-runner/config/definitions/tcmu-runner.yml
=> tcmu-runner: add centos8 to the available distros

ceph-dev-build/build/setup_rpm
=> ceph-dev-build: setup_rpm Support for CentOS8

tcmu-runner/build/build_rpm
=> tcmu-runner: fix environment variable typo

tcmu-runner/build/build_rpm
=> tcmu-runner: fixed creation of chroot cfg file

ansible/examples/slave.yml, ansible/examples/slave_static.yml, ceph-pull-requests/config/definitions/ceph-pull-requests.yml
https://askubuntu.com/a/381527/906620
=> ansible: Support Ubuntu Bionic slaves

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
=> ceph-dev-new-trigger: "fix" conditional step for all other branches

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
=> ceph-dev-new: Don't build master/wip on xenial

ansible/examples/slave.yml
=> ansible: Install distro-appropriate virtualenv package version

sepia-fog-images/build/build
=> sepia-fog-images: Support openSUSE

ceph-build/build/setup_deb
=> ceph-build: Apply e8bdd639

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
add an 'all in one' scenario in order to catch more collocation related
issues.
=> ceph-ansible-prs: add a new scenario

ceph-build/config/definitions/ceph-build.yml
=> ceph-build: Add octopus

ceph-build/build/setup_rpm
=> ceph-build: Update setup_rpm for CentOS8 support

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml, scripts/build_utils.sh
Add a new job in order to test the external ceph clients scenario
testing.
=> ceph-ansible: add external ceph clients scenario

ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml
=> Disabling ceph-pull-requests-arm64 until we have packages and reliable hw

scripts/build_utils.sh
=> scripts/build_utils.sh: install deps for crimson flavor

ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
=> ceph-volume-nightly: adds mimic and luminous to batch mixed type tests

ceph-dev-build/build/build_rpm, ceph-dev-build/config/definitions/ceph-dev-build.yml, ceph-dev/config/definitions/ceph-dev.yml
=> ceph-dev: Build containers from ceph.git branches

ceph-container-prs/config/definitions/ceph-container-prs.yml
This commit updates the matrix of scenario tested in ceph-container CI.
=> ceph-container-prs: update scenarios matrix

ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
and remove centos7 and xenial from master and nautilus runs.
=> Add nightly support for ceph-volume centos8 tests

ceph-container-prs/config/definitions/ceph-container-prs.yml
This commit refact the job template for ceph-container.
=> ceph-container-prs: refact job template

ansible/examples/slave_libvirt.yml, ansible/examples/slave_libvirt_static.yml
`CONFIGURE_ARGS` for the vagrant-libvirt plugin install came from https://github.com/vagrant-libvirt/vagrant-libvirt/issues/951
=> ansible: Update libvirt slave playbooks to support EL8

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph-dev*trigger: Drop notcmalloc for centos7 on master/wip

scripts/sign-rpms, scripts/sync-pull, scripts/sync-push
=> scripts: Update signing scripts to support CentOS/RHEL8

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This will make ceph-ansible CI using new nodes 'braggi'
=> ceph-ansible: add new slave label 'braggi'

ceph-api-nightly/config/definitions/ceph-api-nightly.yml
=> ceph-api-nightly: Add octopus branch to nightly tests

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph-dev-trigger: include octopus branch

ceph-build/config/definitions/ceph-build.yml, ceph-dev-build/config/definitions/ceph-dev-build.yml, ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml
This may need to change in the future if jobs start getting backed up.  Still trying to find the balance.
=> ceph*build: Only build on new braggi builders

ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph-dev-trigger: Fix regex for master conditional step

ceph-build/config/definitions/ceph-build.yml, ceph-dev-build/config/definitions/ceph-dev-build.yml, ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml
=> ceph*build: Update combination filter for bionic/centos8 ARM64

ansible/examples/slave.yml, ansible/examples/slave_static.yml
=> ansible: Install Buster GPG keys

sepia-fog-images/config/definitions/sepia-fog-images.yml
=> sepia-fog-images: Run automatically every week

ceph-dev-build/build/build_rpm, ceph-dev-new-build/build/build_rpm
=> ceph-dev-*build: build containers as root

ceph-ansible-docs/config/definitions/ceph-ansible-docs.yml
Let's build the upstream documentation for stable-5.0
=> ceph-ansible-docs: build doc for stable-5.0

scripts/dashboard/install-e2e-test-deps.sh
This is needed to run cypress.
=> ceph-dashboard-pull-requests: Install xvfb

ceph-build/build/setup_deb, ceph-build/config/definitions/ceph-build.yml, ceph-dev-build/build/setup_deb, ceph-dev-build/config/definitions/ceph-dev-build.yml, ceph-dev-new-build/build/setup_deb, ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml, ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-new/config/definitions/ceph-dev-new.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml, ceph-dev/config/definitions/ceph-dev.yml, ceph/config/definitions/ceph.yml, kernel/build/build_deb, kernel/config/definitions/kernel.yml, scripts/build_utils.sh
=> Add support for Ubuntu Focal Fossa globally

ceph-build/build/setup_rpm, ceph-dev-build/build/setup_rpm, ceph-dev-new-build/build/setup_rpm
fix syntax error introduced by f934188b6cb95a56fd799ff2806a3f4ce30a9c58
=> ceph-*-*: s/esac/fi/

sepia-fog-images/config/definitions/sepia-fog-images.yml
=> sepia-fog-images: Update defaults

ansible/examples/slave.yml, ansible/examples/slave_libvirt.yml, ansible/examples/slave_libvirt_static.yml, ansible/examples/slave_static.yml
Sometimes that user just doesn't need sudo access y'know?
=> ansible: Optionally disable sudo access for jenkins-build user

scripts/sync-pull, scripts/sync-push
=> scripts: Fix sync-pull so it still supports older than Octopus

ceph-website/build/build, ceph-website/config/definitions/ceph-website.yml
=> Add ceph-website job

ceph-dashboard-pr-backend/config/definitions/ceph-dashboard-pr-backend.yml
=> ceph-dashboard-pr-backend: Auto-run on octopus PRs only

ceph-dashboard-pr-backend/config/definitions/ceph-dashboard-pr-backend.yml
=> ceph-dashboard-pr-backend: Target master too

ceph-dashboard-pr-backend/config/definitions/ceph-dashboard-pr-backend.yml, ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml, ceph-pull-requests/config/definitions/ceph-pull-requests.yml
Ernesto requested this via e-mail
=> ceph-dashboard: Enable ansicolor plugin

ceph-dashboard-pr-backend/config/definitions/ceph-dashboard-pr-backend.yml
=> ceph-dashboard-pr-backend: Target nautilus too

ceph-website/config/definitions/ceph-website.yml
=> ceph-website: white-list adamduncan

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph-dev-new-trigger: build nautilus on el8 also

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
it's a follow-up of f57a522325a61ab8de3a2817729013f7f4a96177
=> ceph-dev-trigger: stop building wip-* on el7

ceph-container-build-push-imgs-devel-nightly/config/definitions/ceph-container-build-push-imgs-devel-nightly.yml
In addition of 61b7b619 we also need to update the FLAVORS env variable.
=> container: update nighly flavors

ceph-container-build-push-imgs-devel-nightly/build/build, ceph-container-build-push-imgs-devel-nightly/config/definitions/ceph-container-build-push-imgs-devel-nightly.yml
We can do this kind of changes directly in ceph-container instead of
doing some kind of hack.
https://github.com/ceph/ceph-container/pull/1696
=> container: revert flavors/releases update

ceph-dev-build/build/failure, ceph-dev-new-build/build/failure
Follow-up to https://github.com/ceph/ceph-build/pull/1603
=> ceph-dev*build: Delete ceph-container dir on failure

ceph-dev-build/build/build_rpm, ceph-dev-setup/build/build, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml, ceph-dev/config/definitions/ceph-dev.yml
=> ceph-dev-*: add crimson flavor for master build

ceph-dev-build/build/build_rpm, ceph-dev-new-build/build/build_rpm, scripts/build_utils.sh
=> ceph-dev-*-build: reset CI_CONTAINER when building nautilus

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This adds an optional cephadm_adopt scenario.
=> ceph-ansible-prs: add cephadm_adopt scenario

ceph-release-rpm/build/build, ceph-release-rpm/config/definitions/ceph-release-rpm.yml
=> ceph-release-rpm: Drop centos6

nfs-ganesha/config/definitions/nfs-ganesha.yml
=> nfs-ganesha: Clean up shaman repo files

ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
This adds an optional cephadm container scenario.
=> ceph-ansible-prs: add cephadm container scenario

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml
add integration with https://github.com/apps/cephacheck
=> ceph-perf-pull-requests: paste check status with cbt/githubcheck

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml
so we can check the details of check run
=> ceph-perf-pull-requests: pass job id and job url to check

ansible/examples/slave.yml
=> ansible: mock is in EPEL only apparently

ceph-ansible-prs/build/build
Let's skip these scenarios, they don't make sense.
=> ceph-ansible: skip some scenarios

ceph-api-nightly/config/definitions/ceph-api-nightly.yml
=> ceph-api-nightly: Enable recording of E2E runs

scripts/build_utils.sh
This file doesn't exist anymore.
=> ceph-ansible: remove tox dashboard

ceph-volume-pr/build/build
Otherwise we have two places that define envs.
=> Let tox.ini decide which environments to use

ceph-ansible-rpm/config/definitions/ceph-ansible-rpm.yml
=> ceph-ansible-rpm: Add missing CHACRACTL_KEY

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml
=> ceph-perf-pull-requests: do not fail if symblink already exists

ceph-api-nightly/config/definitions/ceph-api-nightly.yml, ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml, ceph-pr-api/config/definitions/ceph-pr-api.yml, ceph-pull-requests/config/definitions/ceph-pull-requests.yml
=> ansicolor jobs: Set TERM=xterm

ansible/examples/slave.yml
=> ansible: REstart the jenkins agent service when changes are made

ceph-dev-new/config/definitions/ceph-dev-new.yml, ceph-dev/config/definitions/ceph-dev.yml
Two commits, each identical in both builds
=> ceph-dev, ceph-dev-new: get shorter branch name, add SHA1 to build name

ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml, ceph-pr-api/config/definitions/ceph-pr-api.yml, ceph-pull-requests/config/definitions/ceph-pull-requests.yml
Ceph changes brought by https://github.com/ceph/ceph/pull/36771
Fixes: https://tracker.ceph.com/issues/47118
=> test: analyze JUnit results in PR jobs

ceph-pr-commits/build/build
=> ceph-pr-commits: Don't require signed commits for doc/ dir

ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml, ceph-pr-api/config/definitions/ceph-pr-api.yml, ceph-pull-requests/config/definitions/ceph-pull-requests.yml
=> Revert "test: analyze JUnit results in PR jobs"

ceph-pr-commits/build/test_commits.py
=> ceph-pr-commits: skip non-ascii chars

ceph-pr-render-docs/config/definitions/ceph-pr-render-docs.yml
=> ceph-pr-render-docs: Use RTD URL

ceph-multibranch-pipeline/config/definitions/ceph-multibranch-pipeline.yml
=> ceph: multibranch: trust contributors' forks

ceph-pr-commits/build/test_commits.py
Blocking https://github.com/ceph/ceph/pull/37810 https://github.com/ceph/ceph/pull/37849
=> Fix Signed-off-by check with non-ASCII names

sepia-fog-images/build/build
=> sepia-fog-images: Create FOG image template if missing

ceph-pr-api/config/definitions/ceph-pr-api.yml, ceph-pull-requests/config/definitions/ceph-pull-requests.yml
This reverts commit ae9a52ba2faa0b7faf0b9e0c6d3fd289cdd576ea.
=> ceph-pr,api-pr: Revert" skip when not needed"

ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
Not sure if anyone is interested in these, they are currently broken.
=> ceph-volume-nightly: Drop mimic from nightlies

ansible/examples/slave.yml
=> ansible: Disable daily apt transaction on Ephemeral slaves

quay-pruner/build/prune-quay.py
There's also some small cleanups/debug helps.  I've run this a bunch in dryrun mode and once for real, and it seems like it's doing what's desired, but I sure wouldn't mind some review.
=> quay-pruner.py: find orphaned SHA1-based tags and delete

teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
=> teuthology-pull-requests: Do not run on arm64

ceph-pr-docs/build/build
=> ceph-pr-docs: Timeout after an hour

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
=> ceph*trigger: Add pacific conditional steps

ceph-dev-new/config/definitions/ceph-dev-new.yml, ceph-dev/config/definitions/ceph-dev.yml
=> ceph-dev*: Enable dev builds for arm64

ceph-ansible-docs/config/definitions/ceph-ansible-docs.yml, ceph-ansible-nightly/config/definitions/ceph-ansible-nightly.yml, scripts/build_utils.sh
This commit brings the required modification to branch stable-6.0
=> ceph-ansible: branch stable-6.0

ansible/examples/slave.yml
=> ansible: Install tmpreaper/tmpwatch and clean /tmp daily

ceph-dev-new/config/definitions/ceph-dev-new.yml, ceph-dev/config/definitions/ceph-dev.yml, ceph/config/definitions/ceph.yml
=> Update ceph ARCH defaults

ceph-dev-new-build/build/build_mingw, ceph-dev-new-build/build/setup_mingw
=> ceph-dev-new-build: tweak chacra binary and repo endpoints for windows

ceph-dev-new-build/build/build_mingw, ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml
=> ceph-dev-new-build: cleanup root-owned mingw64 pbuilder environment

ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
Signed-off-by: Jan Fajerski <jfajersk@redhat.com>
=> swap ceph-volume maintainers

ansible/examples/centos8-vagrant.yml
=> ansible: New playbook to force reinstall vagrant on CentOS8

ceph-pull-requests/build/kill-tests, ceph-pull-requests/config/definitions/ceph-pull-requests.yml
Fixes: https://tracker.ceph.com/issues/47830
=> ceph-pull-requests: kill orphan processes after job is aborted

scripts/build_utils.sh
https://github.com/ceph/ceph-build/blob/master/scripts/build_utils.sh#L94-L105
=> build_utils.sh: Prefer python3 instead of python2 for virtualenvs

ceph-build-pull-requests/build/build
=> ceph-build-pull-requests: Use newer jjb

scripts/build_utils.sh
=> build_utils: Don't build pacific containers for el7

tcmu-runner/config/definitions/tcmu-runner.yml
=> tcmu-runner: add arm64

ceph-pull-requests/config/definitions/ceph-pull-requests.yml
=> ceph-pull-requests: specify threshold for a failure

scripts/build_utils.sh
so gnupg can be installed for checking the ppa repo's signatures.
=> scripts/build_utils.sh: install gnupg before ppa packages

nfs-ganesha/build/build_deb, nfs-ganesha/config/definitions/nfs-ganesha.yml
See commit comments.  I'm willing to be told I'm wrong about removing those distros.
=> nfs-ganesha: change patch to sed, drop some older distro/releases

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
Signed-off-by: Radoslaw Zarzynski <rzarzyns@redhat.com>
=> ceph-dev-new-trigger: add a crimson-only building variant.

ceph-pr-docs/build/build
=> ceph-pr-docs: remove more leftover source.list

scripts/build_utils.sh
see also https://tracker.ceph.com/issues/50218
=> scripts/build_utils.sh: do not use ppa on bionic

scripts/sync-push
=> sync-push: Use sort -V

ceph-cbt-lint/config/definitions/ceph-cbt-lint.yml, ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml
=> ceph-cbt-lint: add cbt lint test

ceph-pr-docs/build/build, ceph-pr-docs/config/definitions/ceph-pr-docs.yml
=> ceph-pr-docs: add annotation to build result

teuthology-pull-requests/config/definitions/teuthology-pull-requests.yml
https://github.com/ceph/teuthology/pull/1646#issuecomment-841353102
=> teuthology-pull-requests: Allowlist sunilkumarn417

ceph-pr-commits/build/test_commits.py
=> ceph-pr-commits: wrap lines over 79 chars

ceph-website/config/definitions/ceph-website.yml
=> ceph-website: Allow Pete-Robelou to build beta.ceph.io

scripts/build_utils.sh
see also https://github.com/ceph/ceph/pull/41677
=> scripts/build_utils: increase mem per job to 3000 MiB

ansible/examples/centos8-vagrant.yml
=> ansible: Update centos8-vagrant playbook to work for CentOS8.4

ansible/examples/slave.yml
=> ansible: It's called tmpwatch in OpenSUSE

ceph-iscsi-cli/build/build_rpm, ceph-iscsi-config/build/build_rpm, ceph-iscsi-stable/build/build_rpm, ceph-iscsi-stable/config/definitions/ceph-iscsi-stable.yml, ceph-iscsi-tools/build/build_rpm, ceph-iscsi-tools/config/definitions/ceph-iscsi-tools.yml
=> ceph-iscsi-*: Support CentOS8

ceph-website/build/build
Fixes: https://github.com/ceph/ceph.io/issues/161
=> ceph-website: Use proper build env per branch

ceph-website/build/build
=> ceph-website: Update build script for go-live

ansible/examples/master.yml, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
=> ansible: Install naginator on Jenkins master

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml, ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml, ceph-volume-scenario/config/definitions/ceph-volume-scenario.yml
I added irvingi01 and irvingi02 as CentOS7 Vagrant builders today.  We very briefly tried to use DHC for builders but that crashed and burned.
=> ceph-volume-*: Run on irvingi too.

ceph-pr-submodules/config/definitions/ceph-pr-commits.yml
=> ceph-pr-submodules: This job can run anywhere

scripts/build_utils.sh
…y) to reduce risk of aborting build process due to changes;
Signed-off-by: gal salomon <gal.salomon@gmail.com>
=> scripts/build_utils.sh: add package repo for apache arrow (enables parquet objects processing)

scripts/build_utils.sh
=> build_utils.sh: Fix variable

ceph-website-prs/build/build, ceph-website-prs/config/definitions/ceph-website-prs.yml, ceph-website/build/build, ceph-website/config/definitions/ceph-website.yml
The PRs job will build PRs.
The non-PRs job will build the production website.
=> ceph-website: Split job into two (PRs and main)

ceph-build/config/definitions/ceph-build.yml
https://lists.ceph.io/hyperkitty/list/ceph-users@ceph.io/message/GAIDYRWBOXC5FQD4H4UHUHZ6NLNSEKRC/
=> ceph-build: arm64 focal builds too

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, scripts/build_utils.sh
cleanup: add/ remove some missing go to have comments
Signed-off-by: Deepika Upadhyay <dupadhya@redhat.com>
=> update extrapkg needed for crimson, to be added by debian buildprofiles

ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
Signed-off-by: Aaryan Porwal <aaryanporwal2233@gmail.com>
=> ceph-dashboard-pull-requests: Add Applitools key credential

ceph-grafana-trigger/build/build
remove the -combined; a test shows the combined image is working
as expected on arm64
=> ceph-grafana-trigger: change manifest list's name to final form

scripts/dashboard/install-cephadm-e2e-deps.sh
=> ceph-dashboard-cephadm-e2e job: update KCLI image version

cephadm-ansible-prs/config/definitions/cephadm-ansible-prs.yml
change the current scenario name
=> cephadm-ansible: change scenario name

ceph-dashboard-cephadm-e2e/config/definitions/ceph-dashboard-cephadm-e2e.yml
=> ceph-dashboard-cephadm-e2e job: add E2E deps script

chacra-pull-requests/setup/playbooks/tasks/postgresql.yml
=> chacra-pull-requests: Define postgresql_version on >= xenial

chacra-pull-requests/setup/playbooks/tasks/postgresql.yml
=> chacra-pull-requests: Install correct version of psycopg2

chacra-pull-requests/setup/playbooks/tasks/postgresql.yml
=> chacra-pull-requests: Now set the ansible interpreter

scripts/nfs-ganesha/pull-sign-push, scripts/nfs-ganesha/sign-rpm-auto, scripts/nfs-ganesha/sync-push-auto
Signed-off-by: Adam Kraitman <akraitma@redhat.com>
=> Scripts that pull sign and pushes the nfs-ganesha packages on the signer

ceph-build/build/setup_deb, ceph-build/config/definitions/ceph-build.yml, ceph/config/definitions/ceph.yml, scripts/build_utils.sh, scripts/sync-pull
=> ceph: Build for bullseye

ceph-dev-build/build/setup_rpm, ceph-dev-new-build/build/setup_rpm
Fixes: https://tracker.ceph.com/issues/18491
=> ceph-dev-*build: Notify shaman of a build sooner

ceph-dashboard-pull-requests/config/definitions/ceph-dashboard-pull-requests.yml
Related-to: https://tracker.ceph.com/issues/51996
=> dashboard: add Applitools wrapper

ansible/examples/master.yml
=> ansible: Install applitools-eyes plugin on Jenkins

ansible/examples/slave.yml
=> ansible: Modify builder playbook to support CentOS 9 Stream

scripts/build_utils.sh
This would be easier to maintain this directly in ceph-ansible.
so let's move this playbook to ceph-ansible repo.
=> ceph-ansible-prs: refact collect-logs

ansible/examples/slave.yml, ansible/templates/systemd/jenkins.service.j2
Requested by Ernesto via e-mail.  See https://stackoverflow.com/questions/27960996/jenkins-console-output-characters
=> ansible: Set file.encoding=UTF-8

ceph-ansible-prs/build/build, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
see ceph-ansible corresponding pr: ceph/ceph-ansible#6951
=> ceph-ansible-prs: add new scenario subset_update

ceph-dev-new-setup/build/build
https://github.blog/2021-09-01-improving-git-protocol-security-github/
Signed-off-by: Sage Weil <sage@newdream.net>
=> ceph-dev-new-setup/build/build: git:// -> https://

ceph-dev-build/build/build_mingw, ceph-dev-build/build/setup_mingw, ceph-dev-build/build/validate_mingw, ceph-dev-build/config/definitions/ceph-dev-build.yml, ceph-dev-cron/config/definitions/ceph-dev-cron.yml, ceph-dev/config/definitions/ceph-dev.yml
Tested and working https://shaman.ceph.com/builds/ceph/master/884f89ea6f89f10f96a4dd2ad0922a823e26d96d/default/286496/
=> ceph-dev*: Start building Windows binaries for master

ceph-windows-pull-requests/config/definitions/ceph-windows-pull-requests.yml
Run the job only against PRs that target the `master` branch.
=> Update ceph-windows-pull-requests job

sepia-fog-images/README.rst, sepia-fog-images/build/build, sepia-fog-images/config/definitions/sepia-fog-images.yml
This is useful if you already have machine(s) locked
=> sepia-fog-images: Optionally allow specifying machines

ceph-pull-requests-arm64/build/build, ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml
=> ceph-pull-requests-arm64: Skip make check on doc-only change

ceph-pr-api/config/definitions/ceph-pr-api.yml
=> api: allowlist quincy

scripts/build_utils.sh
=> scripts: Support CentOS Stream

ceph-dev-cron/config/definitions/ceph-dev-cron.yml
=> ceph-dev-cron: Keep more builds

ansible/roles/ansible-jenkins/templates/etc_default.j2
Latest version of Jenkins didn't support any of the removed arguments anymore
=> ansible: Update Jenkins master java args

ansible/examples/slave.yml
Some of the braggi were still running out of space
=> ansible: Clean up tmp files older than 14

ceph-dev-cron/config/definitions/ceph-dev-cron.yml
=> ceph-dev-cron: Drop nautilus | Add quincy

ceph-windows-pull-requests/config/definitions/ceph-windows-pull-requests.yml
=> ceph-windows-pull-requests: add quincy

sepia-fog-images/config/definitions/sepia-fog-images.yml
=> sepia-fog-images: Update defaults to latest supported distros

ceph-grafana-trigger/build/build, ceph-grafana-trigger/config/definitions/ceph-grafana-trigger.yml
And upgrade Grafana default version to 8.3.5
=> grafana/trigger: remove docker references 

ceph-grafana-trigger/config/definitions/ceph-grafana-trigger.yml, ceph-grafana/config/definitions/ceph-grafana.yml
=> ceph-grafana: Update quay cred / erase dockerhub cred

scripts/build_utils.sh
=> build_utils.sh: Always remove unwanted python3.X versions

scripts/build_utils.sh
=> scripts: Always reinstall python3 and always set alternatives to auto

ansible/roles/ceph-release/tasks/create.yml
The process is the same for a STABLE release and a HOTFIX release.
=> ceph-release: Fix checkout process for HOTFIX

ansible/roles/ceph-release/tasks/create.yml
=> ceph-setup: missing apostrophe

ansible/roles/ceph-release/tasks/create.yml, ansible/roles/ceph-release/tasks/push.yml
Fixes error: src refspec pacific does not match any
=> ceph-setup: Correct repo and branch name

cephadm-ansible-prs/build/build, cephadm-ansible-prs/config/definitions/cephadm-ansible-prs.yml
So we can test against multiple distro.
=> cephadm-ansible-prs: add multi-distro support

cephadm-ansible-prs/config/definitions/cephadm-ansible-prs.yml
This adds the `unittests` scenario.
=> cephadm-ansible-prs: add new scenario

ceph-dev-container-only/config/definitions/ceph-dev-container-only.yml, ceph-setup/config/definitions/ceph-setup.yml, ceph-tag/config/definitions/ceph-tag.yml, jenkins-job-builder/build/build, jenkins-job-builder/config/definitions/jjb.yml, mita-deploy/config/definitions/mita-deploy.yml
=> Replace remaining references to master

nfs-ganesha-stable/build/build_rpm, nfs-ganesha/build/build_rpm
Not sure why these only got cleaned up on failure but they need to go on a success too.
=> nfs-ganesha*: Clean up leftover shaman repos

ceph-pull-requests-arm64/config/definitions/ceph-pull-requests-arm64.yml
=> ceph-pull-requests-arm64: Do not run make check on c9

ceph-ansible-docs-prs/config/definitions/ceph-ansible-docs-prs.yml
=> ceph-ansible-docs-prs: Disable job

sepia-fog-images/build/build
Shouldn't ever have to run into this issue again but...
=> sepia-fog-image: fetch before checkout

ceph-pull-requests/build/build
=> Revert "ceph-pull-requests/build/build: enable WITH_PMEM"

nfs-ganesha/build/build_rpm
=> nfs-ganesha: mock target is centos-stream-8 now

ceph-volume-pr/config/definitions/ceph-volume-pr.yml
=> ceph-volume-pr: Run on CentOS8 Builders

sepia-fog-images/build/failure
=> sepia-fog-images: Don't unpause if PAUSEQUEUE=false

ceph-volume-ansible-prs/build/build
- enforce py39
- add quincy release
=> ceph-volume-ansible-prs: various fixes

ceph-ansible-prs/build/build, ceph-ansible-prs/config/definitions/ceph-ansible-prs.yml
add functional testing for rbdmirror scenario
=> ca-ansible-prs: add rbdmirror scenario

ansible/templates/systemd/jenkins.service.j2
=> ansible: Replace a couple more instances of slave

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml, ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml, ceph-volume-scenario/config/definitions/ceph-volume-scenario.yml
=> ceph-volume-*: Run on CentOS8 builders. C7 is too old now.

ceph-build/config/definitions/ceph-build.yml, ceph-dev-build/config/definitions/ceph-dev-build.yml, ceph-dev-cron/config/definitions/ceph-dev-cron.yml, ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml, ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-new/config/definitions/ceph-dev-new.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml, ceph-dev/config/definitions/ceph-dev.yml, ceph/config/definitions/ceph.yml, kernel/config/definitions/kernel.yml, scripts/build_utils.sh
=> Add Ubuntu 22.04 (main only for now)

ansible/release.yml
=> ansible: s/ceph.com/ceph.io in ceph-maintainers email addy

scripts/ceph-windows/cleanup
=> ceph-windows: Clean up repo files

ansible/examples/builder.yml
https://github.com/containers/podman/issues/9002
=> ansible: loginctl enable-linger jenkins-build

ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml, ceph-dev/config/definitions/ceph-dev.yml
=> ceph-dev: Automatically build main on centos9

scripts/sign-rpms, scripts/sync-pull, scripts/sync-push
=> scripts: Update signing scripts for el9

ceph-dev-container-only/config/definitions/ceph-dev-container-only.yml
=> ceph-dev-container-only: Use Jenkins controller for main job

ansible/slave.yml
=> Fix slave.yml symlink

ceph-dev-build/build/build_osc, ceph-dev-build/build/setup_osc, scripts/build_utils.sh
The counterpart in `ceph/ceph.git` is https://github.com/ceph/ceph/pull/47458.
=> kickoff v18 reef

scripts/build_utils.sh
This reverts commit dd03c322eaded5f1bb274bb46fb13fbfe7a191aa.
Signed-off-by: Matan Breizman <mbreizma@redhat.com>
=> Revert "build_utils.sh: Disable cephfs_java with Crimson"

scripts/ceph-windows/collect-event-logs.ps1
Previously, the windows event log artifacts were being dumped in evtx format and then converted to txt by individually querying them using wevtutil.  After doing this, the resulting txt logs contained xml entries that omitted the actual event message.
Now, they will be directly dumped as txt using Get-WinEvent and the evtx logs can be obtained using the IncludeEvtxFiles flag.
Signed-off-by: Stefan Chivu <schivu@cloudbasesolutions.com>
=> ceph-windows: Fix event log artifacts

ceph-grafana-trigger/build/build, ceph-grafana-trigger/config/definitions/ceph-grafana-trigger.yml
after https://github.com/ceph/ceph/pull/50845/
=> ceph-grafana-trigger: update the grafana version

scripts/sync-pull
Catch the error where three arguments are not supplied.
=> scripts/sync-pull: update argument check to look for $3

scripts/build_utils.sh
adami nodes have 96 processing units (nproc). Based on the old script logic, we were compiling 90 build jobs with 96 processing units. This combination (96/90) ends up causing many instances of memory overconsumption on adami nodes.
With this new logic, we take into account that jobs take up more memory than we expect. This will make it so adami nodes will compile 67 build jobs on 96 processing units, which will hopefully avoid so many instances of memory overconsumption. (Total memory on adami nodes is generally ~270036 MiB, so 270036 / 4000 = 67)
braggi nodes do not have this problem; they have 48 processing units. It has been working so far to compile 48 build jobs with 48 processing units on the braggi nodes, and this new logic will not change that.
Fixes: …
=> scripts: lower concurrency for many-core machines

sepia-fog-images/build/build
Whether or not we will teuthology-lock machines, we always need teuthology-queue --pause
=> sepia-fog-images/build/build: bootstrap teuthology unconditionally

ceph-rook-e2e/build/cleanup, ceph-rook-e2e/config/definitions/ceph-orchestrator-rook-e2e.yml, scripts/rook-orch/install-rook-e2e-deps.sh
Adding rook orchestrator e2e testing job
Fixes: https://tracker.ceph.com/issues/63019
Testing:
I've been testing this job using my local fork and it seems to be stable so far:
https://jenkins.ceph.com/job/ceph-orchestrator-rook-e2e/
=> project config: adding rook orchestrator e2e testing job

ceph-grafana-trigger/build/build, ceph-grafana-trigger/config/definitions/ceph-grafana-trigger.yml
after: https://github.com/ceph/ceph/pull/54804
=> ceph-grafana-trigger: update the grafana version to 9.4.12

ceph-dev-cron/config/definitions/ceph-dev-cron.yml, ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml, ceph-dev-trigger/config/definitions/ceph-dev-trigger.yml
remove any quincy crimson buils (not a supported release)
remove reef c8 builds
remove main c8 builds
=> ceph-dev*: remove centos8 crimson builds

scripts/rook-orch/install-rook-e2e-deps.sh
Fixes: https://tracker.ceph.com/issues/64013
=> project config: adding logic to create kvm default network

sync-images/build/build, sync-images/build/sync.yml
I might be lacking JJB expertise but this is the only way I could figure out in order to get `sync.yml` in the workspace.
=> sync-images: write sync.yml in workspace

ceph-ansible-prs/build/teardown, scripts/build_utils.sh
If provided, use the custom playbook to collect logs.
=> build_utils: use custom playbook for collect_ceph_logs

ceph-pull-requests/build/build
Fixes: https://tracker.ceph.com/issues/64962
Because of: https://github.com/ceph/ceph/pull/55054
=> ceph-pull-requests: remove WITH_ZBD

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml, ceph-volume-nightly/config/definitions/ceph-volume-nightly.yml
drop filestore testing
make centos distro value more generic (el8 and el9)
=> ceph-volume: update jobs definition

ceph-volume-ansible-prs/config/definitions/ceph-volume-pr.yml
filestore is no longer supported.
=> ceph-volume: drop filestore jobs

ceph-volume-test/config/definitions/ceph-volume-test.yml
corresponding PR: ceph/ceph#56827
=> ceph-volume: update 'test suite' definition

chacra-pull-requests/setup/playbooks/tasks/postgresql.yml
next time: can't we just use a generic "install postgresql"
=> chacra-pull-requests: set postgres version for jammy

ceph-volume-test/config/definitions/ceph-volume-test.yml
This adds the squid release support to the function test suite
=> ceph-volume: add squid release to functional test suite

sync-images/build/build
Mirror `grafana/loki`, `grafana/promtail` and `maxwo/snmp-notifier` in addition to `nginx` and `grafana/grafana`.
=> sync-images: sync all cephadm required images to quay.io

ceph-dev-new-setup/build/build, ceph-dev-new/config/definitions/ceph-dev-new.yml
Requires https://github.com/ceph/ceph/pull/60577
=> ceph-dev-new: Add dwz toggle

ceph-dev-new-build/build/build_rpm, ceph-dev-new-build/build/setup_rpm, ceph-dev-new-build/config/definitions/ceph-dev-new-build.yml, ceph-dev-new-setup/build/build, ceph-dev-new/config/definitions/ceph-dev-new.yml, scripts/setup_sccache.sh
Requires https://github.com/ceph/ceph/pull/60578
=> ceph-dev-new: Add sccache support

ceph-website-prs/config/definitions/ceph-website-prs.yml
@zdover23 is the docs guy and does a lot of website updates.
=> ceph-website: zac is the docs maintainer

ceph-dev-pipeline/config/definitions/ceph-dev-pipeline.yml
So that we can easily test in-development changes to this pipeline.
=> ceph-dev-pipeline: Add CEPH_BUILD_BRANCH param

scripts/build_utils.sh
Take an array of patterns to compare each changed file against. For docs, use the current suggestions from
https://tracker.ceph.com/issues/69650
=> Rework changed-files test (doc-only, container-only)

ansible/examples/builder.yml
This is the follow-up and preferred solution to https://github.com/ceph/ceph-build/pull/2330
=> Install and configure podman on Ubuntu builders

ceph-dev-cron/config/definitions/ceph-dev-cron.yml, ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
should use include-raw-verbatim
=> PR 2315 added back in an 'include-raw' which is deprecated

ceph-perf-pull-requests/config/definitions/ceph-perf-pull-requests.yml, ceph-pull-requests-arm64/build/build, ceph-pull-requests/build/build, scripts/build_utils.sh
Follow up to: https://github.com/ceph/ceph-build/pull/2329 Now that https://github.com/ceph/ceph/pull/62325 is merged.
=> ceph-dev*: final transition to WITH_CRIMSON

ceph-dev-new-setup/build/build, ceph-dev-new-setup/config/definitions/ceph-dev-new-setup.yml, scripts/setup_container_runtime.sh
This supersedes #2334 and #2354. Tested here: https://jenkins.ceph.com/job/ceph-dev-new-setup/92635/
=> Add scripts/setup_container_runtime.sh

scripts/setup_container_runtime.sh
... to the apt update invocation.
=> setup_container_runtime.sh: Add missing sudo

ceph-source-dist/build/Jenkinsfile, ceph-source-dist/config/definitions/ceph-source-dist.yml
The intent is to replace the various `ceph-*setup` jobs.
=> Add ceph-source-dist job

ansible/examples/builder.yml, ansible/slave.yml
Allow automatically fetching api secret from secrets inventory based on 'api_uri'; fix up subuid setting; add comments
=> FIx up builder.yml

kernel/build/setup
This is a required dependency for CONFIG_GENDWARFKSYMS since 6.15.
=> kernel: install elfutils-devel or libdw-dev(el)

ceph-dev-new-trigger/config/definitions/ceph-dev-new-trigger.yml
Replaced by ceph-trigger-build job
=> ceph-dev-new-trigger: Disable

scripts/setup_container_runtime.sh
Also fix a number of shellcheck warnings.
=> setup_container_runtime.sh: Drop bc

ceph-build-pull-requests/config/definitions/ceph-build-pull-requests.yml, ceph-deploy-pull-requests/config/definitions/ceph-deploy-pull-requests.yml, ceph-qa-suite-pull-requests/config/definitions/ceph-qa-suite-pull-requests.yml, chacra-pull-requests/config/definitions/chacra-pull-requests.yml, paddles-pull-requests/config/definitions/paddles-pull-requests.yml, radosgw-agent-pull-requests/config/definitions/radosgw-agent-pull-requests.yml, shaman-pull-requests/config/definitions/shaman-pull-requests.yml
These will be replaced by proper RABC eventually
=> Remove admin lists from ghprb configs

scripts/setup_container_runtime.sh
... if `podman system info` fails.
=> setup_container_runtime.sh: Reset podman

ceph-dev-pipeline/build/Jenkinsfile
The inspiration is to help us find instances of OOM kills, but may be helpful with other issues.
=> ceph-dev-pipeline: Report kernel msgs in post
